### ISSUE TITLE
Extra scripts question

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#1001]
I looked around but couldn't find much documentation on the extra scripts post-processing feature. Does it work for torrent downloads?  Does it only support python scripts?  I have a shell script that I want to run as a pre_script, but it's not being executed. There's nothing in the logs that its even being detected.

**Comment by evilhero** [comment]
As long as it's executable by the user running mylar, bash scripts should work. There's nothing in the mylar.log files indicating the command it's running even?

**Comment by bonebox** [comment]
It is executable by the same user running mylar.  I've run it manually by the same user and it works fine. There's nada in the logs.  I've restarted Mylar a few times just to make sure.  Also double-checked config.ini to make sure the script was there and enabled (See below).  Also tried enabling the "use AFTER post-processing" and still nothing at all in the log.

```
enable_extra_scripts = 0
extra_scripts = ""
enable_pre_scripts = 1
pre_scripts = /usr/local/mylar/webp-mylar.sh
post_processing = 1
post_processing_script = ""
```

**Comment by bonebox** [comment]
One though--should it work if I trigger a manual post-process? Because that's how I'm testing it.

**Comment by evilhero** [comment]
Manual or normal post-processing follows the same workflow - it does the pre, post (comicRN.py by default if not specified) , and then extra scripts in that sequence. 

I had a bash script running fine before but that was last year and haven't revisited it since. I'll have to do some testing to see if its broken or not, and how to fix it.

**Comment by bonebox** [comment]
I played around with it some more but still can't get it to show in the log. It very well could be user error, but not sure what else I might be doing wrong.  I would think even if there were some issue with my script, it would still be showing up in the log that a script was detected.

**Comment by evilhero** [comment]
Ok, so I looked at this - it definitely works with python scripts, but not with bash. Bash scripts don't have the actual bash command piped into the subprocess call so it never calls the proper executable. Got it working on my local repo now (it assumes bash is in /bin/bash though, haven't figured out how to pipe the shebang just yet), so it will be pushed in the next development commit.

Also, the logging was just logging to the downloading client. So manually post-processing wasn't registering any logging so that's why nothing was seen in the logs. This will be fixed in the next commit as well :)

**Comment by bonebox** [comment]
Good to hear, thanks for the update!
