### ISSUE TITLE
OSX Issues

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1005]
I am experiencing several issues with Mylar right now including:
Post-Processing will rename all files in the download folder, but not move files into the Comic Location Path. I have tested this repeatedly. 
All series marked with status Ended unless I manually refresh the series
Series are no longer refreshing automatically.
Issues are now downloading with the issue folder containing an extension i.e. "Title Name 00x (YYYY) (Digital) (Release).cbr"

**Comment by evilhero** [comment]
Without seeing any kind of logs from the mylar.log file (not the gui log) showing these things it's really hard to diagnose anything. Suffice to say, it would appear it's probably a config issue of some sort, or possibly there's an error in the logs that's stopping these things from running it's proper course of execution (all of those issues are working properly).

What branch / commit of mylar are you running?

**Comment by lodasi** [comment]
I'm on Version: b6b8c6293af8587ce03e9aeb7b74c96f95f9e111 (development) 

I do see this in my logs quite frequently:
Uncaught exception: Traceback (most recent call last):
File "/Users/ldsilverman/Applications/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 505, in run
self.__target(*self.__args, **self.__kwargs)
File "/Users/ldsilverman/Applications/mylar/mylar/updater.py", line 244, in dbUpdate
for ann in annualsnew:
UnboundLocalError: local variable 'annualsnew' referenced before assignment

As an example. the most recent volume of Powers was marked as ended until I manually refreshed the comic.

**Comment by evilhero** [comment]
As far as the error you posted above, that message will be fixed in the next development commit.
The error message probably has a hand in some of  your other problems due to the actual db-refresh of said series failing before it can update the issue information properly within mylar - specifically:
- All series marked with status Ended unless I manually refresh the series
- Series are no longer refreshing automatically.

For the 'Post-Processing will rename all files, but not move' problem, I'd need to see the actual mylar.log file showing the start of a post-processing run and the subsequent failure. I 'believe' this might be fixed in the next commit as well, as there was a problem with failing to move the post-processed issue if the file was a cbz and meta-tagging was performed.

The 'Issues are now downloading with the issue folder containing an extension i.e. "Title Name 00x (YYYY) (Digital) (Release).cbr"' problem is probably due to the provider you're using to get the nzb's from (Experimental option will doe this as it throws SAB/NZBget the raw header instead of the filename within). It really doesn't have any effect on the post-processing, as once the file is post-processed that directory should be removed.

**Comment by lodasi** [comment]
Issue seems to have cleared up with the new version. Tested by adding a new series and marking all issues as wanted. Files properly post-processed.
