### ISSUE TITLE
Sabnzbd no longer works when hosted on separate server

### ISSUE THREAD

**Issue by SMcClelland** [evilhero/mylar#1036]
Hi,

I think due to commit af64a462cb26c5e41bb9bbaeb36606224d2918dd, SABnzbd no longer works when hosted on a separate server than Mylar. It used to pass a fileURL but now passes a file location that my SABnzbd server does not have access to.

**Comment by evilhero** [comment]
This was a requirement going forward, since mylar had to switch to the requests module, of which sabnzbd and https sites don't get along. 

I have a fix which requires the specification of a directory where mylar can save the nzbs (other than the default cache directory), with the caveat being that sabnzbd and mylar both have to have complete access to this specified folder on the Sabnzbd machine. I haven't tested it yet but it works on the same premise of the Sabnzbd Download Directory option. 

I have another different way of doing this and using the file URL method for sabnzbd but I need to do the code and test it - and it wouldn't require any settings to be added / fixed.

**Comment by rupaschomaker** [comment]
A note that on my synology, the files are being created with a permission
of 600 (-rw-------).  Since on the synology I run sabnzbd and mylar as
different userids the files are all sitting in the cache directory
unreadable by sabnzbd. :(

Is this something you can tweak?

On Thu, May 28, 2015 at 11:31 PM, evilhero <notifications@github.com> wrote:

> This was a requirement going forward, since mylar had to switch to the
> requests module, of which sabnzbd and https sites don't get along.
>
> I have a fix which requires the specification of a directory where mylar
> can save the nzbs (other than the default cache directory), with the caveat
> being that sabnzbd and mylar both have to have complete access to this
> specified folder on the Sabnzbd machine. I haven't tested it yet but it
> works on the same premise of the Sabnzbd Download Directory option.
>
> I have another different way of doing this and using the file URL method
> for sabnzbd but I need to do the code and test it - and it wouldn't require
> any settings to be added / fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/1036#issuecomment-106671570>.
>



-- 
-Rupa

**Comment by evilhero** [comment]
@rupaschomaker: Yes, I should be able to fix the settings so it enforces the permissions provided by the configuration.
