### ISSUE TITLE
How can I run Mylar as a daemon?

### ISSUE THREAD

**Issue by Schwalbi** [evilhero/mylar#1040]
So I got my Mylar working again, after installing Python 2.7.9 and doing a brand new install of Mylar. It crashed again but I quickly fixed it by backing up the data and doing a brand new install and it kept working fine for a while. Now, it seems Mylar doesn't run as a daemon anymore. The only way I can use it is by going into Terminal and typing "python /Applications/Mylar/Mylar.py", and that screen must remain open, otherwise Mylar won't run. Any ideas? 

Running OS X Yosemite (10.10.3)

**Comment by evilhero** [comment]
This goes back to the script you run in order to start mylar as a daemon. You probably are referencing the incorrect version of python within said script. Locate the startup script that you run that starts mylar as a daemon and point it to the correct location of both python and your mylar installation (look back at the site you followed instructions from as I'm sure it's in there)

**Comment by Schwalbi** [comment]
Yeah, I tried that and no luck. Is there an installation guide made by you? I guess I would prefer to follow your instructions so there's no third party involved.

**Comment by evilhero** [comment]
What does your startup script look like? 

Unfortunately I don't run a Mac OS, so making an installation guide (while very important and is on the todo)  isn't a feasible option atm, just due to the fact that I couldn't test it out properly first.

**Comment by Schwalbi** [comment]
It looks like this. I think you might be right regarding the new Python installation. But I have no clue where the new installation is located or how I can access it via Terminal.

<plist version='1.0'>
<dict>
        <key>Label</key>
        <string>mylar</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/bin/python2.7</string>
                <string>/Applications/Mylar/Mylar.py</string>
                <string>-q</string>
        </array>
        <key>KeepAlive</key>
        <true/>
</dict>
</plist>

**Comment by Schwalbi** [comment]
<plist version='1.0'>
<dict>
        <key>Label</key>
        <string>mylar</string>
        <key>ProgramArguments</key>
        <array>
                <string>/usr/bin/python2.7</string>
                <string>/Applications/Mylar/Mylar.py</string>
                <string>-q</string>
        </array>
        <key>KeepAlive</key>
        <true/>
</dict>
</plist>

**Comment by Schwalbi** [comment]
![screen shot 2015-06-03 at 5 37 47 pm](https://cloud.githubusercontent.com/assets/11640052/7973138/154ab730-0a18-11e5-88e6-454c37ca7f49.png)

**Comment by evilhero** [comment]
Try changing the python2.7 in the first array line to just python and see if that works?

**Comment by Schwalbi** [comment]
No, it didn't work. Tried uninstalling again, but this time I'm noticing that when I input "python /Applications/Mylar/Mylar.py" on Terminal, it starts acting as the log.

Schwalbis-MacBook-Pro:~ Schwalbi$ python /Applications/Mylar/Mylar.py

03-Jun-2015 19:42:28 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
03-Jun-2015 19:42:28 - ERROR :: MAIN : No User Comicvine API key specified. I will not work very well due to api limits - http://api.comicvine.com/ and get your own free key.
03-Jun-2015 19:42:28 - INFO :: MAIN : Checking to see if the database has all tables....
03-Jun-2015 19:42:28 - INFO :: MAIN : Populating Base Exception listings into Mylar....
03-Jun-2015 19:42:28 - INFO :: MAIN : No Custom Exceptions found - Using base exceptions only. Creating blank custom_exceptions for your personal use.
03-Jun-2015 19:42:28 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
03-Jun-2015 19:42:28 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
03-Jun-2015 19:42:28 - INFO :: MAIN : Retrieving latest version information from github
03-Jun-2015 19:42:29 - INFO :: MAIN : Comparing currently installed version with latest github version
03-Jun-2015 19:42:30 - INFO :: MAIN : Mylar is up to date
03-Jun-2015 19:42:30 - INFO :: MAIN : Remapping the sorting to allow for new additions.
03-Jun-2015 19:42:30 - INFO :: MAIN : Sucessfully ordered -1 series in your watchlist.
03-Jun-2015 19:42:30 - INFO :: MAIN : Starting Mylar on http://0.0.0.0:8090/
03-Jun-2015 19:42:30 - INFO :: MAIN : Initializing the DB Updater.
03-Jun-2015 19:42:30 - INFO :: MAIN : Initiating the ComicVine API Checker to report API hits every 5 minutes.
03-Jun-2015 19:42:30 - INFO :: MAIN : Initiating startup-RSS feed checks.
03-Jun-2015 19:42:30 - INFO :: MAIN : Checking for existance of Weekly Comic listing...
03-Jun-2015 19:42:30 - INFO :: RSSCHECK : delaying startup thread for 30 seconds to avoid locks.
03-Jun-2015 19:42:30 - INFO :: WEEKLYCHECK : delaying startup thread for 10 seconds to avoid locks.
03-Jun-2015 19:42:40 - INFO :: WEEKLYCHECK : [WEEKLY] Checking Weekly Pull-list for new releases/updates
03-Jun-2015 19:42:40 - INFO :: WEEKLYCHECK : Weekly pull list present - checking if it's up-to-date..
03-Jun-2015 19:42:40 - INFO :: WEEKLYCHECK : [PULL-LIST] Populating & Loading pull-list data from file
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : Preparing to update to the new listing.
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : Populating the NEW Weekly Pull list into Mylar.
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : Weekly Pull List successfully loaded.
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : Checking the Weekly Releases list for comics I'm watching...
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : Finished checking for comics on my watchlist.
03-Jun-2015 19:42:41 - INFO :: WEEKLYCHECK : No series have been marked as being on auto-watch.
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : RSS Feed Check was last run at : 
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : RSS Feed Check First Ever Run.
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : [RSS] Initiating RSS Feed Check for NZB Providers.
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : [RSS] RSS Feed Check/Update Complete
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : [RSS] Watchlist Check for new Releases
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : Initiating Search Scan at scheduled interval of 20 minutes.
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : Completed RSS Search scan
03-Jun-2015 19:43:00 - INFO :: RSSCHECK : [RSS] Watchlist Check complete.

**Comment by Schwalbi** [comment]
My API is missing, but that's just because I just reinstalled Mylar.

**Comment by evilhero** [comment]
Try doing either : 

From a command line:
which python

Or from within the python shell:
>>> import sys
>>> sys.executable
'/usr/bin/python'

Either / both of those should return the path to your python executable which you can then plunk into your startup script.

**Comment by shadowcharly** [comment]
try this to locate your new python install, in Terminal, write this:

> which python
(It will show a path, maybe "/usr/bin/python"
the part that we are interested is the /usr/bin, because that's where our default python install is.)

> cd /usr/bin
(or the path that was before the python command)
(now comes the tricky part)
> ls -al | grep python
(it will list everything installed in this directory that resembles python. It should show something like this:
-rwxr-xr-x     2 root   wheel     58432 10 sep  2014 python
-rwxr-xr-x     5 root   wheel       925 10 sep  2014 python-config
lrwxr-xr-x     1 root   wheel        75 20 oct  2014 python2.6 -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6
lrwxr-xr-x     1 root   wheel        82 20 oct  2014 python2.6-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6-config
lrwxr-xr-x     1 root   wheel        75 20 oct  2014 python2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
lrwxr-xr-x     1 root   wheel        82 20 oct  2014 python2.7-config -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
-rwxr-xr-x     2 root   wheel     58432 10 sep  2014 pythonw
lrwxr-xr-x     1 root   wheel        76 20 oct  2014 pythonw2.6 -> ../../System/Library/Frameworks/Python.framework/Versions/2.6/bin/pythonw2.6
lrwxr-xr-x     1 root   wheel        76 20 oct  2014 pythonw2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw2.7
)

try and find if there's a python2.7 or something like that and try:
> python2.7 --version

That will show the exact version of that binary.

If you need to broaden the place to search for find, you can allways make the system work for you using the "find" command like this:
> find /usr -name "python" | grep bin
and if the python install is somewhere in the /usr path, this will show all the files that have a python-like name and are in a folder supposed to have a binary (program).

There you can repeat the questioning for version and find the right one to put in the startup script.
Note: to execute the different pythons you find, you'll have to copy the path to each one and do
> path/to/my/python --version


Hope it helps ^.^
