### ISSUE TITLE
Pull List vs. Comic Listing - Identifying New Issues

### ISSUE THREAD

**Issue by razambon** [evilhero/mylar#1041]
Having an issue where a number of comics aren't being identified on my pull list (This Week section).  When I select them, it says "Already in Library".  When I open them, the new issue isn't listed.

Not sure how these connect - seems like some disconnect between comicvine and where the pull list comes from, when things get updated, etc., but just wanted to confirm. 

Thanks!

**Comment by evilhero** [comment]
Mylar pulls all the upcoming information (all of which is exactly listed on the pullist page) from a separate website, and comicvine holds all the actual issue information.  So mylar has to match up word to word (or similar) in order to mark issues as Wanted on the pullist. 

Can I ask what the issues are that aren't being marked? Sometimes it's as simple as just refreshing the series, other times you need to make use of the substitutes.csv file in order to force a match from the pullist to comicvine.

**Comment by razambon** [comment]
Few examples:
ALL NEW X-MEN 
GREEN ARROW 
GREEN LANTERN 
JUSTICE LEAGUE

**Comment by evilhero** [comment]
Nothing  out of the ordinary, I have 2/4 of those and they got marked just fine. 

Try refreshing the series and seeing if that fixes things (it should mark it as Wanted after the refresh if it can match up) 

Otherwise you'd have to post the mylar.log file contents showing the weekly pull list comparison happening for these series.

**Comment by razambon** [comment]
Which 2?  All New X-Men is showing as wanted in the comic 'area' but not in the want list.    I can check the rest and send a log as well...just odd.  I've seen the timing disconnect before, but this time no sync seems to be happening and readding a comic to fix things isn't working.

**Comment by evilhero** [comment]
If reading isn't working, make sure that it's able to complete the add properly (it would say any errors in the log). 

Usually after an add, it will check the pullist for new issues of the newly added series and mark it as Wanted accordingly. 

If it's showing as Wanted in the Wanted tab, then it should be the same in the series page (they're linked to the same table). The pullist/upcoming pages are linked together, bit not to the series page (because it can't ad there is no comicvine id present on the pullist unless it matches via text based comparison). 

Have you tried recreating thr pullist via the Recreate Pullist option on the pullist page? 

And I have All New X-Men and Justice League on my pullist.

**Comment by razambon** [comment]
Looking like it's working better now...I'll keep an eye on it.  Restarted, updated, etc.  I'm trying to use the 'watched' function as well...see if that assists.
