### ISSUE TITLE
issue with sabnzbd

### ISSUE THREAD

**Issue by rgecko** [evilhero/mylar#1055]
When mylar passes the file over to Sabnzbd it hands and doesn't process the files as of the most recent update like so where apikey=an actual API key.

WAIT 37 sec / Trying to fetch NZB from http://0.​0.​0.​0:8083/api?apikey=XXX&cmd=downloadNZB&nzbname=Secret.​Wars.​Journal.​002.​2015.​Digital.​Zone-Empire.​nzb		

it's doing this for every issue fetched.

info on the version used is:
Version: 80d204420f7952a6f323cb6999fa9935ed02671a (development)

**Comment by evilhero** [comment]
Try setting the ip for mylar to be the actual IP of the machine running mylar instead of using '0.0.0.0' or 'localhost'.

If it's still not able to grab the nzb, then you need to enable the mylar API within the configuration, generate a key, save the settings, and restart Mylar. Mylar generates a random apikey for each send, so it won't use the actual generic apikey - but for some reason it's causing some issues atm and I'm currently looking into it.

**Comment by rgecko** [comment]
at fixed it. Thanks!
