### ISSUE TITLE
500 Internal Server Error - datetime.date

### ISSUE THREAD

**Issue by motioneso** [evilhero/mylar#1057]
Getting this error when trying to go home and manageComics. I found a bunch of older issues posted on here with latest dates being incorrect, so I tried to go into /manage and then manage comics, but I'm getting the same error there. This has been working great until recently, and I don't think I've added anything lately. Anyway to find the offender?

Traceback (most recent call last):
  File "/opt/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 1923, in manageComics
    comics = helpers.havetotals()
  File "/opt/mylar/mylar/helpers.py", line 1183, in havetotals
    c_date = datetime.date(int(latestdate[:4]), int(latestdate[5:7]), 1)
ValueError: invalid literal for int() with base 10: 'Erro'

**Comment by evilhero** [comment]
Well since you can't get to the Manage page to see what the problem is, you would have to sort the main home page by the Published column. You could also just type in 'erro' into the Filter box in the upper right hand corner of the main page and that would bring up the filtered list as well.

One of those series has an 'Error' listed in that column and is causing the problem. 

You can probably try to fix it by just going into that series and trying to do a Refresh Series to see if it clears it up. Otherwise, you'd probably have to delete it / readd it.

**Comment by motioneso** [comment]
I can't get to the home page, BUT, I think I found the problem. I opened the db in a sql editor and saw that Y: the last man has a published date of Unknown, and it is also in the loading state. I started Mylar back up and got to that comic id, but when I try to delete it I get the same error. I restarted after trying to refresh Y and now I can't get back to the comic ID manually. I guess I need to figure out how to delete it from the DB?

**Comment by motioneso** [comment]
Deleted it from the DB, but no luck, still getting the error.

**Comment by evilhero** [comment]
Did you delete from the comics table and the issues table ?

**Comment by motioneso** [comment]
Well, it would have helped if I was editing the correct db... Evidently I have two instances of Mylar installed. Edited the correct DB to remove the offending comic (Daredevil had the error) and it is now working properly. Thanks!
