### ISSUE TITLE
Failed downloads from NZBs.in

### ISSUE THREAD

**Issue by Spartan304** [evilhero/mylar#1058]
Last week everything worked great but when Mylar attempted to get this weeks comics they all return the following error:

2015-06-12 15:23:00	ERROR	Unable to download nzb from link: http://nzbs.in/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&t=get&id=999690063c714c5417fc36d52c418d3e [https://nzbs.in/getnzb/999690063c714c5417fc36d52c418d3e.nzb&i=1460&r=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
2015-06-12 15:22:59	INFO	Download URL: http://nzbs.in/api?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&t=get&id=999690063c714c5417fc36d52c418d3e [VerifySSL:False]
2015-06-12 15:21:49	INFO	pausing for 60 seconds before continuing to avoid hammering
2015-06-12 15:21:49	INFO	Shhh be very quiet...I'm looking for The Walking Dead issue: 142 (2015) using NZBs.in (newznab)

I blanked my API key but if you need it for testing purposes or anything I'll PM it to you.  I removed and re-added the account and that didn't fix it.  I pasted the URL into my web browser and it grabbed the nzb file with no issue.  Also all of my other programs (Sonarr, Couch Potato, etc) are having no issues with grabbing from NZBs.in so I'm pretty sure it's something with Mylar.

**Comment by evilhero** [comment]
Should it not be https instead of http?

**Comment by Spartan304** [comment]
Yeah sorry, it was https before and when I re-added it I forgot.  I changed it to https, restarted, and still same error though.

**Comment by evilhero** [comment]
If you want to pass me that extra information then I can test it out, as right now in looking at the post, I can't see why it would be failing.

**Comment by Spartan304** [comment]
Ok I didn't see your email on your profile page.  How would you like me to send you the information?

**Comment by evilhero** [comment]
Yeah, I don't like spam too much - send the info to evilhero@mylarcomics.com and I'll take a closer look at things for ya.

**Comment by Spartan304** [comment]
Emailed :)

**Comment by evilhero** [comment]
Ok, not what you want to hear - but it pulled down the issue you posted the error above for on the first try. 

So what that tells me is that it's either one or both things:
- Are you on the development branch or the master branch ? 
- Your version of python is probably less than 2.7.7 

If I had to take a guess, I would probably guess that you're using less than 2.7.7 for your python ?

**Comment by Spartan304** [comment]
I'm on 2.7.6 for python.  As far as either branch is concerned how would I tell?

**Comment by evilhero** [comment]
To find the branch, it's given at the bottom of every page along with the commit you're on.

Odds are it's due to the python though, anything less than python 2.7.7 doesn't support SNI (which is basically any site that has shared hosting and utilizes https certificates). You'll probably have to update your version of python, which isn't a bad thing anyways since 2.7.9+ closes alot of security issues.

**Comment by Spartan304** [comment]
I'm on the development branch.  I followed a tutorial I found to update to Python 2.7.9 but after rebooting my server it still says I'm on 2.7.6. I hate Ubuntu sometimes lol....

**Comment by evilhero** [comment]
You probably have python 2.7.9 installed in another location, and just need to update the links. I'm betting you can start it by typing in 'python2.7' or something simliar...

I would've recommended using something like 'pyenv' instead of updating since it wouldn't have any possiblity of breaking your system or causing problems like you're having...but since you already updated python, you just need to find out where it is and relink things.

**Comment by Spartan304** [comment]
Got it running with the Python update and comics are downloading.  Thanks for your help!
