### ISSUE TITLE
Mylar can't find issues of "Empowered"

### ISSUE THREAD

**Issue by mutercim** [evilhero/mylar#1062]
Mylar seems to have trouble finding issues of Empowered. I checked dognzb so I know they are there, but mylar just says "Could not find Issue x of Empowered. I _think_ it may be confused because issues are named "Volume 1, Volume 2, etc," but I am not sure obviously.

**Comment by evilhero** [comment]
Yeah, it's more about the lack of an issue # within the filenames.  On CV I can see it says Volume 1 issue #1 kinda thing, which would mean mylar would have to match up to that in order to download it or even scan it in. 

I'd almost consider that a graphic novel / TPB of sorts just because there is no issue # - but it looks like mylar would be able to add the series, you would have to manually download the files, rename them to a name that coincides with what mylar thinks (as above), and you could then manually post-process the bunch and it should pick them up - provided you have each volume as it's own series within mylar (I would think). 

It's kinda for this reason, that mylar doesn't currently support graphic novels, compendiums or trade paperbacks - adding is one thing, searching and scanning is pretty hit and miss.

**Comment by mutercim** [comment]
OK, so after downloading the issues, I manually renamed the files simply "Empowered 001, Empowered 002," etc. That seems to have satisfied Mylar, it can now see them and tag them. That's sufficient for me. I thought I should follow up in case the information might be useful. Thanks for the quick reply.
