### ISSUE TITLE
Problems between SABnzbd and Mylar

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1065]
I have an interesting new problem between Mylar and Sabnzbd today.  I have attached an image of what my SAB queue currently looks like.  ALso, they are both on the same box.
![queue](https://cloud.githubusercontent.com/assets/1617434/8222817/2d3ca91c-153e-11e5-8771-61436c2a73a8.png)

**Comment by evilhero** [comment]
As long as you're running the most recent development branch, then odds are it's due to the localhost problem some users are encountering. 

Check what you have your mylar host address set to within the mylar configuration. Odds are it's set to 'localhost', try switching it to 0.0.0.0, saving the configuration and restarting mylar.

**Comment by wraith1385** [comment]
It was already set to 0.0.0.0

**Comment by evilhero** [comment]
Ok, then you can try one of these (or both, although leaving it as 0.0.0.0 will allow you to hit the mylar server from any machine in your network) :

- change the ip for mylar host in the mylar config to the actual local ip of your machine. Save & restart mylar. 

- enable the mylar api within thr configuration, and generate an api key. Save & restart mylar afterwards.

This should have been fixed in the latest development commit, so if enabling the api makes things work then I need to look at this again. 

Note that mylar generates a unique apikey just for sending nzbs to sabnzbd. The apikey that you generate isn't used for the purpose of sending nzbs. 

One othet question - what version of python are you running?

**Comment by wraith1385** [comment]
I actually tried the API thing first and that didn't work, but changing the the ip address to the actual machine's address did.  

My python version is 2.7.8

**Comment by wraith1385** [comment]
Also, I had to change autoProcessComcis.cfg to use my machine's address in order to get post-processing to work again as well.

**Comment by evilhero** [comment]
Yes you'd have to change the AutoProcesscomics.cfg to correspond to whatever you have in the mylar configuration - which I was going to mention but only after your got the nzbs to send again. Glad it's working now for ya though !

**Comment by richardjarrell** [comment]
I was having this same issue and changing the IP to the machine's IP instead of 0.0.0.0 just now fixed it.  The cfg file has it as localhost though (now also the machine's IP).

**Comment by conbud** [comment]
Yeah, I'm still having the same issue as well. I've been a bit lacking in keeping up to date with the commits recently and updated yesterday and ran into this issue.

Using localhost works fine except I can't access the site from anywhere but the server. Using 0.0.0.0 gives the above error in Sabnzbd. Using the IP of the machine is a hack that will force you to change the post processing script from localhost to the IP.

I hope you can get this working right again ... You're doing a great job with this project.

**Comment by evilhero** [comment]
It was kinda a necessity due to the changes in python and having to use the requests module to transfer items. This coupled with the https/SNI problems in addition to allowing api key interchangeability were all things that needed to get addressed before everything literally went even more south.

I've been a lot of time trying to fix these types of problems and it would seem that the hidden config.ini. option labeled as host_return might be helpful here. What you would do is leave the mylar host ip as 0.0.0.0 (meaning mylar will listen on all local interfaces) and set the autoProcessComics.cfg host to 0.0.0.0 (they need to be identical). Then in the config.ini,  with mylar not running, edit the host_return field so it has the full accessible ip & port..meaning if you were on  another local machine in your network and you wanted to load up mylar, the ip that you would browse to.  So, for example : 
host_return = http://192.168.1.75:8090

Load up mylar and it should send to sab as before, referencing the correct ip instead of a nulled one and downloads/post-processing won't be affected.

I'm working on automating this so that mylar will just try and best guess the ip, but I haven't been able to look into it much at the moment.

Let me know if doing the above works or not.

**Comment by conbud** [comment]
host_return works perfect... thanks again for the help. Keep up the great work!
