### ISSUE TITLE
Mylar not finding anything on indexer

### ISSUE THREAD

**Issue by hermy65** [evilhero/mylar#1066]
I have been running my own index for a good amount of time and have always had mylar pull everything from there with no issues until now. I can see everything in the index but mylar refuses to actually find anything when it searches for it. No errors or anything that i can see, running on development

**Comment by evilhero** [comment]
Can you post the log file showing a search breakdown? 

Is the index newznab+?

**Comment by hermy65** [comment]
Here you go

https://gist.github.com/hermy65/239a4ebe9c25328c7056

**Comment by evilhero** [comment]
The problem is that your indexer isn't indexing the releases property and stripping out thr crap.  The idea behind an indexer is that it allows one to just few the relevant information, not the stuff that has no bearing on the file. 

I'm going to guess you're running an nzedb? This issue has popped up a few times and it's due to nzedb not having the right regexs being applied to the comics newdgroups

**Comment by hermy65** [comment]
yes i am running nzedb, im curious why this issue just popped up, i had no problems last week with comics

**Comment by evilhero** [comment]
It looks like it's the way the poster posted the issues to usenet. Previous weeks didn't have the 'crap' (0-Day 2015.6.17) in the header title most likely.

**Comment by hermy65** [comment]
Nothing came down this week through mylar and i noticed that all of the files had the 0 day info on them again. I looked back through past weeks and found that they always have the 0 day info on them and mylar had always worked fine up until last week. Any other ideas on how to fix this issue?

**Comment by n3IVI0** [comment]
I am having a similar problem. I am using DogNZB and OZnzb for indexers. Everything appears to be correctly configured (mylar finds comics via ComicVine, can access pertinent config directory and Comics directories with correct permissions, creates directories for adding new comics). The problem comes when trying to find the comics to download from the indexers. It generates a functional url from the api (you can download the nzb with it), but then it errors out and won't transfer the download to SABnzbd. I can also verify the file exists by searching from the indexer's website.

Here is the error it keeps throwing:

Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/opt/mylar/mylar/search.py", line 234, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/opt/mylar/mylar/search.py", line 1327, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/opt/mylar/mylar/search.py", line 1817, in searcher
with open(nzbpath, 'wb') as f:
IOError: [Errno 13] Permission denied: u'/opt/mylar/cache/Death.of.Wolverine.01.of.04.2014.Digital.Nahga-Empire.nzb'

Mylar won't find anything to download. Suggestions? Thank you.

**Comment by evilhero** [comment]
```
IOError: [Errno 13] Permission denied: u'/opt/mylar/cache/Death.of.Wolverine.01.of.04.2014.Digital.Nahga-Empire.nzb'
```
Permissions problem - the user running mylar has to have 'rwx' access to the entire cache directory (in your case /opt/mylar/cache/). Without it, it can't access the file in order to write it to the cache, after which it sends it to your nzb client.

**Comment by n3IVI0** [comment]
I have that directory set to 777 and nobody:users. Should it be set to root? Also, I am running it from a docker, so the cache directory is not in /opt/mylar/cache, but in /mnt/cache/appdata/mylar/cache. Do I need to change the path somewhere?

**Comment by evilhero** [comment]
unless you specify the cache directory location within the config.ini, Mylar will default to the root_mylar_directory/cache location (so in your case it would be /opt/mylar/cache/). So, in theory, you would have to set the cache_dir within the config.ini to /mnt/cache/appdata/mylar/cache/

As far as perms, it would depend on what user is running the docker for mylar - the problem with running 3rd party apps against mylar, or any app like it, is really about how the permissions are all setup and if it changes any of the locations that under normal circumstances would default to proper locations.

I would try setting the cache dir first (make sure mylar isn't running when you edit the config.ini)

**Comment by n3IVI0** [comment]
Crud. Didn't work. It eliminated that specific error, but now it reads this:

Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1366, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
File "/opt/mylar/mylar/search.py", line 234, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/opt/mylar/mylar/search.py", line 1327, in NZB_SEARCH
searchresult = searcher(nzbprov, nzbname, comicinfo, entry['link'], IssueID, ComicID, tmpprov, newznab=newznab_host)
File "/opt/mylar/mylar/search.py", line 1808, in searcher
except OSError.e:
AttributeError: type object 'exceptions.OSError' has no attribute 'e'

**Comment by evilhero** [comment]
That looks like it's a code issue - but in relation to that, it says it can't locate the cache directory specified (so it tries to create it, and pumps out that error).

**Comment by n3IVI0** [comment]
Is it something I can fix, or is it a problem with the docker image itself?

**Comment by evilhero** [comment]
I guess it depends on what user is actually running mylar/docker. It looks like it can't even validate the cache directory which would mean it's still a permissions issue of some kind.

You 'could' try to edit line1808 in the /opt/mylar/mylar/search.py file. Change
```except OSError.e:
        if e.errno != errno.EEXIST:
            raise 
```
to
```except OSError:
        pass
```

**Comment by n3IVI0** [comment]
Tried a different docker, and it's working like a champ. The only hitch was the bug that causes "Empty NZBs", but applied the workaround of enabling the Mylar API, and now, along with your other tips, it's downloading comics as planned. Thanks for your help.
