### ISSUE TITLE
Does search run based on current year or "series" year?

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1076]
Several providers are publishing content under the current year, not the series year. For example, Wonder Woman 040 (2015) (Digital) (ThatGuy-Empire).cbz (when the "series year" is 2011). I was able to manually find a lot of issues, but mylar didn't find the same issues. How is mylar searching?

**Comment by evilhero** [comment]
The 2015 is the publication date as listed on the series detail page for the given series. Mylar will poll against that in almost all cases, as it's the distinguishing factor in differences between volumes. Otherwise mylar might also use the series year as the volume label depending on how the files are posted on usenet/torrents.

If mylar can't find the same issues, it's probably due to the way the files are named in relation to the series being searched for moreso than the actual Yeats involved.

**Comment by mnbf9rca** [comment]
ok thanks. i found the "fuzzy year" option too which helped slightly. is there a way to set that as a universal default?

**Comment by evilhero** [comment]
No, and it's an intentional non global. Having it enabled is not the most accurate way of retrieving results as its forgoing the year check, and most cases if a series gets rebooted within a year, there's a good chamce that you would get the wrong file as it marched up to the incorrect series.

**Comment by mnbf9rca** [comment]
thanks
