### ISSUE TITLE
Feature Request: In-browser reading with kthoom, yanapax, or similar

### ISSUE THREAD

**Issue by treyturner** [evilhero/mylar#1086]
I was wondering if it would be feasible to use an in-browser CBR/CBZ reader such as kthoom, yanapax, or Bala Clark's HTML5 reader to allow comics to be read from within mylar or on a page generated by mylar. This would have the benefit of making the collection readable from any remote browser which meets the reader specifications, and could be a nice fallback to access your comics when away from a reading device.

More info:
https://code.google.com/p/kthoom/
http://comicbook.yanapax.com/
https://github.com/balaclark/HTML5-Comic-Book-Reader

Thanks for your work on mylar and the consideration of this feature.

**Comment by evilhero** [comment]
It would be a nice feature to add into mylar, I'll admit - but I also see it being very problematic. Since mylar would be incorporating it within its own libs, it would require separate updating/trouble shooting that would possibly never get resolved. It would also take away from what the main purpose of mylar is - to download (and organize) comics.

This is something I might look at abit later on, as I didn't even know 2/3 of those items existed (TIL lol). Right now though, with the current backlog of problems and other enhancement requests that fall more in line with how mylar operates, this will be on the backburner for awhile most likely. 

I'm all for someone cloning the repo and doing a possible PR for this though ;)

**Comment by treyturner** [comment]
Understood, thanks! Wish I had some Python skills so I could lend a hand. As things stand I'd probably be more trouble than help :) Keep up the great work!
