### ISSUE TITLE
[REQUEST] Torznab support

### ISSUE THREAD

**Issue by the-Dakta** [evilhero/mylar#1089]
I know it's tough to set up torrent search, I get it, but I would love to see Torznab support (akin to what Sonarr uses), so that Jackett can be used to search other torrent providers.

**Comment by evilhero** [comment]
I had no idea that even existed (I use Sonarr, but not with torrents). 

It would definitely be easier to use torznab then having to setup torrent searching on a per site basis (although I don't see anything comic or music based which really would limit it's use - aside from 32p, what and waffles are both heavy into comics ).

I have to do some reading of how it works,  but it sounds like it's trying to stick close to the newznab api structure which would help in implementing it.

Do you know if you can change the default  categories?  From quick skimming it looks like it's restricted to just tv and movie need categories when searching torrent sites.

**Comment by the-Dakta** [comment]
Well this was a quicker response than I expected.

To be honest, I don't have much insight on what can be changed for it, or how it works, but Jackett is on github as well. I think it really just scrapes HTML results for whatever is searched for, so I imagine comics would work just fine as well. I just know that I would love more support than just Kat and 32p(which honestly, if I just had an account would probably suffice), and this seemed to be the easiest way to do it.

**Comment by evilhero** [comment]
Yeah, it looks like the categories are hard-coded within each torrent provider file (I was testing with IPT and couldn't get it to just hit the comics category). I'm not sure how to go about handling this as any URL that mylar would feed into torznab would have to have the category defined or else you'll get back completely wrong results and stagnate alot of the results.

I might have to ask for an enhancement request to allow for category definition either within the gui, or within the provider files. I'm attempting to see if manually forcing the category within the torrent provider file is enough to get things to poll properly, but since I don't use mono/net I have to figure out how to recompile the source cause I'm running ubuntu...

**Comment by Taloth** [comment]
Do any of these trackers/indexers support cbdb ids directly?
newznab and torznab prefer using the tvrageid, season+ep to search on series only reverting to text searches if the rid isn't known.
The idea is that the wildcard searches (q=) should be avoided if possible coz text searches are more heavy on indexer's database vs id searches (using a db index is orders of magnitude faster).
Of course it won't help much with Jackett, coz it does scraping, but you get the idea.
Anyway, even with text searches you still need a way to specify the issue.

I believe that the lack of proper indexing by the trackers is a huge flaw coz atm they're a lot like flea markets. Software like newznab does all that intelligent indexing, and trackers are missing an equivalent of that.

**Comment by the-Dakta** [comment]
I don't know about most of them, but I know that morethan.tv and (more
importantly), IPTorrents don't support search by ID, because they don't
have a public API. Instead, Jackett pulls the name from the source and
scrapes for that.

**Comment by evilhero** [comment]
@Taloth: There is no support for cbdb/gcd or comicvine id's (which Mylar uses) anywhere - and that's a portion of the problem. Unlike TV and movies, which have respective sites that have distinct id's that seem to have made their way to torrent sites as part of the identification process, comics have basically zero identification - almost as horrible as the naming conventions are.

All of the torrent based searching that Mylar does (thus far only KAT, as I haven't released the 32P one yet because I need to talk to the site ops beforehand) is reading the rss that gets returned from the search. I wish that the torrents followed the same aspect as newznab based sites and actually have an API that could be used, but the closest I've seen is the what.cd api - which basically just does screen scraping anyways.

Mylar always sends the search request with the issue # included (sometimes multiple times depending on the variation in the issue numbering) - but being able to limit the search to a distinct category for torrent searches on general trackers (like IPT for example), would lessen the amount of data being returned to be scraped and only return relevant data - which lessens the load for both the app and the site.

I realize that torznab is mainly for tv, but with couchpotato possibly adopting the usage the accommodation of categories that can be specified would have to happen as well (same with headphones - albeit with both they have their respective imdbid and mbid's they could fall back on in in theory).

I would whole-heartily endorse a torznab-based system akin to a newznab-based one as not having something like that in this day and age, with the way things are going, seems kinda 80's (I grew up then, so I can say that with relative confidence lol).

**Comment by Taloth** [comment]
The newznab api spec (and thus implicitly torznab as well) includes a specific t=tvsearch and t=movie search mode to avoid text searches.
But even Sonarr uses the generic 't=search' for anime, and that's not without problems because it returns more results that need to be filtered.

The reason why I asked is simple, I wanted to know if a specific t=comic mode was desired. But it seems that for now we'll have to do with t=search.

I briefly mentioned to @zone117x that Jackett should return the sites original categories mapped in the [custom](https://github.com/nZEDb/nZEDb/blob/master/docs/newznab_api_specification.txt#L574) 100000- range. While at the same time providing aliases on the original newznab categories (7030 for comics, I suppose). newznab and nZEDb don't have the same categories, but i thought it would be good to stick to the originals as much as possible and add 100000 to the site's own cats.
