### ISSUE TITLE
Torrent is not valid bencoding

### ISSUE THREAD

**Issue by Banaliteit** [evilhero/mylar#1093]
Hi

I've seen this issue before, but the solution was to update python to 2.7.9. However, I'm already using that version.
Mylar used to work fine but all of a sudden the torrents wouldn't load automatically in my bittorrent client and when I open them manually I get the 'unable to load "file": torrent is not valid bencoding!' error. Downloading them manually from the same site does work, but with mylar it doesn't. I have tried changing KAT proxies, but it still doesn't work.

**Comment by the-Dakta** [comment]
I'm having this same issue. Just started with the latest update of Mylar.

**Comment by evilhero** [comment]
The KAT proxy use is broken atm due to how torcache added in their automation stopper/fix. I tried to address normal access to KAT in the last development commit yesterday, but that will only work for those who aren't using a proxy and get normally get to kat.cr.

All I can suggest atm is to make sure you're on the development branch, you're running the latest build  (if you don't use a kat proxy ). Otherwise you'll have to wait for the patch probably later today to allow for kat proxy usage.

Note that the latest development build will attempt to use a fallback url if the initial download fails - I don't
