### ISSUE TITLE
Traceback Error when doing Manual Post-Processing

### ISSUE THREAD

**Issue by infected36** [evilhero/mylar#1099]
I get this every time I try to do a manual post process

> Uncaught exception: Traceback (most recent call last):
> File "C:\Mylar\mylar\logger.py", line 159, in new_run
> old_run(_args, *_kwargs)
> File "C:\Python27\lib\threading.py", line 763, in run
> self.__target(_self.__args, *_self.__kwargs)
> File "C:\Mylar\mylar\updater.py", line 159, in dbUpdate
> cchk = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload)
> File "C:\Mylar\mylar\importer.py", line 95, in addComictoDB
> comic = cv.getComic(comicid, 'comic')
> File "C:\Mylar\mylar\cv.py", line 145, in getComic
> dom = pulldetails(comicid, 'comic', None, 1)
> File "C:\Mylar\mylar\cv.py", line 85, in pulldetails
> file = urllib2.urlopen(PULLURL)
> File "C:\Python27\lib\urllib2.py", line 154, in urlopen
> return opener.open(url, data, timeout)
> File "C:\Python27\lib\urllib2.py", line 437, in open
> response = meth(req, response)
> File "C:\Python27\lib\urllib2.py", line 550, in http_response
> 'http', request, response, code, msg, hdrs)
> File "C:\Python27\lib\urllib2.py", line 469, in error
> result = self._call_chain(_args)
> File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
> result = func(_args)
> File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
> return self.parent.open(new, timeout=req.timeout)
> File "C:\Python27\lib\urllib2.py", line 437, in open
> response = meth(req, response)
> File "C:\Python27\lib\urllib2.py", line 550, in http_response
> 'http', request, response, code, msg, hdrs)
> File "C:\Python27\lib\urllib2.py", line 475, in error
> return self._call_chain(_args)
> File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
> result = func(_args)
> File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
> raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> HTTPError: HTTP Error 502: Bad Gateway

**Comment by evilhero** [comment]
Your version of mylar is having problems connecting to ComicVine. Make sure you're using your own ComicVine API key, and that you're not over the 400 hits / 15 minutes threshold (a tally-count is located at the bottom of every page, but if you use the same api across different apps Mylar can't keep track of those hits).

If both of those are fine, then you probably can't reach api.comicvine.com (or www.comicvine.com) due to your internet, or your IP was blacklisted from comicvine for either excessive hammering, or sharing of API keys across multiple IP's.

**Comment by infected36** [comment]
Thanks for the quick response, but the thing is, I only use my API key here and the tally never goes over 100. I can access both of those sites with no problem. I even tried using another comicvine account for the API and got the same error...

Also, I just wanted to say, your product is absolutely great and gorgeous. I fell in love with it the moment I saw it. I have a lot of comic books and this has helped me so so much.

**Comment by infected36** [comment]
Just some further information, every time it does try to process, it places the comic in another folder called 496891, though the last numbers change. It also places a rar version of the file there.

**Comment by evilhero** [comment]
Well thanks for the kudos on the app - hopefully things can keep on trucking for ya (once this is figured out of course).

Can I ask how you're initiating the manual post-processing? The bad gateway indicates it's having a problem reaching the destination, but the only thing mylar ever accesses outside of itself is comicvine.  

Is there anything in the mylar.log file itself indicating any additional information? 

Also the numbers are supposed to be there (it's the comicvine issueid).

Do you do metatagging as well by chance within mylar?

**Comment by infected36** [comment]
I just go to manage, manual post-processing, put the folder location and click on go.

I did, but I wasn't using it, so I just disabled metadata tagging right now, then tried to process, this time it ran perfectly with no problems. Do you still need the log?

**Comment by evilhero** [comment]
Yeah if you could..but re-enable the metatagging (restart mylar after the update) and try a manual post-processing again if you could please.

All I need to see is the portion of the log that involves the metatagging as it is probably screwing up therein.

What version of comictagger are you using with mylar?

**Comment by infected36** [comment]
No, I had it on, I just wasn't using it. I haven't used comictagger

Where's the log?

Also, it's now constantly doing a a cycle of WindowsError: [Error 32]. It says line 77, something about handlers.py

**Comment by infected36** [comment]
it actually stopped doing that when I restarted a bunch of times

**Comment by evilhero** [comment]
The handler is a logging error - it can't access the logs because they're locked by the process. You should have a blurb in the log file about using the concurrent log handler (windows only) which eliminates that error.

Just so I have clarification, turning off the metatagging allowed mylar to post-process fine?

You had said you never had it setup but you had it enabled - what exactly did you have enabled? If it couldn't find the comictagger libraries (they don't come with mylar), then I could definitely see that causing some problems,  albeit not a bad gateway error.

**Comment by infected36** [comment]
Apparently, yeah.

I just had the metatagging option turned on in the quality and post processing tab
