### ISSUE TITLE
Post processing python error + weekly pull list folder

### ISSUE THREAD

**Issue by digitaldiatribe** [evilhero/mylar#1102]
Hi,

On the development branch I'm seeing the following error. I think it's either from RSS searching or post-processing. Not exactly sure.

Uncaught exception: Traceback (most recent call last):
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/PostProcessor.py", line 886, in Process
self.Process_next(comicid, issueid, issuenumOG, ml, stat)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/PostProcessor.py", line 1375, in Process_next
updater.forceRescan(comicid, module=module)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/updater.py", line 1375, in forceRescan
filechecker.setperms(rescan['ComicLocation'])
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/filechecker.py", line 1239, in setperms
os.chown(os.path.join(root, momo), chowner, chgroup)
TypeError: an integer is required

I see it sometimes in the master branch when I run post-processing manually however.

I'm running Mylar as a plugin on FreeNAS and upated internally.

On that note, I'm also having issues with weekly pull lists. The download button does not create the weekly folder with downloaded comics in it and no error is logged from what I can tell.

**Comment by evilhero** [comment]
You need to set the owner:group within the mylar configuration most likely. If it isn't provided mylar will default to setting both to the user running mylar.

**Comment by digitaldiatribe** [comment]
Hmm. I had it set, but I guess it doesn't like mixing names and ID numbers. I made both fields use names and it seems to be working now.

Weekly folder creation still isn't working however and I still don't see errors in the log for it. Anything I can look at?

**Comment by evilhero** [comment]
Check your config.ini for a field called 'weekfolder', for folder creation to be in for weekly pulls that has to be set to 1.

I'm curious about the numbering /names..I had tested on my local Ubuntu and both seemed to work fine - I must be missing something or need to do an additional check perhaps.

**Comment by digitaldiatribe** [comment]
Config.ini shows weekfolder = 1.

**Comment by evilhero** [comment]
Ok so that's right. 

Are the issues downloaded already (in a Downloaded Status on the pull-list)? If I remember how it works (it's been awhile), it creates the new folders on post-processing runs only - which if that's the case, needs to be corrected.  Once it's creates it will then move over said issues during post-processing of the given issue. 

Now that I'm thinking more about this, it's quite possible the download button isn't working since a lot of the backend code got changed. I'll see if I can figure out what's going on and report back.

**Comment by digitaldiatribe** [comment]
Yep, issues in the pull list are downloaded with that status in the pull list and were processed into their respective title folders.

Thanks for your time!

**Comment by evilhero** [comment]
Ok, just checked on this - I forgot I had modified the function awhile ago, but never finished the proper calls. Needless to say, all it would do properly is update the checkbox setting - it never even attempts to do the copying of files (this is only for the Download button, normal post-processing of said files should still be populating them properly into the weekly folders).

Needless to say, it's fixed now on my local repo - so this will be fixed in the next development commit (along with some other items, I'm really hoping to get it out for tomorrow)

**Comment by digitaldiatribe** [comment]
Awesome! Thanks for the quick turn around. Everything else has been solid with this app so far!
