### ISSUE TITLE
Request: Fork or add Ebook support :)

### ISSUE THREAD

**Issue by ruinit** [evilhero/mylar#1105]
Love mylar and thanks! Is there any chance you could make it also do ebooks in general? Or could someone fork this maybe? There use to be a ebook downloader "LazyLibrarian" but author dropped it and everyone who picks it up drops it shortly after :( 

Thanks

**Comment by evilhero** [comment]
There's probably a better chance of a zombie outbreak happening before ebooks get added ;) I barely have enough time some days to dedicate to mylar as it is, adding in a completely new purpose would just kill me - plus I have zero interest in ebooks so that plays a pretty big factor in doing things as a hobby.

Anyone's free to fork it and do whatever with it, although I thought lazylibrarian was being updated just a month or so ago?

**Comment by ruinit** [comment]
LOL ok :) yea ther was someone picked it up for a bit but nothing since may. Someone smart like you could probably fix the bugs in it but no one seems to stick with it. Thanks anyway
