### ISSUE TITLE
Notifications to pushbullet aren't working

### ISSUE THREAD

**Issue by tjiddy** [evilhero/mylar#1110]
I see this in the logs when it tries to send a notification:

```
19-Aug-2015 08:05:52 - ERROR :: Post-Processing : [POST-PROCESSING][NOTIFIER] PushBullet request failed: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v2/pushes</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by tjiddy** [comment]
Sorry, forgot to mention I'm on the latest development branch

**Comment by evilhero** [comment]
Ah crap - yeah that wasn't quite working. 

I have it working now, will push out momentarily for ya - it will still send to all your devices by default (I still need to mangle something together for specific device id's, but at least it will work as is now)

**Comment by lokenx** [comment]
I'm running the dev branch on commit caa8654 and still getting the above issue. Python is 2.7.6 running on Ubuntu 14.04.3.

**Comment by evilhero** [comment]
Your version of python isn't at a compatible level for SNI support with https certificates which is why it's failing. 

It's a matter of security, so you should probably try to update to python 2.7.9 / 2.7.10 both of which fix the issue with invalid https certificates and will ensure that the https certificates are validated properly. Python versions less than 2.7.7 have this problem and I believe are considered insecure due to the certificate signing problem (not 100% sure though)

Notifications were tested and worked on Ubuntu 12.04LTS running python 2.7.9 using pyenv (base 2.7.3).

**Comment by lokenx** [comment]
Thanks for quick turn around! I was actually just loading up your code to see if I could help figure out what's up, but didn't think to check into my Python version...doh!

Keep up great work! (Partly inspiration for my own app :+1: )

**Comment by tatsumasagc** [comment]
I am also getting this error

Mylar Version: master
-- git build e32462330dac05efd8b36c5019f1186cc211460c.
Python Version : 2.7.12

**Comment by evilhero** [comment]
@tatsumasagc: this error hasn't popped up in almost a year and nothing has changed in the last few commits to affect this. 

Please start a new issue and post the error message you're receiving as well as any debug logs

**Comment by benyjr** [comment]
I'm still having this issue again, after it stopped working sometime after April 28, which is the last time I got a snatch notification.  Sending a Release the Ninjas message still works, however.

Mylar Version: development -- git build 3d91a5e5214eb9043769767603fd15ab517b7bf7. 
Python Version : 2.7.12

**Comment by evilhero** [comment]
Weird, it was working although I did make some changes to allow for the test connection button to use the on-screen information instead of using what's in the config.ini (in case it's changed kinda thing). I don't believe my PB works anymore, but I'll try and see what's going on and flip a message back so you're aware of any findings / fixes.

**Comment by evilhero** [comment]
@benyjr: I haven't had a chance to look into PB itself more just yet, but it occurred to me that you might be experiencing the same problems that others users have encountered with not receiving notifications due to an invalid bencode.py/bencode.pyc file in the root/mylar subdirectory. Are your snatches indicating as snatched status, or are they not changing after a successful snatch send to your client (the telltale sign of the bencode problem)?

**Comment by benyjr** [comment]
Right now I'm not getting any notifications at all. But I've attached a screenshot of one of the last notifications I did receive. 

![screenshot_20170624-091145](https://user-images.githubusercontent.com/14084052/27508885-a20e442a-58bd-11e7-8a04-a69f7494f42e.png)

**Comment by evilhero** [comment]
Yep, check your mylar subdirectory and see if that bencode.py / bencode.pyc file(s) exist. If they do, delete them both (with mylar shutdown), and then delete all the .pyc files from that same directory. The problem is that it tries to get the hash of the torrent before sending the notifications, and never gets that far because it's using the wrong bencode module (which is now located in the /lib subdirectory)

**Comment by benyjr** [comment]
OK. I'll let you know what happens the next time a comic is snatched.

**Comment by benyjr** [comment]
Hi @evilhero, this fixed the issue. I just tested it today and I received both snatching and post processing notifications. Thanks!

**Comment by evilhero** [comment]
No problem! Glad it fixed the problem for ya :)
