### ISSUE TITLE
BUG: After selecting +Add Series from the weekly pull list the next screen does not display any comic information

### ISSUE THREAD

**Issue by blindguy** [evilhero/mylar#1112]
After selecting +Add Series from the weekly pull list the next screen does not display any comic information.  In this example I am using CAPTAIN BRITAIN AND MIGHTY DEFENDERS

![image](https://cloud.githubusercontent.com/assets/11575103/9364834/270cdb4c-4663-11e5-92b4-f323a2e2b079.png)

![image](https://cloud.githubusercontent.com/assets/11575103/9364841/34cd758e-4663-11e5-96e1-8308d843ff17.png)

**Comment by evilhero** [comment]
'Tis because the title is incorrectly mapped between CV and the pull-list.
If you change the search to be 'captain britain and the might defenders' it will return the proper title:
[img]http://i.imgur.com/JWxSTB4.png[/img]

You can make use of the substitutes.csv file and add in the entry to point to the correct spelling of the title which will then force mylar to substitute the correct spelling whenever that item is in the pull-list.

Having Mylar remove 'the' from searches can be problematic as well as then it will return a greater number of false hits, and increase the api hits accordingly (which may make you hit the limit sooner).

I'll see what I can do from this end, but using the substitutes.csv file for anything like this is probably the easier method to use (plus it has the benefit of applying to every pull-list in the future).

**Comment by blindguy** [comment]
Awesome, going to go try playing with substitutes.csv.  Haven't used them before.  

Thanks again, I LOVE MYLAR!!

**Comment by blindguy** [comment]
So I fixed CAPTAIN BRITAIN AND MIGHTY DEFENDERS but I'm having the same exact problem with House of M and Howard the Hu
