### ISSUE TITLE
Duplicate Downloads

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1117]
This isn't a big issue as comic files are relatively small and it doesn't hurt anything, but oftentimes the same issue will download twice, a couple of minutes apart.  Like I said, it doesn't really affect anything as both downloads process properly and the new issue just overwrites the old one, but I was wondering if there's some setting or something I have wrong.

**Comment by evilhero** [comment]
This was am issue a few months ago that I thought was resolved, but perhaps not.

What was happening in those cases was that the Force Search was running a search on a fairly big Wanted list. While the searching was happening, the rss check was automatically run at the 20 minute interval. Since the search list is a snapshot of Wanted issues at a given point in time, the Force search had the given issue in its queue but hadn't hit it yet,  the rss check would hit it and find it and mark it as Snatched/Downloaded. Then, the Force Search found it at a later point, and because the snapshot at the time had it as Wanted it tries to search,  and redownloads it.

I guess I'd need to know, do you have a fairly large Wanted list - the more providers you have the more this would impact this problem too I believe.

**Comment by wraith1385** [comment]
I think on average my Wanted list is about 12-18 items each week and I'm using 2 providers.

**Comment by evilhero** [comment]
Sounds like a normal size so it's probably a timing issue like I mentioned above. I'll have to look into this abit more as it's a fairly difficult thing to reproduce and then catch the log - but I'm pretty sure I can fix this so it will stop happening if it's a timing issue alone.

**Comment by evilhero** [comment]
This should be fixed at this point (seeing as how it's been a year now), so I'll go ahead and close this issue. If the issue still exists, please open a new ticket with the new details (I'm trying to keep the tickets relevant to the newest code-base + cleaning out old issues that no longer apply).
