### ISSUE TITLE
Enhancement Request: cover.jpg as folder.jpg

### ISSUE THREAD

**Issue by scooterpsu** [evilhero/mylar#1127]
I use Ubooquity (handy online viewer, can generate a feed that apps can connect to), and it's not great with cover art. It uses the cover of the first comic as the folder pic for that folder, but it's lower-res.

It can, however, use folder.jpg as the folder image, and that can be higher res.

Could we get an option to save cover.jpg as folder.jpg? 

I'm currently running a script to catch and rename them as they're generated, but that's sub-optimal. :)

**Comment by scooterpsu** [comment]
Actually, would it be possible to also get a way to generate all missing cover art files too?

**Comment by evilhero** [comment]
Having the option to change it from cover.jpg to folder.jpg (or whatever), would be farily easy to do - it's only 1 or 2 lines that would have to be changed, so nothing big.

The re-generation of all missing cover art though would be abit more - only because if it's missing in the first place, then Mylar probably wasn't able to grab it properly and subsequent attempts might not resolve that (there are a few series that have covers that it's not able to download no matter what for some reason - usually titles that have a '/' in them). Not to mention you'd be hammering the CV servers  pretty hard if you're mass updating a bunch - but nothing that can't be handled, just would take some testing prior to using it ;)

**Comment by scooterpsu** [comment]
Awesome.

I see what you mean about hammering the CV servers, but I think this might be something different. Mylar has the art already, I more meant the option to save that art to the comic folders, since I had the option disabled when I originally setup Mylar, but now I'd like the covers saved in the folders.
