### ISSUE TITLE
Can't find issues of comic that are available

### ISSUE THREAD

**Issue by ManOrMonster** [evilhero/mylar#1133]
I'm trying to get Phonogram: The Singles Club. Mylar got the first issue but somehow can't seem to find the others.

The one it found is titled `Phonogram - The Singles Club 01 (of 07) (2008) (digital) (Minutemen-PhD)` but the others are titled in this pattern: `Phonogram - The Singles Club 02 of 07 2009 Minutemen-DTs`

I removed the year and set alternate search name as `Phonogram - The Singles Club` as well.

**Comment by evilhero** [comment]
Yeah unfortunately in those types of cases, removing the year and/or using the Alternate Search Names won't help. It's a problem with the way that the files are posted on Usenet, along with the way that Mylar parses the files. Since there is no accepted (or enforced) naming convention for comics, these types of situations occur  - for whatever reason, why the poster changes the actual naming of the files to remove the brackets is beyond me, but it's done pretty rampant.

Mylar uses the bracket positions in order to determine the issue year if present, along with the series title and issue number. The problem with the way the naming is in the files that you can't grab, is that Mylar has no way of knowing if the issue # is 02 or 07, or even 2009 (that one it should know). With the brackets included the (of 7) doesn't get included and Mylar can tell exactly what the issue number is. Without it, it's kinda a crap shoot as it doesn't know even if the word 'of' is part of a series title or not.

I can try to build in some kind of logic for this type of handling, but it honestly might cause more problems than not. It might be a better option to allow the user to manually select an issue to download from the search results, which has other benefits as well obviously.

**Comment by ManOrMonster** [comment]
Allowing a user to manually select would be a great step forward.

As far as finding the proper title is concerned, perhaps something like this lazily written and barely tested regex will help: `(\d+)(\s*|of|\[|\()+\s*(\d+)`

This will find the first and second number in any of the following scenarios:

01 of 10
03 (of 100)
004 of (37)
10 [of 40]
12 of [9070]
12of89
13[43]
97(98)

This will work as long as there is not any sort of number before the issue sequence. Maybe it could do a second search using something similar if the first one fails?
