### ISSUE TITLE
issues snatching

### ISSUE THREAD

**Issue by redboyke** [evilhero/mylar#1135]
im in a hospital and i have installed a router downstairs has a 10.xx.xxx. internal ip
external ip is something like 194.78.xx.xx

in my room i have a mypassport wireless who connect as a client to the wifi downstairs
so i always have perfect bars and dont have to keep searching for a wifi sweetspot.
this mypassport gives me 192.168.60.105 as internal ip

now the problem is mylar(http://localhost:8090/) sends a snatch to sabnzbd(http://localhost:8080/) like this:
http://192.168.60.105:8090/api?apikey=xxx&cmd=downloadNZB&nzbname=xxx.nzb
and it fails to open it cause i think somehow the actualy network of the hospital is refusing it
but if i change it to http://localhost:8090/api?apikey=xxx&cmd=downloadNZB&nzbname=xxx.nzb
and try to snatch it manualy
it snatches in the browser. what do i need to change in mylar so it goes to localhost while snatching instead of 192.168.60.105?

**Comment by evilhero** [comment]
You can try setting the host_resolve in the config.ini to either 'host_resolve = http://localhost/' or 'host_resolve = http://0.0.0.0/' 

Not sure if either would work, if they don't the only other option would be to make sure that port-forwarding is enabled out the router for port 8090 so that it can then hit the IP properly on the given port. Keeping it set to localhost would ensure it never leaves the local machine, but again - this configuration is dealing with hospital networks which are usually pretty locked down (referencing a specific ip/port on such a network would require proper authentication amongst other things possibly, so it might not be so cut & dry)

**Comment by redboyke** [comment]
tried setting host_resolve = http://localhost/ but it gets removed from the ini after bootup
the portforwarding also didnt work cause the hospital connection only accepts 80 en 443
i also tried connecting to the router directly and it also gave me the internal ip instead of localhost
same with my galaxy S4 with 4G connection wich is outside the hospital network
so it's pretty much a mylar thing sending the wrong ip it did not do the comicRN thing on this computer but i did on my nas at home is that why?

**Comment by redboyke** [comment]
i edited my search py to fileURL = 'http://localhost:8090/' + 'api?apikey=' + mylar.DOWNLOAD_APIKEY + '&cmd=downloadNZB&nzbname=' + nzbname

and it snatched it without issue

**Comment by evilhero** [comment]
Think that was my fault ..it's not host_resolve but host_return. Which explains why it got removed after restart as it's not a value that mylar will write to the config.ini

**Comment by redboyke** [comment]
host_return = http://localhost:8090/ worked thx
