### ISSUE TITLE
Error fetching data from dognzb:

### ISSUE THREAD

**Issue by redfro** [evilhero/mylar#1138]
For the past few days I've consistently gotten this error in my logs. Dognzb has always worked before, but now it seems like no matter what I try (restart, change api) it won't work. Any ideas?

**Comment by evilhero** [comment]
I believe they're doing some api maintenance (today at least) due to some api issues over the past few days (search was affected to I believe)

Is there anything in the mylar.log file indicating what the exact error from the site is?

**Comment by redfro** [comment]
All it says in the logs is "Error fetching data from dognzb:" It's the same thing that I've always gotten from NZB.SU but I understand that's on their end. Nothing else in the logs. And from looking at it it's been going on for 3+ days.

**Comment by redfro** [comment]
It also doesn't seem to be happening on my other services (couchpotato, etc.) so that would lead me to believe it's not dognzb...

**Comment by evilhero** [comment]
I'm on dog so I'll try later on to see if I can replicate the problem. Nzbsu though I'm not a member of so if they've changed something on their end I wouldnt be able to test. 

Just so I'm aware to, can you indicate what OS, python version and build of mylar you're running? 

Is it happening to every attempt to download?

**Comment by redfro** [comment]
Running on an Unraid server.
![10-1-2015 9-53-57 am](https://cloud.githubusercontent.com/assets/13789226/10224204/95537558-6822-11e5-81e3-b587bd3f0e84.png)
![10-1-2015 9-54-35 am](https://cloud.githubusercontent.com/assets/13789226/10224207/99452062-6822-11e5-9616-86a825231dc8.png)

**Comment by evilhero** [comment]
I just pulled down the exact same issue from dog with no problems, so at this point it appears to be a configuration problem of some kind possibly.

Since you're running on unraid (using a plug in I'd imagine), the issue might be permissions. Mylar will download the nzb first to the cache directory and then from there send it to your sabnzbd client.  When mylar downloads the nzb it assigns the permissions as provided for on the Web interface tab of the configuration.  I would ensure that those line up with what you need in order to ensure that mylar can write to that directory properly - something might have changed on that side.

Otherwise,  do another search for the said issue and then post/send your mylar.log file (not the gui log) so I can see the debugging information and try to help figure out what's happening.

**Comment by redfro** [comment]
OK, so I remembered that I upgraded my Unraid plugin a few weeks ago, so I downgraded to the earier version and it started working again. Weird, but obviously not Mylar's fault. Thanks for everything you do on this!
