### ISSUE TITLE
"Enforce Renaming/MetaTagging options (if enabled)" doesn't stick

### ISSUE THREAD

**Issue by mnbf9rca** [evilhero/mylar#1141]
1. when in a story arc select the checkbox for "Enforce Renaming/MetaTagging options (if enabled)"
2. Click the "update" button
3. the checkbox is no longer checked. Files do not get renamed.

**Comment by evilhero** [comment]
Currently it's just a placeholder - so it doesn't work (which is why it doesn't save the state of the button itself).

If you download your arc issues using the 'Search for Missing' option in the arc details page, or you use the manual post-processing - Mylar already uses your default metatagging options within the configuration screen so as long as you have metatagging enabled and/or renaming, it will be used for the arc issues as well.

I'll mark this as an enhancement / bug fix so I can remember to address this when I get a chance.
