### ISSUE TITLE
Large Collection - Import Results Management 

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1142]
Have a large comic collect (over 100,000) Unable to add all comics. Import Results Management only shows a small sample. Request a select all button

**Comment by evilhero** [comment]
Do you mean a 'select all' as you can't see all the results on the one page,  or does it not show any additional paging for the results?

**Comment by F688** [comment]
Both, can not see the results on the one page and request a select all button to import all titles on the page. Really like what you have here.

**Comment by evilhero** [comment]
I believe there's already a select all button (it's a check box located in the column heading area for the check boxes ), where you would click that and then select from the drop down the import option to import all of the selected on the given page.

I've done up a 'Mass Import' button that will be located at the very top of the page which will import anything that is in a status of 'Not Imported' and because it's a direct query on the db there's no paging restrictions (it will do them all).

I'm just cleaning up some of the code and will push it out in the next development commit.

**Comment by Riechao** [comment]
I don't have much new to add, but I just moved from one server to an other and I have a huge collection. Tried to import, there is no 'select all button' in the column header, so I just ran some javascript in the console to check them all... but it didn't seem to do anything when I chose 'start import' in the dropdown. I did click the 'import' link on a few, and it imported them.... 28 out of ... a lot.

**Comment by evilhero** [comment]
Yeah that's the internal counter of mylar - once it hits 400 within 15 minutes it halts all further access to CV. After 15 minutes it releases the lock and you can continue again. CV doesn't have a way to check against their server how many api hits you've done (which would solve alot of problems if they did), so mylar keeps track of its' usage as best it can.

**Comment by F688** [comment]
Evilhero
Thanks look forward to the new commit

**Comment by ElementSixtySix** [comment]
F688 I'm interested to know how long it took Mylar to scan your collection. I've done this process a few times and found 3-4 days is the timeframe for scanning. Importing then takes another day.

**Comment by F688** [comment]
Log shows the scan lasts about a minute. Don't know about the analysis. Have not seen any log info on importing

2015-10-22 17:10:46 	INFO 	Successfully loaded 72 series from your watchlist.
2015-10-22 17:10:46 	INFO 	loading in the watchlist to see if a series is being watched already...
2015-10-22 17:10:46 	INFO 	I've found a total of 109324 comics....analyzing now
2015-10-22 17:09:53 	INFO 	I've found a total of 0 comics....analyzing now
2015-10-22 17:09:53 	INFO 	Scanning comic directory: F:\Comics
2015-10-22 17:08:03 	INFO 	[RSS] Watchlist Check complete.

**Comment by F688** [comment]
I'll monitor it for the next week to see if any additional comics are imported from the collection

**Comment by evilhero** [comment]
I have been saying this for awhile but I think the next thing I try to fix up abit is the importing. 

Scanning in 100,000 comics is going to take some time as mylar has to parse each filename and then store the results (in memory temporarily or the db). Adding in scanning for Metadata,  whether it's prior to the parsing or after failed parsing just adds more time obviously.

I'll start looking at this tomorrow abit after I push out the next dev commit. I have a few ideas that might better manage large collections to be imported but I haven't had a chance to put the ideas to code yet

**Comment by F688** [comment]
Update: Still waiting for import to add comics. Will continue monitoring

**Comment by evilhero** [comment]
@F688 : What are you waiting to import?  The weekly pull comics,  or running a manual import?  The import option doesn't run at predetermined times, it's only a manual option to import.

(Sorry if I'm confused about your exact problem - think I had a brainfart)

**Comment by F688** [comment]
No problem.

Basically, I start Mylar.py, go to Manage, set directory path, checked auto add, & hit save changes and scan, and then wait for the comics to be added (imported) into Mylar.  If I go to Import Results Management page no series are shown. It works fine when I test it with one series (where the Import Results Management button pops up) so I assume it has to be due to the processing time required for all those comic (which you mentioned and it was noted by ElementSixtySix that it would take about 3-4 days). Nothing has happened after 6 days so I just posted an update/status message and stated that I will continue monitoring.

**Comment by F688** [comment]
Also got this error:2015-10-29 15:05:15 	INFO 	delaying startup thread for 30 seconds to avoid locks.
ERROR 	Uncaught exception: Traceback (most recent call last):
File "c:\mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\mylar\mylar\librarysync.py", line 570, in scanLibrary
logger.fdebug("comicname: " + soma_sl['comicname'].encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 21: ordinal not in range(128)
NFO 	Starting mass importing...109473 records.

**Comment by evilhero** [comment]
That error would stop the import from completing.  It shouldn't take days to import as it's just scanning based on filename. It doesn't do any comparisons against CV at that stage. But that error would stop the entire process.

0xbc is the unicode character for 1/4, which is in one of the filenames in the directory you're scanning.  I can remove that error so it doesn't pop up, but until then you'd have to remove the filename from the given directory temporarily to let the scan continue further.

**Comment by ElementSixtySix** [comment]
Ah and a mini lightbulb moment. I've got hundreds of comics with all sorts or weird characters. Ö, é, ê, ú, ½ etc.
How to isolate and rename or exclude?

**Comment by F688** [comment]
Ya, file names are derived from comictagger / comicvine so I expect to have a number of naming issues. I'll start renaming. Thanks

**Comment by F688** [comment]
Finished the renaming process. I believe all titles are on the Import Results Management page, Hit the Mass Import button and only 96 titles out of 12,250 show up. Am I missing a step? All comics were previously tagged via comictagger (ComicRack). Should Metadata Tagging be disabled to speed the process?. Folders are set up as $Publisher/$Series

**Comment by F688** [comment]
Ultimately I would like the folders to be set as \\$Publisher\$Imprint\$Series\$Volume\ were metadata fields without an entry are ignored so if there is not entry in Volume the comic is filed under \\$Publisher\$Imprint\$Series\

**Comment by evilhero** [comment]
It's quite possible you're hitting some CV api restriction/ rate limiting.  CV keeps on changing what's allowed, and what's not allowed just gets temporarily banned. Currently it's 1 api request / 1s,  which if you're using the latest development commit or follows @2s intervals. If you're on the master branch or not up to date on the development branch then you're using an outdated  api limiter and you'll hit the rate limit / temp ban quickly. You should have something in the mylar.log file indicating an error/problem possibly with the api during the import process.

The metatagging isn't available just yet ( button is a placeholder atm ), but it's nearing completion soon.

The only problem with your ultimate folder structure is that CV doesn't track imprints - just publisher. So there is no $Imprint option within mylar due to this. It would require a separate mapping method to map the correct imprints to the right publisher.

As far as the volume / no volume option within the directory appearing,  mylar already does this. So long already you're not using $VolumeY,  it will remove it from the formatting (VolumeY is Volume year which every series would have).

**Comment by evilhero** [comment]
Seems CV forgot to change back the default rat limit they had for testing of 5s down to the stared 1s. Meaning that if your requests were coming in at < 5s apart, you would eventually trip their rare limit/ban. They said this would be fixed on Monday back down to 1s intervals, so in the meantime in the config.ini of mylar there's a 'cvapi_rate = 1'  setting which you can change to 5 or 6 in order to circumvent the rate limit they have in place until Monday ( just make sure to change it back on Monday/Tuesday )

**Comment by F688** [comment]
I'll make the change as see what happens. Thanks for the support.

**Comment by F688** [comment]
Received the following errors
2015-11-26 00:12:50	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 568, in addComictoDB
logger.fdebug('issue: ' + str(latestiss) + ' status before chk :' + str(statbefore['Status']))
TypeError: 'NoneType' object has no attribute '__getitem__'
2015-11-26 00:12:49	INFO	[FILE-RESCAN] Total files located: 1
2015-11-26 00:12:49	INFO	Now adding/updating issues for 1001 Arabian Nights: The Adventures of Sinbad
2015-11-26 00:12:49	INFO	moving F:\Comics\Marvel\100th Anniversary Special X-Men\100th Anniversary Special - X-Men - 001 (2014).cbr ... to F:\Comics\Marvel/100th Anniversary Special X-Men\100th Anniversary Special - X-Men - 001 (2014).cbr
2015-11-26 00:12:48	INFO	[FILE-RESCAN] Total files located: 1
2015-11-26 00:12:48	INFO	Mass import - Move files
2015-11-26 00:12:48	INFO	imported is : yes
2015-11-26 00:12:48	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 568, in addComictoDB
logger.fdebug('issue: ' + str(latestiss) + ' status before chk :' + str(statbefore['Status']))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by F688** [comment]
And these errors
2015-11-26 00:13:15	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 523, in addComictoDB
issuedata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
File "C:\Mylar\mylar\importer.py", line 1166, in updateissuedata
weeklyissue_check = annual_check(comicname, SeriesYear, comicid, issuetype, issuechk, weeklyissue_check)
File "C:\Mylar\mylar\importer.py", line 1562, in annual_check
sresults, explicit = mb.findComic(annComicName, mode, issue=None)#, explicit=True)
File "C:\Mylar\mylar\mb.py", line 132, in findComic
searched = pullsearch(comicapi, comicquery, 0, explicit, type)
File "C:\Mylar\mylar\mb.py", line 73, in pullsearch
file = urllib2.urlopen(PULLURL)
File "C:\Python27\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Python27\lib\urllib2.py", line 437, in open
response = meth(req, response)
File "C:\Python27\lib\urllib2.py", line 550, in http_response
'http', request, response, code, msg, hdrs)
File "C:\Python27\lib\urllib2.py", line 469, in error
result = self._call_chain(*args)
File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "C:\Python27\lib\urllib2.py", line 656, in http_error_302
return self.parent.open(new, timeout=req.timeout)
File "C:\Python27\lib\urllib2.py", line 431, in open
response = self._open(req, data)
File "C:\Python27\lib\urllib2.py", line 449, in _open
'_open', req)
File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "C:\Python27\lib\urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "C:\Python27\lib\urllib2.py", line 1197, in do_open
raise URLError(err)
URLError: 
2015-11-26 00:13:14	INFO	Successfully imported : 1001 Arabian Nights: The Adventures of Sinbad
2015-11-26 00:13:14	INFO	[FILE-RESCAN] I have physically found 14 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 14 / 14 ]
2015-11-26 00:13:12	INFO	[FILE-RESCAN] Total files located: 14
2015-11-26 00:13:11	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 95, in addComictoDB
comic = cv.getComic(comicid, 'comic')
File "C:\Mylar\mylar\cv.py", line 144, in getComic
dom = pulldetails(comicid, 'comic', None, 1)
File "C:\Mylar\mylar\cv.py", line 85, in pulldetails
file = urllib2.urlopen(PULLURL)
File "C:\Python27\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Python27\lib\urllib2.py", line 431, in open
response = self._open(req, data)
File "C:\Python27\lib\urllib2.py", line 449, in _open
'_open', req)
File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "C:\Python27\lib\urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "C:\Python27\lib\urllib2.py", line 1197, in do_open
raise URLError(err)
URLError:

**Comment by F688** [comment]
After these errors it stopped adding series:
2015-11-26 00:14:58	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 3106, in preSearchit
sresults, explicit = mb.findComic(ogcname, mode, issue=numissues, explicit='all') #ComicName, mode, issue=numissues)
File "C:\Mylar\mylar\mb.py", line 132, in findComic
searched = pullsearch(comicapi, comicquery, 0, explicit, type)
File "C:\Mylar\mylar\mb.py", line 73, in pullsearch
file = urllib2.urlopen(PULLURL)
File "C:\Python27\lib\urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "C:\Python27\lib\urllib2.py", line 431, in open
response = self._open(req, data)
File "C:\Python27\lib\urllib2.py", line 449, in _open
'_open', req)
File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
result = func(*args)
File "C:\Python27\lib\urllib2.py", line 1227, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "C:\Python27\lib\urllib2.py", line 1197, in do_open
raise URLError(err)
URLError: 
2015-11-26 00:14:53	INFO	Successfully imported : 100 Bullets
2015-11-26 00:14:52	INFO	[FILE-RESCAN] I have physically found 100 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 100 / 100 ]
2015-11-26 00:14:51	INFO	[FILE-RESCAN] Total files located: 100
2015-11-26 00:14:30	INFO	comicname is :1963 Ashcan
2015-11-26 00:14:24	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 568, in addComictoDB
logger.fdebug('issue: ' + str(latestiss) + ' status before chk :' + str(statbefore['Status']))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by evilhero** [comment]
Not want you want to hear but I need to see the mylar.log file as you have more than one add going at a time due to the threading,  it's hard to figure out which series might be causing a problem.

From the looks of it, the url error is most likely due to hitting the cv api rate limit and it returning no results (or is unreachable). The other two errors relate to the information being logged into the text file and mylar being unable to do so because the value is either a None or it has a special character it can't interpret. 

This is awesome stuff BTW (not for you I'm sure,  but for me trying to improve/troubleshoot this) - the more feedback I get about the problems the more things I can fix  so both you and others have a better import success rate than currently ;)

**Comment by F688** [comment]
See attached. 
[mylar.log.1.txt](https://github.com/evilhero/mylar/files/46238/mylar.log.1.txt)
[mylar.log.2.txt](https://github.com/evilhero/mylar/files/46242/mylar.log.2.txt)
[mylar.log.3.txt](https://github.com/evilhero/mylar/files/46239/mylar.log.3.txt)
[mylar.log.4.txt](https://github.com/evilhero/mylar/files/46241/mylar.log.4.txt)
[mylar.log.5.txt](https://github.com/evilhero/mylar/files/46243/mylar.log.5.txt)
[mylar.log.txt](https://github.com/evilhero/mylar/files/46240/mylar.log.txt)

**Comment by F688** [comment]
Tried Mass Import again got one series this time. Open to any suggestions.
[mylar.log.txt](https://github.com/evilhero/mylar/files/79878/mylar.log.txt)

**Comment by evilhero** [comment]
Didn't forget about this - working on using metatag to identify series as well as some other items that might help.  

I plan on pushing a commit out tomorrow as I have a few hours set aside to dedicate to mylar. Not sure if the metatagging identification will make it into the comic or not atm, but when it is I will reference this issue # so you'll have a heads up.

**Comment by F688** [comment]
2016-02-14 01:13:17 ERROR Uncaught exception: Traceback (most recent call last):
 File "C:\Mylar\mylar\logger.py", line 158, in new_run
 old_run(*args, **kwargs)
 File "C:\Python27\lib\threading.py", line 763, in run
 self.__target(*self.__args, **self.__kwargs)
 File "C:\Mylar\mylar\librarysync.py", line 692, in scanLibrary
 myDB.upsert("importresults", newValue, controlValue)
 File "C:\Mylar\mylar\db.py", line 170, in upsert
 self.action(query, valueDict.values() + keyDict.values())
 File "C:\Mylar\mylar\db.py", line 129, in action
 sqlResult = self.connection.execute(query, args)
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings

**Comment by F688** [comment]
Update Unicode string errors

**Comment by evilhero** [comment]
Can you paste in the debug log showing what's occurring just prior to the error?  It's obviously having a problem with a filename but without knowing what it is, it's hard to troubleshoot. 

And mylar should be all Unicode within the dB.. It looks like it's taking a string and trying to write it into the dB as Unicode and failing.

**Comment by F688** [comment]
[logs.zip](https://github.com/evilhero/mylar/files/142673/logs.zip)
Please see attached

**Comment by evilhero** [comment]
Gonna love this - those logs were just info level.  I need to see the debug log  to see what filenames it's coughing on.
You can enable verbose logging by either :
- start mylar with the -v option on startup
- toggle verbose logging on in the log tab within the mylar program

**Comment by F688** [comment]
Will do. No problem. 
[logs.zip](https://github.com/evilhero/mylar/files/149545/logs.zip)

**Comment by evilhero** [comment]
Ok, I can see what's going on (I think).

When you scanned in the files, it looks like this file : Dark Claw Adventures 01 (1997) (Minutemen-Syl3ntBob) is causing some issues due to the content within. Not quite sure why, but it's not able to decipher what's inside of it and it's causing it to abort the scan. Is there any way that you can send me that file - I have a feeling that I need to see what's inside of it and do testing to figure out what I need to do to fix it.

Also, I'm not sure if it will help, but you did the scan a few days before the last commit and in the last commit there was a couple things to help with importing (mainly stuff related to issues that were tagged with CVS), but it might also solve the blank ComicID error when you're trying to import after the initial scan as I added in an exception catch to when it was occuring. So you might want to try doing the scan again in debug mode of course now that you're on the latest commit.

You can probably try with a smaller dataset (not quite sure how many series you're doing, but maybe try 1/3 of what you're doing now just to see if it will work, plus it makes it abit easier to scan through the logs).

**Comment by F688** [comment]
Rename to .cbz
[Dark Claw Adventures - 001 (1997).txt](https://github.com/evilhero/mylar/files/155047/Dark.Claw.Adventures.-.001.1997.txt)
I'll try a smaller set

**Comment by F688** [comment]
This one is also causing an error
Rename to .cbz
[Antarctic Press - Gold Digger Sourcebook, The Official Handbook Of The GD Universe - 002 (2007).txt](https://github.com/evilhero/mylar/files/155266/Antarctic.Press.-.Gold.Digger.Sourcebook.The.Official.Handbook.Of.The.GD.Universe.-.002.2007.txt)

**Comment by evilhero** [comment]
Wow - I don't think I would have caught that on my own without your help!

Both files were erroring out on the comicinfo.xml not containing an entry for 'pages'. The pages field is just a listing of every page within the file, including the image size as well as if one particular jpg is designated as the 'cover'.

I added an exception/catch for not having the page field present, and was able to scan in both files properly as well as having the appropriate IssueID retrieved using the metadata (and thus the ComicID as well).

Again, much thanks for the detailed info!

**Comment by F688** [comment]
Thank you, glad I can help and reap the benefits after

**Comment by F688** [comment]
".cbr is not in a metatagged format (cbz). Bypassing reading of the metatags."
Will there be a future version of mylar that can get metatagged data from cbr files?

**Comment by evilhero** [comment]
I've only ever come across metadata within cbz due to the zip headers, so that's what I've coded against. 

I'm assuming the cbr metadata is stored in a comicinfo.xml format usable by comicrack?

**Comment by F688** [comment]
Yes, cbr is the same as cbz. It just uses winrar compression instead of zip.

**Comment by F688** [comment]
Mass Import did not complete. Another Error logged:

2016-03-07 21:48:48	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 3022, in preSearchit
logger.info(comicinfo['ComicID'])
TypeError: string indices must be integers

**Comment by F688** [comment]
[mylar.log.1.txt](https://github.com/evilhero/mylar/files/162481/mylar.log.1.txt)
[mylar.log.txt](https://github.com/evilhero/mylar/files/162482/mylar.log.txt)

**Comment by Chrisophogus** [comment]
I think this is the closest thread to my issue. I only have about 4000 to add, managed to work around various file issues and the scan completed but I've not hit this in the log:

`2016-03-08 12:04:18	ERROR	Unable to complete the scan: list index out of range
2016-03-08 12:04:18	INFO	tempseries:{'ComicName': u'The Avengers Prelude: Black Widow Strikes', 'Issue_Name': u'Part Two', 'IssueID': u'336121', 'ComicID': u'48560'}`

Any suggestions?

**Comment by evilhero** [comment]
@Chrisophogus: are you on the master or development branch of mylar?

**Comment by Chrisophogus** [comment]
Dev branch

**Comment by evilhero** [comment]
I don't think the error is related to that particular comic that you posted with the error message. It probably has to do with an issue within the 4000 or so that you're trying to add in that it's having a problem with - from anything to not having any metadata, to an invalid filename, although if it was an invalid filename it would have errored out prior to that.

I would try a smaller dataset (for debugging purposes only), and enable debugging mode so that you can get the debug logs and then try doing an import again and seeing what happens. 

Without seeing the full portion of the log that it's trying to import, pasting just the error itself doesn't help that much in these cases unfortunately.

**Comment by Chrisophogus** [comment]
Just to try and narrow it down:

- I know that every comic has metadata as I'm only trying to add those that I've used the ComicVine Scraper on within ComicRack.
- Can't comment on the invalid filename thing. As you say, I'm sure it would have errored out before that.

I ran the scan against a smaller portion of the collection and it managed fine and I have the Import Results page populated. Having some trouble there but I haven't searched on that issue yet so I won't bother you with it.

I'll attach a log if I have any further trouble though. Thanks for your time :)

**Comment by F688** [comment]
Any idea on this error?

2016-03-07 21:48:48 ERROR Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(args, *kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(self.__args, *self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 3022, in preSearchit
logger.info(comicinfo['ComicID'])
TypeError: string indices must be integers

**Comment by evilhero** [comment]
Yeah that's been mentioned previously by someone, either on here or on the forums. Being March break here, my time has been pretty nonexistent this week but it's on my list of things to figure out when I get a chance. 

Pretty sure it's related to files with no metadata trying to lookup a valid comicid and not being able to.

**Comment by evilhero** [comment]
There's a big update coming for the importer in the next development commit (along with some other modules that got recoded) - expect it in a few days and you guys should have a much better experience with the importer (I'm hoping).

I've ran it through 1700+ randomly generated names, with metatagging and without, and various filenames until things weren't broken - so it's definitely going to be an improvement, along with better logging about what's going on during the process.

**Comment by Chrisophogus** [comment]
Sweet. Can't wait to give that a run.

**Comment by F688** [comment]
Nice

**Comment by F688** [comment]
Currently I noticed Errors occurring because of Ascii test like ½ within the metatags. Replacing them solves the error. Have not complete a full scan yet because non standards codes will be found, corrected and the scan needs to be restarted.

**Comment by F688** [comment]
Any progress on reading rar bases comic metatags (.cbr)?

F:\comics\DC Comics\Our Army at War\Our Army at War Vol1 - 142 (1964).cbr is not in a metatagged format (cbz). Bypassing reading of the metatags

**Comment by evilhero** [comment]
Not at the moment - mainly because using cbr would require the usage of UnRAR, and that comes with its own set of problems sometimes.  I'll probably try and get it in the next development commit since this one is pretty huge and is causing me a lot of code related issues before I even push it out, which is requiring me to fix it and taking up a lot of time.

**Comment by F688** [comment]
over 2 million lines and going. "Showing 1 to 25 of 2,108,446 lines (filtered from 2,108,472 total lines)"

**Comment by evilhero** [comment]
So that's good right?  I mean that's a huge amount of an import and no crashes thus far during scanning... Does it say how far in the progress it is in the status bar on the right on the import screen?

**Comment by F688** [comment]
Definitely a good thing. Comics are starting to get imported. Things are looking good.

**Comment by evilhero** [comment]
That's good.. Since you're doing the actual import now, I'd try and keep an eye on any multi volume series that you might be importing (v1, v2, etc). I'm not 100% sure if it will properly pick up the volume from CV (since they don't hold the volume in an XML field), or if it will say it needs 'manual intervention.'

**Comment by F688** [comment]
FYI Averaging about 60 to 100 series before it times out for some reason (maybe ComicVine). After restart additional series are added but it then times out again. Currently, up to 440 series added.

**Comment by evilhero** [comment]
ugh that's not a great stat, I mean it's working - but still. The timing out is probably due to CV and hitting their api thresholds - if you go to comicvine.gamespot.com/api and sign in you can see your api stats and when the counter gets reset (I think it's 200/hits every hr depending on the resource requested tho - searches are less, direct series requests are more)

**Comment by F688** [comment]
[mylar.log.TXT](https://github.com/evilhero/mylar/files/230889/mylar.log.TXT)
21-Apr-2016 14:18:09 - DEBUG   :: Thread-12 : displaycomic : ALF Comics Magazine
21-Apr-2016 14:18:09 - DEBUG   :: Thread-12 : comicname : ALF Comics Magazine
21-Apr-2016 14:18:09 - DEBUG   :: Thread-12 : Default search mode - this will match on ALL search words
21-Apr-2016 14:18:32 - WARNING :: Thread-12 : Error fetching data from ComicVine: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
21-Apr-2016 14:18:32 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Mylar\mylar\webserve.py", line 3316, in preSearchit
    sresults, explicit = mb.findComic(searchterm, mode, issue=numissues, limityear=yearRANGE, explicit='all') #ogcname, mode, issue=numissues, limityear=yearRANGE, explicit='all') #ComicName, mode, issue=numissues, limityear=yearRANGE)
TypeError: 'bool' object is not iterable

21-Apr-2016 14:53:34 - DEBUG   :: RSSCHECK : Starting new thread: RSSCHECK

**Comment by F688** [comment]
Yup connection failed to ComicVine

**Comment by F688** [comment]
Got a new error. Been stuck at 479 series since last comment

2016-04-28 17:11:15	ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\webserve.py", line 3154, in preSearchit
newlist = {k:comiclist[k] for k in comiclist if k['ComicID'] != RID}
File "C:\Mylar\mylar\webserve.py", line 3154, in
newlist = {k:comiclist[k] for k in comiclist if k['ComicID'] != RID}
TypeError: list indices must be integers, not dict

**Comment by evilhero** [comment]
Would you happen to have the log  leading up to the error?  That error looks like it's when it's doing the actual import and the series contains metadata that was detected, but something in that particular grouping (series & vol)  is missing one of the metadata elements for some reason.

**Comment by F688** [comment]
[mylar .log.txt](https://github.com/evilhero/mylar/files/241768/mylar.log.txt)

**Comment by F688** [comment]
FYI - Another error
ERROR	Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\importer.py", line 598, in addComictoDB
updater.forceRescan(comicid)
File "C:\Mylar\mylar\updater.py", line 1236, in forceRescan
chkthis = myDB.select(tmpsql, issID_to_ignore)
File "C:\Mylar\mylar\db.py", line 145, in select
sqlResults = self.fetch(query, args).fetchall()
File "C:\Mylar\mylar\db.py", line 94, in fetch
sqlResult = cursor.execute(query, args)
OperationalError: too many SQL variables

**Comment by evilhero** [comment]
Not too sure about the SQL error, but the comicvine limit should be handled abit better in the next development release - it will now log an error saying the limit has been reached and to try again in ~ hr. It may be possible for me to try and schedule the retry within Mylar, but at this point it's just the logging of the error gracefully, and then exiting from the import process.

Also the list indices error is fixed in the next development commit as well.

**Comment by F688** [comment]
Mylar unable to find other comic series, it stuck on 482 series and has not found others since. Not being able to work with .cbr files is a big issue as some of the series it found it is unable to recognize the .cbr files and so is recording that I am missing them.

**Comment by evilhero** [comment]
Well it works with cbr files - it just doesn't read the metadata within them.  I have yet to find any information on cbr being a valid extension for metadata other than for comicrack and I'm not even sure if comicrack can read the metatagging within such a cbr? 

Reading metadata from a cbr means it has to unrar it in order to see the XML file to extract - which means the user has to have a valid installation of UnRAR and it has to be a level that's error free (5.31+ I believe). Plus, that means that every cbr will be scanned for metadata during the scan which will increase the scan time even more.. I just need to find a way to allow for it without breaking the way it works now, that's the tricky part. 

Does it not scan in the cbr based on filename or are the filenames all messed up (thus the metadata request)?  It should be able to extract the series title and issue number at the very least provided it's Ina somewhat legible format.

**Comment by F688** [comment]
I understand, what I'll do is convert all my .cbr to .cbz via comicrack and then try the save & scan and mass import again to see if more series are added. FYI - Ubooquity can read .cbr metadata, which is my preferred server.
All comics are processed the same way. Tagged with comictagger (comicrack style) and then rename to %series% Vol%volume% - %issue% (%year%).
Thanks again

**Comment by F688** [comment]
I have a number of comics series that are not being added. They show up in the Import Table but will not import no matter how many times I hit the button

**Comment by apastuszak** [comment]
You can also use ComicTagger to to convert CBR to CBZ.

**Comment by F688** [comment]
[Flash Gordon - The Mercy Wars - 000 (2011).txt](https://github.com/evilhero/mylar/files/265076/Flash.Gordon.-.The.Mercy.Wars.-.000.2011.txt)

**Comment by F688** [comment]
Thanks for the suggestion.

**Comment by F688** [comment]
apastuszak 

Do you know a quick way to add cvinfo files to series folders?
