### ISSUE TITLE
Not finding issue with decimal

### ISSUE THREAD

**Issue by sstretchh** [evilhero/mylar#1160]
I am discovering that any issue that has a decimal it's not finding. I have to manually download the NZB. See screen shots and below for examples

for example 
The Flash 023.1
The Flash 023.2
The Flash 023.3

Aquaman 023 1 2013  
Aquaman 023 2 2013

Green Lantern 023.1 2013  
Green Lantern 023.2 2013 
Green Lantern 023.3 2013 
Green Lantern 023.4 2013 

![decimal_notfinding](https://cloud.githubusercontent.com/assets/2204602/11171463/b0b07b5e-8be8-11e5-8582-0bc1f7ccb04e.JPG)
![dognzb_decimal](https://cloud.githubusercontent.com/assets/2204602/11171462/b0aeb6ca-8be8-11e5-9714-dcdca341b6ab.JPG)

**Comment by evilhero** [comment]
I'm pretty sure this is specific to dognzb being used as how they have the filenames for the nzbs all have dots in lieu of spaces. This causes problems when decimal issues are being searched for as it appears to mylar as Aquaman.023.2 2013 - I did have this working at one point long ago (when thr Forever Evil arc was  happening and decimal issues were everywhere), but I haven't revisited it since.

I'll run through some tests on my side to see if I can replicate the problems and if so,  try and get it all fixed up again.

**Comment by sstretchh** [comment]
I looked at both nzb.su and dog and your right it is a space, the dots are in the results in mylar

**Comment by evilhero** [comment]
Ok I found a bigger problem when trying to do some testing (yay?). Because of this bug, mylar kicks out after doing 1/2 searches for issue numbering - meaning it searches for 23.3, but not 023.3 and the result set it wants to use is the 023.3 one (in my sample test at least). This might be happening for yourself - haven't been able to test if it's for every issue or just decimals, but this could be a pretty nasty bug.

I'm looking into this right now,  so hopefully will know more soon.

**Comment by sstretchh** [comment]
that is awesome to hear ! thank you for the update
