### ISSUE TITLE
NZBs not being found again

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1166]
This just started happening this week.  
In Mylar, the series appears as:
Captain America: Sam Wilson (2015)
In attempting to get issue 003, I can look on nzb.su and find:
Captain America - Sam Wilson 003 (2016)
in the misc > Other section.
I have 'Experimental Search' on, so I thought it would catch it.

It also isn't finding Secret Wars Too 001, and some others
Is something up with Experimental Search?

Here's the log

22-Nov-2015 18:37:10 - INFO :: Thread-13 : Initiating manual search for Captain America: Sam Wilson issue: 3
22-Nov-2015 18:37:10 - INFO :: Thread-13 : [SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : Captain America Sam Wilson
22-Nov-2015 18:37:10 - INFO :: Thread-13 : Issue Title given as : None
22-Nov-2015 18:37:10 - INFO :: Thread-13 : search provider order is ['nzb.su', 'Experimental']
22-Nov-2015 18:37:10 - INFO :: Thread-13 : Shhh be very quiet...I'm looking for Captain America: Sam Wilson issue: 3 (2016) using nzb.su
22-Nov-2015 18:37:10 - INFO :: Thread-13 : pausing for 60 seconds before continuing to avoid hammering
22-Nov-2015 18:37:46 - INFO :: Thread-12 : Could not find Issue 3 of Captain America: Sam Wilson(2015) using nzb.su [api]

**Comment by evilhero** [comment]
Well experimental is just that - experimental. Depending on the number of users hitting the site, the responses vary from retrieving the actual results to retrieving no results. There's nothing mylar can do about it, it's just the site gets overwhelmed and returns nothing. That being said, there's nothing wrong per-se with the experimental search, it's working as it always has.

I did notice that there's a slight error in the provider_order counter, it seems that if there's more than one provider, it will leave out one of the providers (ie. if there's 3 enabled, only 2 will get used). I have a fix now and am going to commit something up shortly hopefully in order to address this, as well as some CV API changes that need to get done.
