### ISSUE TITLE
Resolve the SSL issue when using custom NewzNab

### ISSUE THREAD

**Issue by ghost** [evilhero/mylar#1170]
Hi,

Mylar wasn't grabbing my Newznab due to the fact it only supports SSL connections, after some googling, I noticed that the search.py responsible for getting results from Newznab has no SSL implementation at all.

I made a workaround that is not secure, but at least gives me back my Newznab.

I've just added following line at the beginning of the search.py:
     import ssl

And added the following unsecure SLL context line:
            ssl._create_default_https_context = ssl._create_unverified_context

Right before the following line:
                        opener = urllib2.build_opener()

And voila my Newznab is working, if you have a more secure solution, let me know, but this serves my purpose.

Regards,
Trist.

**Comment by evilhero** [comment]
I'm pretty sure the SSL problem you're experiencing is due to not using mylar with python > 2.7.7+. With 2.7.7+ SNI support occurs, which fixes the problems - although if I recall, 2.7.9+ is the ideal as there were still some certificate errors happening in previous versions.

Changing the context to non-verified is akin to driving with no seatbelt. Sure, it will work - but you're definitely not safe, and you're going against the manufacturer's warning ;)  Since you're turning off SSL Certificate verification, it has no way of verifying if the certificate is infact who it says it is (SNI or not), and just lets it pass regardless.

I thought I had converted all of those urllibs to the requests module - so it looks like I'm going to be doing that tomorrow.

I'm actually suprised you weren't getting other errors throughout if you're using < 2.7.7 as the ssl-verification would then fail during rss lookups as well as retrievals.

**Comment by omega1970** [comment]
Actually I have Python v2.7.9 installed. But the only way to get things working was using the fix I described above, I will give your fix a go when I have time (very busy week at work).

Thanks 4 the feedback.
