### ISSUE TITLE
Define Pull List Weekly Directory

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1173]
Hi this is more of a request than an issue.

It would be great if there was a way to either define a custom directory for the Pull List Weekly Directory OR to have them all in a folder and have the dates as sub directories. i.e. Comic Library>_Latest_>2015-11-08... 

Purely just a thought.

**Comment by evilhero** [comment]
Yes I was thinking of this recently as I have a few dozen date directories in my main ComicLocation folder and it's pretty unsightly. 

I'm not sure about defining the directory but definitely adding it so the sub is present is definitely doable and pretty easy to do. This will go well with the new file options to copy/move or hard/sym-link the files so that will also be an added option.

**Comment by evilhero** [comment]
Will be available in the next development commit - config.ini option only currently. Locate weekfolder_loc within config.ini, and change setting to full path to desired directory location where all dated-weekly directories will appear beneath:
```
weekfolder_loc = /mnt/Comics/Latest
```
