### ISSUE TITLE
Story Arc Management - Duplicate Issues

### ISSUE THREAD

**Issue by rmgy733** [evilhero/mylar#1175]
Running into a bit of an interesting issue for a single story arc. All of the issues have duplicated (see the attached image).

<img width="750" alt="screen shot 2015-12-06 at 7 33 45 pm" src="https://cloud.githubusercontent.com/assets/15075692/11616761/9f646738-9c51-11e5-8cf1-869c112945a9.png">

This isn't a rendering issue, but rather the entries became duplicated in the database:

sqlite> select issueid, count(issueid) from readinglist where storyarcid='56280' group by issueid order by count(issueid) desc limit 10;
244804|2
260029|2
261124|2
268209|2
268970|2
269821|2
269827|2
270444|2
272344|2
272345|2

Given that I have several other arcs without this issue, I assume that I hit an edge case when the IssueArcID/Publisher change it is considered a new row rather then modifying an existing row:

sqlite> select issuearcid, publisher from readinglist where issueid = '260029';
56280_1151|DC Comics
56280_5584|

That being said, a unique index on (StoryArcID, IsssueID, ComicID) may be a consideration to avoid such a possibility in the future. 

I'm not sure the preferred method of cleaning this Story Arc up. There are no indices on `readinglist` so I can't remove the older duplicate entry. I'm probably missing it, but I don't see a way to remove the Story Arc on the GUI and re-add it. 

Thanks for the assistance :)

**Comment by evilhero** [comment]
It looks like you had it added at one point, and then when you did a refresh (possibly?) instead of updating the existing issues, it just readded them since there was no publisher given in the previous add I'm guessing. There was a jumping on point where if you had added some arcs prior to one of the builds, mylar switched how it handled alot of the backend stuff and because of the change one would have to readd the story arc using the search option on the story arc page (it's a much cleaner, better option than importing the cbl as the search will automatically tie into the comicids/issueids from CV)

You can delete the story arcs from the main story arc page - there's 2 icons listed beside each story arc you have in your watchlist.
![arcoptions](https://cloud.githubusercontent.com/assets/909424/11616972/567774d4-9c56-11e5-92da-4156d2d365a9.png)
The 'x' icon will delete the story arc, and the 'circular arrow' icon will refresh the existing story arc.

**Comment by rmgy733** [comment]
That worked perfectly. Thanks so much for the fast response and detailed explanation!
