### ISSUE TITLE
There is no logout

### ISSUE THREAD

**Issue by timm088** [evilhero/mylar#1176]
I have setup mylar to i can access it via reverse proxy with nginx etc (seems to work well, nice job)

However, there is no logout option in the UI (at least that I can find)

**Comment by evilhero** [comment]
That's because there isn't one. TBH I never even realized until now, but most other apps like mylar don't have a logout function.  Probably because once you close down the browser, you have to re-enter your credentials again due to the way cherrypy authenticates (unless of course if you cache your credentials..then it's a *tsk*tsk)

**Comment by timm088** [comment]
If you look at similar apps (sonarr, couchpotato, sab) they all provide login/logout now (being able to enable external stuff)

But you're right about closing forcing cherrypy to authenticate again.

**Comment by evilhero** [comment]
I never honestly even noticed (I need to look at those apps again I guess). It shouldn't be too hard to add in. 

I can put this as an enhancement request and when I get a bit of time to tinker I'll see what I can do to add  it in.
