### ISSUE TITLE
NZBs stuck on fetch

### ISSUE THREAD

**Issue by timm088** [evilhero/mylar#1177]
Seeing something weird with mylar downloads after enabling external access

Mylar appears to have downloaded the nzb (its in cache), and has the record to SAB, but it cant seem to retrieve the nzb file?

If i manually use this file in SAB it works. 
SAB and Mylar are on the same machine (with mylar having a root on /comics)

![screen shot 2015-12-08 at 2 19 40 pm](https://cloud.githubusercontent.com/assets/8890118/11646941/d1261efe-9db6-11e5-8cae-fb79d14ac3dc.png)

**Comment by timm088** [comment]
I've also checked that using that URL combination i can actually download that NZB locally, and I can, so I am a bit lost as to why it doesnt go to SABNZBD correctly.

**Comment by evilhero** [comment]
It probably has something to do with how mylar is running. When you run mylar initially it tries to best-guess the local ip.  If it's incorrect in guessing, or you just have an out facing ip then you need to specify it manually via the config.ini  (look for host_return and set it to the ip of the machine running mylar).  If you have sabnzbd and mylar on separate machines, then you need to specify the ip that can access mylar if you were on the sabnzbd machine).

It does this as instead of redownloaong the nzb again from the provider,  it uses the nzb in the cache (which has been verified for integrity by mylar, as well as naming )and then opens up a temporary apikey that goes from sabnzbd back to mylar and grabs the already downloaded nzb. Once it's grabbed, the apikey is trashed.

**Comment by timm088** [comment]
Same machine for me.

**Comment by evilhero** [comment]
What do you have for the IP for mylar host within the mylar configuration? Normally setting it to 0.0.0.0 will make things work as then listens on all interfaces on the local machine (don't use localhost as there are some resolving conflicts for some reason)

**Comment by timm088** [comment]
i was using 127.0.0.1 (for host and return) - i'll change and see

**Comment by evilhero** [comment]
Yeah don't set the host return to anything (leave it blank)...just setting the mylar host to the 0.0 0.0 should be enough for it to all line up

**Comment by timm088** [comment]
Ahh ok , yeh that seems to have fixed the issue (have to retry) 
Cool thanks.
