### ISSUE TITLE
Problem importing CBL files

### ISSUE THREAD

**Issue by stumueller** [evilhero/mylar#1178]
Hi

I downloaded a cbl file from a comicrack forum and tried to import it into mylar so that I could post process the comic I have for hte story arc. However it generated this error. Afterwards I couldn't get into the story arc manager at all and I've had to remove my DB and config.ini file and start again. But I'm still unable to import cbl files.

Traceback (most recent call last):
  File "C:\Mylar\cherrypy_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Mylar\cherrypy_cpdispatch.py", line 29, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 2280, in importReadlist
    logger.febug(str(MSCheck))
AttributeError: 'module' object has no attribute 'febug'

Thanks

Stuart

**Comment by evilhero** [comment]
Yeah that's probably my fault. Earlier in the year I switched how mylar handles story arcs and focused on being able to utilize the data at CV for arcs instead of relying on cbl files. So if you do a search on the story arcs main page it will load up the relevant arc complete with every comicid and issueid already associated with the given arc. The other way relies on text based parsing and then manually having to check for each issue on CV in order to get the proper issue data.

I'm pretty sure the cbl's used with comicrack are pretty identical to how CV has it. I was going to look into this again as I know cbl import was a pretty big part for some people, and having it error out to the point where it can't access the story arc page isn't good - so I'll at the very least fix that part so you can get to the main arc page again. The loading of the cbl files might take abit more work as of how the arcs work now, but it's always possible ;)

**Comment by stumueller** [comment]
Hi

I did use the search function and that was OK...the only problem with it was the order of comics that it specified was different to what comicvine specified.

I added the X-men: Messiah Complex and the order of comics was very different to what was specified in comicvine. So i though I would import a cbl file and then I could control the order of the comics.

Any idea why adding hte story arc through search would produce a different order to what is specified on comicvine?

**Comment by evilhero** [comment]
It shouldn't, but mylar had to manually process all the issue information and alot of times CV has story arcs correct on the Web page,  but incorrect through the api (I've seen it a few times).

I'll try adding messiah complex tonight and seeing what happens with the Reading order - if it's a problem  with mylar, if it's sorting incorrectly by date for some reason , or something else.
