### ISSUE TITLE
Reading order of Story Arcs

### ISSUE THREAD

**Issue by stumueller** [evilhero/mylar#1179]
When I add a Story Arc through the search function. The reading order that it specifies isn't always correct. I have noticed this with both Messiah Complex and with Second Coming. When I added Messiah War this gave the correct order but the other two series didn't.

I take it it isn't possible to manually edit the order the comics come into mylar in?

**Comment by kurnalbert** [comment]
I have noticed this too. Occasionally Mylar will list the comics in the correct reading order within the web interface, but when naming the comics, it will often prepend the incorrect number to the beginning of the comic.

**Comment by evilhero** [comment]
Currently you're not able to edit the order - I was working on a drag & drop interface for it (where you could just drag the issues around within the story arc page to get a customized order), but it wasn't able to drag & drop across multiple pages of a given arc. That and I was having problems getting the correct order to save properly, so it went on the back burner.

If someone has any other idea (aside from the drag & drop) in order to allow for custom re-ordering of the list, I'm willing to try and get something usable to work.

@kurnalbert: is the issue that's getting the incorrect number have additional issues within the given arc that belong to the same series? I haven't come across this myself, but granted I haven't tested this particular scenario either (and replicating it might be a bit difficult in order to troubleshoot properly).
