### ISSUE TITLE
Not sending Pushbullet Notifications

### ISSUE THREAD

**Issue by benyjr** [evilhero/mylar#1183]
I know you've gotten this issue before, but the error is different here:

15-Dec-2015 02:25:07 - ERROR   :: CP Server Thread-3 : [NOTIFIER] PushBullet request failed: {"error":{"code":"","type":"invalid_request","message":"Access token is missing or invalid.","cat":"(=^･ω･^)y＝"}}
15-Dec-2015 02:26:18 - ERROR   :: CP Server Thread-2 : [NOTIFIER] PushBullet request failed: {"error":{"code":"","type":"invalid_request","message":"Access token is missing or invalid.","cat":"(=^･ω･^)y＝"}}

I am running:
mylar build efe447f5170dfcea873b5da735c2fd66d2fe9936
Python Version : 2.7.10
Ubuntu 14.04 LTS

I have verified that this token is correct and working.  It is functioning properly in SickRage.

**Comment by benyjr** [comment]
It might actually be worth checking how SickBeard and SickRage are doing PushBullet notifications, as it was working perfectly even when I was running Python 2.1.6.

**Comment by evilhero** [comment]
This is working for me with no issues, using Test Notification button on the configuration screen and verified message receipt on both website and mobile device (Ubuntu 12.04LTS, python 2.7.10)

Are you saving the configuration and restarting Mylar after enabling/changing the PushBullet Notification option? Right now, if you make any changes to the Mylar configuration, it's necessary to save and then restart Mylar so that the new values can be properly loaded with Mylar. It's a pita yes, and it's a bug - but right now, it's the only method available to ensure that the new values are properly loaded and not some old values.

**Comment by benyjr** [comment]
That fixed the issue. Thanks! 


Beny

Sent by raven from The Wall 
 
  On Tue, Dec 15, 2015 at 8:15 AM, evilhero<notifications@github.com> wrote:   
This is working for me with no issues, using Test Notification button on the configuration screen and verified message receipt on both website and mobile device (Ubuntu 12.04LTS, python 2.7.10)

Are you saving the configuration and restarting Mylar after enabling/changing the PushBullet Notification option? Right now, if you make any changes to the Mylar configuration, it's necessary to save and then restart Mylar so that the new values can be properly loaded with Mylar. It's a pita yes, and it's a bug - but right now, it's the only method available to ensure that the new values are properly loaded and not some old values.
