### ISSUE TITLE
feature request: The Pirate Bay torrent search

### ISSUE THREAD

**Issue by tatsumasagc** [evilhero/mylar#1184]

**Comment by evilhero** [comment]
Probably not going to happen anytime soon - TPB o nly uses magnet links which Mylar doesn't play with (since it doesn't directly link into the torrent client).

That, and nothing recent has been uploaded for comics since august,2015 - granted there are lots of back issues but I'm pretty sure everything on there can be retrieved via KAT.

Unless there's a reliable way to convert magnet links to .torrent files, this is gonna be on the 'way-back-back' burner...

**Comment by kevmullet** [comment]
Hey Evilhero, thought I would jump on this existing feature request rather than a new one.
Any chance of adding myanonamouse.net as a torrent search? I've found comics on there that are not available on 32p and it's updated regularly.
Great product btw

Thanks
