### ISSUE TITLE
Comic import failure

### ISSUE THREAD

**Issue by morpheus200** [evilhero/mylar#1185]
Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/librarysync.py", line 570, in scanLibrary
logger.fdebug("comicname: " + soma_sl['comicname'].encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 43: ordinal not in range(128)

**Comment by evilhero** [comment]
Fix is coming,  but it's the holidays so my time to work on things has been non-existent. 

In the meantime,  it's occuring due to having a character that can't be written to the txt log file that mylar uses. I believe the 0xe2 is the unicode character for â. Removing said character from the filename(s) with them will allow Mylar to continue without those errors.

**Comment by morpheus200** [comment]
I have made several test. And I think the failure appears by the following combination or something like that.

Filepath: /media/cifs/comics/Earth 2 - World’s End
Filename: Earth 2 - World’s End #07.cbz

And there's no â (0xe2).
Could you help me, please.

**Comment by evilhero** [comment]
It's the ’ in the filename in that particular case... That's a Unicode character -  it's not a typical ' so it's unable to complete the request due to how to handle it. 

I'll see if I can fix the Unicode portion of the importing (again),  at least to encompass more of these types of situations.
