### ISSUE TITLE
Doesn't auto-update or download after downtime.

### ISSUE THREAD

**Issue by jackperry** [evilhero/mylar#1187]
Hey there, maybe I'm misunderstanding some Mylar settings or something, but I don't think so.

So, recently I had forgotten to open Mylar after a computer restart, and so I missed probably... 2 or 3 weeks of Mylar running. When I open it, it updates a few comics (3 out of 25+) to show me that I'm missing an issue for each, but doesn't download those missing issues, even if they're set to Wanted automatically. Also, if I go and manually update a comic, or use the Force Update Active Comics, it will find updates for over ten different comics.

Shouldn't Mylar be updating and checking all of these things when it starts up, and if it finds out that there are new issues that get tagged as Wanted, automatically try and download them? It would be nice to not have to manually go and click the Manual Search (magnifying glass) on every new issue for all of my comics.

Thanks!

**Comment by jackperry** [comment]
So I just woke up to a whole bunch of Windows 10 notification noises because all of these issues finished downloading at once. Five hours later, which seems to coincide with the Library Scan Interval setting that is set to 300 mins under the Web Interface tab in Settings.

Does that sound about right? Could I just lower this?

**Comment by evilhero** [comment]
Yeah, if you don't run Mylar 24/7 - then it has catching up to do when you do start it up. From what I recall (it's been awhile since I looked at this part), you can enable/disable the backlog search on startup, as well as set the interval for the backlog search to commence (nzb search interval).

You can also specify the update-check as well (where Mylar checks to see if any new commits have been pushed) - this is a config.ini only option though and is labelled as check_github_interval.

What probably happened is that the weekly pull list check occurred, and in doing so it automatically refreshed any series that it needed to in order to make sure (at the very least) that those particular series were up to date. Once they were current, then the search ran and the issues were downloaded.

The Library Scan interval is the current question mark - it seems to be tied to the actual Import option, which obviously isn't correct. Right now, the updater (Refresh) runs every 48 hrs since since mylar has been running and this isn't a modifiable setting - mainly because running a recheck on one's entire watchlist is pretty comicvine api intensive (or can be if you have alot of series you're watching), so limiting it to every 48 hours should be more than enough to make sure you're current and that on a given Wednesday (when new issues are released) everything is current. 

With that said, I'll have to rejig things abit to make the libraryscan interval option actually be relevant to the library scan itself. Keep in mind that polling the api constantly for new issues isn't necessary as comicvine only populates new issues into their db on Monday's/Tuesday's (aside from corrections, etc) - so hitting it more frequently isn't going to garner any special bonuses.
