### ISSUE TITLE
Mylar deletes original on failed post-process

### ISSUE THREAD

**Issue by Theli93** [evilhero/mylar#1192]
I'm in process of working out a failed permissions issue on my setup (that's on my end), buy Mylar still proceeds to delete the original even though it has failed due to a permissions error.

This means the file has to be re-downloaded. Certainly this is an undesirable action on Mylar's part.

Would it not be better to leave the original in place for the user to address the issue, without having to re-download?

**Comment by evilhero** [comment]
This isn't the typical behaviour for mylar. Once the download completes it moves the file to the intended destination - it doesn't delete files after the move (it might try to cleanup the empty directory though).

You didn't mention a few things that would help troubleshoot this:
- what branch/commit of mylar are you running?
- what OS? 
- how did you install mylar (git / source / something else )?
- are you running mylar as a daemon or through a third party app?
- is this occuring during a manual post-processing run or a download initiated from mylar, and if so which download client are you using?

The mylar.log file also holds alot of information when it comes to post-processing,  if you check it it might provide more information on exactly what's happening or why it's being deleted.

**Comment by Theli93** [comment]
Hi EH,
That's precisely the  issue, but the directory it is cleaning is *not *empty, because the permissions prevented the move.

Just did a reinstall and moved over to development and updated
It's on a Synology, so their -nix variant
Synology package

After the reinstall, I've started moving copies of my downloads into a testing folder so I don't have to re-download. Previously it did on mylar initiated downloads. At the moment it also does it on manual downloads as well as imports (unless import source and destination are the same).

---Begin abbreviated clip from mylar.log---
13-Jan-2016 21:09:22 - DEBUG   :: Thread-14 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: Xxxxx Xxxxx
13-Jan-2016 21:09:22 - ERROR   :: Thread-14 : Could not change permissions : /volume1/Media/Print/Comics/Xxxxx Xxxxx (####). Exiting...
13-Jan-2016 21:09:22 - INFO    :: Thread-14 : [FILE-RESCAN] I have physically found 3 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 3 / 3 ]
13-Jan-2016 21:09:22 - DEBUG   :: Thread-14 : issue: 3 status after chk :Downloaded
13-Jan-2016 21:09:22 - DEBUG   :: Thread-14 : pullupd: None
13-Jan-2016 21:09:22 - DEBUG   :: Thread-14 : lastpubdate: Present
13-Jan-2016 21:09:22 - DEBUG   :: Thread-14 : series_status: Active
13-Jan-2016 21:09:22 - INFO    :: Thread-14 : Successfully imported : Xxxxx Xxxxx
---End Clip---

"Successfully imported" despite "Could not change permissions... Exiting..." and when I verify the source and destination folders both are vacant of the subject material.

**Comment by evilhero** [comment]
Yeah the importer is going through some changes - that's just a quirky message saying that's it finished, not actually successful. I'll look into adding a catch/exception to the permissions failing and halting the removal of the directory (let alone that it's deleting it when it's not empty).

I can also tell you that probably the reason you're having so many permissions problems is due to the syno-package. I hate bashing on something that someone made to allow users to do things on their system with the application, but almost every single person that's posted about permissions problems have been using the syno-package. Since I have no affiliation with the package (or any 3rd party app really), I can't really offer a lot of support/help just because I'm unfamiliar with the way synology's have their permissions laid out.

My advice, at least to see if it clears things up for you, is to install mylar from source or git. Based on other users' feedback about making the switch, all of their permissions problems went away after doing the switch and never reappeared.

**Comment by evilhero** [comment]
I've been running through this - and while I can't say for certain what's going, i'm definitely having a difficult time reproducing the problem. The call to delete a directory is only after it has moved the files (during post-processing), if it fails due to permissions it aborts the entire process. There is also a catch/exception already in place for directories that are not empty, which is after the move/fail portion.

The importer doesn't actually delete any directories, it just moves files and leaves the empty directories thereafter.

Can you post the portion of the log file showing the attempted move/failure and the continuation following the move/failure. There are 3 different modules involved in these types of moves (post-processing, manual post-processing, importing), and each uses varying degrees of similar concepts but yet are different so it's hard for me to track down exactly where it's coming from without seeing the actual move/failure.

**Comment by Theli93** [comment]
Full unmodified log since reinstall available on Pastebin for 24 hours: http://pastebin.com/cNQb1P0r
Please let me know if you don't get it in time and I'll re-up.

Yes, I've seen many posts regarding issues with the syno-packages of Mylar, but had to give it a go (at least for my introductory run). I may have to look at an alternate installation for long term functionality. After I ran into the issue with having to re-download somewhere around a dozen issues (not to mention having to research titles for which ones to manually re-download), I wanted to be sure a flag got raised on this issue before proceeding down another path.

Thank you for responding so quickly!

**Comment by evilhero** [comment]
I'm not sure cause I couldn't see in the logs - but do you have metatagging enabled within Mylar at all (ComicTagger)?

Reason I ask is that there were some recent issues with ComicTagger and putting things in the wrong directories during post-processing, then erroring out because it couldn't find said files and then they would get deleted as they were stranded (more or less).  

I still can't see where it's failing to complete the move - even during the import it indicates that the files were moved successfully, but then the permissions fail (possibly because the files don't exist when the permission settings run?)

I can add in a quick crc check when doing the move - quite simplly, it takes a crc of the issue before the move, then it moves the file, and then it takes a crc of the file in the new location. If they match, then it can remove the original file - it's abit more overhead (not from the crc, as they're comics and crc checksums don't take alot of speed/time for that size of stuff), but the copy/delete might be a bit safer if this is continually happening for whatever reason

**Comment by Theli93** [comment]
No, there's no ComicTagger metatagging activated. I hadn't gotten that far into my setup, as yet.
