### ISSUE TITLE
2nd volumes are not handled properly?

### ISSUE THREAD

**Issue by ManOrMonster** [evilhero/mylar#1193]
Volume 2 of [Jupiter's Circle](http://www.comicvine.com/jupiters-circle/4050-86239/) has been released. It's basically a new miniseries which is a sequel to Jupiter's Circle. Unfortunately, it has the same name on ComicVine. It shows up as "v2" under Version Number on Mylar, but Mylar thinks I already have the issues since I have the old ones.

I'm guessing the way it should work is it should treat different Version Numbers as separate entries. Is this a Mylar problem or a problem with ComicVine editors not naming it properly? The downloads show up as "Jupiter's Circle Vol 2" or "Jupiter's Circle v2".

**Comment by evilhero** [comment]
I'm betting that the 1st volume that you have present is still labelled as being in a 'Continuing' Status, which would be causing the problems. Since both titles are in 2015, and it looks like within a month  of the 1st ending (Sept30), the 2nd started(Nov25) it's just taking the 1st hit since the dates are probably close enough that it assumes it's part of the same series.

Try Refreshing the v1 series to see if goes into an 'Ended' Status, in which case then it should be able to find the v2 properly. Unless you've modified the biggie/indie values within the config.ini to different values (I believe Image is included as a biggie, although it makes no difference since less than 55 days has passed between volumes it won't mark the 1st as Ended)

**Comment by ManOrMonster** [comment]
It's marked as "ended" in the list in Mylar. I noticed the version number is "none" for volume 1. I proposed an edit on ComicVine that would add volume 1 to the original series, not sure if that will help.

**Comment by evilhero** [comment]
Not sure if they would do that as they don't distinguish any other series with the volume label. Worth a shot though for sure ;)

**Comment by ManOrMonster** [comment]
They accepted my edit. The old one now shows as "v1" under Version Number in Mylar. I refreshed the comic and then added the new one, same problem. It uses the same folder and thinks I already have the two issues.

**Comment by evilhero** [comment]
Yep cause mylar doesn't distinguish between items in the same directory.  If it's in a given directory it assumes it's part of the given series (meaning it doesn't look at the volume label).

This is something that needs to get fixed, but it requires a good chunk of code change and testing to implement. 

The only workaround atm is to have a separate directory for each series, but you need to remember that when you add a series it takes your default folder format and applies it. So even if it has v1 in the title, if you don't have the $VolumeN label in your folder format it won't change it.  The 'v1' you had edited is just the description of the title,  both series still have the exact same title but with different volumes.

**Comment by ManOrMonster** [comment]
I had it use a different folder but searching doesn't work without me manually adding extra search names.
