### ISSUE TITLE
multiple select error

### ISSUE THREAD

**Issue by jt196** [evilhero/mylar#1195]
In a comic book page, when pressing the checkbox to select all issues on a page and marking as "wanted" or "archived" etc (basically all batch tagging), Mylar presents an error. If you refresh the page you find that some but not all of the comics have been tagged correctly. 

I've seen this error on both mac and synology installs I've been running. If you select all the comics manually (ie clicking each one) then this problem doesn't seem to occur.

**Comment by evilhero** [comment]
I'm pretty sure this is due to having 2 tables within the page - when you do the 'select all', it attempts to use the annuals table (assuming you're hitting on the issues select all), and then when it goes to try and mark said items as Wanted/Skipped/Whatever it can't find them and it errors out.

I thought I had fixed this in a previous commit - let me check if it's still occuring on my local repo (maybe I forgot to push out that change?)

Can you confirm your current branch/commit just so that I know if you're up-to-date running or not?

**Comment by jt196** [comment]
I'm on this version: Version: e1bc2d9786392bfd1114b11e687ba792d6c5363b 

I got it to select all, but when you change the status, it gives you an error - you refresh the page and it has missed some of the files.

**Comment by jt196** [comment]
It's running on a Synology - installed via the web interface then updated via the web interface. If you need any more info please tell me where to get it!

**Comment by evilhero** [comment]
Try updating to the newest commit in the master branch (since you're running Syno).

 Keep in mind that there have been several Syno-pkg users that have had problems running Mylar installed via the interface (namely permissions problems, but there some other items too). They had to switch to a git-install to get rid of their problems they were experiencing (as it was related to the syno-pkg for some reason), as well as then being able to switch branches and use the more up-to-date development branch.

I'm curious - what browser are you using to do the multiple selections?

**Comment by jt196** [comment]
Hey fella - so it's pretty much working on the Syno. I've had to change
RunAs permissions and folder permissions but it's ok.

It's running on Chrome but I've had this problem on a Mac and a Syno
install. The mylar interface comes up with an error rather than the
browser.
