### ISSUE TITLE
Silent abort using pythonw.exe (python.exe works fine)

### ISSUE THREAD

**Issue by TBhimdi** [evilhero/mylar#1197]
The most recent commit (January 26, 2016) silently aborts if pythonw.exe is being used to run Mylar (pythonw.exe doesn't keep a command-prompt open, _much_ nicer obviously if running on a desktop machine). I believe it's because the commit added "sys.stdout" usage and is causing "pythonw.exe" to fail. More info here:

http://stackoverflow.com/questions/24835155/pyw-and-pythonw-does-not-run-under-windows-7

**Comment by evilhero** [comment]
The sys.stdout is in the comictagger portion which shouldn't have any impact on startup. 

Mylar.py changed in the last commit, so make sure your python.exe is pointing to the correct Mylar.pyw file that you are using.

Otherwise I'll have to take a look at this later - but it shouldn't cause a problem ( sys.stdout was/is used in another module if I recall already ).

**Comment by TBhimdi** [comment]
I haven't renamed Mylar.py, so everything still points to the original file. No changes on my end. Mylar was working beautifully (using pythonw), I do an update to the latest changes, now no longer working.

If I manually open a command prompt and run it, same issues, not working with pythonw.exe, but works fine with python.exe (the command prompt of course stays open with Mylar running with python.exe).

Thanks for taking a look at it.

**Comment by evilhero** [comment]
Yep can confirm - it's the sys.stdout/err that's in the cmtagmylar module. Unfortunately the output is required to confirm if the tagging was successful as it returns the new filename and if not what the error is.

The good news is that I have it about 90% fixed atm on my local repo. I just need to figure out if it's failing on mine now due to a daemon calling another daemon process, or if it's just something that I've missed in thr logistics.

You could disable metatagging within the config.ini and try starting mylar. Since the stderr/stdout error is due to loading of that module, not enabling the option might bypass the error.

**Comment by TBhimdi** [comment]
I'll give it a shot. In config.ini, are you referring to "enable_meta"? That's already set to 0 in my ini file. I don't use any sort of tagging through Mylar currently, never have.

**Comment by evilhero** [comment]
Yep that would be it. It was a long shot guess, as I figured one of the modules preloaded it on startup so that takes that out of the equation than. Unfortunately you'll have to wait for the patch later tonight then - even if I can't get it working tonight I think I can push out something so that if you don't have metatagging enabled it will still startup fine as a daemon.

**Comment by TBhimdi** [comment]
Just updated and started it up a minute ago. Working great so far, thanks for the quick fix!
