### ISSUE TITLE
All New, All Different Avengers won't post-process

### ISSUE THREAD

**Issue by claym** [evilhero/mylar#1199]
Getting this error

[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /mnt/media/comics/mylar/All-New All-Different Avengers (2015)

[POST-PROCESSING] Failed to move directory : /mnt/media/download/sabnzbd/complete/comics/All-New.All-Different.Avengers.004.2016.Digital.Zone-Empire.1/All-New All-Different Avengers 004 (2016) (Digital) (Zone-Empire).cbr to /mnt/media/comics/mylar/All-New All-Different Avengers (2015)/All-New All-Different Avengers 004 (2016) (Digital) (Zone-Empire).cbr - check directory and manually re-run

The directory exists, and it's the only one that has an issue.

Thanks!

**Comment by evilhero** [comment]
This should be working in the last few development commits.  The problem is that the nzb name is different than the actual filename so when it tries to copy it can't locate the source file (due to the comma in the title). Thus exact issue just downloaded and post-processed for me fine on the latest development commit with no errors.

**Comment by claym** [comment]
Yep, fixed in dev. Thanks!
