### ISSUE TITLE
Mylar crashing when opened through windows explorer

### ISSUE THREAD

**Issue by Silverwulf** [evilhero/mylar#1203]
I opened up Mylar for the first time in a long time and did a clean install. Tried to open it through windows explorer and it force closed almost immediately. An excerpt of the log file is as follows:

02-Feb-2016 16:46:02 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.101
02-Feb-2016 16:46:03 - ERROR   :: MAIN : Couldn't find latest installed version.
02-Feb-2016 16:46:03 - ERROR   :: MAIN : Output does not look like a hash, not using it
02-Feb-2016 16:46:03 - ERROR   :: MAIN : Uncaught exception: Traceback (most recent call last):
  File "C:\Users\Silverwulf\Documents\GitHub\mylar\Mylar.py", line 269, in <module>
    main()
  File "C:\Users\Silverwulf\Documents\GitHub\mylar\Mylar.py", line 202, in main
    mylar.initialize()
  File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\__init__.py", line 969, in initialize
    CURRENT_VERSION, GIT_BRANCH = versioncheck.getVersion()
  File "C:\Users\Silverwulf\Documents\GitHub\mylar\mylar\versioncheck.py", line 100, in getVersion
    branch_name, err = runGit('branch --contains ' + cur_commit_hash) #rev-parse --abbrev-ref HEAD')
TypeError: cannot concatenate 'str' and 'NoneType' objects

I am able to open and run Mylar through git shell successfully. I am not really sure what is causing the issue. Thanks in advance!

**Comment by evilhero** [comment]
That's actually normal behaviour when you don't have the git executable in your windows PATH environment. Mylar is trying to access the git executable to run the proper commands to determine your version (since you installed via git) - and it can't access it.

If you put git in your PATH environment as below, you shouldn't have any other problems double-clicking from the shell.

Git’s executable is actually located in:
C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\bin\git.exe

Once you find the <guid> part of the path, do the following:

Right-Click on My Computer
Click Advanced System Settings
Click Environment Variables
Then under System Variables look for the path variable and click edit
Add the path to git’s bin and cmd at the end of the string like this:
```
C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\bin;
C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\cmd
```

**Comment by Silverwulf** [comment]
It worked perfectly. Thanks a lot evilhero!
