### ISSUE TITLE
Error on Mass Import

### ISSUE THREAD

**Issue by CovertDad** [evilhero/mylar#1211]
When I attempt to Mass Import, I get the following error output to the log twice, then the import locks, and I have to restart Mylar to be able to try another import, whether Mass or Manual.  Manual import works fine on a title-by-title basis.

Traceback (most recent call last):
  File "/Applications/Mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 3036, in preSearchit
    logger.info(comicinfo['ComicID'])
TypeError: string indices must be integers

**Comment by Rawh** [comment]
https://github.com/evilhero/mylar/issues/1185 partially similar case.

Do you use search?

**Comment by CovertDad** [comment]
That is not a similar issue.  That is a UNICODE conversion error.  This is an error with string indices during import of multiple comics.

**Comment by CovertDad** [comment]
I have found and have a workaround for the problem: in markImports, when multiple comics are added to the list, they aren't added with a ComicID value.  By adding this additional element to the items in the collection, Mass Import and Multiple Import have begun working again.

**Comment by evilhero** [comment]
I'm guessing you're using data that already has metadata present in the files you're trying to import ? The ComicID only gets populated during the scanning process when the metadata is present,  otherwise it doesn't have a ComicID and the search is required. Having the ComicID present would bypass the searching/matching requirement and just auto-add based on ComicIDs.

You don't have to do a PR for it, but can you paste in what it is that you changed in order to get the process working? If it's working and you've tested it (obviously), then I'd like to incorporate the changes into the program so that others can benefit from it - and (if you installed via git) you don't have to worry about updates failing because you have local changes that can't be merged.

**Comment by CovertDad** [comment]
Yes, my data is tagged with ComicVine.

Here is the changed function:

 def markImports(self, action=None, **args):
        myDB = db.DBConnection()
        comicstoimport = []
        if action == 'massimport':
            logger.info('initiating mass import.')
            cnames = myDB.select("SELECT ComicName from importresults WHERE Status='Not Imported' GROUP BY ComicName")
            for cname in cnames:
                #comicstoimport.append(cname['ComicName'].decode('utf-8', 'replace'))
                comicstoimport.append({"ComicName": cname['ComicName'].decode('utf-8', 'replace'), 
                              "ComicID": 'None'})
            logger.info(str(len(comicstoimport)) + ' series will be attempted to be imported.')
        else:
            for ComicName in args:
               if action == 'importselected':
                   logger.info("initiating mass import mode for " + ComicName)
                   cid = ComicName.decode('utf-8', 'replace')
                   #comicstoimport.append(cid)
                   comicstoimport.append({"ComicName": cid, 
                              "ComicID": 'None'})
               elif action == 'removeimport':
                   logger.info("removing " + ComicName + " from the Import list")
                   myDB.action('DELETE from importresults WHERE ComicName=?', [ComicName])

        if len(comicstoimport) > 0:
            logger.debug("Mass importing the following series: %s" % comicstoimport)
            threading.Thread(target=self.preSearchit, args=[None, comicstoimport, len(comicstoimport)]).start()
        raise cherrypy.HTTPRedirect("importResults")

    markImports.exposed = True

**Comment by evilhero** [comment]
Yep that works and it shows me where the error is - thanks very much for providing that information. There's a patch forthcoming that will affect how you patched your version. I'll try and explain myself:

Currently mylar doesn't pull the IssueID properly from the metatagging when the file was tagged using CVS. The fix is coming, but there's nothing wrong with the way you've patched it either - as the upcoming patch just increases the reliability of successful imports, and currently without your patch the mass import won't properly start. 

The only difference is when the patch that's coming is in place, Mylar will be able to retrieve the IssueID for each file that's scanned in, and do a reverse-lookup on the IssueID in order to get the relevant ComicID and Series from CV. 

It would then bypass the search/parsing method as the ComicID is present (in the patch you did, because there is no ComicID present and it can't retreive it from the meta-tagging it reverts back to the search/parsing and the subsequent prompting for intervention if it can't figure it out automatically).

**Comment by evilhero** [comment]
I forgot to include this notice in the latest development commit, but the fix I was mentioning above is now live in the latest development commit.

**Comment by CovertDad** [comment]
Seems to be working like a charm now!
