### ISSUE TITLE
Mylar randomly marking issues as Wanted

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1212]
Earlier today, Mylar seems to have marked several issues of Fantastic Four (1998) (comicid = 4050-6211) and Fantastic Four Annual (1963) (comicid = 4050-2129) as wanted. 

I'm not entirely sure why it chose to do so.

**Comment by lodasi** [comment]
Also, it randomly added an issue from Detective Comics (1937).

**Comment by evilhero** [comment]
Do you happen to have any other series on your watch list that have either 'Fantastic Four'  or 'Detective Comics' in the title? 

Do you have the option 'Automatically mark all issues as Wanted'  enabled within the configuration (last tab)? 

Are you running the latest commit of either the master / development branch?

**Comment by lodasi** [comment]
Neither one was on my watch list. I added some issues back in December, but these were randomly marked as wanted.

The only one I have marked is 'Automatically Mark Upcoming Issues as Wanted.'

I am running the latest commit of the development branch.

**Comment by evilhero** [comment]
The only thing that I can think of that might cause this to happen is if CV refreshed some of their data for a particular issue/series and it had some incorrect values for either the store date or publication date. If the dates where in the future, then Mylar would assume they were upcoming and mark them as Wanted. This is just a theory though, as I haven't seen this happen as of yet personally.

Do you happen to know/remember the particular issues that were auto-marked as Wanted so that I can try and do some testing?

**Comment by lodasi** [comment]
Basically the first 28 issues or so of Fantastic Four (1998). Most of
Fantastic Four Annuals (1963). Issue #613 of Detective Comics (1937).

**Comment by evilhero** [comment]
Yeah I don't see anything at all wrong with those - especially since they're crossing into different publishers. I'm really abit stumped - normally mylar won't add anything unless it's on your watchlist, you do a one-off from the weekly pull, or you use the story-arc option.

I'm just curious now at this point, as like I mentioned above, I'm really abit stumped atm - but, do you use the story-arc option at all?

**Comment by lodasi** [comment]
I don't use the story-arc option at all. This actually occurred last month
too with the Deadpool (2008) series but I just wrote that off.

**Comment by evilhero** [comment]
I'm really sorry it's doing that - I honestly haven't had any other reports/issues from other users about it just adding random issues that aren't on the watchlist to one's Wanted list.

Have you added these series at all in the past in any form (even if it was an add that failed, or you added, then deleted after you marked some issues as wanted perhaps)

**Comment by lodasi** [comment]
I have added the books so that some files I found on an old drive could be
renamed/sorted. But each of the books added have ended and I never changed
the issues from skipped on my own.

**Comment by evilhero** [comment]
But they all currently exist on your watch list right?  Just that the series were ended and/or they weren't marked as Wanted or should have been?

**Comment by lodasi** [comment]
I guess they technically existed on my watch list, but no issues were
marked as wanted.

Does this potentially have to do with running the Update Active Comics
under the Manage > Advanced tab? Would an update to the CV record
potentially trigger that?

**Comment by evilhero** [comment]
Yes the update option could potentially cause this -  especially if CV went off line at any point during the update. Because mylar wipes out all the issue data, redownloads the  new information and then puts the existing status back to what they were on the new dataset during an update.  If the update fails because it can't get new issue data then it looses the information of any previous existing issues status' and then assumes everything is at a Skipped status. 

Updating the CV record would only affect it if issue information were added/changed (such as store / publication date, new issues etc)
