### ISSUE TITLE
Post processing issue on Ubuntu Linux

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#1215]
The follow error is in my log:

Uncaught exception: Traceback (most recent call last):
File "/home/xxxx/.mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/xxxx/.mylar/mylar/PostProcessor.py", line 877, in Process
self.Process_next(comicid, issueid, issuenumOG, ml, stat)
File "/home/xxxx/.mylar/mylar/PostProcessor.py", line 1112, in Process_next
pcheck = cmtagmylar.run(self.nzb_folder, issueid=issueid, comversion=comversion, manual="yes", filename=ml['ComicLocation'])
File "/home/xxxx/.mylar/mylar/cmtagmylar.py", line 329, in run
ctversion = subprocess.check_output([sys.executable, comictagger_cmd, "--version"])
File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/python', u'/home/xxxx/comictagger/comictagger.py', '--version']' returned non-zero exit status 1

**Comment by evilhero** [comment]
Which version of mylar are you running against? (commit) 

It looks like you're using the non-mylar version of comictagger, which is now included with mylar (located within mylar/lib/comictaggerlib).  There is no need to specify the comictagger path any longer, as mylar will only use the version included - mainly due to CV changes with regards to rate limiting and requiring a user agent. Since development on comictagger has stopped, the version with mylar has been patched to work without incurring bans from CV for failing to comply with rate limiting and user agents.

**Comment by apastuszak** [comment]
I'm using:

Version: 46fe69a4394f843a4f1e0f959dda686dee2e7d00 (development) 

Where do I put my API key for the included version?

**Comment by apastuszak** [comment]
Just did a git pull to the latest version and saw the preference change.  I'm going to mark this one closed.
