### ISSUE TITLE
how instal mylar synology : tutoriel

### ISSUE THREAD

**Issue by solspire** [evilhero/mylar#1219]
Hello (sory for my english),
please help me to instal mylar on my nas synology.

I try the package mylar (communoty package)
but i can't inport my comics, nothing seem like to work.

I read two things :
1) change to branch development => I change the 2 files with winSCP but nothing, I rest on master version, no update. This issu doesn't work !
2) instal with clone git ...blabla : I am not a king of informatic, 
so, I need tutoriel, using putty ? step by step with explain code line...because I am not expert.

Think you for help

**Comment by evilhero** [comment]
If you're using the synopackage,  you need to ask in their forums. I haven't a clue on how to install it on a syno except for the instructions that have been pasted in the forums about switching branches. I have no affiliation with them. 

I wouldn't be able to provide a tutorial because I don't own a synology so I wouldn't be able to provide proper instructions. 

If you go the git way there are tons of instructions on google on how to do a simple git clone command in order to get a git repository on your box:
git clone https://github.com/evilhero/mylar -b development

**Comment by solspire** [comment]
:(
