### ISSUE TITLE
Errors when searching or adding series

### ISSUE THREAD

**Issue by jphil2** [evilhero/mylar#1226]
I keep getting a server error when using the search bar.  Error message follows:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Mylar\cherrypy_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "C:\Mylar\cherrypy\lib\encoding.py", line 188, in **call**
    self.body = self.oldhandler(_args, *_kwargs)
  File "C:\Mylar\cherrypy_cpdispatch.py", line 29, in **call**
    return self.callable(_self.args, *_self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 217, in searchit
    searchresults, explicit = mb.findComic(name, mode, issue=issue)
TypeError: 'bool' object is not iterable

**Comment by evilhero** [comment]
It looks like you're having a problem accessing ComicVine. Whether you're unable to reach comicvine due to routing, or you're possibly temporarily banned for going over your api limit. If you need to check your api, if you signin to the api side of comicvine, it will tell you right away if you've gone over your api limit (it resets every hour)
