### ISSUE TITLE
32p search provider - no downloads

### ISSUE THREAD

**Issue by digitaldiatribe** [evilhero/mylar#1229]
Version: 1e0b319d2bb2c7e5bcf14d795e2ef5f70d6f8621 (development) gets no downloads with 32p as the search provider. The comics exists in 32p but will not download on it's own.

2016-03-09 22:44:59	INFO	Could not find Issue 50 of Detective Comics(2011) using 32P [api]
2016-03-09 22:44:59	INFO	Could not find Issue 50 of Detective Comics(2011) using 32P [rss]
2016-03-09 22:44:59	INFO	Shhh be very quiet...I'm looking for Detective Comics issue: 50 (2016) using 32P [RSS]
2016-03-09 22:44:59	INFO	search provider order is ['32p']

Mylar has been working fine as far as last week's releases.

**Comment by evilhero** [comment]
You probably want to toggle verbose on (either with a -v on startup, or in the log tab toggle verbose), and then search again. 

There is no backlog support in 32p as of yet (it's coming soon hopefully), so it relies on rss feeds only. If you're using auth mode, then it's the new releases feed +personal notification feeds, otherwise it's just the new rss feed.  So it's possible that you might have missed it in your rss feed polling.

**Comment by digitaldiatribe** [comment]
This isn't backlog though. It's this week's comics. It worked fine for weeks. I didn't change anything other than update from one development build to another within Mylar's update notice.

I turned on verbose. But since I've downloaded the majority of the comics in my pull list, I'll have to wait to see when the remaining issues show up.

**Comment by evilhero** [comment]
Ah you know 32p just implemented the google captcha. It gets enabled by default if they're getting my bombarded by password attempts, and I think mylar is failing to sign on due to the captcha being present. 

There's pretty much no way around the captcha, and I've been talking  with 32p about it - the best that we've come up with is that Mylar can detect the captcha if it's present, disable the provider within mylar (so you don't keep on trying and possibly setting off a ban of some kind), and have a warning display on the configuration that says you have to manually sign on to 32p in order to release the captcha hold (apparently it will stop prompting after 10 minutes, but depending on the level of the attack it might stay longer)

**Comment by digitaldiatribe** [comment]
Yep, I just logged out and logged back in. New login screen. I guess I should up the RSS interval from the default 20 minutes?

**Comment by evilhero** [comment]
Well heres the thing - once mylar is able to authenticate successfully once, it grabs your security keys and doesn't need to log on again unless the keys become invalid or mylar is restarted (they're stored in volatile memory). It uses the rss to gather all the subsequent notifications.  

So even if the captcha appears immediately after you've authenticated, it won't prompt unless you restart (invalid keys also of course).

I have a patch coming later tonight to address the captcha problem. Mylar will first test to see if the captcha is present before sending authentication info. If the captcha is present, it just ignores the search/rss request. If it's present and there's a warning about invalid password attempts, mylar will disable 32p until the user can check manually to ensure they don't get disabled. If the captcha isn't present, mylar will just authenticate normally. 

This way, at least hitting the website to check if there's a captcha won't invoke invalid authentication credentials and incur a ban. 

I'll also be including a 'test connection' button in the 32p section of the config. It will check to see if there's any invalid password attempts, warnings or if the captcha is enabled and return the results. 

Note that if you're using the Legacy Auth mode within mylar for 32p,the captcha doesn't come into play at all.

**Comment by evilhero** [comment]
This got delayed a bit - was working on it late last night and ended up being around the same time frame when 32p was experiencing problems on their main sign on page (it was like 3am).

Think I have it sorted out, although not quite sure how things will play out because I can't account for every scenario, so it might just be a release and fix things as it happens. 

I expect to push it out later tonight.

**Comment by digitaldiatribe** [comment]
On the latest development build: 838244e62793aef9c3f20a90279b585159eef45c

I'm getting this now when it tries to search on 32P:

Uncaught exception: Traceback (most recent call last):
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 1642, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 251, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 521, in NZB_SEARCH
a = auth32p.info32p(searchterm=searchterm)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/auth32p.py", line 26, in __init__
lses = self.LoginSession(mylar.USERNAME_32P, mylar.PASSWORD_32P)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/auth32p.py", line 247, in __init__
self.ses.cookies.save()
File "/usr/pbi/mylar-amd64/lib/python2.7/_LWPCookieJar.py", line 83, in save
f = open(filename, "w")
IOError: [Errno 2] No such file or directory: '/mnt/pool1/jails/.32p_cookies.dat'

I guess it looks like it's trying to make a cookie file in a folder it's not supposed to have access to on the account I'm running mylar in a jail. Anyway to change where it's putting that file?

**Comment by evilhero** [comment]
Yep, I'll put it in the cache directory of mylar since it has to have access to that directory for everything mylar-related anyways ... fix coming shortly.

**Comment by digitaldiatribe** [comment]
Yep, that fixed it. I added a new comic to the pull list. It immediately searched and pulled the issue from 32P. All good!
