### ISSUE TITLE
"There is an import already running" error

### ISSUE THREAD

**Issue by max6166** [evilhero/mylar#1232]
I have been unable to get imports to work correctly in recent days. The only way I can import is to click the "Import" command to the right of an individual comic. The problem is that subsequently clicking "Import" for any other comic results in the error, "There is an import already running. Please wait for it to finish, and then you can resubmit this import." The only workaround I have found for this it to restart Mylar. So now I must import 1 comic at a time, restarting Mylar each time.

I did try the code in  #1211 as I was experiencing that error as well. Mass importing was not working for me however  It would initiate and then throw the "There is an import already running" error.

Checkmarking all the comics and running the import command results in the same problems.

**Comment by evilhero** [comment]
Which build/commit of mylar are you currently running? 

If you click on the import to the right of the listed comic, you would only be able to run one of those commands at a time. Clicking on it while it's still running in the background will result in the 'import already running message.' 

If you run mylar in verbose mode, does it give more information about what is happening? Are these series you're trying to import already on your watch list?

**Comment by max6166** [comment]
Mylar Version: development
-- git build 4e56a31f77aa87ab875435b896e54dc58f62b188.
Python Version : 2.7.10

Forgot to specify that comics are CVB tagged and the "Use Existing Metadata" option selected.   

Here are the steps to recreate:
1. Restart Mylar to kill all threads
2. Click on the "Import" button beside a comic. Pink status message appears "There was error".
3. Wait until comic shows as Imported and logs state that the import was successful.
4. Click on the "Import" button beside another comic. (Can click immediately, an hour later, doesn't matter)
5. Nothing happens. Error message states that another import is already in progress. 

```
INFO    :: Thread-12 : [FILE-RESCAN] I have physically found 2 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 2 / 4 ]
DEBUG   :: Thread-12 : issue: 4 status after chk :Wanted
DEBUG   :: Thread-12 : pullupd: None
DEBUG   :: Thread-12 : lastpubdate: January 2015
DEBUG   :: Thread-12 : series_status: Active
INFO    :: Thread-12 : Successfully imported : Batman Annual
INFO    :: CP Server Thread-11 : There is an import already running. Please wait for it to finish, and then you can resubmit this import.
```

**Comment by evilhero** [comment]
Make sure that your import folder is not the same as your Comic Location folder. You can't import files from the location where you want to move them to (for obvious reasons), cause it will fail spectacularly. You can have your folder to be imported within your Comic Location path, you just can't have it be your Comic Location path.

Due to sql locking and db corruption, the import process gets locked down to one run occurrence at a time. If you try to do more than that (clicking on the import button more than once before a prior one completes, running another import scan), you'll get that message as well. If an import fails or something else occurs, the lock doesn't get removed, and that's why you could click an hour afterwards and it still would respond with that particular message.

Have you tried deleting the entry from the import results screen, and then attempting to re-scan/import it again?

**Comment by max6166** [comment]
Love Mylar. Have been using it for about months. Import was working fine until recent update with "use metatag" option (which is a fantastic idea). 

The import folder is not the same as the comic folder. I have flushed the import data and retried many times.

I am importing via the individual comic's import command, because Mass Import option is throwing error as per  #1211.

Initial attempt to import throws a brief "There was error" message in red, but does import the selected issues. Subsequent attempts to import other listed comics show green message that import was successful, but do not work. Logs state that import could not be performed because another import is already running.

Perhaps the first import attempt immediately throws an error, despite working, and therefore does not end properly.

I would much rather use Mass Import though, so I am not sure whether this bug is worth devoting time to.

**Comment by evilhero** [comment]
So, here's an update:
I've spent the last 2/3 days (roughly) and went thru the importer against a randomly generated list of about 1700 filenames. As it was erroring out, I would fix it, and fix it, and fix it (you get the idea I'm sure). 

I discovered some bugs that I didn't even know existed, some I knew existed but could never track down, and made some new bugs with some other changes. I've increased the logging within the imports now too, so that it will display what files were able to get parsed properly, which ones failed parsing, and which ones it was able to extract metadata from, along with a whole bunch of other fixes/enhancements. Also the 'mass import' option should be working by the time this goes live as well.

Because this is using the new filechecker (yes, I completely redid that too), things have sped up abit (I can't be sure, but it's at least a minimal improvement in speed at the very least) and while there's still some additional work/enhancements I want to do (please someone help out with a progress bar during the import!) - it's probably almost ready to get pushed out so everyone can try it out.

Expect it probably in a day or two hopefully, since I need to make sure things aren't broken with the filechecker in other modules it uses (namely manual post-processing which should get a huge speed improvement).

**Comment by max6166** [comment]
Love you man. Thanks for all the hard work. I'll keep an eye out for the update and let you know how it goes.
