### ISSUE TITLE
multiple_dest_dirs & meta-tagging

### ISSUE THREAD

**Issue by dreadxero** [evilhero/mylar#1234]
When using multiple_dest_dirs option and a file is located in the MDD and meta-tagging is used without the same directory in the main comic location folder, the file gets processed and removed from the MDD but then is left in the cache directory.

**Comment by evilhero** [comment]
I guess the question is what would be the recommended work flow in this situation. If the main comic location doesn't exist, but the file exists in the MDD, mylar should be creating the directory in the main comic location. I don't think it should be moving files between the MDD and the main comic location when it's metatagging. 

But that being said, if a file is in the MDD then it should remain in there even after a metatagging. 

If I recall correctly, the manual metatagging wasn't supposed to be applied to files located in the MDD (essentially an archive location was it's initial inception), since those files were essentially archived. This was along time ago tho, so it might be necessary to update things to allow for metatagging in the MDD, or at least figure out why it's not working in this scenario.

**Comment by dreadxero** [comment]
Yeah I was a little surprised that it did anything with the MDD directory. I was just playing around with stuff when I noticed it doing this. It may be a better option to not have it do any meta-tagging if the files are in the MDD.
