### ISSUE TITLE
"is not valid bencoding"

### ISSUE THREAD

**Issue by AustinYQM** [evilhero/mylar#1235]
Anything I download via Mylar is failing to be opened automatically by uTorrent. If I attempt to open the file manually i get "Unable to load [torrent name]: torrent is not valid bencoding!". If I then go and download the exact same file from the server (32p or kat) the file runs fine (both by putting it in the folder and by running it manually). This leads me to believe that Mylar is, somehow, messing up the file during download.

**Comment by evilhero** [comment]
There's currently a problem with 32p and the use of Auth mode. I came across this earlier today and it looks like 32p changed some of the usage of '&' to '&amp / &amp;' within the actual link for the given torrent. So what mylar is doing is basically downloading an invalid link, which is causing the invalid torrent file. 

I'm not aware of this happening with KAT however, just 32P since Mylar parses the feeds differently for each provider. Can you confirm that the invalid torrents are coming from both, or just 32p?

**Comment by AustinYQM** [comment]
You are correct, I was mistaken. The problem seems to be entirely 32P. KAT seems unaffected. I tested this by turning off 32P and using only KAT as a search provider and everything worked fine.

**Comment by AustinYQM** [comment]
> at least until the fix goes live.

Not to be a bother but do you have an estimate on when that will be?

**Comment by evilhero** [comment]
It went into the development branch on the April 7th commit (6085c9f).
