### ISSUE TITLE
No results from RSS from NZB Hydra

### ISSUE THREAD

**Issue by Undeadhunter** [evilhero/mylar#1244]
It seems like there are no results van NZB Hydra when forcing the RSS.

I can't see a request happening on NZB Hydra either. 

I tried debugging to see what RSS feeds Mylar calls but the debug doesn't seem to give me the URL? 

Let me know what type of log you need for troubleshooting

**Comment by evilhero** [comment]
You need to enable verbose/debugging mode in order to view the debugging logs (either start mylar with the -v option, or in the Logs tab, there's a Toggle Verbose ON button that does the same thing).

Then just do a force rss again - and see if that picks up anything.. It just does a standard rss feed request to the newznab provider (which would be nzbhydra) - so if it's not working, then I'll have to see how nzbhydra handles rss requests (or if it even does).

**Comment by Undeadhunter** [comment]
I was trying to figure out to see what URL mylar uses but besides the following

```
14-Apr-2016 09:28:52 - DEBUG   :: Thread-12 : [RSS] Fetching items from Hydra
14-Apr-2016 09:28:52 - DEBUG   :: Thread-12 : [RSS] (provider1) now being updated...
14-Apr-2016 09:28:52 - INFO    :: Thread-12 : [RSS] (provider1) 100 entries indexed.
14-Apr-2016 09:28:52 - DEBUG   :: Thread-12 : [RSS] (Hydra) now being updated...
14-Apr-2016 09:28:52 - INFO    :: Thread-12 : [RSS] (Hydra) 0 entries indexed.
```

Not much info is coming out of verbose. 
Since Hydra uses the same provider you'd expect them both to get the same info.

I guess that the url is something like nzbhydra:port/rss?... as far as I can tell nzbhydra doesn't listen to that, rather it uses nzbhydra:port/api?... for all calls (or at least that's what I'm getting out of Sonarr logs) 

I hope this might help?
