### ISSUE TITLE
Clearing Post-Processed in History Tab

### ISSUE THREAD

**Issue by icebal** [evilhero/mylar#1266]
after post-processing, items switch from Snatched to Post-Processed. when you click the button "Clear Processed", the green notification pops up saying its done, but only gets rid of the "Processed" items and not ones labeled "Post-Processed". i dont know the difference between them, but it should be assumed Processed means both.

**Comment by evilhero** [comment]
Hmmm it's been awhile since I looked at the actual status' in the History tab. I do believe one is for manual post-processing and the other for normal post-processing (initiated via the ComicRN script). 

I'll check into this - there should be only one status instead of two similar ones, so definitely needs to get corrected for the clear option to work properly.
