### ISSUE TITLE
Status 400 when downloading cover images

### ISSUE THREAD

**Issue by gitsnow** [evilhero/mylar#1268]
Hi,

I'm getting Status 400's when trying to add cover images either through a refresh or a new comic add.  The comics and issues add without issue.

I'm running Ubuntu 15.10 x64 with Python 2.7.10 and the latest development build.  Not sure if its related to this issue, but I'm also unable to check for new updates via the gui.  I'm able to update via cli though.

**Comment by evilhero** [comment]
Can you run mylar in verbose/debug mode (-v on startup, or enable Verbose ON in the Log tab in the GUI of mylar), and then try to add / refresh again and then paste in the log showing from the logging line of 'Attempting to retrieve the comic image for series' until 'Sucessfully retrieved issue details for...'
As long as the cache directory is writable by the user running Mylar - it really shouldn't have any problems retrieving the images from CV.

The failure to git update is usually due to making local changes on one of the mylar files and then it can't update because it thinks your changes are too important to wipe. But if you're able to update via the cli, and not in the gui then that's possibly something different as you'd get an error in the cli unless you're doing a forceful overwrite. When you check for updates, is there anything in the debug logs indicating what's happening? What command are you running from the cli in order to complete the update?

**Comment by gitsnow** [comment]
Here's the verbose logs from a refresh.

02-May-2016 13:54:21 - INFO    :: Thread-13 : Attempting to retrieve the comic image for series
02-May-2016 13:54:21 - DEBUG   :: Thread-13 : comic image retrieval status code: 400
02-May-2016 13:54:21 - WARNING :: Thread-13 : Unable to download image from CV URL link: http://static5.comicvine.com/uploads/scale_large/6/67663/4945058-01.jpg [Status Code returned: 400]
02-May-2016 13:54:21 - INFO    :: Thread-13 : Trying to grab an alternate cover due to problems trying to retrieve the main cover image.
02-May-2016 13:54:21 - DEBUG   :: Thread-13 : invalid image link is here: http://static5.comicvine.com/uploads/scale_large/6/67663/4945058-01.jpg
02-May-2016 13:54:21 - INFO    :: Thread-13 : Attempting to retrieve alternate comic image for the series.
02-May-2016 13:54:21 - DEBUG   :: Thread-13 : comic image retrieval status code: 400
02-May-2016 13:54:21 - WARNING :: Thread-13 : Unable to download image from CV URL link: http://static4.comicvine.com/uploads/scale_small/6/67663/4945058-01.jpg [Status Code returned: 400]
02-May-2016 13:54:21 - INFO    :: Thread-13 : previous version detected as None - seeing if update required
02-May-2016 13:54:24 - DEBUG   :: Thread-13 : cv status code : 200
02-May-2016 13:54:24 - DEBUG   :: Thread-13 : there are 5 search results...
02-May-2016 13:54:24 - DEBUG   :: Thread-13 : querying range from 0 to 100
02-May-2016 13:54:24 - INFO    :: Thread-13 : Sucessfully retrieved issue details for Batman/Teenage Mutant Ninja Turtles

To update via cli I've been running 

> git pull

When I click Check for new version via the gui, I see this in the logs

02-May-2016 14:00:02 - DEBUG   :: CP Server Thread-6 : Trying to execute: "git rev-parse HEAD" with shell in /opt/mylar
02-May-2016 14:00:02 - DEBUG   :: CP Server Thread-6 : Git output: 09f6e32d603a818f3cba9d4f6161049457602eb0
02-May-2016 14:00:05 - INFO    :: CP Server Thread-6 : Retrieving latest version information from github
02-May-2016 14:00:06 - WARNING :: CP Server Thread-6 : Could not get the latest commit from github

**Comment by evilhero** [comment]
Are you using a proxy / vpn service when using Mylar at all ?

**Comment by gitsnow** [comment]
Sorry for getting back to you so late.  Yes I have a VPN service.  I've tried downloading with the VPN on and off and it still had issues.

**Comment by gitsnow** [comment]
Is this a known issue and is there a workaround/fix?

**Comment by evilhero** [comment]
Honestly, you're the only one that's come forward thus far about having this particular problem - so there isn't a workaround or anything just because I can't replicate the error in order to fix it (at least not yet)
