### ISSUE TITLE
Not getting any search results

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1270]
This morning I tried to add some new comic series' to Mylar, but when I search, I'm not getting any results. I tried restarting mylar, I checked to ensure it had the correct comicvine api, and that I wasn't running up against my rate limit. I haven't used Mylar much the last couple weeks, but I know I was getting search results yesterday, I just didn't add anything at the time. And as far as I know, I haven't changed anything that should cause something like this.. The logs didn't seem to have much information that I could use, but I'll paste the last few entries anyway.. I just turned on debug logging and tried to search again. I would have pasted from the log file itself instead of the web interface, but the file didn't seem to be up to date yet (about 10 or 15 minutes behind).

```
2016-05-04 07:12:40	DEBUG	there are 0 search results...
2016-05-04 07:12:27	DEBUG	Default search mode - this will match on ALL search words
2016-05-04 07:12:07	DEBUG	If you read this message, debug logging is available
2016-05-04 07:12:07	INFO	Verbose toggled, set to True
2016-05-04 07:05:50	INFO	Finished searching via :api. Issue not found - status kept as Wanted.
2016-05-04 07:05:50	INFO	Could not find Issue 154 of The Walking Dead(2003) using NZB.is [api]
2016-05-04 07:04:48	INFO	pausing for 60 seconds before continuing to avoid hammering
```

**Comment by thingfromspace** [comment]
I'm seeing the same thing. Development branch. Similar debug logs as above. I double-checked my Comicvine API key and it's still valid and showing hits, well below the 200/hour limit, for the past hour.

```
04-May-2016 10:47:34 - DEBUG   :: CP Server Thread-3 : Default search mode - this will match on ALL search words
04-May-2016 10:47:45 - DEBUG   :: CP Server Thread-3 : there are 0 search results...
```

**Comment by evilhero** [comment]
It's a CV problem - search bar on  website is broken, and api is returning no results. There's a bug report in their forums about it, just have to wait it out.

**Comment by thingfromspace** [comment]
Looks like it's all working again. Thanks for the leg work @evilhero! Have some bitcoin

**Comment by Bart274** [comment]
is this problem fixed? I'm still having this issue, since yesterday I don't get any search results at all :s

**Comment by evilhero** [comment]
@thingfromspace: thanks for helping to support the coffee fund ;)

**Comment by evilhero** [comment]
@Bart274: everything is working now as far as I'm aware, and no problems on CV.  If you're not getting any search results it could be any number of things - invalid CV api key, maxed out CV api key, banned from CV api usage,  incorrect search term submitted, inability to get to CV from your local machine. 

What is the error you're receiving when doing a search?

**Comment by Bart274** [comment]
I didn't get any error, the search result was just empty
I have used mylar in the past and just installed it again this week and got this behavior, I recloned the repo and now everything works fine, except I can't get my PushBullet notifications to work.
(btw, have you looked into creating a Gitter room for Mylar?)

**Comment by evilhero** [comment]
PushBullet notifications should be working - does it give a valid response when you try the test button for PushBullet? 
And I have no idea what a Gitter room is, but if it's a chat-type of program we do have a irc channel on freenode.

**Comment by Bart274** [comment]
I just used the test button again and I received the notification on my account.
But there are comics being post processed as we speak and they aren't generating notifications.
Is it because the comics are 'skipped' instead of 'wanted' before the post processing?

gitter.im is a chat platform for github project, you can easily link there to issues etc and people can see the activity on the repo from there :)
for example: https://gitter.im/home-assistant/home-assistant

**Comment by evilhero** [comment]
For notifications to work for manual post-processing, you need to enable the option in the Configuration / Advanced Options labelled as 'Manual Post-Processing - Notify on Completed Torrents', but this will only work if you initially grabbed the issues using the Torrent download method within Mylar.

I'm trying to recall what the reasoning was behind not having post-processing notification on every post-processing issue during a manual run. I believe it was due to excessive notifications - usually when people do the manual post-processing it can be quite a large number of issues they're doing, so to receive all of the notifications was just a nuisance, and for some it would go over a certain maximum of notifications allowed (if I recall).

**Comment by Bart274** [comment]
and what if you looked at PlexPy (https://github.com/drzoidberg33/plexpy), they group notifications for recently added for music albums and tv shows.
maybe you can do the same for manual pos-processing where it would only send one notification for a comic series if it keeps finding comics for that serie?

**Comment by evilhero** [comment]
Yes it's a possibility - I'll have to look more into it (I remember someone mentioning this before, but never followed up on it). 

I guess I would have to add some thresholds in there too - so if it's like less or less issues of the same series, to send the individual notifications, otherwise collate them and send the one notification indicating how many issues of the series were post-processed. 

I don't think I can send massive notifications just due to size limitations, so it would probably have to be something along the lines of 'Successfully Post-Processed 100 issues of SuperDuperDude (2015)'

**Comment by Bart274** [comment]
That would be ideal! :)
Now that I can read my comics in Plex, I want to start again with my collection! :)
