### ISSUE TITLE
Locking Local IP Address

### ISSUE THREAD

**Issue by mypcguy** [evilhero/mylar#1282]
Hi,

Mylar's Basic HTTP Host was left as 0.0.0.0. It started passing the NZB location to SABNZBd using http://10.4.63.102. My machine's on a 192.\* network.

I've found the log entry:
mylar/logs/mylar.log.1:16-May-2016 13:36:15 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 10.4.63.102

I have set the IP as 192.xxx.xxx.xxx and restarted mylar with no luck. The http_host shows correctly in config.ini

I'm on Linux Mint 17.3 and my Mylar was downloaded a few weeks back and install from github. My version shows as NONE.

Has anyone got any ideas?

**Comment by evilhero** [comment]
Leave mylar's host as 0.0.0.0, and then edit the config.ini and change the host_return field so that it's :host_return = 192.x.x.x (where x is the remaining octets of your lan ip). Save the config.ini and then start mylar and you should be OK thereafter. 

You might have to go into the Manage tab /Advanced options and check for updates so that it prompts to update. Otherwise, you'd probably have to do a 'git pull' from within the mylar directory, or even a fresh git clone to see if that fixes things with the updater.

**Comment by mypcguy** [comment]
Wow! How fast are you at responding?!

I've done as you've said re ip address and config.ini. I'm going to leave that run for a bit and see what happens.

I ran the manual update which baulked as it didn't know what my version was it couldn't tell if the version on github was a newer version I guess. I'll run a manual update later today.

Thanks very much for your help.
