### ISSUE TITLE
Post-Processing not moving files

### ISSUE THREAD

**Issue by CrucialTaunt** [evilhero/mylar#1283]
Comics are downloading but not being moved to the final directory.  They get moved out of the download directory but then just disappear.  Was working fine until the latest update.  Here's the relevant debug log:

2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] Post-Processing ABORTED.
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] Failed to move directory - check directories and manually re-run.
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] moveing /Users/downloads/complete/Comics/The_Fix_002_(2016)_(digital)_(Son_of_Ultron-Empire)/The Fix 002 (2016) (digital) (Son of Ultron-Empire).cbr ... to ... /Volumes/Multimedia/Comics/The Fix (2016)/The Fix 002 (2016).cbr
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] odir src : /Users/downloads/complete/Comics/The_Fix_002_(2016)_(digital)_(Son_of_Ultron-Empire)/The Fix 002 (2016) (digital) (Son of Ultron-Empire).cbr
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] Renaming /Users/downloads/complete/Comics/The_Fix_002_(2016)_(digital)_(Son_of_Ultron-Empire)/The Fix 002 (2016) (digital) (Son of Ultron-Empire).cbr
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] Destination: /Volumes/Multimedia/Comics/The Fix (2016)/The Fix 002 (2016).cbr
2016-05-16 09:28:35 DEBUG   [POST-PROCESSING] Source: /Users/downloads/complete/Comics/The_Fix_002_(2016)_(digital)_(Son_of_Ultron-Empire)/The Fix 002 (2016) (digital) (Son of Ultron-Empire).cbr

**Comment by CrucialTaunt** [comment]
This is on Mac OSX 10.11.4, 
Mylar Version: master
-- source build fba18e28656339dc2c195a2a91df782ec366e964.
Python Version : 2.7.10

**Comment by evilhero** [comment]
Can you provide some more information? What branch/commit are you currently running? What were you performing - a manual post-processing or a normal sab/nzbget download? If it was a manual, what was the directory that you passed mylar?

**Comment by CrucialTaunt** [comment]
I'm running the most recent master commit as far as I know.  These files are from a normal sab/nzbget download but the issue also happens if I download files outside of Mylar and put them in the monitored directory.  It sees the files, looks like it tries to move them and then they just disappear.  If I put files directly into the final dirs and then re-scan, it picks them up fine.

**Comment by evilhero** [comment]
Are you doing any meta-tagging at all?

**Comment by CrucialTaunt** [comment]
I am, yes... I have the following checked under metadata tagging options:  Enable Metadata Tagging, Write ComicRack (cr) tags (ComicInfo.xml), and Write ComicBookLover (Cbl) tags (zip comment).

**Comment by CrucialTaunt** [comment]
I just tried another one and it looks like it's trying to convert the file to cbz even though I haven't specified that option:
WARNING	[META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Mylar/cache/ and/or the location where Mylar is trying to tag the files from.

**Comment by evilhero** [comment]
Ok, so what's happening (most likely), Mylar is downloading the issues normally and then the metatagging process kicks off. It moves the file (or copies depending on whether or not you selected copy/move as the file option) into the cache directory located within the root of the mylar directory.. It then performs metatagging in unique directories labelled as mylar_XXXXX. Once the metatagging is completed, it then moves the file into the series directory that's monitored by mylar.

What I think is happening (just a guess), is that your metatagging is failing and it's trying to figure out what file is what because what it thinks it's supposed to be.

**Comment by evilhero** [comment]
Heh too quick. Mylar has to convert to cbz when it metatags. There's been some discussion about whether or not cbr should allow metatags, but even based on your settings Mylar couldn't write the zip comment (which is ComicBookLover tagging) to a cbr file ;)  Something for me to look into for the future...

**Comment by CrucialTaunt** [comment]
Yep, that looks like that is the case.  When I unchecked the 'Enable Metadata Tagging' and tried again, it moved it successfully.

**Comment by evilhero** [comment]
Yep, it's your version of unrar that's causing some problems. This has come up before, and whenever it's died at the initial stage (the conversion happens before the actual tagging), it's been that the unrar version that some are using uses timestamps in a different format and it causes the unrar to actual erorr out. There's a post on the forums about it - I'll see if I can find it.

**Comment by CrucialTaunt** [comment]
I think I found it.  Thanks for the quick response and the help!

**Comment by perezbalen** [comment]
I have the same problem. Also on Mac. I had to disable tagging for it to work.

**Comment by evilhero** [comment]
@perezbalen check tge comment just above. Odds are it's your version of UnRAR that's causing the issue - this was also confirmed by other users on the forums posting about the same type of problem (and all seem to be on Mac OS)

**Comment by perezbalen** [comment]
Which version of UnRAR is a good one?

**Comment by perezbalen** [comment]
Because I went here:
http://appledigg.com/t/handle-rar-and-unrar-through-command-lines-terminal-in-mac-os-x-without-archiver-softwares/91
and installed rar and unrar
and it didn't help

**Comment by evilhero** [comment]
It's dependent on the os -  I believe 5.3.11 is the latest - forum post a out it & comictagger is here : http://mylar.forumatic.com/viewtopic.php?f=8&t=1323&start=10

Note that the reason why lower versions of UnRAR don't work properly is due to a bug with pyunrar which is used by Mylar (it just links your os unrar for use with python) in  handling the timestamps within the rar files.

**Comment by perezbalen** [comment]
I'm actually using 5.40 beta 3

**Comment by evilhero** [comment]
You probably need to set the unrar/rar path in the ct_settings.ini file within the comictaggerlib/ct_settings folder as described in the last few posts of the link I pasted above.

**Comment by perezbalen** [comment]
That did the trick. Thanks.
Though it was kind of complicated. Specially for a casual Mac user.

**Comment by evilhero** [comment]
Yeah I still haven't figured out why it's exactly doing what it's doing. ComicTagger is an external program that I've modified to allow for usage within Mylar (and have some extra bells & whistles, albeit not a grand thing), so it's not really my 'baby' per-se.

This is something that was already embedded within CT when I forked it in, and for some reason it's only happening to MAC users for whatever reason. I'll definitely look into this more, whether to have the default set to the binary path if it can detect it - or perhaps even pass some sort of logging message so that the user can modify the setting themselves (maybe within the GUI).

Thanks for reporting back that it worked tho :)
