### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by partymike** [evilhero/mylar#1287]
i use nginx as a reverse proxy and most times when i search, Mylar logs the following error:

2016-05-18 15:16:17 WARNING Search returned more than 1000 hits [16432]. Only displaying first 1000 results - use more specifics or the exact ComicID if required.

And then I see a timeout error on nginx with zero results displayed from Mylar.

Would this be an expected error ref above or would I need to adjust timeout settings on nginx??

Thanks for the excellent software :-)

**Comment by evilhero** [comment]
I think you need to adjust the nginx timeout settings, it can take mylar awhile to receive the results from CV because they have to be staggered a few seconds apart, and then dissecting the data takes more time depending on the results. 

Can I ask what it's doing/searching for that it's coming back with over 16,000 hits?

**Comment by partymike** [comment]
I did a couple of searches that gave the error:

"man plus" & "over the garden wall"....but i think when I shortened the search term to "over the garden" it worked :-)
