### ISSUE TITLE
[Request] allow filters for search settings

### ISSUE THREAD

**Issue by Bart274** [evilhero/mylar#1289]
I would love to be able to have some filters in the search settings, so we can have a list of required words and a list of forbidden words.
I want to use this, because when I added a comic series yesterday and have Mylar search for torrents, it found the wanted issues, but it downloaded the Portuguese versions...

**Comment by evilhero** [comment]
The entire search module is going to get an overhaul soon to fall in line with other items within mylar - but it's still aways off.  

And adding in keyword exceptions would probably cause more issues than not (because of the current state of the search) and then would have to be redone again once the module got changed over. 

I'll look into it, but I'm not sure if you'll see anything until the module gets the update just from a coding aspect alone.

**Comment by Bart274** [comment]
Ok, then I'll wait until you changed the search module :)
