### ISSUE TITLE
Make transmission possible

### ISSUE THREAD

**Issue by MaikoHermans** [evilhero/mylar#1297]
I was wondering if it's possible to make transmission available. I know you can use transmission by making use of the watchdir but I don't really see this as the prefered way to go.

Looking at the gui code I saw that the transmission part was being commented out. Is there a reason for this? Is this something that should be done in the feature or was previously tried but didn't work?

**Comment by evilhero** [comment]
It's on the road map - but it hasn't even started to be coded against. The commented out items in the GUI are just placeholders for when it's available as you can't make items available that don't have relevant  code. 

You're going to have to use the watchdir option until the transmission option goes live, which might be awhile since I don't use transmission, and it's primarily just myself doing the coding (another fellow had offered to help with transmission, but atm at least, it is what it is).

**Comment by MaikoHermans** [comment]
What does it really need?
Can't the transmission.py from headphones be coppied into mylar? it looks like it's pretty much the same. I might be completely off. I have limited experience with python

**Comment by evilhero** [comment]
It really needs everything. 
It's not just as simple as taking a script from a completely different application and plunking it in.  Mylar used headphones as an initial base, 90% of it has been recoded/redone so it works with comics - it's a completely different beast contrary to popular opinion. Integration requires a new work flow, as well as integration into the current work flow already within mylar and being used by everything therein. 

Like I said, it's on the road map but unless someone steps up with a PR for it, it's going to be a while as there's a bunch of stuff coming in the pipe that's being worked on that's going to change a lot about how mylar interacts with CV.
