### ISSUE TITLE
[feature request]One-offs enhancement 

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1300]
When adding a one-off, the GUI hangs.  As far as I can tell, in the background the issue is added to my search list since I do get the books; it would be helpful if there was a modal or some other GUI indicator that 
1.  One-off has been added to the search list
2. Someplace in the GUI I can see one-off issues I've already added to the search list

Additionally, is there any ability for the user to specify the grab-bag directory used when storing a one-off download?  That would also be useful.

**Comment by evilhero** [comment]
Well the thing about the one-off's (and this was at the time it was put in, it probably needs to get updated), is that it doesn't add it to the Wanted list. It just does a search the one time (rss + api) against the given issue. If it finds it, it does the normal post-processing,moving,renaming,etc if applicable, If it doesn't find it, it literally forgets about it.

You can set the grab bag directory within the config.ini (the variable is grabbag_dir).

Once I finish with the new pull-method and CV-less queries, I'll update the one-off's so they'll be actually added to the Wanted list and go through the normal cycle (right now everything requires a specific number, the one-off's don't have that so I have to mock something up that will work for those), as well as having them a separate colour in the Wanted tab so that it's easily viewable (perhaps?)

**Comment by ForumFerret** [comment]
Ah, I see! 

Well, that makes sense. 

I'll edit my config for grab bag, and yeah - appearing on the wanted list in a different color would be 100% great.

**Comment by evilhero** [comment]
Should be all working now as expected - if not, please open a new issue ticket with the details. As this issue hasn't been touched for over a year, I'm going to close this.
