### ISSUE TITLE
[Feature Request] Option to move instead of copy to weekly directory.

### ISSUE THREAD

**Issue by cerinthus** [evilhero/mylar#1310]
As per title.

**Comment by evilhero** [comment]
Unfortunately not a simple task, as moving the file would mean that it would have to monitor a seperate directory or forget about the file all together, which would mean that in it's current state it would attempt to redownload it (since it didn't know it was downloaded).

It's possible, but the move to a weekly directory would also fall in line with not having series directories auto-created - which in itself requires abit of code rework. Not saying it can't or won't be done (I really rarely ever say that it seems), but I haven't looked into how much of a code rework/change this would entail and the scope therein.

I'll mark this as an enhancement request and hopefully can get around to looking into it in the next little while. Will update this post accordingly ;)

**Comment by cerinthus** [comment]
I'll keep an eye out.  Thanks!
