### ISSUE TITLE
Failed Download

### ISSUE THREAD

**Issue by dilbaggins** [evilhero/mylar#1315]
I fixed the SSl cert issue by creating a new cert for my indexer (nzedb).  however i am now seeing "unable to download nzberrors" :  

	Unable to download nzb from link: https://INDEXERLINK/api?apikey=KEY=get&id=bc429d119fb829e536a2fac38c2a973cb3e10fda [https://INDEXERLINK/getnzb/bc429d119fb829e536a2fac38c2a973cb3e10fda.nzb&i=21&r=f6594c1a7e973da7729835923a49194e]

when i manually go to this link the nzb is correctly being downloaded.  @evilhero i can give you access to my public indexer (based on nzedb an amazing indexing platform,  if you want to check it out firsthand.

**Comment by evilhero** [comment]
Sure, if you pass a login and such I can attempt to test it out based on what my system/install is doing. It still might be something local with your setup, but definitely to help narrow things down, I can test things out from my side ;)

**Comment by dilbaggins** [comment]
@evilhero i may need an external email to send you the invite.  (git no longer has the private message feature)

**Comment by evilhero** [comment]
I'll post it then wipe it after (just so the spam bots don't get me lol) - evilhero@mylarcomics.com

**Comment by dilbaggins** [comment]
just checked github api to get it (invite sent) :)  thanks @evilhero

**Comment by evilhero** [comment]
K got it.. I'll sign in hopefully in a few hrs when I'm in front of a machine.  :)

**Comment by dilbaggins** [comment]
thx sir!

**Comment by evilhero** [comment]
OK tried it and got the exact same error - which I believe I was also receiving this am when I was doing some testing.  So it's definitely not a problem on your end - I believe the format of the url that Mylar is sending is malformed, but I'll need to check it in the morning since it's 4am and I have to get a few hrs of sleep. 

I'll fire back an update when I can do some testing on it, most likely in the late am ;)

**Comment by evilhero** [comment]
Didn't forget - unfortunately my time in front of the machine has been nonexistent today due to kids. I'll try later on tonight again once they're in bed and hopefully I can push out the fix at the same time.

**Comment by evilhero** [comment]
Sorry about the delays, but I think I might have figured it out.

It 'looks' like nzedb has a problem with the api 'get' command (https://SITENAME/api?apikey=xxxxx&t=get&id=nzbid). Using this link - which Mylar will use by default since it's regenerating the link on the fly and rebuilding it to accommodate any changed apikey, it failed to download and received the same response as you. Even from a browser window, same response (actually blank screen).

Now, using the actual link (https://INDEXERLINK/getnzb/nzbid.nzb&i=UID&r=xxxxxx) it was able to download within Mylar and in the browser.

I'm just not sure at this point if it's a problem with the nzedb api not supporting the t=get option (even though it's in the docs), or if it's something else. I can get around this fairly easily by adding an option to force the /getnzb option instead of the t=get option - but again I'm just not sure at this point where the problem lies.

**Comment by dilbaggins** [comment]
@evilhero  i put in a issue on the nzedb git and linky'ed this conversation: https://github.com/nZEDb/nZEDb/issues/2212 

lets see what comes up.

p.s. im sure you smart people will figure it out :)

**Comment by DariusIII** [comment]
It should be fixed in commit https://github.com/nZEDb/nZEDb/commit/e5cbb3d68e0422e830d2a5b29ed121c8e98f08e6

**Comment by dilbaggins** [comment]
Fixed thank you @DariusIII  and @evilhero .  love how my two fave pieces of software work together. kudos to you guys for all you do!
