### ISSUE TITLE
Wanted  page - %00 Internal Server error

### ISSUE THREAD

**Issue by gamergeekv2** [evilhero/mylar#1322]
Seems like it's pulling comics like it should but I can't check the wanted page to be sure what has been grabbed. Also, when I click add series on the pull-list page I can see it getting added on the log but the GUI does nothing.

**Comment by evilhero** [comment]
The Wanted tab problem has been fixed in the latest development commit (See #1319 ). As long as you're on that commit,  you just need to do a Recreate Pullist for things to line up properly again and then you won't have any problems accessing the Wanted tab.

The GUI not response is intentional when adding a series from the pullist. Alot of users have asked for the ability to add a series from the pullist and have it go into the background to add the series, but keep the pullist screen up so that they don't have to keep flipping back/forth.
