### ISSUE TITLE
Mylar downloading issue for different volume

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#1326]
I've been noticing that Mylar sometimes downloads an issue that is for a later or earlier volume than the series it's trying to download for. 

For example: i have The Spectacular Spider-Man v1 in Mylar and not v2, but for some reason Mylar sends "The.Spectacular.Spider-Man.v2.02" to sabnzbd and i can't see any reason. 

In sabnzbd the source is http://xxx.xxx.x.x:8090/mylar/api?apikey=xxxxxxxxxxxxxxxxxxxxxx&cmd=downloadNZB&nzbname=The.Spectacular.Spider-Man.v2.02.nzb

Mylar also see's the v2 download as v1 and post processes the file as such so i end up with a v2 issue in my v1 folder.

Any ideas? Anything else i can provide to help out? It's not just happening to this series, there are other series too. I've checked the logs but cant see anything out of the ordinary.

**Comment by evilhero** [comment]
If you're up-to-date on the development branch, the large commit from a few days ago should have solved this problem - as well as the manual post-processing problem.

You might have to make sure that the volume label within Mylar for the given series is correct as well (since it's auto-populated from CV, it's not a 100% guarantee it's accurate unfortunately). You can find it in  the series detail page for the given series, Edit Settings tab, Version Label.

**Comment by jimbojnr81** [comment]
Yeah its all up to date. I had just done a fresh install of the Dev branch about 30mins before posting this thinking it might help my problem but unfortunately no. (Although upon checking the Info tab in settings the branch is saying Master but it's definitely the Dev branch i installed...) I'll do one more fresh install just in case i used an older version i already had downloaded or something went wrong with the update.

The volume label in Mylar for the series is showing the correct Volume number. 

Also the post processing is working 99% of the time, the one series so far that i have noticed isn't processing is The Amazing Spider-Man v1. I've noticed that the nzb its grabbing doesn't have the volume number in the file name, could that be the cause?

**Comment by jimbojnr81** [comment]
I also just added The Spectacular Spider-Man v2 just to see what happens, it downloads the same v2 file but then mylar post process the v2 file to the v1 The Spectacular Spider-Man same as above.

**Comment by evilhero** [comment]
I think the problem might be CV data related.  From what I could see quickly, there is no spectacular spider-man v1,  as it's actually called Peter Parker, the spectacular spider-man v1.  Then v2 becomes the spectacular spider-man v2.  

So mylar would only match against 'The spectacular spider-man v2', and normally if it's the only title of that name it would bypass the volume check if it's a v1 or not specified, but for some reason it's removing the volume entirely and just matching it. 

It's a bug, I just need to duplicate it on my end to see what's causing it - whether it's a CV data related problem, the way mylar is handling that data, or a combo of both.

**Comment by jimbojnr81** [comment]
Something i did notice on this that may or may not help. I put the Alternate Search Names in as Peter Parker, the spectacular spider-man and selected issue no. 263 as wanted (this issue only exsists in vol 1). In the logs i noticed that it initially searches for "The spectacular spider-man", cant find it and then searches for "Peter Parker, the spectacular spider-man" which makes sense using the alternate naming. Is there a way to override it searching for the original name first and just force search for the alternate name instead?

**Comment by jimbojnr81** [comment]
or even give us the ability to manually change the title of the series completely?

**Comment by evilhero** [comment]
The original name searching can't be changed, as in almost all cases searching against the original name (if it's incorrect) won't return any valid hits, which would then get picked up by the Alternate Search Naming.

And changing the title of the series isn't a valid option either as because it's constantly polling against CV it would always be matching up against different names and it would cause a lot of confusion within the program itself. 

The indica says it's Peter Parker, the spectacular spider-man maybe it needs to get changed on CV itself so that it references the correct series title.

**Comment by jimbojnr81** [comment]
I don't think CV will change it as the series started with Peter Parker at the start of the title and then dropped it 127 issues later, so it's half and half. 

All good, at least it means that Mylar is not doing anything wrong and my install is working, it's just the bloody naming of the comic. Why are comic issues always Spider-Man related...
