### ISSUE TITLE
[Feature Request] Zooqle support

### ISSUE THREAD

**Issue by cerinthus** [evilhero/mylar#1330]
With KAT gone, zooqle appears to be the next best thing for public trackers.

**Comment by Lasborg** [comment]
A variety of public trackers would be nice.The way it is implemented in sickrage/sickbeard would be even better.

**Comment by evilhero** [comment]
zooqle doesn't have any comics really - it's more for the other stuff it looks like (which is neat, but still not for Mylar).

I have a commit going up shortly into dev that uses 3 different public torrent sites to poll/retrieve information from depending on what it is that is being done (TorrentProject for search/ Demonoid & WorldWideTorrents for RSS). TP is a meta-search engine that hits on 5/6 torrent-sites, and DEM & WWT are being used as that's where the most recent stuff seem to be going to).

I don't think a variety of public trackers would help in this case, since comics isn't like movies/tv shows where it can change from site to site - plus there are really only a small handful of sites that actual have comics and are being updated/maintained.
