### ISSUE TITLE
Unable to refresh all comics

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#1332]
Go into Manage->Manage Comics.

Change to Show All Results per page.

Click on the checkbox on top so that it selects all comics.

Choose refresh from Dropdown and Mylar says:

"You didn't select any comics!"

Nothing downloaded last night, because all of my comics need a refresh for some reason.

If I select individual comics it does the same thing.

Running latest development branch.

**Comment by evilhero** [comment]
Haven't been able to confirm ad of yet, as haven't gotten to my machine.  Will update / fix if can replicate, and will be in the next development commit if can be fixed.

**Comment by evilhero** [comment]
Yep, definite bug. Stupid conversion on my part - was erroring out on logging the number of results incorrectly. Will be fixed in next dev commit.

**Comment by apastuszak** [comment]
Thank you!

**Comment by jimbojnr81** [comment]
This is happening to me but for every instance where i can select all, is manage comics, import comics etc. Doing it in lots of 10 25 or 50 or one at a time works fine, but All give me the error 'no comics selected'. On the latest Dev version. As far as i can remember it has always done this, but ive never really needed to use it. Also i have just imported all my comics into mylar (20k+) so that might be a factor.

**Comment by evilhero** [comment]
The number of comics isn't a factor in the select all, unless of course you're viewing 20k+ of comics on one screen ;) 

The select all option is dependent on the screen you're on when you encounter the error. 

If you can let me know the screen you're trying to do a select all option on and what it is that you were trying (ie. manage comics tab, delete selected) I can look into it more. Currently the fix was for the Manage Comics page, which should have worked on other ones as well, but not then I need the information to fix things.

**Comment by jimbojnr81** [comment]
At the moment it's in the manage comics page, but it was also doing it in the import results page (only when selecting all, clicking mass import didn't return the error)
