### ISSUE TITLE
mylar-sabnzbd download woes

### ISSUE THREAD

**Issue by linklooklisten** [evilhero/mylar#1339]
i've had this issue before, see [https://github.com/evilhero/mylar/issues/886](url), and it looks like it has returned. sabnzbd states that the API key is incorrect, yet mylar states that it tests ok. i also use nzbgeek if that helps at all. this was working about a month ago, not too sure what happened since. also, every time i click on Wanted, i get a 500 internal server error.

**Comment by evilhero** [comment]
Check the config.ini values to make sure the api key given therein is correct. Without seeing the debug log, it's really difficult to figure out what's going on just from describing it, especially since no one has mentioned it since that og post. 

I'd also need to see the 500 error that's being flipped back, as well as knowing if you're running an up-to-date version of mylar.

**Comment by linklooklisten** [comment]
here's the 500 error:


500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Users/matt/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Users/matt/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/matt/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/matt/mylar/mylar/webserve.py", line 1821, in upcoming
    if int(upc['weeknumber']) == int(weeknumber) and int(upc['year']) == int(weekyear):
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by evilhero** [comment]
Make sure youre running the most recent development branch and do a recreate pullist. It will fix the error which is due to recent changes in the pull that are trying to be applied but you already have the pullist populated, so it needs to recreate it with the new items.

**Comment by linklooklisten** [comment]
ok, wanted is fixed now. thanks for that.

also, the api is correct in the config file.

**Comment by linklooklisten** [comment]
log:
2016-07-28 12:13:32	INFO	Connection to SABnzbd tested sucessfully
2016-07-28 12:13:32	INFO	APIKey provided is NZBKey which is the correct key.
2016-07-28 12:13:32	ERROR	Error detected attempting to retrieve SAB data using FULL APIKey: API Key Incorrect
2016-07-28 12:13:32	INFO	status code: 200
2016-07-28 12:13:28	INFO	Branch detected & set to : development

**Comment by evilhero** [comment]
So wait it's not having any problems downloading issues correct? 

The sab error message is correct because the first time mylar tries a key it's as the full api key, which isn't correct as you've given the nzb key. So sab logs it as an incorrect api key.  Then mylar tries the provided key as an nzb key, and succeeds - no error in log pertaining to that particular query against to sabnzbd. 

I should probably have it try the nzb key first so that it doesn't get to the full api key request if it's correct.

**Comment by linklooklisten** [comment]
It rarely ever downloads an issue. Sometimes it does, but most of the time it doesn't.

**Comment by evilhero** [comment]
OK so then I need to see the debug log for a search and what happens during the search. I don't think it had anything to do with the sabnzbd key at this point, as this probably correct.

**Comment by linklooklisten** [comment]
I'll send it soon

**Comment by linklooklisten** [comment]
Doesn't really look like anything is wrong, but I swear this thing doesn't download comics!!
2016-07-28 18:22:40	INFO	Connection to SABnzbd tested sucessfully
2016-07-28 18:22:40	INFO	APIKey provided is NZBKey which is the correct key.
2016-07-28 18:22:40	DEBUG	You may have given me just the right amount of power (NZBKey), will test SABnzbd against the NZBkey now
2016-07-28 18:22:40	ERROR	Error detected attempting to retrieve SAB data using FULL APIKey: API Key Incorrect
2016-07-28 18:22:40	INFO	status code: 200
2016-07-28 18:22:40	DEBUG	testing connection to SABnzbd @ http://192.168.1.2:8080

**Comment by evilhero** [comment]
That's just from the test connection, try doing a manual search for a particular issue (the magnifying glass located in the options column in the issues section on the series detail page) and you should get a lot more in the logs.

**Comment by linklooklisten** [comment]
What the hell!?!?! It found it! Going to play with this a bit more. Going to double check and make sure nothing older is set as skipped. Thanks for the help, sorry if this was a waste of time. I feel bad as this is novice stuff!

**Comment by evilhero** [comment]
Heh no worries. Just remember that the rss search fires off every 20 mins (by default), and the rss + api goes off every 6hrs (unless you force it with the Force Search option on the Wanted tab) and the magnifying glass search does an rss + api search for that particular issue without marking it as Wanted.

**Comment by linklooklisten** [comment]
For RSS, I enter my nzbgeek UID, right? Tried to google it earlier, but do I have to set up anything else? Is RSS mandatory?

**Comment by evilhero** [comment]
Yes just your UID which is taken usually from the provider's rss feed and designated with the i=xxxxx where the xxxxx is the UID. 

It's not mandatory but it hits it every 20mins and it will probably save you doing backlog searching since Mylar caches all the rss entries for each provider - so the longer you have the cache running, the more entries in the dB for mylar to quickly poll against instead of hitting your provider and causing api hits.

**Comment by linklooklisten** [comment]
Ok cool. Going to add it in there anyway. Thanks again brethren!
