### ISSUE TITLE
cache still filling up with post processing files.

### ISSUE THREAD

**Issue by icebal** [evilhero/mylar#1361]
mylar is still filling up with the mylar_XXXXX folders in the  cache directory. i saw CBRs in there atleast, i dont usually do CBZ files. im on the latest dev release. after deleteing the folders, some are reappearing, even though the files its trying to post proccess have already been moved.

**Comment by icebal** [comment]
it looks like its related to the manual post-processing. i just tried it out on Lady Mechanika. all folder permissions are correct, comic permissions are correct. i get the error:
 [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
and the folder stays in the cache dir.

**Comment by evilhero** [comment]
If you have metatagging enabled the it's trying to convert the download  cbr's to cbz. 

Unless you specified the cache directory in the config, it will default to the cache directory within the root of the mylar directory. Mylar has to have full permissions within in order to extract, move/copy, and delete. 

In this case, it's usually due to permissions of some kind, but I'd need to see the debugging logs showing the post-processing as there hasn't been any problems indicated by any one else regarding this (so replicating the problem would be very difficult)

**Comment by icebal** [comment]
.cache was in mylar root, and permissions were correct. it was processing correctly, just wasnt removing the files. i have recreated it to get clean logs. when it happens again i will post them, or close the issue if i cannot get it to repeat :)
