### ISSUE TITLE
Dognzb and nzb.su

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1363]
Does Mylar not work with these anymore? I've been noticing that Mylar hasn't been finding anything from these sources. Under search providers, when I check mark, enter dognzb api into the field and restart. It searches using it. But nothing comes up. Then I go back to settings, search providers, dognzb is unchecked. Not sure why. I'm on the latest development branch. Willing to provide the api keys so you can try.

Thanks

**Comment by evilhero** [comment]
There was some code put in a while ago that if you went over the dog api limit, it would temporarily disable the provider until the situation could be manually rectified by the user. I'm wondering if with all the changes that have happened with the other providers/services within Mylar that perhaps something is failing now with that. I'll have to check more into this (haven't used dog since they took down lifetimes, not because of them perse, but just wasn't using it)...

Nzb.su nothing has changed as far as I'm aware - unless they've made changes to their API, or they've set some API restrictions that I'm unaware of (I don't have an account there, so I cannot test against nzbsu)

**Comment by lostkt87** [comment]
Ok, I have. I problem with providing you the APIs for either. Just need a secure way to send them only to you.

**Comment by lostkt87** [comment]
Stupid autocorrect, I have no problem that should say.

**Comment by evilhero** [comment]
heh - I'll blank out the email after I receive the email but you can send it to evilhero@mylarcomics.com

**Comment by evilhero** [comment]
Will be checking into this hopefully later tonight - might just take out the api limiter for dog within mylar since that's probably what's causing this to occur.

**Comment by evilhero** [comment]
Are you using a VPN with mylar by chance ?

**Comment by lostkt87** [comment]
No
