### ISSUE TITLE
Duplicates are not processed if series is complete

### ISSUE THREAD

**Issue by jerblack** [evilhero/mylar#1365]
I'm seeing a pattern during my imports where if the files added to the import folder are duplicates to already existing files, and the series they are a part of is already 100% complete, the duplicate in the import folder will not be moved to the duplicates folder. The file just stays in the import folder, requiring manual intervention on the import process. Here's what it looks like in the log.

```
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Checking folder Z:\_work\proc for newly snatched downloads
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : there are 1 files.
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : [FILENAME]: BATWING # 027.cbr
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : I have located 1 files that I should be able to post-process. Continuing...
28-Aug-2016 13:15:00 - WARNING :: FOLDERMONITOR : Batwing is either Paused or in an Ended status with 100% completion.
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : [POST-PROCESSING] No matches for Manual Run ... exiting.
28-Aug-2016 13:15:00 - INFO :: FOLDERMONITOR : [FOLDER-CHECK] Finished checking for newly snatched downloads
```

**Comment by evilhero** [comment]
Yeah atm that's by design - I can look into the code to move them out, but it's not even getting to that point since the series is 100% complete it just ignores the series as being a valid match. So it's not even getting to the compare part where it would hit the duplicate checker - I would have to make that an optional choice in the config as the current work flow (where it ignores series that are 100% complete) was requested by several individuals,  and restructuring to an additional work flow is going to require some code rewrite & testing.

**Comment by jerblack** [comment]
Thanks. I would appreciate that. I am importing a large number of comics at the moment, and ideally after a "Manual Post-Processing", the only thing that would be left in that import folder would be files for which there was no series to match them to. I can't trust that in the current setup and I find myself spending a ton of time manually intervening on imports to see if the file itself just has a problem that broke post-processing (which happens a ton, and for some reason completely stops the post-processing process if a single error in the program occurs)  of if the file already exists.

Since we're talking about workflows, the ideal workflow for me seems like it would be the simplest to support.
1. Add files to import folder
2. Run manual-post processing on the folder, which would leave behind only files for which there was no series associated in Mylar.
3. Mass import the rest under "Scan Comic Library", adding them as series in Mylar and leaving behind only files for which no matching series was found.
4. Import folder should be empty when 2 and 3 complete unless a real problem has occurred.

Right now that's not really true for 2 or 3. 
- 2 could be a problem at the moment because manual post-processing stops completely when a single file is found that it does not know what to do with (usually manifests as an uncaught exception). 
- 3 could be a problem because duplicates aren't being properly removed, so I need to go either manually import them or figure out if I already have them. 

I

**Comment by Nobrumski** [comment]
I would love if I could enable series to continue post processing even if they are complete or paused with 100% completion. 

I am currently re-organizing my library and since my collection got spread among multiple drives I am trying to consolidate. This has left me with some duplicates. 

The issue I run into is Mylar scans the import folder and comes across issues where the series is is ended or paused with 100% completion and the match is ignored. Once Mylar runs manual post processing on the import folder and moves the duplicates and missing issues, I then run a scan comic library on the import folder with auto add, use existing metadata, and move files checked. This way I can mass import any new series I was missing. This is also then trying to re-add series which are complete since those issues are still in the import folder even though they are duplicates.
