### ISSUE TITLE
Mylar+Python+Synology=SLOW

### ISSUE THREAD

**Issue by xkelly** [evilhero/mylar#1375]
My Synology Diskstation DS412+ has started experiencing massive slow downs the last few months.  Not sure if it's Mylar related, but I noticed each time that memory was of 80% utilized and that Python was the culprit. I began stopping python apps with minimal gains until I stopped Mylar. Memory dropped back to about 25% utilization.  Memory stayed low when I restarted everything backup, including Mylar.  But over time, the system starts dragging badly. Restarting Mylar always fixes it, but it's becoming a bummer.  I've 3GB of RAM in the Diskstation.  Not sure if there's a memory leak or what. Any ideas? 

EDIT: Forgot to mention, it's been working fine for a couple of years. The only major change, other than obligatory OS updates, was upgrading storage speed from green drives to 7200 RPM.  Apps have been pretty much status quo.

**Comment by evilhero** [comment]
It might have something to do with your version of mylar that you're running if it's not up to date - as well as your version of python.  Since a lot of what mylar does relies on CV, if things stall from that side, it can cause a nasty ripple effect that just locks up a lot of stuff within mylar - have you been having any provlems adding /refreshing series? Do you have a lot of issues on your Wanted list?

**Comment by xkelly** [comment]
Good points. This is what the version shows as:

Mylar Version: master
-- git build 562a8a851204051c1a60a63d80f6b1beb1b499fa.
Python Version : 2.7.11
You know, I rarely look at my wanted list. Just did. LOTS of stuff. Quite a
bit of scrolling to get to the bottom.

Also, Performance has been poor with adding series. i usually browse the
This Week list, select a series I'm interested it not already in my list.
Finding something I like, I hit Add Series and that's when it falls apart.
I takes a long time for the interface to present the search results to
select from. Then when it does and I hit Add this comic, it's hit or miss
what happens next. Sometimes it takes me to the comic's page, waiting for
CV to refresh the information.  Sometimes it takes me back to my main
library page. The comic may have been added or it may not have. Usually
I'll do a manual search again to add it.  After 4 or 5 comics, I give up,
too frustrating.  Actually, it's so slow/glitchy, I'm not sure what the
workflow is supposed to be when I select a comic under This Week.

---
Scott Kelly

m: (917) 562-8148
e: scott@xkelly.com

**Comment by evilhero** [comment]
There was a fix in dev that hasn't reached master yet (or it's going to soon, I can't recall exactly at this moment) that dealt with the return to the main page / added series page problem. It also addressed some other issues with adding series, but for the most part adding a series is pretty straight forward and what you seem to be doing already: add series from pulllist, comic gets added to watchlist. 

The search results returned depend obviously in what's being searched - a lot of times it's a very open ended search call due to how CV allows searches (which really sucks), so it might well return 2000+ results, but only display the first 1000 to the screen - and out of those 1000, probably 6/7 are actually relevant. 

You also have to remember that Mylar is at the mercy of CV as far as search results and timing usually. If you use the CV api key you have in mylar with any other program you will hit their api limit (which is something like 200/hr I think) and then weird and wonderful things start happening that can't really be explained or even duplicated. 

In the dev branch there is a new pullist method which takes a lot of the load off of CV api hits and almost does away with the add series search (it knows the comicid and will just auto-add the series immediately with no searching needed), as well as better naming which results in better search results if it needs to search (the pullist mylar pulls from in the master has a bad habit of abbreviating words that cause the search within mylar to return almost no results of merit)

**Comment by xkelly** [comment]
Thanks for the reply. Looking forward to some of the updated goodness as the builds rollout. 

—
Scott Kelly
m: (917) 562-8148
e: scott@xkelly.com

**Comment by xkelly** [comment]
Thanks for the reply. Looking forward to some of the updated goodness as
the builds rollout. l
—
Scott Kelly
m: (917) 562-8148
e: scott@xkelly.com


On Sep 4, 2016, at 10:22 PM, evilhero <notifications@github.com> wrote:

There was a fix in dev that hasn't reached master yet (or it's going to
soon, I can't recall exactly at this moment) that dealt with the return to
the main page / added series page problem. It also addressed some other
issues with adding series, but for the most part adding a series is pretty
straight forward and what you seem to be doing already: add series from
pulllist, comic gets added to watchlist.

The search results returned depend obviously in what's being searched - a
lot of times it's a very open ended search call due to how CV allows
searches (which really sucks), so it might well return 2000+ results, but
only display the first 1000 to the screen - and out of those 1000, probably
6/7 are actually relevant.

You also have to remember that Mylar is at the mercy of CV as far as search
results and timing usually. If you use the CV api key you have in mylar
with any other program you will hit their api limit (which is something
like 200/hr I think) and then weird and wonderful things start happening
that can't really be explained or even duplicated.

In the dev branch there is a new pullist method which takes a lot of the
load off of CV api hits and almost does away with the add series search (it
knows the comicid and will just auto-add the series immediately with no
searching needed), as well as better naming which results in better search
results if it needs to search (the pullist mylar pulls from in the master
has a bad habit of abbreviating words that cause the search within mylar to
return almost no results of merit)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1375#issuecomment-244645797>, or mute
the thread

**Comment by xkelly** [comment]
Thanks for the reply. Looking forward to some of the updated goodness as
the build
—
Scott Kelly
m: (917) 562-8148
e: scott@xkelly.com


On Sep 4, 2016, at 10:22 PM, evilhero <notifications@github.com> wrote:

There was a fix in dev that hasn't reached master yet (or it's going to
soon, I can't recall exactly at this moment) that dealt with the return to
the main page / added series page problem. It also addressed some other
issues with adding series, but for the most part adding a series is pretty
straight forward and what you seem to be doing already: add series from
pulllist, comic gets added to watchlist.

The search results returned depend obviously in what's being searched - a
lot of times it's a very open ended search call due to how CV allows
searches (which really sucks), so it might well return 2000+ results, but
only display the first 1000 to the screen - and out of those 1000, probably
6/7 are actually relevant.

You also have to remember that Mylar is at the mercy of CV as far as search
results and timing usually. If you use the CV api key you have in mylar
with any other program you will hit their api limit (which is something
like 200/hr I think) and then weird and wonderful things start happening
that can't really be explained or even duplicated.

In the dev branch there is a new pullist method which takes a lot of the
load off of CV api hits and almost does away with the add series search (it
knows the comicid and will just auto-add the series immediately with no
searching needed), as well as better naming which results in better search
results if it needs to search (the pullist mylar pulls from in the master
has a bad habit of abbreviating words that cause the search within mylar to
return almost no results of merit)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/evilhero/mylar/issues/1375#issuecomment-244645797>, or mute
the thread

**Comment by xkelly** [comment]
Hey EvilHero-

Since I have to go in a frequently start/stop/start the mylar package to keep python from choking my NAS, I'm thinking I'd rather setup a scheduled task to do it 4-5 times a day. 

Would you be able to give me the script parameters to restart the Mylar service? Since this is SynologyNAS are embedded Linux devices, I'm assuming the syntax is pretty linux standard beyond the actual service name and path.  

Thoughts?

**Comment by rupaschomaker** [comment]
If using the synology package, /var/package/mylar/scripts/start-stop-script
which takes start, stop, restart, and maybe status.
