### ISSUE TITLE
Enhancement Request For Weekly Pull List: Publisher

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1377]
Lots of comics on the weekly pull list just have 'COMICS' as the publisher.  Would it be possible to get, y'know, 'BOOM Studios' and such on there?  Or is it a case of "that's just the data we have"?

Thanks!

**Comment by evilhero** [comment]
It's due to the nature of the data that the pull list comes from - they don't distinguish publisher aside from the typical DC, Marvel, etc. Unfortunately there's nothing that can be done with that particular data set to include the publisher, but there is an alternative that you can use.

Shutdown Mylar, open up the config.ini and edit the alt_pull variable so that it's 'alt_pull = 2'. Save the config.ini and then start up Mylar. You'll notice a few things that are more improved with the pull list now (such as publishers, proper-casing, no searching when adding in some cases, ability to go a few weeks in advance, and most importantly, far fewer CV api hits)...

Note that if you get an error when trying to access your Wanted tab, go into the Weekly tab and do a Recreate Pullist and things will get corrected.

**Comment by thewindupboy** [comment]
Thanks much!  You are awesome as always

**Comment by thorinmesser** [comment]
alt_pull = 2 seems great, except now there seems to be no way to search a comic before adding. Can the comic name link to a search so I can see what an unfamiliar new book is before adding it?

**Comment by rupaschomaker** [comment]
+1. I assume this is still a work in progress so I haven't asked about it
yet.

**Comment by evilhero** [comment]
Well the thing with the new pull method is that it actually knows the exact comicid of each series in the pull list. If you hover over the 'add series'  option it will display a msg of 'auto-add by ID is available'  or just a 'search for'  (or maybe nothing at all, I can't remember atm). 

I can add in a search option again but the results may be as mixed as before since it would just fall back to the original search option. 

I could also add a link to the series on CV, so that a user could actually click on the link to see what the series is. 

Not sure which one both of you are requesting (or both options),  so please fire me back a response and I can take it from there ;) 

It is a WIP, but it's more about matching proper titles and issues than anything else, as well as the timing of the updates - but there's always room for enhancements and such at this stage as well.

**Comment by thorinmesser** [comment]
Personally I love the auto-add by id. My personal preference would be if you could please add a link to the series on cv. And also because this can't be said enough and I didn't in my previous comment, Mylar is great and I am very happy for all the work you do on it.

**Comment by evilhero** [comment]
Thanks for the comps ;) 

I have the link option in my local build (the title of the series has always been clickable when the title exists in your watchlist, but now any series that Mylar knows the ComicID to but isn't on your watchlist will also be displayed as a clickable link - but it will open up the series on CV)

**Comment by thorinmesser** [comment]
That's fantastic, thank you so much! I will quote OP and say you are awesome as always.

**Comment by rupaschomaker** [comment]
When there is only 1 issue (so looking at new comics) there is no 'add
series'. Just skip, 'watch' and one off.  Clicking on issue name goes to
the home screen.

This is the workflow that I either don't understand or I figured was still
a wip.

**Comment by evilhero** [comment]
Usually with the first issues (ie. new series) there is no issue data on CV let alone series data usually until late Wed. 

The watch option will add the given series/issue to the auto-want list where it will check CV every few hrs to see if the series has data yet. Once it does it will auto add the series and mark the given issue as Wanted. With the alt_pull 2 method, it will (as in not atm, but soon) check the backend site for the given series data every hr or so, and then auto-add add it that way (and thus save on more api hits against CV). 

Those that have a #1 issue should also have a add series /search option, so I'll add that back in for the next development commit.
