### ISSUE TITLE
CV link for COMIC in weekly alt_pull 2

### ISSUE THREAD

**Issue by thingfromspace** [evilhero/mylar#1386]
It would be great to have the Comic/series field in the weekly pull list, using the alt_pull=2 method, link to the CV page. I like to discover and research new series through the weekly pull and being able to link directly to the CV page makes this easier.

**Comment by thingfromspace** [comment]
Sorry. I just noticed this happens already on some records (but not all).

**Comment by evilhero** [comment]
The reason why it's not all of the issues is because mylar doesn't know the id's yet. The new pull updates every hr on the backend, and as it learns new id's they get updated on the pullist. Then every 2 hrs (or on a recreate pullist) mylar will poll the new site for the info. So ideally by Wed you should have almost all of the id's present in your pullist and they'd be clickable to CV (Wed depends entirely on CV and their update schedule of course)
