### ISSUE TITLE
Mylar downloads, but will not move to destination anymore

### ISSUE THREAD

**Issue by Jakesparrow** [evilhero/mylar#1387]
I have about 15 different comics being monitored. In the past, I would periodically get new comics as they were released. Now I notice that the folder that Mylar downloads to is being filled with the releases, but it is not post processing.  They don't have any special characters in them, they are not all caps (I noticed people had problems like that in the past), so I am not sure. I am including the logs.

[mylar.txt](https://github.com/evilhero/mylar/files/470552/mylar.txt)

**Comment by evilhero** [comment]
Well based on that log, and that it's trying to process 1700+ files in the given directory - I'm going to just guess that it's not post-processing because it can't parse the filenames properly (namely the .pdf files). There probably should be an option to exclude pdf when post-processing since that file-type is enabled by default, but right now there isn't one.  

So what you can do in the meantime just to see if that indeed is the problem is either move the pdf files out of your processing directory and try again, or move the cbr/cbz files into anothet directory and point the folder monitor/manual post-processing to that folder path.

**Comment by Jakesparrow** [comment]
You are dead on. I moved the folder with comics to another subfolder, pointed mylar to it, and it cleaned house!
Thanks mate!
