### ISSUE TITLE
Request for a bulk refresh files and bulk refresh comics

### ISSUE THREAD

**Issue by F688** [evilhero/mylar#1400]
Large number of comics series are not showing/counting all issues in folder, going to each comic detail sheet to recheck files and refresh comics is time consuming. Request option to recheck/refresh multiple series or all series.

**Comment by evilhero** [comment]
This is already available in the Manage tab / Manage Comics option. Change the view to All and then select the series you want to refresh and then choose Refresh Series from the drop down. 

Refresh does a Recheck as the last step of a Refresh, so there wouldn't be a need to do individual checks if doing a Refresh anyways. 

I can add in an option for Recheck Files, but I have some other items more pressing atm to deal since it literally breaks mylar usage.

**Comment by F688** [comment]
Thanks for the quick response.

**Comment by F688** [comment]
Thanks your awesome
