### ISSUE TITLE
Annuals naming structure

### ISSUE THREAD

**Issue by dsawejka** [evilhero/mylar#1401]
I have Series Annual Integration checked but they wont show up in the comic listing.
What is the naming convention needed to work?

**Comment by evilhero** [comment]
If the annuals are listed for the particular series, then it should be able to scan in based on normal naming conventions (ie. SeriesName Annual 1 (2016).cbr). Keep in mind that if you have more than on volume to a given series, you need to distinguish which annual it belongs to in the naming convention (ie. SeriesName v2 Annual 1 (2016).cbr). Not doing this might cause Mylar to move the annual to the incorrect series since it can't determine which volume it belongs to (sometimes year isn't enough either if 1 series ended, and another began in the same year).

**Comment by dsawejka** [comment]
I have it set as SeriesName Annual (Year)
Nothing shows up.

**Comment by evilhero** [comment]
Ok, wait - what is it that's not showing up? 
Are the annuals not being listed within the series detail page as to what's available? 
Or the annuals not showing in a Downloaded status under the Annuals section of the series detail page ?

If it's the first, you need to refresh the series so that the annuals will get loaded now with the particular series (as prior to the annual-integration being enabled, polling annual information from CV was ignored for the given series).

If it's the 2nd (showing as Archived/Skipped instead of Downloaded), then I need to see the mylar debug logs showing a file check run so I can see what's happening under the hood.

**Comment by dsawejka** [comment]
Its the first. they are not showing up in the detail page.
I have refreshed the page multiple times.

**Comment by evilhero** [comment]
Then you probably need to do a Refresh Series (the button at the top of the series page), not refresh the actual page. Mylar needs to update the information against CV now that you want it to monitor Annuals for the given series...it doesn't know that until you do a Refresh Series.

If that doesn't work, try restarting Mylar in case there was some other error locking up a thread in the backend.
