### ISSUE TITLE
No 'Add Series' link for ANY titles

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1412]
Hi
I had an issue (1328) where there was no Add Series link for new titles.  I've noticed, recently, that there is now no Add Series link for ANY titles.
Did I miss something?
Thanks!

**Comment by evilhero** [comment]
It depends on your alt_pull method that you're using. If you have alt_pull set to 0, then the add series is actually just 'search' now, meaning that a search has to be done on CV to find a matching series. 
If you have alt_pull set to 2, then 'add series' is present when mylar knows the comicid which is part of the pullist itself, otherwise if the comicid is not known it's a 'search'  option.
