### ISSUE TITLE
Issues added from CV with StoreDate = '0000-00-00' must be manually changed from Skipped to Wanted

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1437]
I know that from other bugs  (#653), there are issues when CV does not have all metadata for an issue on New Comic Book Day Eve.

However, recently, I've noticed this behavior:
Timeline:
Daily(?) Active Series Runs:
```
2016-11-01 14:24:37	INFO	[45/288] Refreshing :Champions [94612]
2016-11-01 14:02:45	INFO	controlValue:{'COMIC': 'CHAMPIONS', 'ISSUE': '2', 'WEEKNUMBER': '44', 'YEAR': '2016'}
2016-11-01 14:02:45	INFO	Now adding/updating issues for Champions
2016-10-31 14:02:44	INFO	controlValue:{'COMIC': 'CHAMPIONS', 'ISSUE': '2', 'WEEKNUMBER': '44', 'YEAR': '2016'}
2016-10-31 14:02:44	INFO	Now adding/updating issues for Champions
2016-10-30 14:03:02	INFO	controlValue:{'COMIC': 'CHAMPIONS', 'ISSUE': '2', 'WEEKNUMBER': '44', 'YEAR': '2016'}
2016-10-30 14:03:02	INFO	Now adding/updating issues for Champions
```

Issue that is added now has StoreDate = '0000-00-00' and has status of Skipped.

Running a Refresh Comic manually updates the issue record
```
2016-11-01 19:32:54	INFO	Now adding/updating issues for Champions
2016-11-01 19:32:51	DEBUG	comicname:Champions
2016-11-01 19:32:51	INFO	Sucessfully retrieved issue details for Champions
2016-11-01 19:32:45	INFO	Directory (F:\Comics\Marvel\Champions (2016)) already exists! Continuing...
2016-11-01 19:32:45	INFO	Sucessfully retrieved details for Champions
2016-11-01 19:32:45	INFO	Now adding/updating: Champions
```

However, after the StoreDate is set to a valid DATE from the Refresh operation, the issue remains Status = Skipped.

I realize this is due to the CV database missing the values when the record is created locally. However, should behavior operate like one of these three?

1. Issue record is added with StoreDate = '0000-00-00' and Status = Wanted. Issue record is updated by later series refresh setting StoreDate to a valid value.
2. Issue record is added with StoreDate = '0000-00-00' and Status = Skipped. Issue record is update by later series refresh setting StoreDate to a valid value. Update also sets Status = Wanted.
3. Mylar ignores adding new issue records where StoreDate = '0000-00-00'. Later refresh sees issue record in CV has StoreDate <> '0000-00-00' / NOT NULL (I have no idea how CV db stores these values) and then inserts new issue record into local db with Status = Wanted.

I really appreciate all the work everyone has contributed to this project, I'm just wondering if there's a solution to having to manually go through and update each series individually each week.

**Comment by evilhero** [comment]
Yep it's a problem with the way that CV is now doing the updates for the new week pull. It seems as of late they've taken to updating the information really, really late. So when mylar does the initial compare there is no store date given on CV, but it knows it's a match so it marks it as Wanted on the weekly tab, and adds it onto the series detail page with either a '0000-00-00' date or the actual date of the pullist. It does not mark it as Wanted as in order to mark issues as Wanted on the series page it has to have an issueid and or valid date.
Mylar polls CV for new info for the pullist every 24 hrs, or on a restart (if it's been more than 5 hrs since the last poll/refresh). So in your case, at 14:03 there wasn't enough data on CV, but at 19:30 there was a d as such it updated and lined it all up properly at that point. If you had waited for the 24hr period to lapse, or restarted mylar (since it was >5hrs since the last poll), it would have populated it properly as well. 

Again, due to how CV does it now - before, issues were getting fully updated by early Tuesday at the latest, now I've seen issues not get fully updated until Thursday which causes problems due to the 24hr polling. 

There is a method which might work better for you that's been available for the past few months. The 'alt_pull = 2' method. In your config.ini there's an alt_pull variable. 0 is the default where it polls against CV every 24hrs and from a specific site containing pull list data that's kinda crappy. 2 is the new method which uses an intermediate site to poll against and contains all the updated CV information in regards to a given weeks pull. It's updated on the backend every hr, and mylar polls against this site every 2/4 hrs (I cant remember which atm). The benefit is that it's way more accurate in matching, it already knows the id's from CV as they get populated with relevant data, it's updated every few hrs for mylar and it follows CV naming convention (ie. no all  capitalization, no weird abbreviations that cause mylar not to match things up, etc). Oh also no CV hits are tied to your specific api due to it being the intermediary site, which is a big plus as well. 

There is still a glitch with the 0000-00-00 stuff to a degree, but because of the much lower polling it's not really a factor for most series. A simple recreate pullist from the weekly tab will poll the intermediary site immediately for any updated information and then have mylar react accordingly. 

From the intermediary :
```{"publisher":"Marvel Comics","series":"Champions","issue":"2","comicid":"94612","issueid":"556468","alias":null,"weeknumber":"44","year":"2016","shipdate":"2016-11-02","coverdate":"2017-01-31","type":null,"lastissue":"1"}```

**Comment by lodasi** [comment]
Thank you for the advice. I figured this had to be more of a CV issue, and I have also noticed issues with their DB being out of date. I will try the method you have described.
