### ISSUE TITLE
Error grabing issue form Story Arc 

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1450]
After clicking on the "Grab it" button of an issue on the Story Arc list, I've got this error on the log. Of course, issue is not downloaded. Can this be a side effect of my modification on #1441 ?

```
2016-11-08 17:09:47	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 1295, in queueissue
logger.fdebug('publisher: ' + Publisher)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2016-11-08 17:09:47	INFO	Marking Prowler #1 as wanted...
2016-11-08 17:09:47	INFO	IssueArcID : None
2016-11-08 17:09:47	INFO	Story Arc : The Clone Conspiracy queueing selected issue...
```

**Comment by evilhero** [comment]
That's one of those issues that doesn't have a publisher stated for it, so it's erroring out on that. I don't think it has anything to do with the issuearcid change you did in the PR, although I'm not 100% positive either since I cant recall if that issuearcid is supposed to be nil.

I'll have to do some testing - or you could even revert the change you did, start up mylar and refresh the arc and then try the grab to see if mylar is able to grab it. If it does, then the issuearcid has to be written to, maybe not as a control value though.

**Comment by WedgeSparda** [comment]
@evilhero Yeah, mi fix was the problem. I created a new PR (#1451) with a fix for my fix... that's sounds crazy.

The problem was that I wasn't  inserting the IssueArcID on the database with the `upsert` function. I seems that `upsert` inserts the values used on the control parameter even if they're not presente on the new values parameter. 

I tested and now the error disappeared from log and the issue is changed to wanted.
