### ISSUE TITLE
Post Processing Failure with files containing ".rar" in their name

### ISSUE THREAD

**Issue by GTSlayer** [evilhero/mylar#1462]
First off, running the latest Development branch on Ubuntu 16.04. Unrar is 5.30 beta 2, latest version as well. NZBGet is my downloader.

In the past week or so I've ran into an issue with ComicRN post processing. On occasion, mylar will grab a .nzb with ".rar" in the file name. An example is as follows:
> Deadpool.-.Too.Soon.Infinite.Comic.001.2016.digital.Son.of.Ultron-Empire.-.Nem.-.rar.nzb

These files will always fail to post process. In the NZBGet logs, it says it can't find the valid cbr/cbv file, like below: 

> info	Fri Nov 18 2016 10:58:18	Collection Deadpool.-.Too.Soon.Infinite.Comic.001.2016.digital.Son.of.Ultron-Empire.-.Nem.-.rar added to history
> error	Fri Nov 18 2016 10:58:18	Post-process-script ComicRN.py for Deadpool.-.Too.Soon.Infinite.Comic.001.2016.digital.Son.of.Ultron-Empire.-.Nem.-.rar failed
> info	Fri Nov 18 2016 10:58:18	ComicRN: Unable to locate a valid cbr/cbz file. Aborting post-processing for this filename.
> info	Fri Nov 18 2016 10:58:18	ComicRN: No version # found for series - tag will not be available for renaming.
> info	Fri Nov 18 2016 10:58:18	ComicRN: Comic Version: None
> info	Fri Nov 18 2016 10:58:18	ComicRN: Comic Location: /data/Comics/Deadpool Too Soon Infinite Comic (2016)
> info	Fri Nov 18 2016 10:58:18	ComicRN: Year: 2016
> info	Fri Nov 18 2016 10:58:18	ComicRN: Series: Deadpool: Too Soon? Infinite Comic
> info	Fri Nov 18 2016 10:58:18	ComicRN: Publisher: Marvel
> info	Fri Nov 18 2016 10:58:18	ComicRN: Issue Year: 2016
> info	Fri Nov 18 2016 10:58:18	ComicRN: nzbname: Deadpool.-.Too.Soon.Infinite.Comic.001.2016.digital.Son.of.Ultron-Empire.-.Nem.-.rar
> info	Fri Nov 18 2016 10:58:18	ComicRN: Loading config from /opt/nzbget/scripts/autoProcessComics.cfg
> info	Fri Nov 18 2016 10:58:18	Executing post-process-script ComicRN.py for Deadpool.-.Too.Soon.Infinite.Comic.001.2016.digital.Son.of.Ultron-Empire.-.Nem.-.rar
> 
If I manually download them without the ComicRN script, convert them to CBZ, then manually post process them with Mylar, it runs fine and gets placed into the right series folder.

**Comment by evilhero** [comment]
Yeah that was initially by design I think, due to users having downloading other things that were .rar files and they were getting post-processed incorrectly and well, wrong. 

Can I ask what the provider is that your pulling these types from? 

The fact that it's finding the nzb name reference within mylar is a good thing. I think I might be able to allow for these types to fly by (or at least just do an initial rename so things move forward like you're doing  manually now). 

I have a few other things that are kinda pressing me for time atm with mylar, but once I get those wormed out where I have some breathing room I should be able to get this going.

**Comment by GTSlayer** [comment]
Provider as in my usenet? or my indexer?

Supernews and News Farm. NZB Hydra with a plethora of various indexers setup. Althub and Lulunzb seem to be the better indexers for comics.

**Comment by GTSlayer** [comment]
Lulunzb seems to be the main culprit with .rars in the file name.

**Comment by evilhero** [comment]
Makes sense, they're running nzedb. I know from prior problems, that nzedb can do some stuff with cbr that it shouldn't do (rename to rar, read inside the cbr/rar and rename nzb to be filename + rar extension kinda stuff). 

I'll still see about adding this, but you might want to post an issue on their forums / support to see if they can clean up the names to indicate what they actually are instead of assuming all cbr = rar and cbz = zip.

**Comment by GTSlayer** [comment]
Alright. I'll do that. Thanks for the assist.

**Comment by GTSlayer** [comment]
In case anyone else has issues with this, while not a perfect solution, enabling a minimum file size above a couple MB (I used 5), seems to eliminate a lot of the issues. 

While after manually downloading the same files seem to be right, nzbhydra reports the files ending with ..rar.cbr files with file size in the KBs, not the 30-40MB range like most comics should be.

**Comment by evilhero** [comment]
I would set if for a min size of 10mb, as there are very, very few cbr's nowadays that are anywhere near that even. Still, gotta love the spam ;)
