### ISSUE TITLE
31 commits behind

### ISSUE THREAD

**Issue by miroresh** [evilhero/mylar#1469]
Hi,

I'm on version: ed263d8784cb14859def1fd8cca479708f496013 

I'm getting the following error: 
**A newer version is available. You're 31 commits behind. Update or Close**

Clicking on update restarts Mylar but does not update. 

I do see the following line in the logs, not sure how to fix. :( 
22-Nov-2016 09:49:09 - ERROR   :: MAIN : Invalid update data, update failed: ['evilhero-mylar-2b0b28b', 'evilhero-mylar-646309b', 'evilhero-mylar-d688440', 'evilhero-mylar-ed263d8']

```

22-Nov-2016 09:49:03 - INFO    :: MAIN : Mylar is updating...
22-Nov-2016 09:49:03 - INFO    :: MAIN : Downloading update from: https://github.com/evilhero/mylar/tarball/master
22-Nov-2016 09:49:07 - INFO    :: MAIN : Extracing fileC:\mylar-master\master-github
22-Nov-2016 09:49:09 - INFO    :: MAIN : Deleting fileC:\mylar-master\master-github
**22-Nov-2016 09:49:09 - ERROR   :: MAIN : Invalid update data, update failed: ['evilhero-mylar-2b0b28b', 'evilhero-mylar-646309b', 'evilhero-mylar-d688440', 'evilhero-mylar-ed263d8']**
22-Nov-2016 09:49:09 - INFO    :: MAIN : Mylar is restarting...
22-Nov-2016 09:49:09 - INFO    :: MAIN : Restarting Mylar with ['C:\\Python27\\python.exe', 'C:\\mylar-master\\Mylar.py', '--nolaunch']
22-Nov-2016 09:49:12 - INFO    :: MAIN : Successfully discovered local IP and locking it in as : 192.168.1.74
22-Nov-2016 09:49:12 - INFO    :: MAIN : Branch detected & set to : master
22-Nov-2016 09:49:12 - INFO    :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
22-Nov-2016 09:49:12 - INFO    :: MAIN : [Cache Check] Cache directory currently set to : C:\mylar-master\cache/
22-Nov-2016 09:49:12 - INFO    :: MAIN : Checking to see if the database has all tables....
22-Nov-2016 09:49:12 - INFO    :: MAIN : Populating Base Exception listings into Mylar....
22-Nov-2016 09:49:12 - INFO    :: MAIN : Populating Custom Exception listings into Mylar....
22-Nov-2016 09:49:12 - INFO    :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
22-Nov-2016 09:49:12 - INFO    :: MAIN : Correcting Null entries that make the main page break on startup.
22-Nov-2016 09:49:12 - INFO    :: MAIN : Retrieving latest version information from github
22-Nov-2016 09:49:14 - INFO    :: MAIN : New version is available. You are 31 commits behind
22-Nov-2016 09:49:14 - INFO    :: MAIN : Setting ComicTagger settings default path to : C:\mylar-master\lib\comictaggerlib\ct_settings
22-Nov-2016 09:49:14 - INFO    :: MAIN : ComicTagger settings location exists.
22-Nov-2016 09:49:14 - INFO    :: MAIN : Remapping the sorting to allow for new additions.
22-Nov-2016 09:49:14 - INFO    :: MAIN : Sucessfully ordered 131 series in your watchlist.
22-Nov-2016 09:49:14 - INFO    :: MAIN : Starting Mylar on http://0.0.0.0:8090/
22-Nov-2016 09:49:15 - INFO    :: MAIN : Initializing the DB Updater.
```

**Comment by evilhero** [comment]
Try starting mylar from just the command line and use the -v option (ie. python Mylar.py -v), and then try to  do the update and see what it does. It looks like it can't update things properly due to some sort of permissions but without seeing the logs I'm not 100% sure.

Either that, or try doing just a 'git pull' from the root of the mylar directory (in a command window), with Mylar not running and seeing what it does at that point (Mylar does a git pull when you issue the update command via the GUI)

**Comment by miroresh** [comment]
Ok, trying now.  I'll report back with findings.  Thanks!

**Comment by miroresh** [comment]
Just noticed this too but might be unrelated?

Warning (from warnings module):
  File "C:\mylar-master\lib\js2py\constructors\time_helpers.py", line 9
    warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)
Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time

**Comment by evilhero** [comment]
I don't think that would halt it, but it's definitely a warning for sure.

Yes, it's pretty simple just do a 'pip install tzlocal' from the command line in order to install it (it's a python module for determining local timezones). Once that's installed, you won't get that error message during the git update.

**Comment by miroresh** [comment]
Ok, my skills are failing me here (sorry).

When you say run from the command line, do you mean to run those commands from the windows cmd or from the python shell?

**Comment by evilhero** [comment]
You'd need to do the 'pip install tzlocal' and the 'git pull' from the windows cmd - they're not python scripts, although they're used by python. Pip install is the installer that is used to install modules into python for global usage.

**Comment by miroresh** [comment]
Dang, I'm feeling pretty bad here. I should be able to figure this out.  At least, I was able to update pip (so I'm doing something right :) )

`C:\Python27>python -m pip install -U pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |################################| 1.3MB 306kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Uninstalling pip-8.1.1:
      Successfully uninstalled pip-8.1.1
Successfully installed pip-9.0.1`

But I don't know where to run those other commands from, I'm in Windows.

`C:\Python27>git pull
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\mylar-master>git pull
'git' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by evilhero** [comment]
oh doh, you're not using git. Ok, that was my fault - I should have caught that previously.

So in your case you installed Mylar originally by downloading the source file (zip) - and it looks like it's failing to do the update because it can't move things (in one of those 4 commits it mentions, alot of stuff got moved into the lib directory which might be causing the issue).

The easiest thing for you at this point, is to go to the github page for mylar and grab a new source file for the latest commit. Then, backup you mylar.db, config.ini and substitutes.csv (if you have one) files as well as your entire mylar\cache directory (it holds all of the covers for your series). Then delete the directory and unzip the source file you downloaded into the location. Copy those files you backed up into the new location and then start it up and you should be ok.

If you're not adverse to using git, it might be worth your while to install git (there is a git for windows) - course then you'd have to reinstall again, but you could do it first and then not have to reinstall twice (you wouldn't need to do the steps above save for backing up).

**Comment by miroresh** [comment]
YES!  That worked!  Thank you!

If anyone is having this same issue, follow instructions below.

1. Rename mylar-master file to something like mylar-master-OLD
2. Download new package from github
3. Unzip, run mylar, update and then shutdown 
4. Copy and override mylar.db, config.ini, substitutes.csv (if you have one, i didn't) and mylar\cache folder.

`The easiest thing for you at this point, is to go to the github page for mylar and grab a new source file for the latest commit. Then, backup you mylar.db, config.ini and substitutes.csv (if you have one) files as well as your entire mylar\cache directory (it holds all of the covers for your series).`

This fixed my issue but as evil mentions above, it might be simpler to run git for windows.
