### ISSUE TITLE
Can't add annual issues to reading list

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1476]
Hi

On the issues list for one comic there is no option to add the annual issues to the reading list (no glasses icon). Is this the normal behaviour or is something missing?

**Comment by evilhero** [comment]
Him, it was there at one point, but I think the reworking of the annuals and the reading list awhile ago just left the option stranded so it was temporarily disabled. I think it had to do with the way annuals were tracked on the reading list, since they're in their own table if users have the annuals option enabled.

**Comment by WedgeSparda** [comment]
Annuals can't be added to the reading list like a normal issue?

**Comment by evilhero** [comment]
Well it can, just I wasn't sure if the code was still in place - and I just checked, it's all there so I fixed up the link and put it back. Will be in the next dev commit ;)

**Comment by WedgeSparda** [comment]
Great. Thanks.
