### ISSUE TITLE
Legacy search of 32p yields incorrect snatches

### ISSUE THREAD

**Issue by Arathen** [evilhero/mylar#1481]
Each week for a while now, ive had a problem where Mylar snatches a comic from 32p (using legacy mode), but then a completely different file gets sent to my client. Looking back, the first time it happened seems to be 21st September, and its happened 3 to 5 times each week since then.

Here the last 4 examples, showing what Mylar thought it was snatching versus what actually ended up in my DL client:

Snatched: All.Star.Batman.004.(2017).(Webrip).(The.Last.Kryptonian-DCP).cbr.(-.Nem.-)
Downloaded: <snip>?id=9714&torrentid=25979

Snatched: Wonder.Woman.010.(2017).(2.covers).(digital).(Minutemen-Thoth).cbz.(-.Nem.-)
Downloaded: <snip>?id=14407&torrentid=26005

Snatched: Batgirl.and.the.Birds.of.Prey.004.(2017).(2.covers).(digital).(Minutemen-Thoth).cbz.(-.Nem.-)
Downloaded: <snip>?id=2999&torrentid=26006

Snatched: Deathstroke.006.(2017).(2.covers).(Digital).(Zone-Empire).cbr
Downloaded: <snip>?id=5681&torrentid=26073

The logs dont give a lot of reasons, but here's the last example:

```
10-Nov-2016 01:43:53 - INFO :: RSSCHECK : Shhh be very quiet...I'm looking for Deathstroke issue: 6 (2017) using 32P [RSS]
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : 32P
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : rss:yes
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : allow_packs:False
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : Found Deathstroke (2017) issue: 6 using 32P [RSS]
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : prov : 32P [RSS][26073]
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : [FAILED_DOWNLOAD_CHECKER] Successfully marked this download as Good for downloadable content
10-Nov-2016 01:43:55 - INFO :: RSSCHECK : matched on Deathstroke
10-Nov-2016 01:43:57 - INFO :: RSSCHECK : setting the nzbid for this download grabbed by 32P in the nzblog to : 26073
10-Nov-2016 01:43:57 - INFO :: RSSCHECK : Sending Pushbullet notification
10-Nov-2016 01:43:59 - INFO :: RSSCHECK : [NOTIFIER] PushBullet notifications sent.
10-Nov-2016 01:43:59 - INFO :: RSSCHECK : [UPDATER] Updating status to snatched
10-Nov-2016 01:43:59 - INFO :: RSSCHECK : [UPDATER] Updated the status (Snatched) complete for Deathstroke Issue: 6
10-Nov-2016 01:43:59 - INFO :: RSSCHECK : Completed RSS Search scan
```
You can see that Mylar really thinks it found "Deathstroke" in torrentid #26073, but that torrentid on 32p doesnt contain a lot of Sladey goodness.

Currently running:

> Mylar Version: development
> -- git build e6a0f69767e78132b86b541f5c2b20ad58b28e8b.
> Python Version : 2.7.9

Thanks heaps.

**Comment by evilhero** [comment]
I've looked into this a bit more, and the more tests I run against it, it looks like it has something to do with the data within the rssdb (which is localized due to the providers). 

What I'm thinking is happening is this: you've had Mylar running in legacy mode probably for awhile ( greater than a year?) and in that time it's built up a nice cache of releases so that it can do backlog searches in the form of a "poor man's api". However, with 32P they tend to trump alot of single releases in favor of putting them into packs. 

So Mylar has recorded that '26073' is the single issue for Deathstroke #6 within the rssdb (not the correct volume, since when things get posted to the rss feed for 32p they are all vol.0 until they get checked so by default Mylar will assume it's v0 based on posting dates,etc). On 32P, they trumped the release into a pack, and the 26073 becomes invalid. At some point, they recycled that torrent id into something else - and well, yeah Mylar is still thinking that 26073 = Deathstroke, when instead it's 26073=Hoax Hunters.

The easy fix would be to clear the cache from the rss, but then you loose the entire cache you've built up. I'm going to see if I can figure out a way to fix this cleanly so it minimizes the amount of stuff that has to get removed/updated....stay tuned ;)

**Comment by Arathen** [comment]
Ok, you're gonna LOVE this one :)

Here's the output:
```
sqlite> select * from rssdb where link = "26073";
Title|Link|Pubdate|Site|Size
Deathstroke 006 (2017) (2 covers) (Digital) (Zone-Empire).cbr|26073|Wed, 09 Nov 2016 14:42:16 +0000|WWT|39898316
```

So that immediately poses the question - WWT? So I looked it up and sure enough... https://worldwidetorrents.eu/torrents-details.php?id=26073 is Deathstroke #6. Which means it looks like Mylar is finding that comic ID on WWT, but then actually doing the snatch from 32p for some reason. I do have Public Torrent Search turned on as well as 32p, so that appears to be relevant.

So the immediate workaround is probably to just turn off public torrents and use 32p exclusively, or vice versa?

I really didnt see that coming to be honest :)

**Comment by evilhero** [comment]
Oh hell. Fartmother. 

Yeah that's not good, at all and definitely not what I was thinking it could even be. 

But, on the plus side, thanks to that result I now know where to look and actually why it's doing it, so I should be able to fix things hopefully fairly quickly. 

The immediate workaround would be to turn off public torrents and just use 32p as you've guessed yourself ;) 

I'll try to get a fix out asap, which should be before the Wed flurry of new issues... 

Thanks again for the response and doing that little query - saved me hours of work just in that response alone!

**Comment by evilhero** [comment]
Should be good to go now - tested against your exact issue (26073), watched it snatch the incorrect torrent from 32p when it said it was referencing the incorrect id on WWT. Modified the code, ran it again and correct snatch from WWT - since there was no 26073 in your rssdb for 32P it didn't try snatching from there.

Thanks again for the helpful post, and patience - couldn't have done this as quickly without your assistance!

**Comment by Arathen** [comment]
Yep, it looks like this is fixed in the latest commit. In the latest round of issues I had 7 snatches from WWT and 8 snatches from 32p, all correct and no problems.

Thanks heaps Evilhero for the fix :) Theres no need to thank me either. Mylar has been automating my comics for years now, and im very grateful for it. Im just happy to be able to help you out in a small way in return :)
