### ISSUE TITLE
[Feature Request] Support for multiple comic storage folders

### ISSUE THREAD

**Issue by elmerfdz** [evilhero/mylar#1483]
At the min, my default comic storage folder on Mylar is e.g: x:\media\comics, I've got a separate folder for my mature themed comics that I do not want to include in my default comics folder.

So currently, I add the comics I want and manually edit the path to the 'mature theme' folder (x:\media\..\mature themes\, this becomes tedious after sometime, when you have to do it multiple times. Also, by the time it allows me to edit the folder path, it already creates a folder in my default comics folder.

My suggestion/request for this problem is to be able to set multiple storage folders and so on, or the ability to remember any folders used in the past on the edit comic page.

Mylar could ask where you want to store the comic when you click 'add this comic', if there are no additional folders set then no popup is displayed and Mylar downloads to the default folder like it does now.

The above would also be useful for the people that like to store their comics based on a publisher like x:\comics\marvel , x:\comics\dc etc.

I use Ubooquity as my comic streaming server and someone has created a great ComiXology theme, it starts to become quite useful when the comics are stored under their respective publisher folders.

Thanks

**Comment by evilhero** [comment]
Well currently, you can set the publisher in the format field for your series (for new ones at least, for existing series it would take more work but it sounds like you already have them in the publisher format) - just set your Folder Format in the configuration GUI to start with '$Publisher\', the \ being important as Mylar will interpret that as a directory level and create according to that ( ie. $Publisher\$Series ($Year) )

The idea behind the automation of the folder naming was to take a hands-off approach once all the settings were configured, since in most cases users aren't manually editing the series folder locations outside of the default settings. But obviously hand-balming the directory locations isn't the ideal situation to be in either. The problem being due to the way Mylar uses the directory automation currently, it has to be recoded so as to not automate things, and then allow for breaking out to do a popup sequence (or something simliar)

This has been brought up before to some extent (not having Mylar create series folders on adding), so I should be able to look into this - there's currently one thing on my plate that I need to address before working on anything else, so once I have that done I can look into this abit more and see what I can come up with.
