### ISSUE TITLE
[Story Arc] Issue location not added to story arc entry if issue has been previously downloaded

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1492]

**Comment by WedgeSparda** [comment]
I just noticed, due to my previous commit to add download links on story arc issues list, that if issue has been previously downloaded because is part of a following comic, the location of this issue is not inserted on the DB story arc record of that same issue.

**Comment by evilhero** [comment]
The download option doesn't write anything to the dB, it just loads up the location for the downloader to grab from. Maybe it's just the early am with no Java yet, but I'm having problems following what the error is -  do you have any logs so I can follow along that way?

**Comment by WedgeSparda** [comment]
Check this screenshot. Captain America and All-New Avengers are issues I previously downloaded because they're part of two comics I'm following. But the other two are comics I grabbed with the story arc.

<img width="913" alt="shot" src="https://cloud.githubusercontent.com/assets/48375/21297254/a0b69372-c57c-11e6-9409-15bbcbc14251.png">

Now, this is the code showing the download link on the story arc list

```
%elif item['Status'] == 'Downloaded' and item['Location'] is not None:
     <a href="downloadthis?pathfile=${item['Location'] |u}"><img src="interfaces/default/images/download_icon.png" height="25" width="25" title="Download the Issue" class="highqual" /></a>
%endif
```

So, the item['Location'] on the database is empty for the previously downloaded issues.

**Comment by evilhero** [comment]
Ohh maybe cause the item['Location'] only references the readlist table and not the issues table - do those 2 issues that aren't showing up have files present in the arc directory?

**Comment by WedgeSparda** [comment]
No. Only issues grabbed from the story arc are present in the arc directory.

**Comment by WedgeSparda** [comment]
I think that one possible solution would be linking to the issue file inside the comic folder, but, in that case, if "Append Reading# to filename" is enabled we'll miss the reading number on those issues, right?

**Comment by evilhero** [comment]
I actually recoded it to do it on the fly now dependent on the arc itself. So prior to displaying the arc details page, it will look at each issue therein to see if the item location is empty but the status is set to Downloaded. If it's true, then it will do a reverse lookup on the issueid against the issues table and retrieve the actual filename/location, and then subsequently update the readinglist table to point to the new location oustide of the arc directory.
I tested it on 4/5 arcs and it found the incorrect Downloaded issues (where there was no location set, but it was Downloaded), and recorrected them so that the location became populated on the readlist and thereby the download icon was available on viewing the arc page.

**Comment by WedgeSparda** [comment]
Fantastic. And do you append the reading order to those issues too?

**Comment by evilhero** [comment]
No, the reading order can't get appended unless the story arc directory option is enabled as otherwise the series directory holding the given issues will have numerics in the issues, which wouldn't normally cause problems for the file checker, but trying to rejig things to accomodate the reading order changes (which can happen), as well as tracking multiple arcs that might have the same issue would be problematic.

The append reading order option should be dependent on if the arc directory option is enabled or not actually the more I think about this. The copy/move option while says 'arc directory' will default to the grab_bag directory location so that's not dependent on the arc directory option.

**Comment by WedgeSparda** [comment]
Of course, I was talking about appending the reading order only if the option is enabled.

**Comment by evilhero** [comment]
I can add that in before I push this out, sure...let's see what I can do while I wait for some java ;)
