### ISSUE TITLE
[Question] Option to delete issues files (cbr, cbz...)

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#1496]
Hi. This is more a question than an problem. I'm trying to find a way to clean my read issues files automatically but don't know how to so it (if there is an option). If one issue is marked as read (I see this option is only present on read list), will it be deleted on a background process? There is an option like this at all?

Thanks

**Comment by evilhero** [comment]
No, there isn't an option to delete a given issue from within Mylar. Marking an issue as Read from the ReadList will just remove it from the readlist, but it won't physically delete the file. I'd be a little hesitant to have an option to delete issues just because it can open up a Pandora's box kind of thing in regards to problems, but at the same point - Mylar has evolved into something much, much larger than I ever would have thought (it was initally just a pull-list notification system). So file management has been included in various other aspects, it might be something to consider adding as an option...
