### ISSUE TITLE
Story Arc and Series Conflict

### ISSUE THREAD

**Issue by s-cotton** [evilhero/mylar#1500]
I have the "Guardians of the Galaxy: Tomorrow's Avengers (2013)" series loaded into Mylar, and am trying to load the "Utopia" Story Arc, here are the two URLs on CV:

Series: http://comicvine.gamespot.com/guardians-of-the-galaxy-tomorrows-avengers/4050-55905/
Story Arc: http://comicvine.gamespot.com/storyarc/4045-55905/

It appears that the matching (well, mostly matching) IDs is causing a conflict, as a story arc search for Utopia shows it already in the library, with the link going to the Series and providing no way to add the Story Arc:

http://your.mylar.tld/searchit?type=story_arc&name=Utopia

Looks like the columns for Comic Name, Publisher, and Issues is populating correctly, but the row is yellow and instead of the "Add this Story Arc" link you get the "Already in Library" link that goes to the series.

**Comment by s-cotton** [comment]
No, that was a search from the Story Arc Management screen, thats how the type=story_arc got into the URL.

**Comment by s-cotton** [comment]
Further, the ComicName column value does link to the proper Story Arc page on CV

**Comment by s-cotton** [comment]
the haveit variable set on line 480 of mb.py relies on the function listLibrary() defined on line 1716 of helpers.py.  That function doesnt seem to fetch story arc ids, only issues and annuals.  The matching ID of the Series would be found in that list, triggering all of the template logic that relies on the haveit variable.

Hoping to be contributing soon, but only about a quarter of the way through the code base and still brushing up on my 5 year hiatus with python.  I am not entirely sure how you are storing story arcs yet or I would try to assist with an updated helper function.

Thanks for all of your hard work!

**Comment by s-cotton** [comment]
Took a crack at it, basic testing on a fresh installation with CV API and Base Directory configured utilizing the specific case reported originally shows the desired result of having the record behave as a new record, not an existing record. #1501

**Comment by evilhero** [comment]
Sorry, Christmas holidays are playing havoc with any free time atm - everything looks good from a visual standpoint but I haven't merged it into my local repo for testing (not expecting any problems, but just saying).

I appreciate the PR (and the subsequent ones too) ! Once I can get some free time to do testing I can merge them up - I do have a few things that affect story arc's that are going up (or are coded for, but haven't been commited yet), that deal with the location of the file within a given arc. Instead of just storing the filename, it will store the entire path - so that if the storyarc option isn't enabled (and the subsequent copy/move to arc folder), then it will retain the original location in either the series folder if it exists or the grab-bag directory. If it is enabled, then it will point to the arc directory + file (and if it's got the appended reading order # as well)...

Was hoping to get this all out before Christmas, but we'll see ;)

**Comment by s-cotton** [comment]
Sounds good.  I gotta figure out Git a bit better so I can separate out those additional requests and a couple more I want to do.  Any pointers?  Any other guidelines I can follow to make it easier on you?

**Comment by evilhero** [comment]
No, the way you're doing it is great - as long as you're pulling it against the latest dev branch there aren't usually any problems when I go to merge things together. You can't really not put all the files required in the PR, so breaking it up isn't a logical step in the equation - so if there's problems merging (usually due to code base changes when I merge the PR onto my local build), I'll usually just fix those as long as it's not going to be the entire PR ;)

**Comment by s-cotton** [comment]
I'm doing things in separate branches on my fork now, hopefully that makes things easier on my end to keep updates/initiatives separate.  Working on an option to allow the sync to tablet with separate folders to match the main comic locations instead of dumping them all into the root of the SFTP.  Thanks!
