### ISSUE TITLE
Issues are searched by two digits, but only found by three digits

### ISSUE THREAD

**Issue by amalafrozalam** [evilhero/mylar#1506]
Mylar searches for issues like this: Issue XX

However, many times issues are found like this: Issue XXX.

At that point, Mylar reports that issue is not found. Not sure if this is already fixed, and just don't know the setting.

**Comment by evilhero** [comment]
Mylar will search for all occurances up to  3 digits (ie. 5.05.005) due to how nzb search providers utilize their search api. 32p only searches for the numeric once as the value is stored on 32p as an integer. 

If mylar cant find a given issue then it's usually due to naming mismatches /inconsistencies.

**Comment by amalafrozalam** [comment]
I'll mark it closed for now. The issue is kind of hit or miss. It was happening quite often earlier, did a restart of mylar (the computer it was on really), and the issue has disappeared for the most part now.
