### ISSUE TITLE
Cloudflare Protection for 32P

### ISSUE THREAD

**Issue by Undeadhunter** [evilhero/mylar#1508]
Seems like Mylar hits the CF 32P protection.

Might need to add the cfscraper to the 32P login process? 

Let me know if I should look into this myself @evilhero I'll see if I can whip something up

**Comment by evilhero** [comment]
Ah damn, yeah I noticed that yesterday but the holidays are totally killing any free time I have in front of the machine.

If you have the time and the inkling/knowledge to do it, I'd gladly take the help in getting this out since it will affect everyone using 32p (especially because of tomorrow). I won't be able to get to a machine to even try doing stuff until later tonight to try and figure things out, but can do a PR from my phone (I think, I have in the past for critical things)

**Comment by Undeadhunter** [comment]
Won't have time today to do it either. Checked with the staff, they've put
32p into 'under attack mode' this will cause issues with most applications.

I'll try to implement cfscrape anyway.

**Comment by Undeadhunter** [comment]
I ran into a dead end, and not sure if you'd agree with the alternative. 

When you send a POST request to a page that does a 302 forward (like CF) it seems like the POST requests is lost in the mean time... 
Not sure how to best solve this issue besides doing something strange like: https://stackoverflow.com/questions/38034984/python-requests-post-doing-nothing

My python knowledge is not advanced enough, could be something lacking in cfscrape or I could be missing something. 

In any case PR #1510  with basic replacement of the requests is there, might be easier to work from there. Issue seems to be in the `valid_login_attempt` part. And without that nothing seems to work, so can't check all the other functionalities yet ... 

Alternatively we just wait for the end of the year to be over, since it seems like they'll be back to normal after new year.

**Comment by Undeadhunter** [comment]
Ok, PR #1510 should do the trick

**Comment by evilhero** [comment]
Sweet thanks for doing the PR! I should be able to push it out in a few hrs - sick kids aren't helping atm. 

I was gonna say that cfscrape needs to do a get before the post, so that the cookies can be grabbed and then sent in the post request, but it looks like you've figured that out anyways ;)

**Comment by evilhero** [comment]
I just tried the PR and it's not getting past the cloudflare.. So I'm not sure if the cookies/user agent have to be first retrieved from cloudflare before going onto the login post.

**Comment by Undeadhunter** [comment]
Hmmm, strange, I'll try it on another system (what OS are you running your tests on?), I deleted the cookies multiple times to make sure it ran. 
I'll check on another system. 
Can you send me a debug log ? I added a bunch of debug loggers, might give me some more info of where to look further

In any case I noticed master branch works ... sometimes, doesn't seem like cloudflare gets hit 100% of the time, but would be great to get it to work even when they disable it.

**Comment by evilhero** [comment]
I tested it against my main repo which is on Ubuntu. It look like the cloudflare has gone away for the moment so testing it out will be kind of hard - plus logs rolled over on me due to the PR's I pushed out last night. 

All I remember is that it said that it was missing an option and it was being rejected due to the missing parameter...i couldn't see what parameter was missing tho, but then the cf kicked off and it went away.
