### ISSUE TITLE
Bootstrap Interface

### ISSUE THREAD

**Issue by s-cotton** [evilhero/mylar#1530]
Ive started building a new interface for mylar, essentially copying the default and rebuilding as a bootstrap compatible interface.  Ive got the basics in place for the different required libraries, and Ive started rebuilding a few screens.   I have attached them below.  I am just using a bootswatch theme, so some colors are a bit, well, loud.

In doing this work, I am also extracting and reworking the javascript and AJAX request logic, so hopefully the frontend can be a bit more organized.  You can find my work under the 'bootstrap' branch in my fork.  The main changes are some javascript objects to help manage the ajax, notifications, logging, and initialization of screen logic.  I have also loaded in the venerable plugin to handle the table paging and filtering actions, so as of now, that is a WIP and ajax actions are not doing the $.load logic to update the table contents.  I am also working on a clone of the api class to use for these ajax calls, allowing for more data to be passed back to the frontend application as json.  This may eliminate the need for updating the entire table as I could just target the affected issues for updates in-place.  This may not pan out as there are currently action links that are not loaded at all in the initial page load that you may need on individual issues after a status change; I will just have to see if there is a way for me to load all actions and then hide based on status.

@evilhero I am hoping you can let me know how you would like me to proceed to ease the merge process down the road.  I hope to do most of the python logic within the new ajax class so as to not interfere with the already working default interface, calling existing threaded functionality where possible, and recreating some of the other logic from the existing webserve exposed functions.  Otherwise all other files should be contained within the new interface folder.

![bootstrap work comic details 2](https://cloud.githubusercontent.com/assets/561773/21700029/4d878c3a-d36c-11e6-9166-9f940700f1b9.png)
![bootstrap work comic details](https://cloud.githubusercontent.com/assets/561773/21700032/4d8efb64-d36c-11e6-9d10-c61f432facc6.png)
![bootstrap work manage advanced](https://cloud.githubusercontent.com/assets/561773/21700030/4d8b3fb0-d36c-11e6-8fdd-cb3249f86b2f.png)
![bootstrap work manage scan](https://cloud.githubusercontent.com/assets/561773/21700034/4da64454-d36c-11e6-81d3-0ae76d74db4f.png)
![bootstrap work manage scan postprocess](https://cloud.githubusercontent.com/assets/561773/21700031/4d8c832a-d36c-11e6-84c6-84645b603dc3.png)
![bootstrap work](https://cloud.githubusercontent.com/assets/561773/21700033/4d9204c6-d36c-11e6-9fa5-b6605a818de9.png)

**Comment by s-cotton** [comment]
I think for now, the biggest issues I am running into are in regards to some additional data/images I would like to use.  

In doing this rework of the frontend, and looking over the comicvine API, I am noticing that as I make this responsive, the biggest challenge is the issue table, but there is an easy (i hope) solution.  There is just no good way to make the table responsive without requiring a lot of horizontal scrolling, so I would like to pursue a dual display of the issues.  First would be the new table sorter that you see in my branch currently.  The second would be a grid approach with the covers of the issues shown instead.  This would make it a lot easier to adapt to the smaller screen sizes.  It could also be adapted to the main home listing (as we have those covers cached) while the search listings could be easily condensed (not many columns to handle).  Maybe these can be cached in the same way as the overall series image is cached?  Or maybe it would be stored inline with the actual CBR/Z files?

Additionally, and certainly lower priority, can we fetch/cache the "Character", "Object" and "Location" data associated with each series and issue?  Spinning up a new set of pages for these shouldn't be too hard, and it would allow us to do deep linking from the single comic series screen.  "Hey, that's a neato fandangled-doo-dad they used in that issue, I wonder if it shows up in any other series?" or "That guest character was AWESOME, I wonder if I have any other issues or series with them in it?"  Do you think this is something that can be done?  Would it run afoul of the CV API Terms?

**Comment by s-cotton** [comment]
Or maybe, for the issue covers, we just put a covers.jpg next to the cover.jpg in each series folder.  That file could be a compiled grid of all of the issue covers, following a simple placement algorithm based on issue number (20 issues per row, expected width/height allows us to determine where to find the appropriate image for the frontend to use as a CSS background with background position).  This would allow for only a single additional resource request to the server, and it wouldnt cloud up the main series folder.  I know how to do something like this in PHP using the GD functions, but I am at a loss for how to help out with that in python.  Processing times and resources may not allow for this either.  I know I'm about to move my install to an RPi3, so maybe that needs to be considered too

**Comment by s-cotton** [comment]
Sorry, still getting used to the structure of the project and the available Python modules/functions, so finding answers to my questions and then leading myself into further questions.  I now see the image url columns in the issues table, but then thought about the bandwidth that would be required to pull all that down from CV.  Instead, we already have that information available for downloaded issues.

https://pypi.python.org/pypi/rarfile/
I stumbled onto the IssueInfo helper function when I was working down the single comic page to convert ajax functions.  Looks like only zip files are extracted, but in there you do already have cover image extraction.  The library linked above provides the same for rar files.  Maybe this can be part of the post-process, maybe another action on the comic screen to extract all issue covers.  Let me know what you think would be best.

I also found pillow, http://python-pillow.org/ which looks a lot like what im used to using in PHP GD, so maybe the combined/merged grid approach is valid.  This would certainly work better for storage, as a covers.jpg next to the issues would then be in a storage location where space is (assumed to be) not as limited.  I can only imagine some larger libraries not being so thrilled at having these cached images alongside their mylar installation in a potentially space limited location.

**Comment by s-cotton** [comment]
Start of RAR and Cover Extraction: https://github.com/s-cotton/mylar/commit/7e677ffe6a993040e6fcb62c885628d88f8203b2

Let me know if you foresee any issues I am not seeing to go forward with this composite image approach.
Let me know as well if you have any preferences on approach for installation of dependent libraries, such as the rar library I am promoting here.

Thanks!

**Comment by evilhero** [comment]
I have to first apologize for my lack of input thus far. I've been reading the comments, but haven't been able to respond until now (being on a phone and doing long responses really doesn't work well + family life doesn't make things easier). I'll try to answer your questions as best I can (and if I miss some, or don't go into enough detail just ask - there's alot of points)

> There is just no good way to make the table responsive without requiring a lot of horizontal scrolling, so I would like to pursue a dual display of the issues. First would be the new table sorter that you see in my branch currently. The second would be a grid approach with the covers of the issues shown instead. This would make it a lot easier to adapt to the smaller screen sizes. It could also be adapted to the main home listing (as we have those covers cached) while the search listings could be easily condensed (not many columns to handle). Maybe these can be cached in the same way as the overall series image is cached? Or maybe it would be stored inline with the actual CBR/Z files?

I love this idea. It's something I've been wanting to do since I started Mylar, but my knowledge depth of trying to accomplish it was less than pleasant. I don't see anything wrong with the dual-display option at all, either on the issues page, the main page or even the search results. Options are a good thing, and having a visual identifier for what is what would make for a more pleasant viewing experience for everyone I'd imagine.  The only problem, as you've eluded to already is the storage of the covers, aside from the series covers themselves since they're already stored in the cache. Caching the issues independently from CV would require abit of timing (so as to not run afoul of their TOS), but it also doesn't require the usage of an api - since it's a direct link to the image itself. Obviously downloading issues dynamically wouldn't do well for speed wise on very large series (thinking 2000AD as an example cause that one always causes some kind of speed problems just as text alone). Extracting from the issues if they're in a Downloaded status could alleviate some of the 'downloading' - something to think about for sure as to what would be more appropriate and to have a good balance.

> Or maybe, for the issue covers, we just put a covers.jpg next to the cover.jpg in each series folder. That file could be a compiled grid of all of the issue covers, following a simple placement algorithm based on issue number (20 issues per row, expected width/height allows us to determine where to find the appropriate image for the frontend to use as a CSS background with background position). This would allow for only a single additional resource request to the server, and it wouldnt cloud up the main series folder. I know how to do something like this in PHP using the GD functions, but I am at a loss for how to help out with that in python. 

This sounds really neat - I've never even heard of something like this being done before, so to even think it's a possibility draws my interest. It would definitely get away from the storage issue location on a local level, and loading it dynamically would be much faster than individually I would also imagine. If this is something that's possible, I believe it would be probably the best way to travel down this road - I can do the python stuff as required, my PHP is decent but not great, so unfortunately that part would rest on your shoulders.

**Comment by evilhero** [comment]
> https://pypi.python.org/pypi/rarfile/
I stumbled onto the IssueInfo helper function when I was working down the single comic page to convert ajax functions. Looks like only zip files are extracted, but in there you do already have cover image extraction. The library linked above provides the same for rar files. Maybe this can be part of the post-process, maybe another action on the comic screen to extract all issue covers. Let me know what you think would be best.

The only reason why zip files were extracted and not cbr was due to how the metadata is currently stored - the typical user has almost everything metadata-related stored within the cbz file (either in the zip comment field, or as an xml file within the archive itself), with a few users deciding that they'd like to have a cbr file hold the metadata. I didn't write in the code to support the cbr+metadata, as it seemed it was a fringe-use type of case, and it created some additional issues at the time that I couldn't get around (which may have been resolved since then).

>I also found pillow, http://python-pillow.org/ which looks a lot like what im used to using in PHP GD, so maybe the combined/merged grid approach is valid. This would certainly work better for storage, as a covers.jpg next to the issues would then be in a storage location where space is (assumed to be) not as limited. I can only imagine some larger libraries not being so thrilled at having these cached images alongside their mylar installation in a potentially space limited location.

This seems like a viable option to consider as well. I can't really imagine loading up 1000+ issue covers for some series in an attempt to load the screen to display - let alone the storage space it would consume for some individuals.

>Start of RAR and Cover Extraction: s-cotton@7e677ff
Let me know if you foresee any issues I am not seeing to go forward with this composite image approach.
Let me know as well if you have any preferences on approach for installation of dependent libraries, such as the rar library I am promoting here.

I don't see any issues going forward, so long as the required libraries are available for most distributions if they're to be installed at the OS level. If they're to be packaged within Mylar, as long as they're located in the /lib folder within Mylar and imported accordingly (Mylar will first try to import modules from the lib library before trying at the OS level for installed modules, so doing an 'import pillow' would be enough instead of 'import lib.pillow')

I have your branch cloned on my local repo, so as you push out items I'll merge them into mine to see how things work from an outside perspective, or if there's anything you need help with as far as the python code (because unfortunately I can't really help much with the PHP stuff) just holler.

**Comment by evilhero** [comment]
> Additionally, and certainly lower priority, can we fetch/cache the "Character", "Object" and "Location" data associated with each series and issue? Spinning up a new set of pages for these shouldn't be too hard, and it would allow us to do deep linking from the single comic series screen. "Hey, that's a neato fandangled-doo-dad they used in that issue, I wonder if it shows up in any other series?" or "That guest character was AWESOME, I wonder if I have any other issues or series with them in it?" Do you think this is something that can be done? Would it run afoul of the CV API Terms?
Yep, it can be done - it's just a matter of adding a field to the field_list when mylar queries against CV for anything. It wouldn't needed to be done for say searches, but for adding a series it would be easy enough to add in those 3 fields (I think it's just 3, I'd have to check the CV API in order to determine it exactly). Aside from some probably formatting / unicode concerns with these, it should be relatively simple to add it to the query and then include it in the response so that it can get written to the comics table ;)

**Comment by s-cotton** [comment]
Family always comes first! I appreciate the feedback whenever it comes!

I am just going to lock all this functionality (rar, img composition) behind config options for now, so users with limited space can be spared.

I only mentioned the PHP GD because that is what I have experience in as a Full Stack LAMP guy by day.  Ive read up on the pillow documentation and it has everything I need, so I am going to pursue that route.  Probably will split it up to 20 issues per composite image, keyed off that INT_ISSUENUMBER field so I have a known offset for each issue.  I'd like to store these alongside the issues as that seems the best route for storage space.  Maybe in a subfolder for each series?  Thinking of 2000AD as a worst case scenario, that's 100+ composite covers images, so to keep it clean the subfolder route might make the most sense.  Actual storage space used is something im interested in seeing, but if it gets crazy, i can try to add in some image optimization libraries and shrink the sizes as much as possible.

It looks like you can get the IDs of the objects/characters/locations in the series and issue queries, but there would be additional calls for the individual items at their own endpoints.  I havent played yet with queries to the CV API, but most APIs have a way to do a single call for multiple IDs, so hopefully it shouldnt hurt the timing/rate-limiting too much.

**Comment by s-cotton** [comment]
I think it would also be a two-way approach.  If we have the issue, mylar can grab the covers from the file.  If its an upcoming issue or one we don't have, we can reach out to CV to compensate.  Should give us complete coverage while limiting the amount of bandwidth we need to hit CV with

**Comment by HypKin** [comment]
is there a way to test this as a user?

**Comment by evilhero** [comment]
The easiest way is to do a separate git clone of his repo and then checkout the bootstrap branch(git checkout bootstrap). You can then copy over your mylar.db and config.ini files (and your cache folder with your jpgs inside) and start it up and it will load up. 

I'll eventually add it as a separate branch within mylar, but I'm just waiting to hear if it's completed enough to add.

**Comment by s-cotton** [comment]
Made good progress on the config screen tonight.  Only have the advanced tab left to do.  Also added in a responsive tabs plugin to shift from tabs to an accordion approach on screens <768px

**Comment by s-cotton** [comment]
![coverflow](https://cloud.githubusercontent.com/assets/561773/22614138/a0b38e9e-ea4c-11e6-9625-d917dbf2fbb3.png)

**Comment by MadDucks** [comment]
Looks very good

**Comment by s-cotton** [comment]
Bootswatch CDN capabilities:

![bootstrap work bootswatch](https://cloud.githubusercontent.com/assets/561773/22716439/0df74828-ed64-11e6-9741-16a0182c9842.jpg)

**Comment by Synopis** [comment]
I really love that.

**Comment by s-cotton** [comment]
I'm just gonna go ahead and get ahead of the inevitable request for a Cover Flow view.
![cover flow](https://cloud.githubusercontent.com/assets/561773/22760016/b29e3ce2-ee22-11e6-935d-5b961dee6ba8.jpg)

**Comment by Synopis** [comment]
If you don't mind me asking.. exactly how are you getting the covers?

**Comment by BRTPOB** [comment]
Magic.

**Comment by s-cotton** [comment]
Evilhero has been caching them since before I got involved. Issue covers are another story, but there's another issue I put in with some ideas on how to snatch those. If you feel like playing with some python.... [nudge] [nudge]

**Comment by s-cotton** [comment]
Working on the cover layout, added in the Latest Issue, an Icon to indicate status, have vs total to the top, and moved the title into the panel body so I have a bit more control over width as the cover flow was not liking the excessively long titles.
![bootstrap work cover panel layout](https://cloud.githubusercontent.com/assets/561773/22768621/4fdea518-ee51-11e6-90cd-2a5b87c8541b.png)

**Comment by s-cotton** [comment]
And the updated cover showing the action buttons and the action buttons and overlay for additional metadata:
![bootstrap work cover panel overlay](https://cloud.githubusercontent.com/assets/561773/22787993/35754cd0-eeac-11e6-8bb4-f087c0967d15.png)

**Comment by kingfenix** [comment]
so exactly when and how can the rest of us use this interface?

**Comment by evilhero** [comment]
You'll know when it's mentioned in here that it's available. ATM it's still being worked on and isn't ready yet (@s-cotton ca  confirm this), as only one page is being done.

**Comment by s-cotton** [comment]
There wont be an "exactly" for quite some time.  This is an almost complete rebuild of the frontend, so right now I am just at the point of getting together the smaller components that will make up the whole.  Hoping to work out the issue cover generation today, which will remove a big hurdle towards extending these views I have built to issues and not just series.  Feel free to clone out my branch and poke around the manage comics screen if you want to see the difference in speed and responsiveness, but I dont expect to be done this project anytime soon

**Comment by m00n22** [comment]
I know it's been a while. But any more info/progress about this?

**Comment by sukhysall** [comment]
Hi, have you managed to progress any further with this?

Also, is there any kind of guide you could recommend for a noob who would like to try his hand at creating his own theme?

Thanks

**Comment by BRTPOB** [comment]
Unfortunately this has sort of died off.

**Comment by sukhysall** [comment]
Lol. indeed. I guess I was hoping maybe it might kick off again.

So far I've just a copy of the default interface folder and renamed it  to test. I could then see that in Mylar in the dropdown option.

Now I just need to figure out how to change the colours. My primary issue, which stems from working from home during thie pandemic is that I'm stuck in front of a Laptop screen with applications which predeominently have a white background and of course like with Mylar, there's no theme support so I can't change to a dark theme.

It really does a number on my old eyes. 

My first step for playing with a new interface for Mylar is simply change the background colour. I don't care about anything else right now. I just wanted to figure out the file where the colour for the background is coded so i can try switching it to black.

Fun and games.......

**Comment by DarkSir23** [comment]
I actually do have a partially finished Bootstrap 4 interface for mylar in the works.  I'd lost the thread on it, but I'll try to get back to working on it.

**Comment by sukhysall** [comment]
@DarkSir23 you are a star sir. I look forward to seeing as an option. 

In the meantime, I think I figured out how to do some basic changes with my existing Mylar setup. Thankfully I haven't touched my current Mylar instance but I'm tweaking the Mylar instance I have setup on my Raspberry Pi 4. 

Thankfully I have my LazyLibrarian using a good dark theme that I want to mirror so been using the Firefox F12 Developer Option to get the correct colours and just generally learning how to change things.

Still a work in progress but have a look

![image](https://user-images.githubusercontent.com/5501195/81485550-afea7b80-9245-11ea-8aa7-b6fec3d78c08.png)

**Comment by barbequesauce** [comment]
Nice stuff.... I'd recommend you try to apply these changes in the [mylar3 repo](https://github.com/mylar3/mylar3)  - this repo has been effectively end-of-life'd given Python2 EOL...

**Comment by sukhysall** [comment]
Closing this issue as python2 version is end of life.
