### ISSUE TITLE
Reasonable File Image Extensions and Max Covers

### ISSUE THREAD

**Issue by s-cotton** [evilhero/mylar#1532]
Is it possible to settle on a reasonable number of possible covers?  10, 20, 26?  I see accommodations for 5 alt covers in the issue detail function (000a-000e), but should this be variable from 000a to 000z, just in case?

How common are webp files in issue archives?

**Comment by evilhero** [comment]
Well usually with alternate covers they hold the first few letters of the alphabet - I haven't seen many releases that more than 5 covers included (which is what I based that portion of code off of). I think going to the full z might be too extreme, but maybe going to 10 might be enough. If you're just making sure that you get a cover of some kind to display, going past 10 would be overkill - and then it'd have to be decided which of the alternate 10 covers (in addition to the main cover if it's present) to use and display.

Webp files are common amongst some individuals, but I don't see it taking over the mainstream of cbr/cbz anytime soon just due to how the comic readers and such mainly support the main 2 formats. I added it in as an option to allow for the retrieval of the cover if it was a webp image - I honestly haven't a clue if it works or not since I don't have any webp images to test it against ;)

**Comment by s-cotton** [comment]
yeah, i havent run across any webp either, but it doesnt hurt to keep it in the regex.  I was thinking for my composite image that I could stack the alt covers below the main cover, and in the frontend I can have it scroll through them when available

**Comment by s-cotton** [comment]
Got to the point where I needed these to continue, so here's my first pass at it: https://gist.github.com/s-cotton/1ba9cd68a8263ff70b891b4bb53b588b  Drop this into your mylar folder and send in a single parameter of a folder for a series.  

Requirements:
https://pypi.python.org/pypi/rarfile/
https://python-pillow.org/
Non-free unrar, or we could use the supplied rarfile.py https://rarfile.readthedocs.io/en/latest/faq.html#how-to-avoid-the-need-for-user-to-manually-install-rarfile-unrar

@evilhero I'm not sure how you want to go about integrating this into mylar proper.  I think it would be entirely valid to just have an ajax endpoint that will fire this off for a comic, and I can detect 404's on the frontend when I try to load an issue cover, call that endpoint, then update the html frontend with the CV image temporarily.  This would reduce the overall size requirements to just those comids that you are actually visiting in they system.  Let me know your thoughts

Things still to do here are:

1. Integrate into Mylar, changing OS folder lookups to calls for actual db issue file locations
2. Determine where in mylar we trigger this from
3. Add config flags into mylar to control Rar usage as well as maybe an "aggressive" option that would allow for these to be generated whenever an issue is post processed
