### ISSUE TITLE
pull list showing random comics as wanted

### ISSUE THREAD

**Issue by rupaschomaker** [evilhero/mylar#1536]
I've updated to the latest development branch.  I've noticed this for the past couple of weeks but haven't seen anyone else report the same issue...

My wanted list is showing many many issues in the pull list as wanted when they are issues that I've never actually marked as wanted.  Mylar doesn't seem to be actually downloading these issues but the UI makes it hard to actually mark something that is already wanted as really wanted...

 I'm running in alt_pull=2 mode.

Anyone else experiencing this?

**Comment by evilhero** [comment]
Can you give a screenshot showing what you're indicating? This hasn't occurred for we'll over a year and not with the new pull method, so if it's happening I'd like to investigate it further.

**Comment by rupaschomaker** [comment]
![image](https://cloud.githubusercontent.com/assets/1816608/21934946/199f9f42-d971-11e6-8935-90e65f561191.png)

I don't see a pattern other than it appears only the recent issues are showing randomly as wanted.  If I sort by issue #, most are in issue 1, a couple are in issue 2, and I don't see any past that which are wanted incorrectly.

**Comment by evilhero** [comment]
Yeah that's not normal - can you do a Recreate Pullist from the weekly pull tab and see if it re-aligns things properly?

**Comment by rupaschomaker** [comment]
One of the first things I tried.  Unfortunately, didn't work. :(

**Comment by evilhero** [comment]
If it's not realigning I would suspect you have some stale entries in your dB (have you ever used the auto-want feature in mylar where it marks upcoming issues as wanted?)

**Comment by rupaschomaker** [comment]
ah, yes.  I have used the auto-want feature before....  I also recently
deleted a bunch of comics that completed and I no longer wanted tracked.

**Comment by rupaschomaker** [comment]
oh wait, not auto want.  I've used the "Watch" feature though where mylar
watches for a release and then adds to wanted when CV finally gets around
to adding it.

**Comment by evilhero** [comment]
well - watch turns into auto-want (or did, the terminology/wording might have changed over the past few months), but yes the 'watch' feature is what I was asking about.

What might be happening is that it's trying to re-add those series into your watchlist so it would then mark them as Wanted - it only does this for issues that are 1st issues in most cases. You can verify if they're on your auto-want/watch list by clicking on the Upcoming tab, and at the bottom of that page you'll see 3 tabs, the middle tab is labelled as upcoming_nodata and shows what series are on the auto-watch list that have yet to be added (they're normally removed once they get added successfully).

Can you confirm that those series don't exist on your watchlist at all (just in case they got readded due to the above stuff happening)? Also, on the pull-list itself, the series names should become clickable links that reference back to the series detail page within Mylar for the respective series - does clicking on one of those series titles do anything?

**Comment by rupaschomaker** [comment]
upcoming_nodata just has one issue and it looks like one I would have chosen.  ![image](https://cloud.githubusercontent.com/assets/1816608/21955858/36ccd314-da39-11e6-8f7b-33add9511ef7.png)

Clicking on the title brings me back to the Mylar home screen.  The links are all http://[redaced]/comicDetails?ComicID=None.

**Comment by evilhero** [comment]
Ok so what looks like is happening is that you have a blank comicid entered somehow and because the comicids on the pullist have a blank value until they're matched up using the alt_pull 2 method, the ones that still don't have a comicid are matching to the bank series on your watch list and making it as wanted (pretty good guess). 

Try going to your main page and sorting by status - you should have some series that are in a Loading state (spinny wheel), you need to either refresh those series so they're in a normal state again, or delete them entirely. Then once you've done that, go back to the pullist and do  recreate and it should fix everything. 

When you start mylar up it is supposed to remove any comicids that have  None value, so not sure why it hasn't done that if you've restarted mylar recently.

**Comment by rupaschomaker** [comment]
Don't see it in the database:
```
sqlite> select status,count(*) from annuals group by status;
Downloaded|7
Skipped|31
sqlite> select status,count(*) from comics group by status;
Active|106
sqlite> select status,count(*) from failed group by status;
Failed|56
sqlite>  select status,count(*) from futureupcoming group by status;
Wanted|1
sqlite> select status,count(*) from issues group by status;
Archived|413
Downloaded|168
Snatched|4
Wanted|51
sqlite> select status,count(*) from snatched group by status;
Downloaded|5076
Post-Processed|35
Snatched|4175
sqlite> select status,count(*) from upcoming group by status;
Wanted|388
sqlite> select status,count(*) from weekly group by status;
Downloaded|16
Skipped|93
Wanted|10
```

Don't see any spinny thingies either.

I followed the steps of going to Manage Comics (I wasn't supposed to DO anything in there was I?) and then did a recreate and I still have those issues marked as wanted.

**Comment by rupaschomaker** [comment]
```
sqlite> select count(*) from annuals where comicid = '' or comicid is null;
0
sqlite> select count(*) from comics  where comicid = '' or comicid is null;
0
sqlite>  select count(*) from failed where comicid = '' or comicid is null;
50
sqlite> select count(*) from futureupcoming where comicid = '' or comicid is null; 
1                            
sqlite> select count(*) from futureupcoming where comicid = '' or comicid is null;
1
sqlite> select count(*) from issues where comicid = '' or comicid is null;
0
sqlite> select count(*) from snatched where comicid = '' or comicid is null;
0
sqlite> select count(*) from upcoming where comicid = '' or comicid is null;
0
sqlite> select count(*) from weekly  where comicid = '' or comicid is null;
5
sqlite> select * from weekly where comicid = '' or comicid is null;
2017-01-11|BOOM! Studios|2|Jim Henson's The Storyteller: Giants||Skipped||||jimhensonsstorytellergiants|2|2017|19
2017-01-11|DC Comics|1|Justice League/Power Rangers||Skipped||||justiceleaguepowerrangers|2|2017|35
2017-01-11|DC Comics|1|Justice League of America: Vixen||Skipped||||justiceleagueofamericavixen|2|2017|37
2017-01-11|Titan Books|1|The Assignment||Skipped||||assignment|2|2017|102
2017-01-11|Titan Books|1|Reassignment||Skipped||||reassignment|2|2017|105                                               
```

I did the steps you requested.  Went to Manage Comics (wasn't supposed to do anything there, right?) and then recreated the pullist.  Still no good. :(

**Comment by evilhero** [comment]
Can you delete that futureupcoming entry ? If it has a null value for comicid, it's trying to reference that against your weekly pull list on every try, sees the comicid being null and matches against the 5 null values you have on your pullist (which is right, mine's the same way in that regards) it might be throwing things off.  

Before you delete it tho, can you grab the data from the sql cli and paste in what it actually has in the futureupcoming table for that one entry that exists ? I tried to add an item to the 'auto-want' list, and then recreated the pull-list but the 5 issues that have no comicid's didn't get marked as Wanted - so I'm thinking that there might be some other value in there that's messing it up.

The Manage Comics thing I mentioned - if you went into that screen and sorted it by status (or whatever) you might be able to see some inconsistencies (it's a bit different of a view than the main page - plus you can do actions from that tab such as Delete, Refresh, etc)

**Comment by rupaschomaker** [comment]
```
sqlite> select * from futureupcoming;
Injustice: Gods Among Us - Ground Zero|1|||2016-12-07|DC Comics|Wanted||49|2016
```

After doing some logger.() tracing, the line that is causing it to become wanted is below which matches up with your comments.:
```
                    if weeknumber:
                        if any([week >= int(weeknumber), week is None]) and all([mylar.AUTOWANT_UPCOMING, tmp_status == 'Skipped']):
```

I removed the single entry from future-upcoming and... no good.

Hmm...  ok, so AUTOWANT_UPCOMING must be set and sure enough it is.  

Now, noticed that the value of haveit is always 43018 for the ones that switched to Wanted.  43018 is in the annuals table as two entries:

```
sqlite> select * from annuals where comicid = 43018;
354037|1|united they fall|2012-10-27|Skipped|43018||||1000|The Flash||||
420205|2|the quick and the green; details|2013-09-01|Skipped|43018||||2000|The Flash||||
```

Deleting these just got me a new static comicid -- so I'm assuming that somehow the matching being done for haveit is somehow returning false positives?  Figured I'd stop here for advice before going further.

**Comment by evilhero** [comment]
Sorry, just got back to a machine today - so it looks like it's inadvertently marking series with no ComicID as having the same ComicID and marked as Wanted. I'm not quite sure where the 43018 series is coming from as the logs/lines you posted didn't indicate where it was getting marked as such.

The haveit logic is very simple - it just checks to see what you have available and if it matches exactly to what's on the pull-list it marks it as Wanted. I have a feeling the real problem here is the incorrect handling of the autowant-upcoming. It should only be taking into account the comicid's that match up, but the test it's doing looks like it's not taking into account the nulls.

Can you check your comics table for anything with a comicid of a value of 'None' ? There has to be some invalid value in there somewhere that's causing the problem, as it seems to be localized to just you unfortunately.

**Comment by rupaschomaker** [comment]
Nothing with comicid = 'None'.  the reason I focused on the haveit part is that prior to setting haveit, tmp_status is Skipped.  Then the line setting haveit is called which returns the same comicid for each entry which then satisfies the AUTOWANT_UPCOMING condition which sets tmp_status to Wanted.

weekly['ComicID'] is NoneType for the cases when it is marked as wanted.  So when used as an index into watchlibrary[] we're getting....  ?   Maybe the 0th entry?  Looking

**Comment by rupaschomaker** [comment]
The matching is done by ComicID, not by Comic Name.  If ComicID is None that whole section should be skipped, right?

**Comment by evilhero** [comment]
It does both, if first checks for comicid as that's the best way to find an exact match with the alt_pull 2 method. But if that doesn't work properly due to naming problems, it drops down to do a name comparison match - which is where I think it's causing a problem for you.

If you check your pull-list for this week (it would have populated yesterday), you probably have a bunch of issues that are in a Wanted state that you don't have on your watchlist ?

**Comment by rupaschomaker** [comment]
This simple patch seems to fix it for me, I'll test more, but the logic seems sound:

```
diff --git a/mylar/webserve.py b/mylar/webserve.py
index 89042bb..25cd0e1 100755
--- a/mylar/webserve.py
+++ b/mylar/webserve.py
@@ -1641,7 +1641,7 @@ class WebInterface(object):
             for weekly in w_results:
                 xfound = False
                 tmp_status = weekly['Status']
-                if weekly['ComicID'] in watchlibrary:
+                if all([weekly['ComicID'] is not None, weekly['ComicID'] != '']) and weekly['ComicID'] in watchlibra
ry:
                     haveit = watchlibrary[weekly['ComicID']]

                     if weeknumber:
```
