### ISSUE TITLE
Better Safe Start Mode

### ISSUE THREAD

**Issue by s-cotton** [evilhero/mylar#1537]
I am noticing a few areas where safe start is not being respected.  On start of course it can take you to manage, but for other actions, such as deleting a comic, it goes to home. Can this be made more consistent to avoid the costly queries across the board?

**Comment by evilhero** [comment]
Oh, you mean when you're on the Manage screen and delete a series when you initiate Mylar via the safestart option, it returns to the home page instead of staying on the Manage screen?

**Comment by s-cotton** [comment]
Even deletes from a single comic page are going to home afterwards.  Just wondering if actions where we redirect after start, if those should respect the flag as well

**Comment by evilhero** [comment]
Yes, most definitely - the safe start was a quick hack I did about a year ago when problems were occuring on startup due to some invalid references / db problems. They've since gone the way of the dodo-bird, but the safestart remained because I thought it was a useful thing in case of an emergency (kind of like, just load a limited interface showing a few options, when it's completed - restart in full blown mode).

But yes, definitely it should be respecting the flag and returning to whatever page called it in that instance.

**Comment by s-cotton** [comment]
Maybe the use cases need to be split up. A "default screen" option could be useful for people who always head to the home, manage, readlist, or pullist screens frequently when loading the app, while an emergency start mode that perhaps also stops the various threads from running on daemon start could still be useful in its own right.

**Comment by evilhero** [comment]
Yes, there's alot that can be done/managed from either route - the emergency/barebones startup mode would be the one that I would think would benefit people the most for when things don't work properly as they should for whatever reason.

I'm not sure about the default screen - well not so much that it wouldn't be useful, just I'm not sure what would be the best items to place on such a screen, or the best way to run things from said screens.
