### ISSUE TITLE
HaveTotals Optimization

### ISSUE THREAD

**Issue by s-cotton** [evilhero/mylar#1538]
Was playing around with some queries, but you probably know this function better than I do.  Could these queries be optimized to eliminate the additional Queries?  Just playing around with some queries here:

`SELECT comics.*, COUNT(haveIssues.IssueID) AS HaveIssues, COUNT(totalIssues.IssueID) AS TotalIssues FROM comics 
LEFT JOIN issues AS haveIssues ON haveIssues.ComicID = comics.ComicID AND haveIssues.Status = "Downloaded"
LEFT JOIN issues AS totalIssues ON totalIssues.ComicID = comics.ComicID
GROUP BY comics.ComicID`

`SELECT comics.*, COUNT(haveIssues.IssueID) AS HaveIssues, COUNT(totalIssues.IssueID) AS TotalIssues, COUNT(haveAnnuals.IssueID) AS HaveAnnuals, COUNT(totalAnnuals.IssueID) AS TotalAnnuals FROM comics 
LEFT JOIN issues AS haveIssues ON haveIssues.ComicID = comics.ComicID AND haveIssues.Status = "Downloaded"
LEFT JOIN issues AS totalIssues ON totalIssues.ComicID = comics.ComicID
LEFT JOIN annuals AS haveAnnuals ON haveAnnuals.ComicID = Comics.ComicID AND haveAnnuals.Status = "Downloaded"
LEFT JOIN annuals AS totalAnnuals ON totalAnnuals.ComicID = Comics.ComicID
GROUP BY comics.ComicID`

I dont think the annuals one is quite right yet, but the first one seems to be working as expected.  This would reduce the number of queries required to 1 instead of a count query for each of the comics after the initial query.

**Comment by evilhero** [comment]
Which queries were you looking at changing out with these options in the havetotal function? The only thing I noticed quickly looking at the query is that there's no need to subset the query based on Status. The 'Have' column within the comics table already holds all the necessary information which is handled by the updater.py module - the reason being between Downloaded status, Archived, Ignored, Snatched and then the various options for each (count ignored as have, count snatched as have, etc) - relying on the one status to count by would give incorrect results for that tally count.

That being said, the first one seemed to work fine, but it took several seconds to return all the results - so maybe a staggered resultset might be of better use with that query so that things load up quicker on the main page (where it's used also)? I've been wanting to stagger the main page display so it loads quicker (people that have 1000+ series on their watchlist indicate it can take over a minute to load the main page alone), but using datatables has some inherent complexities to the problem.

The second one, given just a cut & paste locked up on my db. Which is probably due to the fact that depending on if you have annuals integration enabled/disabled, it will dictate in which table the annual data is stored (if enabled, annual data is stored in annuals table / if disabled, annual data is stored in issues table) and that it's causing some weird joining problems.

**Comment by s-cotton** [comment]
Correct, the second query is not quite right.  The offending line I am seeing is the count issues query right after you get into the comiclist loop.  That is going to be run for every comic, but it's result only appears to be used when this function is called for the refresh action.  I am wondering if this was done because the column counts in the comic table are not trusted?  If we instead included them in the main query via joins, per the first query I posted, could we avoid having to do a count query for every comic?  A comparison of the comics.Have versus the new TotalIssues gathered in the joined query could tell you if there is a discrepency without having to execute the additional queries

**Comment by evilhero** [comment]
Well the issues counter isn't being used at all except to validate that there is somesort of issue data available for the given comic. It is used for annuals however (the count), as the total column that's in the comic table does not contain any annual counts - it's just a count directly from CV of the number_of_issues. So it needs to 'count' the number of annuals that are linked to a given comicid and append that to the total count, so that the total number on the main home page is correctly tallied (otherwise the have would exceed the total in some cases where annuals exist and all of the normal issues are present). The discrepancy between the total / have counts should only exist when annual integration is enabled, so it would be possible to use the initial query you presented and then account for the variations, or have 2 seperate 'big' queries as you have - and only reference one or the other depending on if annual integration is enabled or not.
