### ISSUE TITLE
WWT changed RSS categories

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1542]
category 50 is no longer the latest comics, they created a new one for Nem43 Comics... This one should work:

https://www.worldwidetorrents.eu/rss.php?cat=132

**Comment by evilhero** [comment]
Well that's good in a way, bad in another - since if someone other than Nem uploads anything other than a new release, it's not gonna hit the correct category.

I added the 132 category to the feed, so now it will track both 50 & 132 for recent additions. Not sure if it's worth it to put it in 2 separate feed calls as opposed to just 1, other than the hard limit of it returning 50 items (2 separate feeds = 100 items, 1 joined feed = 50 items combined)

Now in development ;)  Thanks for the heads-up too!

**Comment by weidercs** [comment]
Validated update, thanks!
Closing
