### ISSUE TITLE
Copy Processed files to Additional Directory

### ISSUE THREAD

**Issue by dhmartin82** [evilhero/mylar#1543]
I manage a sort of Reading List by copying new issues to a cloud drive folder. I can then delete these issues from any device without worry as the comics stored in the mylar "Comic Location" folder act as an Archive.

I'd like to be able to specify a directory where newly post-processed files (i.e. tagged files) can be copied (without the creation of a series folder) in addition to the "Comic Location" managed by mylar. A setting for each comic would be ideal.

I thought this might be possible through multiple_dest_dirs, but it doesn't seem so (I'm not entirely clear on the function of this option).

Thanks as always for the superb work!

**Comment by evilhero** [comment]
I can understand the desire for post-processing to go to a newly post-processed directory (kind of like the way the pullist-directories work where it puts all comics for a given week in their respective week directories), I just didn't follow your thinking of the 'setting for each comic' - can you explain what you mean further as atm I can't determine what it is that you're trying to describe. There is a 'grab-bag' directory location within Mylar that you can set to a specific location, where one-off's and such that don't have a designated location to be sent to go. It might be possible to rework things so that they go to this one-off location where you could then copy them from there up to the cloud.

On the side, as I'm not sure if you're aware or not, but there is a Reading List Management section within Mylar (Manage tab / Advanced Options / ReadingList Management), which has some options that might be beneficial for your workflow - it tracks read / not read issues, can send issues to your 'reading list' that are newly post-processed, new pulls, or marked to be sent, and can even send specified issues to be sent to a 3rd party device (right now it's just Android devices). 

The multiple_dest_dirs is used for alternate series locations across multiple sources provided they all have the same relative path. So if you have comics on say c:\comics, and then have other comics on f:\comics, setting the multiple_dest_dirs to f:\comics would literally indicate that c:\comics is the primary directory where all file-type operations are allowed, and f:\comics is like an archive-location where a limited amount of file-type operations are allowed. The benefit of this all being that both locations are scanned in for issues and represented as a whole so it's possible to disperse large collections over several drives (the multiple_dest_dirs can handle more than one location), but all post-processed issues go into the primary location.

**Comment by dhmartin82** [comment]
Thanks for the quick and detailed response!

When I say a setting for each comic, I mean that instead of turning this on globally for all newly processed files, you could specify which comic series you would like to send to this alternate directory. This would prevent turning on a firehose of comics when you say, start adding a bunch of back-issues for a series you want to get caught up on. I'd suggest a check box in the "Edit  Settings" tab for a given comic series that would enable moving all new processed files to the specified alternate directory.

I have played with the Reading List section and I think it's really well thought out. I'm thinking about how I can make use of it. At the moment I split my reading evenly between iPad and MacBook Pro (an iMac at home acts as a server that runs mylar and other apps). The simplest way I've found to maintain some sort of shared reading list library between the two is to copy new issues to an iCloud Drive folder that syncs with these devices. When I finish reading an issue I can just delete the copy from the iCloud Drive folder, removing it from my reading list, while the original copy is archived in my mylar managed folder on my iMac.

Thanks again!

**Comment by dhmartin82** [comment]
I can nearly get this working with mylar as is:

- Set the SABnzbd mylar category to download to the alternate directory (ending with * to prevent creation of job folder)
- Set mylar to copy instead of move processed files

Unfortunately the file that remains in the alternate directory is not tagged/renamed.

**Comment by dhmartin82** [comment]
A quick follow up to this request - I've found an easy solution using built-in tools that should work for anyone on a Mac seeking this functionality.

Create an Automator Workflow that simply copies input to a specified directory. Make sure it is saved in ~/Library/Workflows/Applications/Folder Actions

Then, for each series subfolder in your Mylar-managed directory, apply a Folder Action (control click a folder or group of folders- Services - Folder Actions Setup...) and assign the workflow that you created above (it should appear at the bottom of the available scripts in the Folder Actions Setup window).

You will have to assign the workflow for each series subfolder that you want to auto-copy to the new directory, but it's a one-time setup and not difficult. The nice thing is you can check/uncheck folders in the Folder Action Actions Setup.app as needed.

Thanks evilhero for all your hard work on Mylar!
