### ISSUE TITLE
Error when starting Mylar

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1545]
```
Traceback (most recent call last):
  File "/Applications/Mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/Applications/Mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Applications/Mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/Mylar/mylar/webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "/Applications/Mylar/mylar/helpers.py", line 1325, in havetotals
    c_date = datetime.date(int(latestdate[:4]), int(latestdate[5:7]), 1)
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by evilhero** [comment]
Have you restarted Mylar since the error occurred ? This type of error is typically handled on startup during the 'db cleanse' cycle where it gets rid of these types of problems that stop Mylar from starting.

It looks like you have a series on your wachlist that has an invalid latest date value - usually it can be fixed by performing a Refresh of the given series. Try restarting Mylar and then if you can get in, find the series where the latest date is either None or Unknown and refresh said series.

**Comment by thewindupboy** [comment]
I can't actually get in to mylar :(

**Comment by evilhero** [comment]
Can you not restart Mylar via the cli or kill the existing process and then just start up the daemon again ?

**Comment by thewindupboy** [comment]
I kill mylar (finding the process by "ps - ax | grep mylar"), and then restart.
That brings me immediately to the page with the error.

**Comment by evilhero** [comment]
What page are you trying to load up that gives the error - and is the error on the page the same as what you posted ? 

If you're just loading the main page, maybe you can try loading '/manageComics' instead of '/home' - which might allow you to load the additional series (it might not, but worth a shot). Or even try going to '/pullist' and doing a Recreate pullist from that screen might sort things (perhaps an earlier attempt at the pullist failed and it died on attempting to write the data')

**Comment by thewindupboy** [comment]
OK, I'm able to get to some other pages.  I got an error on /manageComics, but I was able to get to pulllist and do a recreate.  I then did a shutdown, and started back up and still have the error.

**Comment by evilhero** [comment]
How big is your mylar.db file ? If at all possible, and if you're ok with it - I'd like to look at the .db file itself so I can run tests against it and see how I can fix things. I mean, aside from you going into the sql and deleting the offending series, or restarting from scratch - there isn't an easy fix unless I can determine what's happening under the hood, and the only way to do that unfortunately is to analyze the db itself.

**Comment by thewindupboy** [comment]
File siz: 3878912
I'm comfortable in SQL, though I'm really an Oracle guy (I'm not sure what flavor mylar uses).  But I'm happy to send this to you.

**Comment by evilhero** [comment]
That's not that big at all - Mylar uses sqlite3, which if you know sql it's just a lite version of it ;)

If you can email it to evilhero@mylarcomics.com - and then flip back a message when you do so I can remove my email from post so the spammers don't catch me I'd really appreciate it.

If you want to go into sqlite3 - in the same directory as the mylar.db file (and in the cli) ,do a: 
`sqlite3 mylar.db` and hit enter. Once in the sqlite cli, you'd probably have to do the following to see all the series that have improper latest date values:
`select * from comics where latestdate is NULL or latestdate is 'None';`

Then `delete from comics where comicid=XXXXX` where the XXXX is the relevant ComicID given in the previous command.

(if you're going to send me the file - don't delete anything until after you've sent it please :) )

**Comment by thewindupboy** [comment]
The select returned nothing, so I sent you the file
Thanks!

**Comment by evilhero** [comment]
I got it - sweet, thanks! 

Going to sideroad this now to see what's going on ;)

**Comment by thewindupboy** [comment]
Just updated to the newest build and it all looks good!  Thanks!
