### ISSUE TITLE
no longer starting up

### ISSUE THREAD

**Issue by dreaganluna** [evilhero/mylar#1546]
mylar is running on an intel NUC running Windows 7. I haven't had any problems with running Mylar, until somewhere this week. There haven't been created any new log entries since the 15th. Whenever I stop/start the service, nothing happens.

When I try to start it up manually, I get the following stacktrace:

```
C:\mylar>python Mylar.py
lib\js2py\constructors\time_helpers.py:9: Warning: Please install or fix tzlocal
 library (pip install tzlocal) in order to make Date object work better. Otherwi
se I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in
order to make Date object work better. Otherwise I will assume DST is in effect
all the time', Warning)
C:\mylar\lib\js2py\constructors\time_helpers.py:9: Warning: Please install or fi
x tzlocal library (pip install tzlocal) in order to make Date object work better
. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in
order to make Date object work better. Otherwise I will assume DST is in effect
all the time', Warning)
20-jan-2017 08:52:11 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic direct
ory: C:\mylar
20-jan-2017 08:52:11 - ERROR :: MainThread : Uncaught exception: Traceback (most
 recent call last):
  File "Mylar.py", line 274, in <module>
    main()
  File "Mylar.py", line 200, in main
    mylar.CFG = ConfigObj(mylar.CONFIG_FILE, encoding='utf-8')
  File "lib\configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib\configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "1".

Traceback (most recent call last):
  File "Mylar.py", line 274, in <module>
    main()
  File "Mylar.py", line 200, in main
    mylar.CFG = ConfigObj(mylar.CONFIG_FILE, encoding='utf-8')
  File "lib\configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib\configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "1".
```

**Comment by evilhero** [comment]
It looks like your config.ini file got corrupted somehow, as it's saying there's an invalid character on line 1 and it won't read past that. If you have a backup of the .ini, restore that -  otherwise you'd have to generate a new one by starting Mylar up without a config.ini present (ie. delete/move the old one). Once it's generated, shutdown Mylar and then you'll have to copy & paste relevant stuff back into the .ini (like keys and such) and you should be fine thereafter. This can sometimes happen when you edit an .ini file in Windows outside of a normal python editor, as windows editors tend to add hidden characters to files for formatting purposes.

You might want to do the 'pip install tzlocal' as well from a command line just to make sure that when Mylar does date comparisons that it can do proper time comparisons regardless of timezones.

**Comment by F688** [comment]
Having the same problem. Created new config. and "pip.install tzlocal" but I'm still not able to launch page. Changed port. Removed User/Password. Still can't start webpages


C:\mylar>cd c:\mylar

C:\mylar>python mylar.py -v
21-Jan-2017 07:48:34 - INFO :: MainThread : [DIRECTORY-CHECK] Found comic directory: C:\mylar
21-Jan-2017 07:48:34 - INFO :: MAIN : Successfully discovered local IP and locking it in as : 192.168.0.16
21-Jan-2017 07:48:34 - DEBUG :: MAIN : Logger set to use : Rotational Log Handler (default)
21-Jan-2017 07:48:34 - DEBUG :: MAIN : ConcurrentLogHandler package not installed. Using builtin log handler for Rotational logs (default)
21-Jan-2017 07:48:34 - DEBUG :: MAIN : [Windows Users] If you are experiencing log file locking and want this auto-enabled, you need to install Python Extensions for Windows ( http://sourceforge.net/projects/pywin32/ )
21-Jan-2017 07:48:34 - DEBUG :: MAIN : Trying to execute: "git rev-parse HEAD" with shell in C:\mylar
21-Jan-2017 07:48:34 - DEBUG :: MAIN : Git output: 2d71763a96838eb130992d5c5186e4ec47707af4

21-Jan-2017 07:48:34 - INFO :: MAIN : [DB Module] Loading : sqlite3 as the database module to use.
21-Jan-2017 07:48:34 - INFO :: MAIN : [Cache Check] Cache directory currently set to : c:\Mylar\cache
21-Jan-2017 07:48:34 - INFO :: MAIN : Checking to see if the database has all tables....
21-Jan-2017 07:48:34 - INFO :: MAIN : Populating Base Exception listings into Mylar....
21-Jan-2017 07:48:34 - INFO :: MAIN : Populating Custom Exception listings into Mylar....
21-Jan-2017 07:48:35 - INFO :: MAIN : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
21-Jan-2017 07:48:35 - INFO :: MAIN : Correcting Null entries that make the main page break on startup.
21-Jan-2017 07:48:36 - INFO :: MAIN : Making sure the latest dates are all correctly pointing to the correct issue numbers & dates

**Comment by evilhero** [comment]
@F688 I don't see my error messages in your log output that resemble the OP's post. 

Do you get any type of error message either in log/screen when trying to access the GUI? If you have a lot of series in your watch list, you might have to wait a few as its determining if the latest dates are correct.

**Comment by F688** [comment]
I received the same error and then followed you directions. The error went away. Now it is stuck on the check issues numbers and date. Yes I have a lot (116K comics). Will this date check take a long time every time are start Mylar? Last time I tested it is still checking dates for over 30 minutes and counting.

**Comment by evilhero** [comment]
It only checks series, not each issue - so it really shouldn't take that long unless you have 100k+ series. It only has to run once but it does the check on each startup to ensure that the latest dates are correct and pointing to the correct issue as well. It only fixes those that are incorrect otherwise it doesn't do anything.  The GUI should still be somewhat responsive so long as you're not loading the main page - have you tried going to a different page on startup? (ie.  /pullist, or /config even)

**Comment by F688** [comment]
I have about 33K series. Some are older (1940/1950) where ComicVine does not provide dates.
 However I know its running in the background using 10% of the CPU. I usually start with /config or /manage as /home takes over 20 minutes  to load normally. Nothing is coming up. Still running over 1 hour. Log has not made any entries past:
21-Jan-2017 09:25:30 - INFO    :: MAIN : Making sure the latest dates are all correctly pointing to the correct issue numbers & dates

**Comment by evilhero** [comment]
Weird, not sure why it'd be taking that long unless like you said it's getting hung up on a series. 

You can try this if you'd Ike, shutdown mylar and edit the mylar/__init__.py file.  Find the line that has ```helpers.latestdate_update()`` and change it to ```#helpers.latestdate_update()```
Save the file, delete the__init__.pyc file in the same location and start up mylar - with any luck it'll bypass. 

If it works after that change, I'll remove that option since that would be the offending line. 

Just a note too, the last commit had some db optimization for the main page loading - it should load much faster than previously, but obviously I haven't tested it against a library of your size.

**Comment by F688** [comment]
Works now

**Comment by F688** [comment]
I expect some delay because of my library size. I have seen some speed improvements recently so thanks again. You have a great product here.

**Comment by F688** [comment]
FYI - Correction - # of Series you're watching: 13971

**Comment by evilhero** [comment]
Heh yeah that's ok - I'd be interested in knowing how long it takes for the main page to load with that many series with the new optimization. Someone else mentioned it's considerably faster, but their library wasn't your size I'm sure.

**Comment by evilhero** [comment]
@F688 : the most recent development commit has the fix for the startup problem (I just removed the call entirely). So if you're wanting to update, you'd have to revert the change you had made to get it to work, and then the update will work (otherwise it'll throw an error indicating that you need to stash your work kinda thing).

**Comment by F688** [comment]
Thanks, will do. FYI - Main page load - Can't say for certain, it takes overnight to open, stopped checking after 3 hrs. Of course last time I opened the home page (the over 20 min) I did not have all the issues incorporated into the database.

**Comment by evilhero** [comment]
Well there was some db locking issues going on that are happening only on Windows instances and involves the main page and calculating the totals. Based on the number of series you're watching, and that you're running Windows, it's a pretty good bet that you may have been affected by the locking (the current dev build has 2 identical calls to the comics table which causes unnecessary loading and would increase the wait time to load the main page).

I'm gonig to be pushing out the fix for the db locking, and the removal of the duplicate calls - so you should see an improvement in speed loading the main page thereafter.

**Comment by F688** [comment]
Just tested it. A million time better. Load time less then 20 sec
