### ISSUE TITLE
A problem that may be crashing my dropbox.

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1551]
Hi

Some part of mylar seems to be continually creating an old file structure where I used to store my comics. The result is, being very similar to the new structure, it seems to crash dropbox, where the comics are stored. More details:

I used to have a different Dropbox Pro account, so the parent folder was, let's say, "Drobpox (A)". (A) is the name of the entity on the Pro account). My new Dropbox Pro account, let's call it "Dropbox (B)". Inside that folder, All my mylar comics go into a folder called "Comics".

Every few days, the file structure of "Dropbox (A)/Comics" reappears, with a few new comics in it. 

A strange detail: For a while, some parts of the ini file, I think it's "grab_bag_dir" and one other, kept reverting to my old download location. I finally got that to stop reverting and now says "Dropbox (B)/Comics". But the problem is still happening.

What can I do to prevent this happening? Do I need to install from scratch?

**Comment by evilhero** [comment]
Did you do the locmove option within the config to change the old paths to the new one by chance? 

It sounds like you might not have done that, and now only new series or series that are refreshed will have the correct path (changing the comic location path doesn't update all the  series already in your watchlist, only new ones)

**Comment by AtariBaby** [comment]
I didn't! Where is it?

**Comment by evilhero** [comment]
Sorry just got back to the machine.

You need to make sure Mylar isn't running, and edit the config.ini.

- Set your locmove to 1 to enable the option to rename the locations.
- Set your newcom_dir value to new location you wish to store your comics at and very important, make sure your destination_dir value is set to your current location
- If you have special folder formatting happening (ie. you have $Publisher/$Series subfolders), you need to enable the fftonewcom_dir option to 1 so that the current folder_format option will be applied to the new folders (otherwise it'll just change the base and might leave things out).

Save the .ini, start up Mylar and Mylar will say it's initiating the locmove option and then start to change the locations with the db to the new location. Once it's done, you can verify that they're set correct by going into some series. If it's all good, make sure to change your Comic Location Path to point to the new location (otherwise any newly added series won't point to the correct location), then save the config and restart and that's it. Note that the value for locmove will reset to 0 upon completion of the locmove during startup so it doesn't keep on trying to do things over & over ;)

**Comment by AtariBaby** [comment]
Okay, I have stopped it and confirmed it was stopped (page wouldn't load)
I changed it to 1 and made sure all the dirs were correct.
I restarted the service.
I never saw any messages about "locmove" working. But maybe it wasn't working before, because I wasn't stopping mylar first. I was saving then restarting.

**Comment by AtariBaby** [comment]
Just in the interest of suggestions, a graphical interface would be better! Tho I don't mind this one bit, of course.

**Comment by AtariBaby** [comment]
I need your help here. It's not working. The "rogue folders" are still being created, and as I'm now monitoring the events very closely, it appears more sure that this is what's crashing Dropbox.

**Comment by evilhero** [comment]
It actually unlikely that the program itself is causing Dropbox to crash since it has zero interaction with it. 

Make sure that you're looking at the right config.ini (check the path on the first tab in the configuration GUI), and possibly disable the 'enforce permissions' option as I would imagine if Dropbox can't access the folder due to mylar overwriting the permissions it would cause some problems (and it would do it on every refresh / add / post-process / recheck action)

**Comment by AtariBaby** [comment]
Well I don’t want to get into the minutia here, but the problem is that it’s creating the old dropbox structure which is nearly identical to the new one.

I will disable that. But I don’t think this is working because it continues to create these old directories and i never see this page you mention stating that “locmove” is happening.

**Comment by AtariBaby** [comment]
Also, i must have the right file, because the "1" does change to "0".

**Comment by evilhero** [comment]
Ok so the config.ini is the right one then if it's retaining the value. 

What I meant by the unlikely is that mylar itself has no direct interaction with Dropbox, so it isn't directly doing something to make Dropbox crash.  The fact that it's creating your old directories repeatidly is indicating that the locmove wasn't initiated for whatever reason, or the paths aren't matching for the change to transpire.

So we need to look at your config.ini and what series this is occuring for and their path destinations as indicated within mylar for the respective series (not all, just one / two is all that's needed most likely)

**Comment by AtariBaby** [comment]
Okay sorry so what do I need to do?

**Comment by AtariBaby** [comment]
just delete and re-add the associated comics when this happens?

**Comment by evilhero** [comment]
Sorry dude, paste in your config.ini with the keys removed  as well as one of the series directories that is having a problem (do it from within the Gui as mylar sees it - so from the comic details page of the respective series)

**Comment by AtariBaby** [comment]
I wound up creating a new Windows profile and that fixed the dropbox crash. What a PITA, Dropbox +Win10.
