### ISSUE TITLE
[Request] Manage Comics - Add Rename All

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1552]
Is is possible to add a "Rename All" to the Manage Comics section?

**Comment by evilhero** [comment]
Well it's possible - there are actually more than one renamer function within the program just due to how it's being called and the information that's available. But if it can metatag, then it should be able to rename files just as well.

I'll look into this and see how difficult it is and report back when I've looked into it more ;)

**Comment by baz1860** [comment]
Has there been any progress on this?

**Comment by evilhero** [comment]
Not as of yet unfortunately, as there's been other things requiring my attention as opposed to some enhancement requests. Ive done a few requests over the period, but just didn't tackle this one yet as it's a bit more involved since it's actually dealing with modifying files on a mass basis. 

I'll try and look into this again soon, but thanks for the reminder about the request still pending.

**Comment by baz1860** [comment]
No rush, very aware that you're doing this as a side project - you'll get to it when you do :)
