### ISSUE TITLE
Why is <volume>1</volume> tag being added to all issues metadata now?

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1559]
I am not sure when this started, but at least for the last month or so, all my metadata includes volume=1 which is throwing off my reader since older issues do not have this tag.  It wouldn't be so bad if it actually corresponded to story arch or something, but they are always 1.  My questions are, 1) is this a bug, and if not 2) Can I disable this portion of the metadata?

**Comment by evilhero** [comment]
It probably started middle of last year, I think?  It actually polls it against what mylar has for volume label (edit settings tab for a given series), so it's not that it's always 1 but moreso the titles you're looking at either are new series, or have an incorrect volume if it's not a new series. 

That being said the option should exist to toggle the volume to be part of the tagging, so I'll try and add it into the next dev commit.

**Comment by evilhero** [comment]
Ok, so looking at this more - it seems to be a problem with ComicTagger and how it handles the data. It will write the volume data regardless of a value being present as it's a required metatag. 

So I can put an option within Mylar, but there will always be a volume tag within the metadata, just if this new option is enabled, the metadata for volume would be:
`<Volume>None</Volume>`

Otherwise I'd have to delve into the CT code to allow for the volume tag to be optional, and to be honest it's probably too much work atm just because I didn't write it. At some point I might try to add it, but atm I just don't have the time to manage this type of code change.
