### ISSUE TITLE
Annuals keep coming back

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1562]
In the main Star Wars series `ComicID=79398`, I have deleted the annuals section because I have them added as their own series.  The annuals keep coming back into the main series tihough, so I have to continually delete the section.  How can I fix this?

**Comment by DrSeussFreak** [comment]
FYI, I would use the main series to track the annuals, but in this case, for some reason, it keeps overwriting issues 1 and 2 of the main series with the annuals 1 and 2.

**Comment by evilhero** [comment]
They keep coming back because enabling annuals is a global option - if you have the option enabled, it will attempt to load up the annuals for each series on a refresh/add. Now if you're removing the annuals, they shouldn't be populating again, so I'm going to guess that that's a bug in relation to how annuals are purged from the db, but the values are retained to ensure they don't get re-added when it's automated.

As far as annuals 1 & 2 taking the place of issues 1 & 2, it's probably due to the filenames of the annuals. Can you post what they're named as so I can test it out on my local repo to see if I can duplicate the problem at hand ?

**Comment by DrSeussFreak** [comment]
So I name it "Star Wars Annual - 2016 - 1.cbz" but when I rename it via the series management, it becomes "Star Wars - 2016 - Annual 1.cbz".  When I go to download issue 1 of the main series, it downloads the Annual, rather than the issue 1 that exists (see screenshot)
![screen shot 2017-02-05 at 8 30 21 pm](https://cloud.githubusercontent.com/assets/175500/22632792/f25bb906-ebe1-11e6-82d7-90eef8756a9f.png)

**Comment by evilhero** [comment]
Well the parser is having problems with the way it's being renamed (it's ignoring the annual portion of the issue when it's in a series - year - annual # format). Now if you want it to be named as how you originally named it, then you're file format in the configuration is probably wrong - it should be something like "$Series $Annual - $Year - $Issue". The difference being that the $Annual field would be removed from the string if the issue isn't an annual, but if it is one than that's where it would be placed in context with the other variables.

You didn't actually say what you're intended naming scheme would be for annuals - whether 'Star Wars Annual - 2016 - 1' or 'Star Wars - 2016 - Annual 1'. Mylar should be able to parse either correctly, which it's obviously not so that's something that I'll have to address, but if  you kept your original naming scheme (before the renamer renamed it) it looks like it should pick it up just fine. Note that if it does pick it up fine, the original 1 would go into Archived status since Mylar can no longer find it - so you'd have to mark it as Skipped/Wanted and then do a ReCheck Files to ensure that everything is all lined up properly.

**Comment by DrSeussFreak** [comment]
So my primary naming convention is `$Series - $Year - $Issue`, I would want the annuals to be `$Series $Annual - $Year - $Issue`

Leaving the previous naming convention, it then finds the annuals to download rather than issues 1 or 2.  no explanation why

**Comment by DrSeussFreak** [comment]
Adding $Annual to the name string did the trick!
