### ISSUE TITLE
Extra Script After Snatch?

### ISSUE THREAD

**Issue by darknessgp** [evilhero/mylar#1572]
Not sure if there are already plans for this or what? I am a developer, so I don't mind picking this up as an item to add and do a pull request for.

But my thought is to add the ability to run an extra script after snatching a torrent or nzb item. Currently, I've ran into the issue where I have a remote server doing the real downloading and then I need a way to transfer the file into a local folder for handling by mylar. It makes the most sense for me to do a script after the snatch occurs. I do something similar in some other automated media managers.

**Comment by evilhero** [comment]
I've actually been working on something exactly like this for my own personal needs due to a similar setup. But it's actually integrated within Mylar, so that once a torrent is sent to the client the program will monitor the torrent until it's completed downloading (@30s intervals) - once it's completed and the script registers it as completed, it will initiate an lftp shell to snatch the torrent into a given directory (I send it to my mylar monitor folder) and then it can be post-processed as normal.

I haven't released it as part of Mylar as of yet for a few reasons:
- it uses multi-processing instead of threads so it fires up an additional instance of Mylar on startup that just 'listens' for post-processing requests
- the queue pool that is being currently used fails when it has to monitor more than 5 items at a time, so i need to rework the pool management portion so that it can handle more.

Right now I have it working with rutorrent, and almost finished for use with deluge.

The idea of a post-process on snatch tho is an interesting notion - which obviously has merits (since I  basically started with that). I did my 'on snatch' call within the search.py module right after line 2185 where it calls the rcheck. I think it would be pretty easy to call an extra script after snatch right there as well (ie. after confirmation is received that the client has received the file).

**Comment by darknessgp** [comment]
I see. That sounds similar to an issue I had ran into. For sonarr, I utilize their stuff to do a post snatch event to download my stuff. I wrote a nodejs app (https://github.com/darknessgp/TorrentEcho) that is basically a HTTP listener for a post request of a label to download then in its configuration it connects to rutorrent and downloads via lftp everything with that label to a certain local folder... it seems to work well for me there, and I handle incomplete downloads by re-checking every 15 seconds. Node being js based, I'm able to just utilize the setTimeout to re-check, it seems to not use too much resources. But I haven't indepth looked at it

That said, I love the idea of something built-in to mylar. but I also know requiring lftp would be a pain for windows users.
