### ISSUE TITLE
Skip SSL cert validation in Sabnzbd post-processing

### ISSUE THREAD

**Issue by mrgstiffler** [evilhero/mylar#1573]
I might be completely missing this but I don't see a way for the post-processing script to skip validating the cert when it connects to back to Mylar. Yes, not exactly the best practice but still would be nice.

Here's the error that Sabnzbd shows:
Unable to open URL:  [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by evilhero** [comment]
I actually believe that's handled by sab and the addurl reference, not by Mylar itself. 

I mean, mylar is running as an https instance in your case - it submits a request to sab to download the nzb (which is stored in the cache directory of Mylar so it has to use the addurl to snatch it, instead of re-downloading it again), and the request url it's submitting is the https via the addurl command within sab. So the initiating request to snatch the nzb from mylar's cache is coming from sabnzbd - I'm not sure how you can set it to not verify via the addurl option within sabnzbd to be honest. As far as I know, there's no way to either verify/not verify the addurl request, it just defaults to verify if it's https.

**Comment by denics** [comment]
sorry to revive this, but I am having a similar behavior, latest Mylar, latest Sabnzbd and: 
``The client sent a plain HTTP request, but this server only speaks HTTPS on this port.`` 
This message on SabNzbd without being able of downloading or better, the issue get downloaded but not in the right folder and Sabnzbd gives me this: 

```
Name xxxxxxxxxxxxxxxxxx
Completed a few seconds ago
Status Failed
Size 123 MB
Category comic
Path /home/pi/Comics/xxxx - xxxxxxxxxx
Source https://localhost:8090/api?apikey=zzzzzzzzzzzz&cmd=downloadNZB&nzbname=xxxxx.nzb
Download Downloaded in 5 seconds at an average of 6.9 MB/s
Age: 2712d
1 articles were missing
Servers -------=35.8 MB
Repair [xxxxxx] No par2 sets
Script Exit(1) The client sent a plain HTTP request, but this server only speaks HTTPS on this port. (More)
```

what am I doing wrong? both Sabnzbd and Mylar are using HTTPS

**Comment by evilhero** [comment]
If you're using ComicRN - have you set the ssl=1 within the autoProcessComics.cfg file ? 

You could also just use Completed Download Handling and not worry about ComicRN scripts at all.

**Comment by denics** [comment]
Moved to nzbToMylar and now everythign is fine. However I had to move to basic authentication otherwise SSL does not work with SabNzbd. Thanks
