### ISSUE TITLE
Story arc all issues state skipped

### ISSUE THREAD

**Issue by phairplay** [evilhero/mylar#1576]
Hi,
I've just added civil war 2 and every issue is marked as skipped and I had to click grab on each one. How can I resolve this going forward?

**Comment by evilhero** [comment]
Yeah it might have something to do with a few commits ago where the default state for all issues that weren't in a downloaded/archived status on the watchlist would go into a Skipped status by default.

I believe if you do a 'Search for Missing' it would initiate the search for all issues that are in a Skipped status and mark them as Wanted during the process. If not, well it needs to get fixed so that you can mark the issues as Wanted (or else what's the point right?)

**Comment by phairplay** [comment]
Hitting search for missing doesn't change the status
