### ISSUE TITLE
comicinfo.xml not being added to .cbz

### ISSUE THREAD

**Issue by danfozzy** [evilhero/mylar#1581]
Running the current master release using docker (linuxserver.io image)

not sure if this is a issue with the linuxserver.io docker image that im running now instead of the synocommunity image on my synology Nas 415+ but i never had this issue previously.

after downloading using NZBget and using the comicRN script (which reports as working successfully) the comic is added to my library. There appears to be no problems until trying to view the comic info it pops up saying unable to extract the metadata from the file. When looking into the cbz file, comicinfo.xml is missing, even when the report that the metadata was successfully tagged to the comic report is in the log.

[mylar.log.1.txt](https://github.com/evilhero/mylar/files/801919/mylar.log.1.txt)
[mylar.log.txt](https://github.com/evilhero/mylar/files/801918/mylar.log.txt)
![2017-02-26](https://cloud.githubusercontent.com/assets/1420742/23339347/32864fc8-fc18-11e6-946a-7ca30c04ce35.png)

**Comment by evilhero** [comment]
Have you tried to enable the option in the config 'Overwrite existing cbz tags if they exist'? 

Either there is some kind of tag already present so it's not writing them, or because it's a cbz file and that option isn't enabled it's just ignoring tagging completely. 

Mylar hasn't actually written any metadata (it never fires off in the log), it just tried to do the cbr-cbz conversion and then just stops and tidies up - so it looks like if you were to enable the overwrite tags option things should work as expected. I'll need to look into why it's not even trying to tag the cbz file although I suspect it was by design since mylar doesn't actually check if tags exist, just by extension.

**Comment by danfozzy** [comment]
The only options I have for tagging in the post processing section is

Enable Metadata Tagging

Convert CBR to CBZ ONLY

Both of which are ticked.  I can't find any option to overwrite?

**Comment by evilhero** [comment]
Uncheck the convert cbr to cbz only. That does only exactly what it says - it only converts to cbz and does no metatagging. That explains why you're not actually getting metadata in the files ;)

**Comment by danfozzy** [comment]
Oops lol thanks for you time, all sorted
