### ISSUE TITLE
Sort by Have field sorting by first number not proportion of downloads

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#1583]
I have noticed now I have uploaded my comics folder to Mylar that when I sort by the Have field it sorts by the first digit only instead of the download proportion. For example, I would expect to see 0/X 1/X 2/X but am seeing 0/X 1/X 10/X 16/X 2/X
I would expect the have field to calculate the proportion of total issues and sort by that in ascending or descending order but that doesn't seem to be happening.
Any idea what might be causing that?

**Comment by evilhero** [comment]
There's a fix that just went into dev earlier today to address this. It actually sorts by the have, not the totals (well it's by the resulting % of have /total). 

Can you confirm what branch /commit you're running?

**Comment by rutskiuk** [comment]
Excellent, I'm running:
Mylar Version: master
-- source build 3fa3cfe032f0b567af34f902c3348da4f287222f.
I have been running the latest version available.

**Comment by evilhero** [comment]
I'll probably push it within the next day into master, I just need some confirmation that it's working as intended by some dev users prior.

**Comment by mcaron1234** [comment]
I can report that comics are sorting in the correct numerical order now.

**Comment by rutskiuk** [comment]
Hi,
I have just updated to the most recent master release but it still isn't sorting by the proportion of downloads. I am currently running:
Mylar Version: master
-- source build a825a8959aa042820777c3bbe2a0bb520f3d0d6c.

Right now if I sort by the have field I see the top 4 are:
1 42/58, 2 40/40, 3 35/35, 4 31/31 and 5 26/27, the correct order should be 1,5,2,3,4 (or 1,5,4,3,2 depending on whether completed series are in ascending or descending order)

Is this still work in progress?

**Comment by evilhero** [comment]
No its fixed. I'm not sure about the calcs you're using tho to determine it's out of place. 

It's a calc of the have total in relation to the total issues, so it takes the (have total + total issues) /1000 in order to get a value and sorts by that. The sequence you gave is correct for the calculations. It is also dependent on how you're doing your secondary sort (if you click on continuing /ended first and sort that, then by have you'll get different sequences than if you clicked on the series and then have. By default, mylar is set to sort by continuing /ended status, and then by series title.

**Comment by rutskiuk** [comment]
I would expect to see series sorted by proportion of completion. When sorting by Have it would be by percentage of completion (have total / total issues * 100) this, when sorted would leave the least complete at the top (or bottom if picking reverse order).
As I listed previously their corresponding percentage of completion are currently 1 42/58 (72.41%) 2 40/40 (100%) 3 35/35 (100%) 4 31/31 (100%) 5 26/27 (96.3%) that's why I put the alternative order.
The idea of this is to easily identify which series are missing issues, a large library may spread over multiple pages and the current sorting method arbitrarily separates them. I do see what you mean by saying they are in numerical order now however that only sorts by a number rather than representing the completion of the series.
I use a number of similar clients and this is the behaviour of Sickbeard/Sickrage which make managing a large TV library easy, I was hoping for a similar functionality from Mylar.

**Comment by evilhero** [comment]
The problem is that one person wants it one way, the other another and still another, yet another way. I can't appease all the folks with just one so k uti. I do see how you're looking at it, but I did initially use that some logic for the sort order and the orders was really messed up - I'm not sure if it was due to the numbers or just some inflated ones, but it really looked messed up. I'll look at this again and if I can create some kind of option to allow for this within the config.ini I'll try and add it in. Keep in mind that there wouldn't be a secondary sort on the same column, so the 40/40, 35/35, 31/31 would be sorted either by series titles or continuing/ended status (because data tables can't do secondary sorts on the primary sort column)

**Comment by rutskiuk** [comment]
Thank you for taking a look. 
I agree it's impossible to please everyone. I understand about the secondary sorts, I think once I knew which series were missing an issue I wouldn't be concerned about completed/up to date series. I have massively increased my usage of Mylar in the last 6 months because it's such a good tool and I want to get the most from it. 
I was even thinking is it possible to have that column with 4 options which you could cycle through with a left click (total issues descending, total issues ascending, percentage completion descending, percentage completion ascending)? That might cover all bases but I have no idea how that would be displayed in the column header. I think for many people who use tools like this the purpose is to manage what they have and fill any gaps they find, this column is the key piece of information that does that. Thank you again.

**Comment by evilhero** [comment]
I have a fix coming that should make things right again - when you choose to sort on the Have column, it sorts first by percentage, and then does a secondary sort of the total issues so that there is a sense of sequencing to things.  

I also adjusted some other things in order to clean up the display a little in the process (comicnames longer than 60 characters are truncated but hovering over the series title will display the full name). Basically in addition to the sort, all lines in the watchlist should fit on one line from that point forward.

**Comment by rutskiuk** [comment]
Thank you for the latest release :) 
Sorting now working exactly how I was hoping it would
