### ISSUE TITLE
Reading List and Story Arcs

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#1593]
Hi!
I've been seeing mention of Story Arc management and, of course, the Add To Reading List button.
Can someone point me to where I can learn about these?

THANKS!

**Comment by yongbi85** [comment]
I don't think you can learn about it anywhere, we are lacking a wiki and i must admit i could also participate so i won't blame anyone for this.
But i can tell you where you can find those. In the manage menu in the advanced options you got Story Arc Management and Reading List Management

**Comment by evilhero** [comment]
The best place to learn is to search the forums - there's lots of information scattered around in regards to it, but unfortunately not in one place (aka a wiki). 

Otherwise, add an arc via the arc management screen, and go from there (don't use the add cbl option if you still have one, it's outdated and will be removed in the next little while). 

Just shout back in here with any questions and I'll answer them as best as I can ;)

**Comment by thewindupboy** [comment]
OK, figured out Story Arc management.  Is there an available list of arcs?
I'm a little confused, however, as to what Reading List actually does.

**Comment by thewindupboy** [comment]
(Also, Story Arc Management makes me VERY happy!)

**Comment by evilhero** [comment]
The reading list management screen is just a way to track at a quick glance what you've read already, what you intend to read, and what you have yet to read. The idea being that you can be on a series page, click on the reading glasses and the given issue will be added to your reading list in a status of 'Added'. Once it's on your reading list, you can then queue it up to send to a 3rd party device - currently only android is supported, and it has to be done via an sftp server on the android, but if it's setup Mylar will send your entire reading list that you have 'inqueue' to the device and then mark those issues on your reading list as 'downloaded'. Then once you're done, just mark them as 'Read'.

You can send any newly post-processed items that are on the weekly pull-list automatically to your readlist if you have that option enabled as well so that 'new' issues can be in queue automatically to be read.

It's not a complete solution by any means, but it does allow you to transfer batch files to your device (again, android only), and it also allows you to download individual issues to your device if you're viewing mylar from the device.
