### ISSUE TITLE
Renaming Comics with alphanumeric characters not working (MU, INH, ...)

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1598]
Mylar Version: master
-- git build 3fa3cfe.
Python Version : 2.7.13

Whenever i try to rename some comic with MU, INH etc. in it i would get an error on the renaming and the following message in debug

Timestamp	Level	Message
2017-03-20 21:51:51	DEBUG	ALPHANUMERIC EXCEPTION : [INH]
2017-03-20 21:51:51	DEBUG	issueid is now : 442923
2017-03-20 21:51:51	DEBUG	annualize is None
2017-03-20 21:51:51	DEBUG	issueid:None
2017-03-20 21:51:51	DEBUG	issue#: 20.INH
2017-03-20 21:51:51	DEBUG	comicid: 53725

Nothing else written in the log, it just stops there and doesn't rename.

Also when i use the post processing, it successfully renames the file correctly (tested with a 001.MU issue i snatched through mylar), it only appears when doing manual renaming or import.

**Comment by unclenospam** [comment]
Getting this as well right now with alphanumeric comics + annuals.

I now get the error: "ERROR	Invalid Issue_Number - please validate."

git build 32134e796e267cf7aa3004abe4626e4fd61c644a

**Comment by evilhero** [comment]
@unclenospam : the patch was to fix the problem in relation to import and manual renaming. 

What are you trying to do when the error occurs (post-processing with sab, manual post-processing, importing, renaming, etc) and please show the debug log leading up to the error so that I know what's happening from a coding side.

**Comment by unclenospam** [comment]
@evilhero here's what happens:
I have imported all titles successfully into the Mylar library. Issues that have alphanumeric numbering and annuals both show up fine in Mylar's database.

I have turned on auto renaming and have also been using manual renaming for Mylar.

My renaming settings if it matters are: Folder: $Publisher/$Series ($Year) | File: $Series $Annual $VolumeY $Issue ($monthname $Year) -- I was originally trying it without $Annual in File settings.

Specifically when I try to manually rename either an alphanumeric or annual book, I get the error message in Logs.

If I use the manual rename tool for titles that dont have these within the folder, then they all rename correctly. If one of these files is within a folder I'm trying to mass-rename, then it will only rename up to that file and then error out the same way.

Here's what's happening when I click "rename" when there's an annual
2017-04-07 10:29:44	INFO	[FOLDER-CHECK] Checking folder /downloads for newly snatched downloads
2017-04-07 10:28:51	ERROR	Invalid Issue_Number - please validate.
2017-04-07 10:28:51	DEBUG	annualize is yes
2017-04-07 10:28:51	DEBUG	issueid:None
2017-04-07 10:28:51	DEBUG	issue#: 2
2017-04-07 10:28:51	DEBUG	comicid: 53508
2017-04-07 10:28:51	DEBUG	os.path.basename: Action Comics Annual (2012)
2017-04-07 10:28:51	DEBUG	dir: /comics/DC Comics/Action Comics Annual (2012)
2017-04-07 10:28:51	DEBUG	multiple_dest_dirs:

Here's what happens when I click "rename" when there's an alphanumeric file in the folder (I cleared the log right before doing this to make sure this is all it was giving me):
2017-04-07 10:36:52	INFO	delaying thread for 60 seconds to avoid locks.
2017-04-07 10:36:51	INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads
2017-04-07 10:36:51	WARNING	There were no files located - check the debugging logs if you think this is in error.
2017-04-07 10:36:51	INFO	there are 0 files.
2017-04-07 10:36:51	INFO	[FOLDER-CHECK] Checking folder /downloads for newly snatched downloads
2017-04-07 10:36:28	INFO	Not renaming Avengers V2016 004 (April 2017).cbz as it is in desired format already.
2017-04-07 10:36:28	INFO	Not renaming Avengers V2016 001 (January 2017).cbz as it is in desired format already.
2017-04-07 10:36:28	INFO	Not renaming Avengers V2016 003.1 (March 2017).cbz as it is in desired format already.
2017-04-07 10:36:19	INFO	Web logs cleared

So here, for some reason, even with Debug turned on,  it's like it comes across the 1MU file and then stops completely, not even mentioning it in the Logs. There are supposed to be 12 total files in this directory.. If I remove the file with "1MU" from the directory temporarily and then try to rename, it sees  and renames all of the files without issue.

Thanks! If there's anything else I can provide to help out let me know please.

**Comment by evilhero** [comment]
K, I checked more into this and it looks like there were some problems with how it was handling annuals when annuals_enabled was turned off. The alphanumerics was a miscode error (I forgot to save the variable when it was testing to see if it existed) - so I got that working as shown in here in a fake mockup file:
```
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : ALPHANUMERIC EXCEPTION : [MU]
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : character space denoted as : .
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : issue_except denoted as : .MU
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : iss:1
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : issueno:1
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Zero Suppression set to : 00x
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : issue detected less than 10
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Zero level supplement set to 00x. Issue will be set as : 001.MU
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Pretty Comic Issue is : 001.MU
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Issue Year : 2017
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Publisher: Marvel
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Series: Avengers
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Year: 2016
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : Comic Location: /Comics/Avengers-(2016)
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : not an annual - removing from filename paramaters
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : new format: $Series $VolumeY $Issue ($monthname $Year)
08-Apr-2017 19:03:37 - DEBUG   :: CP Server Thread-4 : New Filename: Avengers V2016 001.MU (March 2017).cbz
```
I also think I fixed the annual problem as well that was occuring - I'll be pushing this out in the next day or so (I need to clean up abunch of things within this commit cause it's a big one), so hopefully when it goes into dev it'll get tested, reported on and then I can push into master ;)
