### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by Evoley** [evilhero/mylar#1599]
Turned debug logging on while scanning my comics and got the following error. Only happens when doing a scan. There's nothing in the actual debug log about it so it might be a python error. This has happened before but I just brushed it off thinking it's not really important.

WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file filechecker.py, line 343
21-Mar-2017 07:29:38 - DEBUG :: LibraryScan : date: 1985
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)

**Comment by evilhero** [comment]
Yeah that's the python logger having problems rolling over the log files into new ones. Only happens on windows machines due to the locking of the files - it's a know python issue but only happens when things fire into the logger at the same time (mylar still works, but the logging doesn't after that error). 

The 'fix' if you will is to install the concurrent log handler - do this by going to a command line and typing ```pip install ConcurrentLogHandler``` (note that you need to have pip installed but it comes with most versions of python I believe). 

Once it's installed mylar will auto-detect that it's installed and use it for logging and rotatin -  You'll also see a message in the logs indicating the it's using it.
