### ISSUE TITLE
Weekly Directory

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1601]
I'm not sure if this is a bug or if it's working completely as you intended, but I was wondering why the comics go both into their normal directories and the weekly directory when this option is selected.  

Also, I turned on the weekly directory option for this week, and Mylar has named the folder "2017-03-01" instead of the proper date or week number.

**Comment by evilhero** [comment]
Well the issues have to go to the series location so that it can monitor the status of the issues. The weekly directories are more for people that went a quick way to read the given week's comics. The intent is to eventually change over the copy to have it either copy / symlink / hardlink the issues into the weekly directory instead of just a copy.

The weekly directory folder only gets created when new issues are placed in it (ie. Downloaded status on the pullist). There's an option in the config.ini to alter the format of the weekly folder (weekfolder_format, setting it to 0 will put it in the format of 2017-10 (where 10 is the week#) , setting it to 1 will be in a 2017-03-22 type of format if I recall)

**Comment by andrewgribben** [comment]
I'm having this issue too. Despite having weekfolder_format set to 0. I can click download on my pullist page to copy to the correctly weekly directly which is fine but automatically in the background it has already added the books to another folder with the name 2017-02-22 (same folder each week)

`[WEEKLY-PULL COPY] Sucessfully copied to /share/Drobo/Comics/2017-02-22/Teen Titans 6 (2017).cbr
2017-03-23 08:54:19	INFO	[WEEKLY-PULL COPY][DIRECTORY-CHECK] Creating comic directory (0777) : /share/Drobo/Comics/2017-02-22
2017-03-23 08:54:19	WARNING	[WEEKLY-PULL COPY][DIRECTORY-CHECK] Could not find comic directory: /share/Drobo/Comics/2017-02-22`

**Comment by andrewgribben** [comment]
Should weekfolder also be set to 0 and a path set?

`weekfolder = 1
weekfolder_loc = ""
weekfolder_format = 0`

**Comment by evilhero** [comment]
weekfolder is the actual enable / disable toggle, but just in boolean (0 = off, 1 = on)

So you want weekfolder enabled (set to 1), the weekfolder_format I had explained above (no need to retype), and the weekfolder_loc you can manually specify a full directory location path where the weekly sub-folders will be created beneath. Leaving it blank will create the weekly directoriers underneath your Comic Location root path.

Are you using the alt_pull = 2 method, or is it at the default of alt_pull = 0 ?

**Comment by wraith1385** [comment]
I'm using alt_pull = 2 and I have essentially the same issue that andrewgribben is having.  I actually don't really care which format is used, but this current week it threw everything in a folder named 2017-03-01, and in the past when I've tried using it before, it continues to download everything to the same folder every week instead of creating a new weekly folder.

**Comment by andrewgribben** [comment]
@wraith1385 That's exactly what I'm experiencing, just with a different folder name. I *think* that was the date of the first time I had used the weekly pull list feature.

Just to confirm
weekfolder = 1
weekfolder-format = 0
weekfolder_loc = ""
alt_pull = 2

Mylar triggers my download, scans the watch firetory, renames and sorts the files and automatically copies them to a folder named "2017-03-22" inside my Comics directory. This location wasn't set by me, but week by weeks the books are copied to it. On the other hand clicking the Download button under "This Week" triggers the expected behaviour, creating a folder eg 2017-12 this week and copying my new downloads to it.

**Comment by evilhero** [comment]
Ahh ok, that's the difference - the post-processing was using a different method to determine the pull-list date (so it would default to yyyy-mm-dd), but the default of weekfolder_format of 0 sets it to yyyy-weeknumber.  The download button on the pullist abides by this, but the post-processing would be doing something entirely different with the dates.

I'm looking at this now, so hopefully can get a fix out soon for you guys...
