### ISSUE TITLE
 'nzbid' referenced before assignment

### ISSUE THREAD

**Issue by gsemet** [evilhero/mylar#1603]
Here is an error I see in the logs:
```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/webserve.py", line 1280, in retryissue
sendit = search.searcher(fullprov, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True, newznab=newznabinfo)
File "/app/mylar/mylar/search.py", line 1970, in searcher
nzbid = generate_id(nzbprov, link)
File "/app/mylar/mylar/search.py", line 2635, in generate_id
return nzbid
UnboundLocalError: local variable 'nzbid' referenced before assignment
```

Seems to happen when a Newznab respond "spam" or does not return the nzb file.

**Comment by evilhero** [comment]
It looks like a provider you're using is giving back an link to the nzb in a format Mylar can't understand (it parses the link in order to get the details for usage). 

What's the provider that you're using that is encountering that error - or even better, do you have a debug log showing the leadup to that error, as it will provide a heap of information related to the problem.
