### ISSUE TITLE
Metatagging issue with ascii characters

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1613]
Mylar Version: master
-- git build 32134e7.
Python Version : 2.7.13

OS : Synology 5.2

2017-04-02 14:37:26	DEBUG	[MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
2017-04-02 14:37:26	WARNING	[META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /usr/local/mylar/var/cache and/or the location where Mylar is trying to tag the files from.
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Absolute path to script: /usr/local/mylar/env/bin/python
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Executing command: ['/usr/local/mylar/env/bin/python', '/usr/local/mylar/share/mylar/comictagger.py', '-e', '--delete-rar', u'/usr/local/mylar/var/cache/mylar_8BIvj9/Fantastic Four v3 \xbd (1998).cbr']
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Enabling ComicTagger script: ['/usr/local/mylar/env/bin/python', '/usr/local/mylar/share/mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/usr/local/mylar/var/cache/mylar_8BIvj9/Fantastic Four v3 \xbd (1998).cbr']
2017-04-02 14:37:26	DEBUG	[META-TAGGER] CR Tagging enabled.

Also this is how the name shows if i connect in ssh and look into the cache folder of mylar

mylar_77UWu_/Fantastic Four v3 Â½ (1998).cbr

And in the original comic folder

-rwxrwxrwx 1 admin users 10414557 Apr 2 14:35 Fantastic Four v3 Â½ (1998).cbr

But on windows samba share it does shows like Fantastic Four v3 ½ (1998).cbr

There is no permission issue by the way, everything is admin:users and mylar is run by admin user and all the other comics are successfully metatagged.

**Comment by evilhero** [comment]
This looks like a localized issue - I just mocked up a fake file with that exact filename, ran post-processing against it and even tried manual meta-tagging, and both came back with zero errors and tagged successfully. 

Probably the tell-tale sign is that your shell isn't set up to support utf-8 characters (the Â denotes a problem character and just a general representation of some kind usually). Normally this has to do with what your locale is set to for your shell environment, because mylar submits it to the comictagger program via your shell - even though it's a python program, it's still all command line paramaters being passed.

Try running just 'locale' from the command line and seeing what it outputs. LC_ALL should probably be set to some sort of UTF-8 coding.

**Comment by yongbi85** [comment]
This is the result of the command so it seems to be UTF-8... i don't get it

HPPROLIANT> locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

**Comment by evilhero** [comment]
What are the files in the cache directory that it gives... Just cbr or cbr /cbz? I'm wondering if it's something to do with the delete option for comictagger

**Comment by yongbi85** [comment]
It seems to depend but it also impacts unrar it seems.
I have a comic named X-Men v1 000.5.cbr but inside the .cbr when i open it with winrar there is a folder named : X-Men ½ (1998) (digital) (Minutemen-Bluntman)
In that case the metatagging cant even unrar the file so i don't know where is the issue anymore... for now i just unrar them through windows, rename them and metatage them with name as 000.5 to avoid special characters.

**Comment by evilhero** [comment]
well ok, if it's within the rar file - that might be the more probably cause then - because comictagger hands off to your local unrar binary for extraction it might be not recognizing the encoding properly. I can definitely see something like that causing it to error - it's not the filename itself however, it's what's within the filename that's causing problems and erroring out the metatagger.

So now that I know where to look even deeper, I can ;)
