### ISSUE TITLE
When adding any comic it results in a 500 Internal Server Error

### ISSUE THREAD

**Issue by glassneedles** [evilhero/mylar#1617]
Just installed Mylar on a windows VM I have already successfully running sabnzb, sonarr and couchpotato and whenever I try to add a new comic (whether going through the this week section or searching it will take me to the comic details page but won't load any issues or the cover art. 

When I navigate away from this I get this error message and need to restart the service

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "c:\Mylar\lib\cherrypy\_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "c:\Mylar\lib\cherrypy\lib\encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Mylar\lib\cherrypy\_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Mylar\mylar\webserve.py", line 99, in comicDetails
    cskip = mylar.COMICSORT['SortOrder'][i]
KeyError: 0

I've checked my comicvine account and can see that it shows some requests so that part appears to be working. Please let me know if you need any further info.

**Comment by glassneedles** [comment]
Python version is 2.7.13 and CherryPy 3.2

I've just checked the logs and not seeing anything but heres everything in the logs in case it's useful

[log.txt](https://github.com/evilhero/mylar/files/910861/log.txt)

Here's a screenshot of the detail page, it never loads anything past this. I'm using the navigation links at the top to try and change page.
<img width="400" alt="screen shot 2017-04-10 at 18 10 44 copy" src="https://cloud.githubusercontent.com/assets/7456470/24873641/8ccb5a14-1e19-11e7-89d0-a2b09ad91a47.png">

**Comment by evilhero** [comment]
Don't use the nav links at the top maybe, click on the mylar logo in he upper left to return to the main page. 

It might be throwing that error out because you don't have any series in your watchlist yet to browse amongst (if so, it's a bug it should just never leave that page then). The error would stop the populating of the series so that might explain things possibly.

**Comment by galacticat** [comment]
I am seeing the same issue with the details.page, but periodically I will get the Error 500 just by loading the Web Interface. I. Running Python 2.7.12 and CherryPy 3.2 on an Ubuntu 16.04 headless server (It is a VM)

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Mylar/mylar/webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "/opt/Mylar/mylar/helpers.py", line 1354, in havetotals
    "ComicPublished":  re.sub('(N)', '', comic['ComicPublished']).strip(),
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by evilhero** [comment]
It sounds like you have a series on your watchlist that isn't able to complete the loading process properly - usually due to cv problems (api usage, being down, can't be reached, etc). 

When the 500 error hits again, shutdown mylar and view the logs to see what was the last thing that was being done. Odds are it's related to the series being added in some way, but without seeing logs it's hard to tell as everything is working normally. 

You are using your own cv apikey and not the one included with mylar correct?

**Comment by galacticat** [comment]
Yes, I am using my own API Key. It often happens after adding a new series so that makes sense, maybe it needs a catch when it can't communicate with comicvine, so that it just times out before the 500 error hits?

I'll get more details from the logs next time it happens.
