### ISSUE TITLE
Request: Add ability to determine trade volume by parsing ComicVine data.

### ISSUE THREAD

**Issue by CptanPanic** [evilhero/mylar#1618]
What I would like is if I had issue 8 of Descender it would know that it is part of TPB volume 2.

What comic vine calls a volume isn't what I think of a volume. For example if you get all the volumes of comic "Descender" you get 5 volumes. The regular monthly comic, the 3 TPBs and the reprint of the first issue.  There is no straight forward way to do this with comic vine, but you can do this by going through all the above volumes and reading what issues the TPB collects. What do you think?  

I can look at working on this, and making a pull request.

**Comment by evilhero** [comment]
I honestly don't see the benefit to mylar atm - especially considering that mylar doesn't work with tpb's. 

It'd be nice 'I wonder if this could work' kinda thing I think, but CV has no rhyme or reason behind some of its volume separation in some cases, and there's also no absolute way to find which issues are in each tpb as CV doesn't track that information at all (it kinda does in the description but it's not reliably populated and the terminology is all over the board)...

**Comment by kingfenix** [comment]
the benefit would be to see if you are adding one or not and to enhance working with storyarcs in your collection.


________________________________

**Comment by evilhero** [comment]
That's what I'm trying to say - CV doesn't properly track tpb's and mylar cant scan them.. So having one in your collection, mylar wouldn't be be to tell if it's within tpb1 or tpb2, because there's no information presented on cv to gather that data. Parsing the text. And even if there was mylar cant parse filenames with no issue #, so it wouldn't be on a watchlist and so it couldn't verify the numbers. 

I get what you guys are saying about tpb's, but until mylar can scan in tpb's there's no way it could do the rest of the request reliabily. Once the scanning happens, then sure the request would be easier to accommodate and implement. 

@kingfenix: you can add / remove issues from arcs in the dev branch - so you could remove a tpb if it exists (cause cv sucks and they do that), and replace it with actual issue numbers and it'll get picked up properly ;)
