### ISSUE TITLE
Mylar marking unreleased comics as wanted

### ISSUE THREAD

**Issue by rutskiuk** [evilhero/mylar#1625]
Hi there,

I have noticed that Mylar is listing comics as wanted that haven't been released yet. I would expect Mylar to mark them as wanted from the release date onwards, not before. If it's marking as wanted before the release that would trigger searches from your usenet indexer that will not produce results.

For example:

![image](https://cloud.githubusercontent.com/assets/25068977/25316402/bb4bb4a2-285e-11e7-9024-1a7a06e66ba9.png)

When I select this comic I see it hasn't been released yet:

![image](https://cloud.githubusercontent.com/assets/25068977/25316413/d9ff14b6-285e-11e7-9428-3d14936ab291.png)

Mylar Version: master
-- source build 32134e796e267cf7aa3004abe4626e4fd61c644a.
Python Version : 2.7.11

Many thanks in advance

**Comment by evilhero** [comment]
What you're seeing in the date column is the publication date, not the store date. Publication date is always after the store date, the store date being the date the issues are available in the stores. 

It marks issues correctly, as it's basing the marking of the issues as being Wanted using the store dates (which for those issues the store dates were around Apr 11, 2017)

**Comment by rutskiuk** [comment]
Thank you for getting back to me. I've had a look at your reply a few times and have tried to follow what you're saying. There are two dates, publication and in store dates and the wanted status is triggered by the store dates not the publication date. If that's the case why does the publication date show? Which date is the trigger for the search request with the indexer? I'm sorry for asking basic questions.

**Comment by evilhero** [comment]
The publication dates are the normal dating method used by the comic industry to indicate the issue publication date. In the 'old days', the publication date was the shelf life of the issue - basically the date the newstands had to sell the issues by or ship back the remainder to the publishers. Publication dates are just, I guess, the industry standard for issue dates. 

Of course that doesn't help with mylar, as it needs to know when the issue is actually available - thus the use of the store dates. Unfortunately alot of older issues dont have this information available, and in those particular cases mylar will attempt to use the publication date.

The store dates are what triggers things in mylar, but when that's not available it uses the publication dates (even some newer issues on CV have incorrect dates). 

If you want to see both - if you go to the Manage tab / Manage Issues option and then pick a status to view, the results will display both the publication dates and issue dates for the issues listed.
