### ISSUE TITLE
Move week span from Wednesday to Wednesday?

### ISSUE THREAD

**Issue by galacticat** [evilhero/mylar#1634]
So I recently learned that ComicVine doesn't update their comics until the day before release. In the US this is Wednesday. To prevent scraping ComicVine for issues that don't exist yet, couldn't the Start and End date by dynamically set?

This would be for the purpose of generating the pull list.

**Comment by evilhero** [comment]
Mylar doesn't generate the pullist using cv ;) It uses external resources and then either every 24hrs checks against cv for new issue data for watchlisted matches on the pullist (alt_pull = 0), or retrieves the pullist from another site (alt_pull = 2) every 4 hrs, which already has the cv information within it along with other information that makes matching lot easier. 

Starting /stopping dynamically would have no impact on mylar since the new pulls are available on every sun (alt_pull =2 can go +4 weeks in the future as well so they're available prior to that). But it would introduce a whole slew of additional problems with the backend (especially on alt_pull =2),since it uses the dates as starting points for various things.

**Comment by galacticat** [comment]
Thanks!, That seems to resolve several issues I have been having getting data from the cv api. I do still notice that only my current weekly pull list is populated. Future and Past list are always blank, but the issues I am watching still show up in my Wanted list.

**Comment by evilhero** [comment]
It takes a few seconds sometimes for each week to populate when you browse to it initially as it has to poll the data from the site. 

Also make sure your filter bar is completely empty (as if it's not it will only display the a filtered view). 

Try restarting mylar and then once it's finished it startup sequence, do a recreate pullist from the weekly tab so or regenerates everything.

**Comment by galacticat** [comment]
Did this for Week 18, but when I check the debug logs I am only seeing a log entries for Week 19
Logs: https://pastebin.com/XenapPXs

**Comment by galacticat** [comment]
I figured it out. It was resetting to 'alt_pull = 0' because the Systemd service was not fully stopping the mylar service when I went to do my edits. I stopped the service, made the changes, and restarted and now it is populating. Thanks for your help!

**Comment by galacticat** [comment]
Issue was resolved by the following:

1. Stop the mylar service.
2. Update config.ini entry alt_pull=0 to alt_pull=2
3. Restart mylar service.
