### ISSUE TITLE
Dognzb not showing as a valid search provider

### ISSUE THREAD

**Issue by TheBigZig** [evilhero/mylar#1635]
I'm having issues with Dognzb as a search provider.  I have it selected, and have the correct API key in, but when I attempt a manual search, I get the following in my logs:
2017-05-13 22:10:41	ERROR	[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.
2017-05-13 22:10:41	INFO	Issue Title given as : None
2017-05-13 22:10:41	INFO	[SEARCH] Special Characters exist within Series Title. Enabling search-safe Name : American Gods Shadows
This Dognzb API key is working with SickRage and CouchPotato, but Mylar isn't happy with it.  Any thoughts?
Thanks
Bill

**Comment by evilhero** [comment]
When you make a provider change of any kind and save the config you need to restart mylar for the changes to take effect. This is because it generates the provider search order on startup only, so changing it and not restarting gets mylar confused about what is enabled /disabled and what order a provider is to be in. 

Quick fix: shutdown mylar and edit the config.ini. Find the line that says provider_order and delete the entire line. Save the config.ini and then start mylar and your providers will be back in sequence again.

**Comment by TheBigZig** [comment]
Worked perfectly!!! Thanks for the quick reply!  I'm a HUGE Mylar fan, and the quick support just seals the deal.
Bill
