### ISSUE TITLE
Mylar not moving files to directory

### ISSUE THREAD

**Issue by dogwoodfire** [evilhero/mylar#1638]
Once a file has been snatched, it is not moved to my designated Comics directory, it's just marked as 'Snatched' in Mylar.  I checked the logs, and saw the following, so I think it is trying to find the files:

`INFO	[FOLDER-CHECK] Finished checking for newly snatched downloads`

There are files that have been downloaded a few months ago in the watch directory that have not been moved across, so I do not think this is a refresh-time based issue, and the 'Folder location to monitor' is correct in the settings.  This worked fine up until a few month ago, is there anything I need to update to get this working again?

Thanks for your help!

**Comment by barbequesauce** [comment]
You may also want to check permissioning on both the watched directory or the designated comics directory... that bit me recently.

**Comment by dogwoodfire** [comment]
Thanks both!

Barbequesauce - checked permissions, and everything seemed fine

evilhero - It was set to 'move', tried changing to 'copy', but no difference.  The logs haven't updated since yesterday, is there anything specific you need from the on-screen log pages?

I did see one WARNING error:
`2017-05-17 14:09:55	WARNING	Error fetching data from ComicVine: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`
...and I noticed that the search for new comics isn't working correctly.  Is that related?

**Comment by evilhero** [comment]
Well the handshake error indicates that your python isn't up to spec - Mylar requires a minimum of 2.7.9 as it's needed for ssl certificate verification. ComicVine just recently switched to an https-only site, so verification of the certificate has to happen now with every request. Normally this error happens in two cases: 
1) the python version isn't at least the required 2.7.9
2) some dependencies for verification are missing from the installation (pyopenssl not being the right version, openssl, some other things etc). If the python is up to spec, than normally this 2nd step can be accomplished by simply doing a 'pip install requests[cryptography]' from a command line and that will upgrade all the necessary items required for certificate validation.

The certificate verification happens for all ssl-related sites normally (you can turn off some verification as required within Mylar for specific providers), so it could be very well related to the items. Also, if you have notification setup to notify on snatch, if it's unable to send a notification it will stop the updating process entirely and the issue will remain in a snatched status.

Other than that, as far as the folder monitor not processing, which it should be - I'd need to see the actual debug logs to troubleshoot as it could be any number of things ( like @barbequesauce mentioned permissions will mess this up ).

**Comment by dogwoodfire** [comment]
Thanks for that, updated to newest 2.7 Python, search isn't working, but it's doing something else now, so that's cool, will play around a bit with it.

Here's the logs after the most recent monitoring -
https://pastebin.com/RC9Q3fxY

**Comment by evilhero** [comment]
It looks like everything is fine in the log - it's checking your folder that's being monitored for new releases and either they're coming back as being in an already downloaded status and the issue you have in the series directory is a higher filesize (because you have filesize priority being used), or the series are already completed (which means it's in an Ended status and you have 100% of the files). Since it won't post-process issues that don't have a matching series on your watchlist (which might be the only  other option I can see atm that might be happening), everything looks fine.

Unless I'm missing something in the logs and you see something happening on your end that's making you question how things are working? If you wanted to make sure things were post-processing and cleaning up (in a manner of speaking), you can enable the duplication dump folder option which will move any items that it deems as a duplicate during post-processing into the dump folder location. It will move it either from the series directory, or from the folder monitor directory so that you can view things prior to deleting them (if they are indeed duplicates).

**Comment by dogwoodfire** [comment]
I tried changing the folder permissions again through command prompt, and that fixed it this time. Sorry for wasting your time, and thanks again for all the help!!
