### ISSUE TITLE
Uncaught exception: Traceback (most recent call last): File "/opt/mylar/mylar/logger.py", line 158, in new_run

### ISSUE THREAD

**Issue by ProtoJazz** [evilhero/mylar#1640]
```
Uncaught exception: Traceback (most recent call last):
File "/opt/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, self.__kwargs)
File "/opt/mylar/mylar/webserve.py", line 1460, in queueissue
foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)
File "/opt/mylar/mylar/search.py", line 260, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs)
File "/opt/mylar/mylar/search.py", line 554, in NZB_SEARCH
a = auth32p.info32p(searchterm=searchterm)
File "/opt/mylar/mylar/auth32p.py", line 37, in init
if not lses.login():
File "/opt/mylar/mylar/auth32p.py", line 581, in login
if (self.test_login()):
File "/opt/mylar/mylar/auth32p.py", line 552, in test_login
if (self.valid_login_attempt(self.un, self.pw)):
File "/opt/mylar/mylar/auth32p.py", line 499, in valid_login_attempt
logger.debug(self.module + " Request URL: %s \n Content: %s \n History: %s \n Json: %s", r.url ,r.text, r.history, d)
UnboundLocalError: local variable 'd' referenced before assignment
```

I get this any time I try to search for anything. My install was recently updated and Im trying to get things working again.

**Comment by evilhero** [comment]
Well the error is calling an invalid variable - so that's one problem (which I'll fix right now). But the main thing is that you're not properly authenticating against 32p for some reason. It could be that your login/pass is invalid, or you've hit the 6 attempts and have to wait it out, or your session cookie is old and needs to be recreated (usually this last one can be fixed by just deleting the .32p_cookies.dat file in the mylar cache folder with Mylar not running and then when it restarts it will attempt a clean logon). Once you're able to authenticate, you won't get the error any longer as it will only try to trigger the log of it when it gets an invalid status code response from 32p.

ATM you can't do the test connection without first saving the configuration so the new values can be loaded properly (probably best to do a restart of Mylar as well). I'm working on getting it to take the current values do a test before you save the values (cause that makes more sense obviously), but it's not there yet.

**Comment by ProtoJazz** [comment]
Ah, yeah ive definitely hit more than 6 attempts. Ill let it sit till I get back from work.  Thanks

**Comment by btxgit** [comment]
In case you didn't catch both of the errors:

diff --git a/mylar/auth32p.py b/mylar/auth32p.py
index 22a94a9..bb0e0dd 100644
--- a/mylar/auth32p.py
+++ b/mylar/auth32p.py
@@ -490,7 +490,7 @@ class info32p(object):

             if r.status_code != 200:
                 logger.warn(self.module + " Got bad status code from login POST: %d\n%s\n%s", r.status_code, r.text, r.headers)
-                logger.debug(self.module + " Request URL: %s \n Content: %s \n History: %s \n Json: %s", r.url ,r.text, r.history, d)
+                logger.debug(self.module + " Request URL: %s \n Content: %s \n History: %s \n", r.url ,r.text, r.history)
                 self.error = {'status':'Bad Status code', 'message':(r.status_code, r.text, r.headers)}
                 return False

@@ -498,7 +498,7 @@ class info32p(object):
                 logger.debug(self.module + ' Trying to analyze login JSON reply from 32P: %s', r.text)
                 d = r.json()
             except:
-                logger.debug(self.module + " Request URL: %s \n Content: %s \n History: %s \n Json: %s", r.url ,r.text, r.history, d)
+                logger.debug(self.module + " Request URL: %s \n Content: %s \n History: %s \n", r.url ,r.text, r.history)
                 logger.error(self.module + " The data returned by the login page was not JSON: %s", r.text)
                 self.error = {'status':'JSON not returned', 'message':r.text}
                 return False

**Comment by evilhero** [comment]
Yep i got both initially but forgot to push it last night - thanks as always @btxgit for the helpful diff and the reminder ;) 

@ProtoJazz Everything should now be fixed in the latest dev commit in regards to the logging error - not sure if you're still experiencing logon problems however.

**Comment by ProtoJazz** [comment]
All seems fixed, thanks!
