### ISSUE TITLE
Going back to Home Page and 0 search Providers

### ISSUE THREAD

**Issue by aerorush91** [evilhero/mylar#1649]
Hi there,

I am running into an issue now where in mylar I search for a comic. and I click on "Add this Comic" instead of going to the comic description page it goes back to the mylar home page. It takes about 3 times before it finally goes to the description page. I am not sure if this is a bug issue or something I am not running in mylar correctly?

Also it is now giving me a warning that I have 0 search providers enabled when I do Dognzb is check marked. This wasn't an issue prior to the manual search issue with NZBget.

**Comment by evilhero** [comment]
Whenever you make a provider change, you need to save the config and restart mylar so it can load in the proper values. This is due to how mylar generates the provider order, which is done on startup only. So if you change a provider and mylar doesn't have an up to date provider order sequence, it throws the '0 provider' error to indicate it can't search properly. This is a long outstanding issue that I hope to fix soon, but it requires a pretty big code change across several modules. 

The add comic issue, I believe this has happened in the past to series that cv has listed as 0 issues. 

Also, even if it goes back to the main page, it should still be adding/loading the series in the background - you'd just have to refresh the main page to see the listing for it. 

Do you know the series you were trying to add in which it did this? The series /year /comicid is what I would need. 

Also which branch of mylar are you running (master / development) and are you up to date on it?

**Comment by aerorush91** [comment]
On the provider issue I always check that it is marked so no biggie there.

It is pretty much any series I add it will go to home sometime if I open in a new tab it will go right to the comic description page but not always.  The last one it did it on was "Shipwrecked (2016) ComicID:94663".

I am also seeing another issue. Comics I am adding in to Mylar that have files in them mylar is showing the the issues in the series but when I access the folder files are missing. I check mylar and they are going from a downloaded state to archived. I recheck the comics in the series and they go back to wanted. Issues were there originally. It's like mylar is deleting them. Has this happened before or is there something not configured right with mylar or could this be a glitch

Mylar is pulling duplicates of the same issue when searching for it.
