### ISSUE TITLE
Pushover notifications not sending on snatch/post process

### ISSUE THREAD

**Issue by mcaron1234** [evilhero/mylar#1653]
For the last two weeks or so I have stopped getting pushover notifications when Mylar snatches. I only use Mylar for torrents (pretty much just 32P), and use the blackhole method with ru/rtorrent. I haven't changed any settings and notifications are enabled in settings. If I send a test notification it does work.  I saw the recent issue with telegram notifications and I wonder if this is related? My install of Mylar is on the dev channel, version 3d91a5e5214eb9043769767603fd15ab517b7bf7.

**Comment by evilhero** [comment]
The telegram notification problem was due to the code since it wasn't really tested fully prior to being implemented. 

Now, pushover hasn't been touched for a while, save for in the last few commits where the test connection button will take the screen data to test against as opposed to what's in the config file. Other than that, nothing should have changed. 

I'll have to load up pushover and see what's going on as I have a feeling it'll be a test / fix kinda thing ;)

**Comment by evilhero** [comment]
I just tested against a local watchdir snatch, as well as a direct send to client snatch and both notifications went thru using Pushover. The test notification button still uses the db settings however (meaning if you change a key/setting for pushover within Mylar and hit the Test Connection button, it won't take those values to test against, but what you have saved in the config.ini).

I'm not sure if an application key ever expires within Pushover, but you might want to ensure that you have the correct keys (although if test is working it's kinda a weird thing to not work).  Have you restarted Mylar recently as well?

If you could, if this is still an issue, provide the debug logs for a snatch showing the notification flow it might be helpful in figuring things out.

**Comment by mcaron1234** [comment]
Here is a log, I downloaded Winnebago Graveyard, and received no notification.  https://pastebin.com/UY8N90VF

**Comment by evilhero** [comment]
Ahhh ok you're getting the bencode error. That usually means you have a bencode.py (and bencode.pyc) file in the mylar/mylar directory. Shutdown mylar first, then check out the files in that location. If you see either/both, delete them and then start mylar back up and you won't get the error anymore and notifications will start again. You weren't getting notifications because the notifications happen after the torrent sending to the blackhole is finished, and the bencode is part of mylar getting the hash of the torrent for tracking ;)

**Comment by mcaron1234** [comment]
I found a bencode.pyc and deleted it per your instructions above, but I'm still not getting notifications.

Here is a new log:  https://pastebin.com/7D6bPg1A around line 1770 there is an error, that may be related.

Here is the output of ls -lhR /opt/Mylar/
https://pastebin.com/sBHQ1ptt
it does show two bencode files in /opt/Mylar/lib but I'm not sure if I should delete those?

(thanks for the support, btw)

**Comment by evilhero** [comment]
No those 2 in /lib are where they are supposed to be now. 

Try deleting all the .pyc files in the mylar subdirectory. I think the last fellow who had this problem said there was a rogue bencode.pyc being called from helpers.py (so deleting all the .pyc files would force python to recreate them on startup instead of use existing ones)

**Comment by mcaron1234** [comment]
I got the notifications working.  I stoped mylar, deleted all the .pyc files, and restarted mylar.  snatched an issue of Walking Dead, and no notification.  So I tried the best computer troubleshooting step of all time, turned it off and back on again, i.e. I disabled pushover, restarted mylar, enabled notifications, restarted mylar and boom, notifications working again. 

Thanks again for the support, above and beyond, especially considering what you charge for your time.
