### ISSUE TITLE
Comic not parsed, The invisibles vol 2 and 3

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#1655]
I have all 3 volumes of the invisibles by Grant Morrison. Vol 1 works just fine when importing.
all files are tagged correctly with comicvine info.

When i try to import the files from vol 2 and 3 (from two seperate dirs) i get a parsing error and the files are not post processed.
The files are named like this The Invisibles Volume Two #08 (September 1997).cbz
If i remove "Volume Two" the files parse and are added to mylar as downloaded.
All good. but now it gets exciting!
If I then use Mylar to rename files according to my settings $Series #$Issue ($monthname $Year) the files are renamed to The Invisibles Volume Two #08 (September 1997).cbz just like before, and mylar chokes and sets the status to archived. Somehow Mylar has a hard time when Volume is part of the file name.

**Comment by evilhero** [comment]
It's not so much that it's because it's part of the filename, but because it's part of the series title in this case. Mylar can handle volume formats in a varying number of ways (v1, v2016, vol.1, volume 2016, etc), but when it's indicated as it does in comicvine as being part of the series title (ie. The Invisibles Volume Two), which is incorrect as subsequent volumes have it denoted elsewhere other than the series title since the indica itself doesn't even indicate that the title is 'The Invisibles Volume Two', just 'The Invisibles' and only the 1st issue indicated it as being vol.2.

So yeah, it'll fail on this due to how CV has it - if CV were to change the series title to coincide with 90% of the rest of the series they have listed, it would just read as 'The Invisibles' and it being denoted as v2 elsewhere outside of the series title itself. This goes more towards CV using a standard across all series, instead of just adhoc'ing depending on whose updating the series (long-standing problem I and others have with them in this regards). I'll see if I can try to account for this, but when Mylar is expecting a volume to not be part of a series title as per normal usage, and then for the odd series it's included it's kinda difficult to get things to work the other way and vice-versa. I'll see what I can come up with tho.

Under the series details/ Edit Settings tab - If you were to change the Alternate File Naming to 'The Invisibles', and change the volume label to say 'v2',  Mylar would be able to parse that in that format easily (ie. The Invisibles v2 #8 (September 1997).cbz kinda thing). The Alternate File Naming is used to force Mylar to use whatever is provided in the field as the series title instead of what CV has, which helps with file-checking and post-processing when some series are mistakenly named on CV.

**Comment by Lasborg** [comment]
Found another one that is giving me problems

Preacher Special: Cassidy : Blood and Whiskey

Tried different search names and I tried making search name the same as the filename. Still no luck.

**Comment by evilhero** [comment]
If the file doesn't have an issue number in it, mylar won't be able to parse it - thus the lack of support for GN's and TPB's. This applies to searches too - no issue number in search result means its ignored. 

You'd have to download the file manually, put an issue number in the file (as if you look in mylar at the given series it would have an issue #) and then manually post-process it for it to work.

**Comment by Lasborg** [comment]
I have gotten it to work. It seems I need to get better at managing the alternate search name and alternative file-naming.
