### ISSUE TITLE
Comic not updating issues and marked as ended when should be continuing

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#1664]
Today I realized that several comics that I haven't read in a while was with a "Ended" status in the main page. I was suspicious about few and ran a manual refresh which found like 5 new issues and marked the comic as "Continuing". I have Mylar running 24x7 and is restarted daily.

I believe there are more comics in this situation. Should I run a "Force update active Comics"?

Any idea why this could be happening or how can i avoid it?

**Comment by evilhero** [comment]
Odds are the series weren't on a regular publication schedule (meaning every 30-50 days a new issue), so when the issue came out and another issue wasn't found in that time frame, it assumed the series was ended. I would guess that either the series was rebooted under the same ID, or some were published under a lesser known publisher (which usually means inconsistent release times). 

Mylar has to calculate if a series is ended vs not as CV doesn't populate this information at all.

Force update will update all your series that are in an active state. It will also try to do them in sequence until they're all done which might killer your cv api hits depending on how big your watchlist is. I have something going into git today / tomorrow hopefully where it will update up to 12/series an hr on the backend so that series are more consistently updated than every 48hrs (which is the default) - and I'm guessing restarting mylar daily would make the scheduler start the clock over every time so that the update every 48hrs never occurs (it has to run once to store the time of the run for use). 

You can also do a mass refresh of series via the Manage tab / Manage Comics option and then select the series you want to refresh and bulk refresh those (to ensure you don't hammer the cv api hourly limits).

**Comment by cesalo** [comment]
You're right, at least with 1 that I just checked. Just when it stopped to add issues the next issue came 2 months after.
Thanks also for the tips.
Is there a way that I can change the time limit where Mylar thinks that a comic series has ended? Like for example to 70 days or some other number of days.

**Comment by evilhero** [comment]
You  can set the biggie_pub value (for DC, marvel and dark horse) and/or the thr indie_pub value for all other publishers to the number of days for it to be considered a continuing series. 

By default, biggie is set to 55, and indie is set to 70. The biggie shouldn't need to be adjusted as if it's set to high then it won't recognize reboots in the same year (cause both marvel & DC are doing that like mad lately), which would in turn mean issues won't get marked correctly and tied to the right volume/series. 

I think the majority of the problems you're having with not updating is the restarting daily and mylar not being able to track when to run the series updates on the backend due to that. Hopefully my fix for this will help you out (it really should), but otherwise you can try those variables in the config.ini but I wouldn't skew too far from them (ie. Don't try setting it to 200),or else you'll get some really weird and most likely wrong results.

**Comment by cesalo** [comment]
Ok, thanks. In the meantime I will also change the daily restart to a weekly schedule.

Thanks a lot for your help and this program ... It's really amazing.
