### ISSUE TITLE
Torrent error

### ISSUE THREAD

**Issue by pipieye** [evilhero/mylar#1670]
not sure if this is a bug or setup error.
Recently activate torrent and I am getting the following error when manually searching
------
03-Jul-2017 09:16:48 - DEBUG :: Thread-15 : Torrent Provider:TPSE
03-Jul-2017 09:16:48 - INFO :: Thread-15 : matched on Deadpool
03-Jul-2017 09:16:48 - DEBUG :: Thread-15 : filename for torrent set to : /Volumes/sg4tb-c/Comics/comictorrent/Deadpool_24_2017.torrent
ERROR:root:'http://torrentproject.se/torrent/.torrent' returned an error. Could not collect tokens.
03-Jul-2017 09:16:48 - ERROR :: Thread-15 : Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
03-Jul-2017 09:16:48 - INFO :: Thread-15 : Could not find Issue 24 of Deadpool (2015) using TPSE [api]
03-Jul-2017 09:16:48 - DEBUG :: Thread-15 : Could not find issue doing a manual search via : api
------
Seems like full filename is not being passed?
Thanks,
Pipi

**Comment by pipieye** [comment]
PS> Also getting the following every few mins.

03-Jul-2017 11:12:43 - DEBUG :: RSSCHECK : 'Traceback (most recent call last):\n  File "/Volumes/Samsung840EVO/Users/pipi/Myapps/Mylar/mylar/mylar/scheduler.py", line 78, in runAction\n    self.action.run()\n  File "/Volumes/Samsung840EVO/Users/pipi/Myapps/Mylar/mylar/mylar/rsscheckit.py", line 62, in run\n    rsscheck.torrents(pickfeed=\'TPSE\')    #TPSE = DEM RSS Check + WWT RSS Check\n  File "/Volumes/Samsung840EVO/Users/pipi/Myapps/Mylar/mylar/mylar/rsscheck.py", line 257, in torrents\n    \'size\':     helpers.human2bytes(str(tmpsz[tmpsz_st:tmpsz.find(szform, tmpsz_st) -1]) + str(sz)),\nUnboundLocalError: local variable \'szform\' referenced before assignment\n'

**Comment by evilhero** [comment]
The 2nd error has been fixed in dev - you either need to switch to dev, or if you're already on that branch, then update to the latest. 

The 1st error is probably something with TPSE itself, as usually a token error means it's being hit too hard so they slow things down or something similar. Give it a bit and try again to see if it clears up (there's a delay set in mylar, but it's also possible you hit the anti-hammering on their site and got a temp ban which lasts a few mins).
