### ISSUE TITLE
API key being used as get id.

### ISSUE THREAD

**Issue by ronlipke** [evilhero/mylar#1672]
I have an intermittent problem that only occurs with results from dog.  Mylar will report that it has found an item, and log the download url with my API key as both the api key and the id for the item, even though it has the correct item id in the returned fetch url.
It will do this for seemingly random items, as it will successfully grab several things from dog beforehand.

```
2017-07-05 21:49:02	ERROR	Unable to download nzb from link: https://api.dognzb.cr/api?apikey=DERPAPIKEYDERP&t=get&id=DERPAPIKEYDERP [https://dognzb.cr/fetch/ee060ce3d2e5eb0f91b129bb6bc789e0/DERPAPIKEYDERP]
2017-07-05 21:49:02	INFO	Download URL: https://api.dognzb.cr/api?apikey=DERPAPIKEYDERP&t=get&id=DERPAPIKEYDERP [VerifySSL:True]
2017-07-05 21:49:02	INFO	Found Some comic I was looking for issue: 13 using dog (newznab)
```

**Comment by evilhero** [comment]
I'm pretty sure the download url link given with both apikeys is just for logging (it should be in debug mode, not info mode), as mylar would use the link that has the /fetch in it to retrieve the nzb from dog (I'll have to double check, but that's the way it was being used prior as I think one of those url formats wasn't supported at the time). 

Is the item taken from the RSS or an api search? Mylar will cache the RSS stuff so it's possible the nzb is no longer available if it was purged on their end for whatever reason, albeit I can't see this happening for more than a handful of items.

**Comment by ronlipke** [comment]
It's from an API search, not RSS.

So I went back and grepped through all of the log files I still have on disk and it doesn't look like any dog downloads are working, but they are successful from nzbgeek.  In the logs at least, the search url for nzbgeek has the correct API key and item ids. 

The items definitely still exist in dog too, since I can take the Download URL and replace the erroneous api key with the actual item id and it downloads the nzb just fine.  The fetch URL also works. 

I haven't dug into the code too much, but not sure why it would work for other indexers but not dog.

**Comment by ronlipke** [comment]
Forgot to mention that I'm on the latest master.

**Comment by ronlipke** [comment]
Soooooo, after spending some time debugging `search.py` I figured out what the problem was...  
I was still using a custom newznab for dognzb instead of the built in provider 🤦‍♂️ 

After disabling the custom one, it was throwing some weird errors because it thought it was still enabled, so I had to go into the config file and remove it along with the provider order (which still had old indexers I don't use anymore).  

Everything is working perfectly now.  Sorry if I took up any of your time!

**Comment by evilhero** [comment]
Glad you got it working ;) 

The weird errors were probably due to the provider change. Whenever you enable / disable a provider and subsequently save the config, you need to restart mylar for the settings to be used properly. This is mainly due to the provider_order sequence, as it's only generated on startup so if you don't restart after a provider change it has no way of knowing if a given provider is enabled /disabled. It's also normal to see providers in the provider_order line in the config.ini to show one's that aren't enabled any longer, as mylar will only use ones that are enabled but in the  sequence order that is given. 

Hope that helps explain a bit why you were getting those weird errors - it's a long outstanding glitch in how mylar loads things, due to the base mylar went off of initially (headphones), and my inexperience at that time with python. I hope to fix things so a restart isn't required, but I need to rebase alot of the code within a few modules so that it's all working as to be expected.

**Comment by ronlipke** [comment]
Thanks for the heads up.  I think it was also an error on my part, because it was trying to use "dog" which is what my custom provider was named before I renamed it while troubleshooting.  Either way, all is working and I got to know a lot more about the actual code and guts of mylar.  Thanks again!
