### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by TwistedG** [evilhero/mylar#1673]
Ok I'm kind of new to this but I am having an issue with the way I have set up my Linux Server while running Mylar and then accessing it on a network connected Windows computer using Comicrack. I have set the files to write with no permissions using Sabnzbd+. I then shared the folder with my Windows computer and use Comicrack to organize and categorize all my comics. But when it wants to move the files or write new data to them it can't. 

I don't know if this is the place to be able to find help with this but I thought I'd shot it out there.

Also I am having an issue where the Post script ComicRN gets hung up in Sabnzbd if anyone could help me with this to that would be great. I think it stems from trying to download multiple copys of the comic.

**Comment by HypKin** [comment]
why not give them read/write permissions for everyone? "no" permissions seems kinda strange?

**Comment by evilhero** [comment]
@HypKin is right in my best guess too. Depending on how you're sharing (ie. Samba) you can specify the user and the permissions (ie. 775) so that things can get accessed via your Windows machine (my setup is similar, I have a headless Ubuntu server and access everything via my Windows laptop using samba shares). 

Mylar can also tag the issues as they're being post-processed which would save you a step in your workflow and then you don't have to move anything around unless via manual intervention (as in once you move the files out of the location where mylar thinks they are, it can no longer monitor said files). 

As far as the comicRN problem, I'd need to know more - is mylar running on a separate machine than your sab? Did you setup the autoProcessComics.cfg file with the same values as in the mylar GUI? I can help, just need to know more info first...

**Comment by TwistedG** [comment]
To be honest with you guys I just followed a guide setting up Sab and Mylar. I don't know what kind of permissions I need to set or where to do them. I know that I am sharing my Comics folder with samba by right clicking on the folder and starting the Network Share feature with read, and write allowed for others. If you guys tell me what kind of screenshots I need to add so that I can explain better I will lol

**Comment by HypKin** [comment]
you could just give your files rights like 777 - that means that everyone can do everything with them, should work but its not very secure.
