### ISSUE TITLE
"Have" Status incorrect count

### ISSUE THREAD

**Issue by JaBaine** [evilhero/mylar#1674]
I am running the latest dev and I have noticed that the have status no longer shows the correct count and has marked all the issues in for the comics as "archived" . This seems to occur when the comic search path is set to the base comic name. This search path enables the "Annual handling" to find annuals and mark them as downloaded.

![capture1](https://user-images.githubusercontent.com/3401143/27964085-07708052-6305-11e7-9372-0d980f914504.GIF)
![capture3](https://user-images.githubusercontent.com/3401143/27964090-0d67f850-6305-11e7-9cd5-fc560b045fef.GIF)
![capture4](https://user-images.githubusercontent.com/3401143/27964317-d62dc7b0-6305-11e7-9bd8-be66adb049ad.GIF)

My typical folder organization includes a folder for Annuals and a folder for each Volume 

![capture2](https://user-images.githubusercontent.com/3401143/27964388-16b941e2-6306-11e7-8739-7a9d36905930.GIF)

I have tested that if I add the Volume folder to the search path the Have status is corrected but the Annual Handling comes up as Wanted.

I thought at one point this was working correctly based on my folder structure but I may be mistaken and I am wondering if I should reorganize to a different folder structure for everything to work correctly.

**Comment by evilhero** [comment]
It's pretty much always been that way as mylar scans everything beneath the series base folder and assumes it all belongs to the same series. So the way you currently have it, it wouldn't be able to scan in the right folder accurately - you'd have to set the series base to the correct volume, and include the annuals either in a subdirectory of that series base or as individual files therein for everything to get picked up accurately. 

It's a neat distinction you're trying to make in the grouping, but will not work given how mylar does the scan and comparison (ie. It doesn't check the issue dates against the filenames, unless the series has duplicate issue numbers - it just checks against issue numbers for a match). I might try to look into being able to parse out the folder name as a sub-base against a multiple volume series, but the logistics would have to be spot-on for that to work accurately (it can be done since it already knows the subfolders since it parses from the base during a filecheck, just would need alot of testing/coding).

**Comment by JaBaine** [comment]
alright I will work on restructuring a few things. Thanks for the feed back

**Comment by JaBaine** [comment]
alright I will work on restructuring a few things. Thanks for the feed back
