### ISSUE TITLE
Pushbullet Channels Support

### ISSUE THREAD

**Issue by galacticat** [evilhero/mylar#1680]
Is it possible to add pushbullet channel support for notifications?

**Comment by evilhero** [comment]
It looks like it's supported by their api, so it should be doable as an option in Mylar. Just not sure of eta when you would see it as I only do a few enhancements at a time, and have some already on deck. 

I'll mark this as an enhancement request tho so I can remember it when I can get around to doing it - otherwise PR's are accepted if you're python-capable ;)

**Comment by davalanche** [comment]
@evilhero, I would like to volunteer to work on this enhancement (if possible). Thanks!

**Comment by evilhero** [comment]
Sure I don't have a problem with some help (especially since I don't use pushbullet).

Thanks for the offer @davalanche :)
