### ISSUE TITLE
Import Management > Manual Intervention > Select doesn't often work

### ISSUE THREAD

**Issue by Rumik** [evilhero/mylar#1685]
Hi there,

My import scan has deteced several series with more than 1 match on the scraper, but when clicking the "Select" link, nothing happens. This has worked before on other series, but my experience has been that it doesn't work 8/10 times.

Thanks

**Comment by evilhero** [comment]
It might be dependent on the information it has on hand when it's trying to do the search for the given issues - all it has to go is the series title, and metadata.  

The previous times this occurred that I was able to duplicate it was due to some irrelevant search results being returned and throwing the results off (as they didn't have any year present or similar). But all that was fixed awhile ago - can I ask you to give the filenames that are causing problems to the series you're trying to import? I can then mock up the fakeness on my end to see if I can duplicate the problem, but without seeing the names, or the debug log showing the import process (which would be really long due to the size of the import) - it's hard to troubleshoot from this perspective.

**Comment by Rumik** [comment]
Hey there!

Okay, so I've figured out that this happens under two conditions:

1 - It can't find a match for the comic I'm scanning - e.g. Final Fantasy Lost Stranger. There's no comicvine metadata for this comic (annoyingly).

2 - There are multiple series matching the metadata in the same folder on the hard drive - e.g. Spider-Gwen. There are two volumes for this series, both identified as Volume: 2015 by ComicVine, and have identical series names, so they get sorted automatically by ComicRack into the same folder. So there are two issue 1s, 2s, 3s, etc. If I manually separate out these two volumes into separate folders and run an import on each one individually, I'm able to Select the correct series.

BTW do you have a Patreon I could subscribe to? Mylar is excellent and you always respond to requests for help, and very quickly - you deserve to be supported.

Thanks!

**Comment by evilhero** [comment]
Well the no comicvine data problem I should be able to solve that - it actually should be returning no results instead of displaying the select option and changing the status to 'Manual Intervention'. So that one should be a relatively easy fix (I'm guessing without looking at it of course).

The 2nd one is just how Mylar handles scans. It assumes everything in a given sub-directory is a complete set - so if you happen to have 2 series in one folder, then it gets mixed results from querying against it's calculations (it checks against number of issues it scans in so the counts would get double up and such). Not sure if there's anything I can do other than maybe make mention on the import screen that individual series have to be in dedicated folders for an import to properly parse?

No Patreon - there's just the typical bitcoin / pp addresses which are located within the program if you were wanting to help support the program and anything is very much appreciated regardless :)

**Comment by Rumik** [comment]
How about an option to manually identify issues much like the comicvine scraper plugin in ComicRack?

**Comment by evilhero** [comment]
I don't use cv scraper so I'm not sure how it works on that end. Manually identifying an issue could be a laborious job, or are you meaning identifying a series manually?

**Comment by Rumik** [comment]
You should check it out, it's very good. If it has multiple matches for the comic you're scanning it shows you a list for you to choose from, much like Mylar does, but after selecting a series it also allows you to choose the issue of the comic you're scanning.

**Comment by Nukien** [comment]
I just discovered mylar and it looks like a present from the gods :)  If I can get it to work - I hate to ask questions to quickly.

I'm using the docker version from linuxserver.io.  It seems to see everything properly, the cv apikey is in, the dirs are all correct, so it all looks good.  I do a library scan of a single comic (eg: **/comics/Batwoman**) and it finds them all correctly.  

But upon import I get the Manual intervention required, and clicking Select just blinks the page momentarily.  Each one is labeled along the lines of `Batwoman v1 23 (2013) (Digital) (Nahga-Empire).cbr` but it keeps saying in the logs "_There is more than one result that might be valid ..._"

I've tried about 10 different comic dirs, and the same result for all :(

**Comment by evilhero** [comment]
Not sure how I missed this, or I thought I responded and I guess it didn't accept the response (stupid phone)....Anyways, I'll take a look at this now and see what's happening. I've been knee-deep in some other aspects of Mylar for the past week or so, so I haven't really been paying too much attention to things either (totally my fault).

**Comment by Nukien** [comment]
They're all in individual dirs - Batwoman-v1, Batwoman-v2, Annuals, Rebirth.
I added the blacklisted_publishers as you describe, but still no luck.  Every import results in Manual Intervention, and clicking `select` just results in the browser page blinking momentarily.
I can package up the dirs for you to check with if you want.  It's about 1.5G.
Meantime, here is the logs from an import attempt for just v1.  I stopped the container, removed the mylar.db, then restarted the container - (it has the latest according to the update check).
[http://paste.ubuntu.com/25939857/](url)

**Comment by evilhero** [comment]
Don't think there's a need for the dirs to be sent. Still not sure what's happening - I ran a mock test as per some of your file names and it came back with the select, but then displayed the page properly.

Have you restarted mylar since you made the config.ini change by chance?

Also, what might help more, but be more lengthy, is to put mylar into verbose mode and perform an import that way so that it gets all the debug logs (you can enable it on the logs tab - toggle verbose on).

The log you had provided was info level of logging which unfortunately doesn't help very much when it comes to troubleshooting something of this nature.
