### ISSUE TITLE
Post-Process / Import non-watchlist issues.

### ISSUE THREAD

**Issue by jackperry** [evilhero/mylar#1698]
I've got a lot of individual comic files and would love if I could place them in my watch directory and have it process those and add them to my watchlist if it's not already on it.

The Manual Post-Processing page says "Only series' that exist on your watchlist will be post-processed with your current post-processing options." which led me to believe that this was already supported but I had my options wrong. I don't actually see any option that would enable this though.

**Comment by evilhero** [comment]
No you can't post-process series that arent in your watchlist just due to safety measures really. The entire post-process matching is automated down to the issue, so there's no way to prompt for any user required choices (ie. Multiple volumes, 2 series in the same year but no volume labelling in files, no issue year/volume in files, etc). 

Your best bet is to use the import a directory option in the Manage tab. It will scan your files regardless of folder structure, and asomg as they're named in a somewhat recognizable format it will parse them to get the necessary info. It will then allow to select multiple series from the scan and import them, bulk import the entire lot, or after an import comes back as having manila intervention required allows you to select the proper series. It will move/rename your files as required (if enabled), but will not add metadata to the files.

**Comment by jackperry** [comment]
@evilhero Thanks for the quick response. My hope was to avoid having to create all of the folders with the appropriate names as it would be pretty sweet to just dump the cbr or cbz files and have Mylar automatically put those in the right place, etc.

Your explanation for why this isn't an option makes perfect sense, I'll start working on these folders now and I'll go ahead and close this issue.

**Comment by evilhero** [comment]
You don't have to create the folders, mylar looks at individual files and only if they're named as something it can't parse properly it will look to the parent folder for more info. Just throw a bunch of files into a temp directory and scan it, you'll see what I mean (it groups them accordingly, or does a best effort at least)

**Comment by jackperry** [comment]
Oh sick, I'll give that a try. Thanks a bunch.

**Comment by jackperry** [comment]
@evilhero That seemed to work, but it keeps upping the "Number of valid files to process" and "Files that were parsed" with a few extra hundred (from TWD and Invincible it seems). The Import Results Management also keeps listing comics that are set up in Mylar already and have no new issues.

I would think if a comic and all of the issues I have of it are already tracked in Mylar that it wouldn't show up when I run this scan/import?

**Comment by evilhero** [comment]
Well no, I mean it really shouldn't show existing series, but atm it currently does. Mainly because it's a 2 part process: it scans the files for information and/or uses any metadata within to get series title, series/issue years and volume. At this point it has no correlation to anything in your watchlist as that's tracked by comicid, not by name due to multiple volumes of series being possible. Once you try to import it should note that its already part of your watchlist. 

If any of your issues have metadata, it would tag them as being in your library during the 1st part of the scan process. I could try to make it show a possible watchlist match based on filename alone, but it wouldn't be accurate if the filenames aren't named appropriately, or metadata doesn't exist. 

The upping of files during the process is a glitch that I haven't been ae to track down thus far, but it's more for statistical knowledge than anything that mylar actually uses for count purposes when scanning.
