### ISSUE TITLE
Mylar randomly unticks the DOGNZBD option

### ISSUE THREAD

**Issue by Rumik** [evilhero/mylar#1699]
Every now and then I notice that my searches aren't happening, and I check my search settings and the DOGNZBD checkbox has somehow become unticked.

Thanks

**Comment by evilhero** [comment]
Yes, it's a glitch that's been troublesome, even more so lately. It's supposed to disable the provider if it gets back an invalid message from dog when performing search queries (such as api limit reached, server down, etc). 

I'll be trying to fix this soon, just summer is difficult to find alot of free time to work on code due to kidlets.

**Comment by Rumik** [comment]
Totally understand, glad it's on the to do list! :)

**Comment by barbequesauce** [comment]
@evilhero Do you have an idea where the error is occurring? I can add in a cool down timer if that might help... I see a lot of places where it might apply, but I don't want to break too much doing so....

**Comment by evilhero** [comment]
The only place I can see it happening is in the search.py module at line ~684. It's the only place where the mylar.DOGNZB gets set back to 0 (to denote that it's not enabled anymore). But according to the code, it should only trigger when an error is received back from dog during a search request that the daily API limit has been reached.

It's already adhering to the 60s delay between searches, so I'm not sure if a cool-down timer would help (not 100% sure either mind you), and since I don't have VIP on dog anymore, I can only really test against the api limit error (since that's what triggers when it goes over the limit).

Any help/assistance in this would save me a great deal of troubleshooting blindly (to a certain degree)....

**Comment by Rumik** [comment]
I'm happy to give you temporary access to my DOG account if it'll help?

**Comment by barbequesauce** [comment]
No worries, I have a dog VIP account... I'm finding it impossible to trigger a rate limit though. How many issues are you requesting?

**Comment by Rumik** [comment]
It varies. Sometimes it’s only one, other times it’s 30 or more.

**Comment by Rumik** [comment]
I haven't been able to pin down when it happens. I just check every couple of days to see if the problem has happened again. Next time I see it, I'll save the log and post it up here.

**Comment by Rumik** [comment]
So it's just happened again, but the log is so massive and it's still updating it's impossible to find the moment it happened. Is there a way to export the entire log rather than going through it a page at a time?

**Comment by evilhero** [comment]
The log files are located in the logs subdirectory within the mylar directory. Zip them all up and send is probably the easiest thing to do (shutdown mylar too so that the logs don't roll over)L before you can send them).

**Comment by Rumik** [comment]
Phew, at last! 
[logs.zip](https://github.com/evilhero/mylar/files/1272173/logs.zip)

**Comment by evilhero** [comment]
I've looked through the logs, but can't find any reference to dog even being enabled let alone getting disabled. I'll keep on checking, but you might have to try to get another set of logs (just make sure to shutoff mylar when you catch it so they don't roll over).

Sorry bout that, I'll keep on skimming the logs, but atm it doesn't look helpful without some reference to dog therein.

**Comment by xkelly** [comment]
Just saw this has been happening to me as well. I noitce dog is unchecked. I check it, confirm the api is correct (still vip, as well), save and restart. Still checked after restart. A few days later, could go in there and find it's not checked. Strange.

**Comment by evilhero** [comment]
I think what's happening right now is that if Dog returns an error code of some kind, Mylar will disable it due to unavailability. At one point there was some discussion about a timed re-enabling option, but I don't think that made it's way into the code as of yet. So right now, if dog is down for maintenance, or just down in general (which I believe happens at least once a week for scheduled maintenance, I can't speak about unscheduled downtime) it will return an error code and Mylar will disable it and would only be re-enabled by the user manually doing so (this just doesn't apply to dog - it should be doing this for all the providers if they return an error code that indicates it's unresponsive).
