### ISSUE TITLE
Search Interval/Force Search doesn't seem to always work

### ISSUE THREAD

**Issue by Rumik** [evilhero/mylar#1700]
I have observed that issues get downloaded more reliably when manually searching an individual issue than when waiting on the search interval to kick in, or when performing a force search. I have over 60 issues marked as wanted and doing a force search doesn't download any of them, even after waiting all night, but doing a manual search on several of the issues has resulted in them being downloaded.

**Comment by evilhero** [comment]
They all use the same module for searches, and depending in the number of providers you're using it  could take time. It's possible that it's getting timed out, or some backend error is occuring (due to identical multiple jobs running at the same time) - albeit I haven't had this issue happen and I have it running 24/7 usually. 

If your only provider is dog, and it's getting disabled during the search process that would explain why it doesn't find anything usually (as the provider is disabled and has to be manually enabled). Do you not have RSS enabled - as that would poll your provider every 20 mins for the newest files and wouldn't have need for the force search (which does RSS + API). Since it caches the results, the longer you leave mylar running the less chance it has go to the Api for search requests that were tagged at some point by the RSS feeds.

**Comment by Rumik** [comment]
I have disabled everything except the dog search so I will see how it goes. How does the RSS search work though? I can't see anywhere to specify a feed address?

**Comment by evilhero** [comment]
You don't specify an address - it uses your active indexers to poll RSS feeds against. So if you had dog, experimental, and geek as an example, it would actively query (~every 20 minutes by default) their rss feeds and cache the results. 

As long as you have it enabled, it will auto-rss search at the required interval each provider you have enabled (including torrents) and cache the results for more localized searching as opposed to requesting items from the providers for every item.

**Comment by thingdeux** [comment]
@Rumik - Please close / resolve this issue.
