### ISSUE TITLE
Download not working - Trying to fetch NZB msg

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#1701]
I just moved my original setup to docker and since then I have no downloads. Checking the logs of SABNZBD i see a lot of:

WAIT 36 sec / Trying to fetch NZB from http://172.​17.​0.​5:8090/api?apikey=XXXXXXXXXX&cmd=downloadNZB&nzbname=[Comic Name ... ].​nzb

Just changed the apikey and comic file name.

Any idea what is this IP address: 172.17.0.5? In the past I had it running in my QNAP and had no issues.

Thanks in advance.

**Comment by evilhero** [comment]
The 172.x.x.x is the local up that mylar is detecting (your local ip from the looks of it). 

It's trying to request the already downloaded nzb from the mylar app, but it's requesting it at that ip address, which it can't reach. 

You can use the host_return field within the config.ini and set it to the full url to your mylar install (ie. http://192.168.1.7:8090) - doing it this way allows you to keep 0.0.0.0 as your mylar host so it can listen on all interfaces.

**Comment by cesalo** [comment]
Part of the change was moving mylar to a different server so SAB is still running in my QNAP NAS.
That IP address is not the one of the server, is not even one in my network, wondering where 
I'll use "host_return" and get back to you. Thanks for the help.

**Comment by evilhero** [comment]
The 172.x.x.x is an ip that mylar detects on your system during startup - it attempts to use the local ip if one isn't set, but it's also not 100% accurate due to the nature of differing systems. 

If you set the host_return value to the 'http://ip:port' of mylar that can be reached from outside of the machine itself (ie. If you were accessing mylar from a separate machine, the url you would enter into a browser to pull up the mylar GUI), nzbs should be able to be sent/used properly. 

Also make sure you have the checkbox enabled under the downloaders tab that mylar and sabnzbd are on different machines.

**Comment by cesalo** [comment]
After updating "host_return" the issues are solved. Thanks a lot.
