### ISSUE TITLE
Mylar does not find comic on NZB indexer ->> Miatrix

### ISSUE THREAD

**Issue by mmwaveguy** [evilhero/mylar#1707]
Mylar search engine never seems to find any comics on NZB indexers.

For instance it could not find Watchmen (1986) 001 on MIatrix even tough the files do exist on the indexer.  Miatrix lists the issue as follows:

Watchmen 01 (of 12) (1986) (Digital) (ZoneKing-Empire)

Eperimental search engine also does not work.  Clearly the search engine needs to be improved.

**Comment by barbequesauce** [comment]
Interesting. Most of my downloads come from dognzb, with WWT as a day behind.

How are you using Miatrix? As a Newznab provider? I'm not familiar with it.

Can you provide an example file you were searching for, with debug logs?

**Comment by evilhero** [comment]
I really dislike condescending tones in someone asking for help - and most times I wouldn't even bother to answer this type of issue (cause you know, no one gets paid for this stuff), but this was a pretty obvious solution....

Miatrix is a newznab-based indexer, so there's no problem with using it. In fact, I just used it, and it pulled down the Watchmen issue @mmwaveguy indicated with no issues - so clearly there aren't any problems with the searching algorithm as was so nicely indicated.
```
2017-09-09 23:10:37 | DEBUG | issues match!
2017-09-09 23:10:37 | INFO | Found Watchmen (1986) issue: 1 using Miatrix (newznab)
2017-09-09 23:10:37 | DEBUG | link given by: newznab
2017-09-09 23:10:37 | INFO | prov : Miatrix (newznab)[74649fc9ed27e52c5d217764b00d3041]
```
But perhaps, if one is referencing an issue that's 4.7+years old on a given indexer, you should set your 'Usenet Retention (in days)' to the appropriate setting so that it can take those values into account (ie. 2000).

![idiot](https://user-images.githubusercontent.com/909424/30245860-d1286ad6-95b4-11e7-8dc3-3e1692c589f9.png)

PS. Thanks @barbequesauce for tryin to help ;)

**Comment by mmwaveguy** [comment]
Sorry didn't mean to be condescending.  I didn't realize that Mylar had a retention setting.  Mine was set at the default of 1500 days.  Changed it to 3000 days and its now working - thanks:)

**Comment by mmwaveguy** [comment]
by the way @barbequesauce Miatrix is a fairly new newznab site.  I've been using it for about a year now -mostly for tv shows and it's been really good.

**Comment by barbequesauce** [comment]
Nice... it's picking shows up faster than my other nzb indexers / private trackers... thanks for the tip!

BTW - if you're good with this issue after evilhero's fix, don't forget to close the issue please...

**Comment by mmwaveguy** [comment]
OK all is good - closing issue:)
