### ISSUE TITLE
BeautifulSoup warning

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1713]
Hey there - was watching a startup today trying to figure out why a file wasn't being sucked up by mylar and saw the attached warning in the log... I'd submit the PR as described but I'm thinking it implies dependencies that might not exist on some people's machines...

```
/opt/mylar/lib/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 783 of the file /usr/lib/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

```

**Comment by evilhero** [comment]
Yeah by default if it's not specified it tries to use the best available parser on the given system, so it will change from system to system (and thus provide different results).

I set most of them to use HTML, but I guess I missed one - since HTML parser is native to Python it will always be available, whereas lxml as an example has to be manually installed.

I'll locate the other non-specified parser options and force it to html so it's the same across the board.
