### ISSUE TITLE
Odd count issue in front screen

### ISSUE THREAD

**Issue by barbequesauce** [evilhero/mylar#1716]
Started getting this weirdness on the front page... when I look at the directory, the file count (31) is correct, but the issues list is only 30. I'm guessing it's adding the annuals on one part but not on the other? It's happening to 7 of my 60 tracked series at this point... and wasn't there yesterday.

<img width="989" alt="screen shot 2017-09-18 at 4 48 50 pm" src="https://user-images.githubusercontent.com/25070944/30564099-e9d12a76-9c91-11e7-951f-36eccde5fdd1.png">

**Comment by evilhero** [comment]
Yep it's the annual glitch that started occuring a few commits ago..

What it did is if an annual was presently listed, when it refreshed the series it didn't reload the annuals and they got dropped. Then when it refreshed again, since there were no annuals present it couldn't drop them, so it added them back. And then it just keep on doing that cycle.

The fix went into dev about an hr (I was aware of this yesterday, but had  make sure it actually fixed things prior to pushing it out)

Thanks for the heads-up regardless, and if the latest dev doesn't fix things just let me know!

**Comment by barbequesauce** [comment]
I'm on 40ab now, and it's still happening. On a hunch I tried refreshing the comic from the comic page, and it errored out...

```
18-Sep-2017 18:44:14 - INFO :: Thread-15 : Attempting to retrieve the comic image for series
18-Sep-2017 18:44:19 - INFO :: Thread-15 : Sucessfully retrieved issue details for Batman
18-Sep-2017 18:44:25 - INFO :: Thread-15 : Now adding/updating issues for Batman
18-Sep-2017 18:44:25 - ERROR :: Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 165, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/updater.py", line 304, in dbUpdate
    cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
  File "/opt/mylar/mylar/importer.py", line 423, in addComictoDB
    issuedata, anndata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
ValueError: too many values to unpack

Traceback (most recent call last):
  File "/opt/mylar/mylar/logger.py", line 165, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/mylar/mylar/updater.py", line 304, in dbUpdate
    cchk = mylar.importer.addComictoDB(ComicID, mismatch, annload=annload, csyear=csyear)
  File "/opt/mylar/mylar/importer.py", line 423, in addComictoDB
    issuedata, anndata = updateissuedata(comicid, comic['ComicName'], issued, comicIssues, calledfrom, SeriesYear=SeriesYear, latestissueinfo=latestissueinfo)
ValueError: too many values to unpack
```

**Comment by evilhero** [comment]
Ugh that's the large volume right.. The one with 700 issues (roughly)?

I didn't test against that size if it is..

**Comment by barbequesauce** [comment]
No, it's the current one (post-Rebirth, 30 regular plus 1 annual).

**Comment by evilhero** [comment]
Been working on this since yesterday, and it's kinda snowballed into me changing some stuff that touches a few different modules. So I'm trying to work thru the errors, while not creating any new ones - so it's taking a bit more time to track everything affected down...

**Comment by barbequesauce** [comment]
No worries - I'm a couple of weeks worth of reading behind anyway :)

**Comment by evilhero** [comment]
Crap -- I forgot to update the commit before pushing it. Lastest dev commit should fix this issue now, although if you have some series that are showing as incorrect counts (ie. orange), you might have to do a Refresh Series for these particular series (quick batch way, is to go to Manage/Manage Comics/sort by the have column so the orange's all appear at the top, select them and choose Refresh series from the dropdown).   

Rechecking these won't work, as they're incorrectly counted due to not having any annuals present in the issue database, thus a refresh is needed. 

If there's any other issues that pop up, please let me know. I tried to track down most of these as I was working through, but I'm sure I missed a few that will eventually show up somewhere down the line...

**Comment by barbequesauce** [comment]
Looks good, thanks!
