### ISSUE TITLE
Post-Processing Error

### ISSUE THREAD

**Issue by cjamesdesigner** [evilhero/mylar#1719]
Mylar Version: development-- 
git build c6a7f4dbdfb4c80002a7c8b6e58f364b8641a47b.
Python Version : 2.7.9
--

ERROR | Uncaught exception: Traceback (most recent call last):File "/media/sdr/c7j8d9/mylar/mylar/logger.py", line 165, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 763, in runself.__target(*self.__args, **self.__kwargs)File "/media/sdr/c7j8d9/mylar/mylar/PostProcessor.py", line 1358, in Processself.Process_next(comicid, issueid, issuenumOG, ml, stat)File "/media/sdr/c7j8d9/mylar/mylar/PostProcessor.py", line 1996, in Process_nextlogger.fdebug(module + ' New format: ' + str(chunk_file_format))UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 8: ordinal not in range(128)

**Comment by evilhero** [comment]
What's the name of the file you're trying to post-process ?

**Comment by cjamesdesigner** [comment]
Green Arrow 030 (2017) (2 covers) (Digital) (Zone-Empire).cbr

I took out the endash and it still gives the same error.

**Comment by cjamesdesigner** [comment]
Possibly unrelated (I can start a new issue if you would like).

WARNING | Error fetching RSS Feed Data from TPSE: 403 Client Error: Forbidden
Doesn't seem to be searching WWT even after the change to .me
Is this warning normal just because TPSE is down?

**Comment by evilhero** [comment]
Can you paste in the debug lines just previous to that error message... There's nothing wrong with that name, so there might be more info in the lines leading up to it.

The forbidden error is probably due to TPSE being completely down, and might not even be coming back. As long as it's searching the other 2 public trackers it should be fine - but both of the other 2 rely on RSS feeds only (no api/backlog functionality)

**Comment by cjamesdesigner** [comment]
post process debuglog:
https://pastebin.com/V9j3cWrT

for searching it doesn't look like its using wwt at all:
https://pastebin.com/x62ewHCi

**Comment by cjamesdesigner** [comment]
nm on the searching...no backlog (I missed that) future issues should get caught by wwt right?

**Comment by evilhero** [comment]
Well .eu was down do nothing go logged during that time, but the cache should still work for wwt.eu as it stores  the torrent id and then creates the link from the url path (which has been changed to the  .me)

And yes, future issues WL get caught fine as long as mylar is running.

**Comment by evilhero** [comment]
It looks like your folder format might have something in there that doesn't belong.

I can fix the error so that it doesn't throw that error, but without knowing what your file format string is, I can't account for what might happen after that one line (since the file format would be actually getting applied later in the workflow, the error is just stating it can't log it properly due to the invalid character).

**Comment by cjamesdesigner** [comment]
ahhh! My mac at work added an emdash to the rename instead of the endash. Working!
