### ISSUE TITLE
You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.

### ISSUE THREAD

**Issue by Rumik** [evilhero/mylar#1727]
So even though I've got DOGnzbd specified in my settings, the above error has started showing up in my log and nothing is downloading.

I'm also 8 commits behind but Mylar won't update.

I'm running on a QNAP, could anyone please give me some instructions on how to fix this?

Thanks.

**Comment by cjamesdesigner** [comment]
Erase provider_order line from the config.ini and restart mylar for DOGnzbd. Manually update Mylar by replacing the contents with the latest zip from github or use a terminal and and git pull the latest if you are using git.

**Comment by SUBnet192** [comment]
Just had a similar issue with updates not working and doing the git pull/clone fixed it for me.
git clone https://github.com/evilhero/mylar.git -b development

**Comment by Rumik** [comment]
So I took that line out of config.ini and then downloaded the latest zip from Git and copied the contents over. Now when I click the Settings button I get a horrendous error:

Error !

AttributeError: 'module' object has no attribute 'RSS_LASTRUN'

<label>RSS Interval Feed Check</label> <input type="text" name="rss_checkinterval" value="${config['rss_checkinterval']}" size="6" /><small>(Mins)</small> <a href="#" style="float:right" type="button" onclick="doAjaxCall('force_rss',$(this))" data-success="RSS Force now running" data-error="Error trying to retrieve RSS Feeds"><span class="ui-icon ui-icon-extlink"></span>Force RSS</a> </br><small><% rss_last=mylar.RSS_LASTRUN %>last run: ${rss_last}</small> </div> </fieldset> <fieldset> <div class="row checkbox left clearfix"> <input id="usenzbsu" type="checkbox" onclick="initConfigCheckbox($(this));" name="nzbsu" value="1" ${config['use_nzbsu']} /><legend>NZB.SU</legend>
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/data/interfaces/default/config.html, line 612:
</br><small><% rss_last=mylar.RSS_LASTRUN %>last run: ${rss_last}</small>
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/data/interfaces/default/base.html, line 87:
${next.body()}
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/share/CACHEDEV1_DATA/.qpkg/Mylar/mylar-master/mylar/webserve.py, line 52:
return template.render(**kwargs)

**Comment by Rumik** [comment]
And it's still complaining that it's 8 (now 9) commits behind :(

**Comment by evilhero** [comment]
Try to delete all of the .pyc files in the mylar/mylar subdirectory. If you downloaded the lastest Master zip, it shouldn't be saying your 8/9 commits behind, unless after you downloaded the zip you didn't alter your original config.ini variable of git_branch from development to master.

Delete everything from your Mylar folder, execept for the config.ini, mylar.db and your entire cache folder (it's always good to back these up - especially the config.ini & mylar.db files). If you want to keep on running devlopment, download the latest development zip, unzip it so that everything unzips from the root of Mylar. Make sure your git_branch variable in the config.ini is set to development, start it up and you should be up to date.

**Comment by Rumik** [comment]
I hadn't downloaded the development zip, but even though I have now, and I'm still definitely running in development mode, it's still complaining that I'm several commits behind. I can get into settings now tho.

When I originally installed the .qpkg, it created the mylar-master directory under the root Mylar directory. Could that be why it's still giving me the error?

How can I start from scratch? Is there a command I can run in putty to reinstall the development branch from scratch? I'll back up my config.ini, db and cache. I just don't know exactly what to type in putty.

Thanks!

**Comment by evilhero** [comment]
Well you need to decide on how you're going to run Mylar going forward - you can't install the .qpkg and then try to do git commands, or try a source install and expect things to fly smoothly, cause they won't. I have like zero knowledge of the .qpkg install, but if you installed via that method and you're having problems I would uninstall the .qpkg and try to clear out all remnants of that install (make sure again to have a backup of config.ini / mylar.db / cache directory).

The easiest and best method to use Mylar is in conjuction with git. If you have git installed (type just ```git``` into your command line, and if you get a valid response back you have it installed and can continue, otherwise you'd have to install git). 

Once you have git installed, from the parent directory of where you want mylar to be located (ie. you want it to be /opt/mylar, so you would make sure you're in the /opt directory), and then do a ```git clone https://github.com/evilhero/mylar.git -b development``` which would install the development branch into the chosen directory. Since your config.ini git_branch is already set to development, you should be able to just drop back the config.ini / mylar.db / cache folder and start it up and you should be current. Thereafter, using the GUI updater should work fine as it's installed via git, and it can sync using git - instead of having to download the zip, extract, move, delete, etc.

**Comment by Rumik** [comment]
Git is installed in share/cachedev1_data/.qpkg and when I type git I just get an error: /Apps/bin/git: No such file or directory.

So it expects Git to be somewhere else.

Maybe I'll just go back to the master version. How often does it get updated?

**Comment by evilhero** [comment]
If you try typing in 'whereis git' it will give you the path where it's installed to - you could then (in theory at least) create a symlink from where it is, to where it expects it, and then you can run it as per normal.

Otherwise, master gets updated probably on average once / month. Alot depends on how big some of the changes are in dev and if there's been enough feedback prior to pushing it out (especially some of the experimental stuff). But I usually try to at least merge dev into master at least once / month, maybe more if there's something critical that needs to be addressed on both branches immediately.

**Comment by Rumik** [comment]
"whereis" doesn't work either :(

I'll go back to the master branch :( Thanks for your help though, I appreciate your time!

**Comment by Rumik** [comment]
UGH! Goddamn it :( Going back to master breaks the config page again /cry

Not sure what to do now! I can't get either version to work :(

**Comment by Rumik** [comment]
Also, erasing the provider_order line from the config.ini didn't fix the original issue, so I still can't get Mylar to download anything :(

**Comment by evilhero** [comment]
doh - I'm really at a loss for qpkg stuff, just thinking it would work as the 'whereis' is standard with most linux installations.

Ok, let's try dealing with one thing again ;)  Let's start with the config page, since that's kinda important to access. If you're on the master branch, can you see what version you're running (bottom of every screen the full long alphanumeric string), and did you change the git_branch to master if you're now on the master (instead of devleopment) ?

**Comment by Rumik** [comment]
I went back to my development backup, but I also downloaded the latest dev zip so I should be up to date even if it tells me I'm not. So I'm essentially back to where I was. My main concern now is the dognzb error.

**Comment by evilhero** [comment]
Ok, so you're back up and running - is the dognzb provider enabled or disabled in the GUI ? If it's enabled, disable it - if it's disabled, enable it. Then save the config and restart Mylar (this is the important part - if you don't restart Mylar after a provider change of enabling/disabling then Mylar will get confused about the sequence of searching and report that there is no available providers). Once it comes back up, if it's enabled still that's good - if it's disabled because you manually disabled it in the step above, re-enable it, save the config and restart Mylar again so it line up the provider search order sequence properly (it only does this calculation on startup, thus the need to restart on a provider change)


I'm currently working on restructuring things to finally do away with the provider order error that has plagued it for so long, but it requires a complete overhaul of the config and how things load so it's taking abit of time to truck through it.

**Comment by Rumik** [comment]
I actually tried all that before you suggested it, and it hasn't made any difference :(

Right now dog is enabled in the config, but the log is still complaining that it's not.

**Comment by evilhero** [comment]
Ok, so save the config and then shutdown mylar. Then edit the config.ini and see what the value of use_dognzb is (or enable_dognzb, I can't recall atm). The setting of 0 is disabled, 1 is enabled.

Then delete the entire provider_order line from the config so it's just a complete blank line, save the .ini and start it up.

**Comment by Rumik** [comment]
heh, the shutdown button just restarts it... have shut it down manually from the NAS admin page.

Okay, so there's this:

provider_order = 0, dognzb, 1, tpse, 2, Experimental, 3, nzb.su, 4, NZBPlanet.net

and then:

[DOGnzb]
dognzb = 1
dognzb_apikey = blahblablahmyapi
dognzb_verify = 1

I deleted the entire provider order line and restarted Mylar.

Same problem :(

[WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.

**Comment by evilhero** [comment]
I think the problem in this is that you're editing the config.ini while Mylar is still running which you can't do.

Kill the mylar process entirely, ie. Shutdown via the NAS admin page and then make sure it's not running still (by going to a mylar page and seeing if it opens up).

When it's completely down, edit the config.ini and wipe out the provider_order line again.

Either you're editing the wrong config.ini file (because some third party packages move ini files into a specific location outside of the actual application directory), or its not completely shutdown so when it restarts it overwrites any changes to the .ini.

**Comment by Rumik** [comment]
Okay yeah, this is weird - my NAS tells me Mylar has been shutdown, but I can still get to Mylar's web interface! WTF?!

**Comment by evilhero** [comment]
Yeah, see that's what I mean - either the NAS admin panel isn't shutting things down properly, or it's shutting it down, but there's more than one instance of Mylar running.

From your shell, type in a ```ps -xg``` and see how many instances of Mylar you see running. If there's still some running, you can kill them by doing a ```kill -9 <pid#>``` where the pid# is the number listed on the leftmost side of the resulting list from the ps -ag command.

**Comment by Rumik** [comment]
So it seems like all I had to do was reboot my NAS! Mylar is now up to date and appears to be using dog as a provider! So sorry for stealing all of your time. Thanks so much for trying to help me, you really are awesome! Please set up a patreon so I can support you monthly! :D

**Comment by jangrewe** [comment]
I noticed something similar. When changing the enable search providers (e.g. having an NZB indexder enabled, and then also enabling torrent search), the list of search providers gets emptied.
A restart of Mylar fixes this, but it still unexpected behaviour. It should at least keep the current list, if not just re-read it on config change. (Other tools seem to handle this just fine ;-) )

**Comment by evilhero** [comment]
It's due to the way that the config system was (when I forked headphones years ago, it's probably one of the few things that have remained almost intact aside from the interface). Due to how the search order provider is generated, it only generates it on a startup sequence - so basically, if you make a provider change (enable/disable), and then save the conifg, Mylar will never recognize the fact that you have new providers enabled as the search order sequence hasn't changed as far as it's aware, but one or more providers may have been disabled which throws the sequence out.

I've been at this one for awhile - but I'm slowly trying to convert the config over to a completely new system, allowing for migration from an older config to the config seamlessly (I hope), and in doing so I can then restructure how the search order gets generated, so instead of on every startup sequence it would happen on every save config (as an example). I'm hoping to get this out soon, just hitting a few stumbling blocks with the integration into Mylar (the code is finished and tested, just integrating it now is all that's left)
