### ISSUE TITLE
This Week Pull List: Titles open to ComicVine?

### ISSUE THREAD

**Issue by sifu36** [evilhero/mylar#1728]
Hi!
Not really an issue maybe an enhancement.

Right now when I look at the weekly pull list, titles which are in my library are linked to the comic title in my library.
Titles which are not in my libary are linked to 1.2.3.4:8090/No (don't know if it's by design).
Is it possible, maybe in the future, to link those titles (not in the library) to the comicvine site specific to the title?

Thanks and keep up the good work!

**Comment by evilhero** [comment]
This is already available if you set your alt_pull to 2 in the config.ini (with mylar not running). 

The reason why they're 'no' is because they can't match anything on CV - with alt_pull set to 2 it uses another site that acts as an intermediary and it contains most of the comicids as they are matched up. It does change throughout the week tho as the intermediary site is updated frequently and mylar polls against it every 4hrs (as opposed to alt_pull =0 which polls CV directly every 24 hrs and doesn't have alot of the extra functionality that the 2 method does)
