### ISSUE TITLE
Batch import works but reports tons of errors in the command prompt window

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1729]
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file filechecker.py, line 858
21-Sep-2017 16:00:44 - INFO :: Thread-32 : Series_Name: Sacred Creatures --- WatchComic: Series Name
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file filechecker.py, line 858

**Comment by evilhero** [comment]
This is a windows problem, not so much a mylar problem (aside from the excessive logging).

The default logging module included with python will lock the log files as they're being used in Windows, and then when it tries to move the current log to a new file in order to start writing to a blank file, it won't release the lock and you have that error.

There's an option that's automatically detected within mylar if you use Windows called the concurrent rotational log handler. It completely gets around that lock but you have to install something on your system first  in order for mylar to detect that you have it. I'm mobile atm, but if you check the mylar forums and search for 'concurrent log handler' you should get a few hits back and one of them had instructions about installing the requirement locally (its just running an .exe from a sourceforge repo)

**Comment by SUBnet192** [comment]
pip install ConcurrentLogHandler

Resolved. Thanks.
