### ISSUE TITLE
all archived titles are marked wanted

### ISSUE THREAD

**Issue by dreaganluna** [evilhero/mylar#1738]
After the last couple of updates (9 commits) all issues that were marked archived are now marked wanted again. Which means that I'll have to do a lot of manual correcting right now.. : \

edit: not all archived issues though, as far as I can tell only currently runnng series have been affected.

**Comment by evilhero** [comment]
It was due to the updater incorrectly reassigning previous status when it was refreshing a series. 

As of the latest dev commit things should be cleared up and the status' will retain the correct settings on a refresh/db update running.

However, anything that was in an Archived status and got switched to Skipped/Wanted will have to be manually set to Archived again as Mylar no longer knows it was once Archived (the previous status' get cleared out on a status change).

If you're still experiencing problems going forward, please let me know. This bug started small and then really snowballed, so there were several 'fixes' for it over the last few week trying to address them and I think (really really hope) now they're finally fixed.
