### ISSUE TITLE
Trace back error?

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#1740]
Not sure what this is telling me. 

Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/volume1/@appstore/mylar/mylar/__init__.py", line 36, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "lib/apscheduler/schedulers/background.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler  File "lib/apscheduler/schedulers/base.py", line 11, in <module>
    from pkg_resources import iter_entry_points
ImportError: No module named pkg_resources

**Comment by barbequesauce** [comment]
What was happening when this was thrown? 
Can you send the portion of the log both before and after this error?
Can you reproduce this on-demand, or was this a one-time error?
If you can reproduce, can you send a log in debug mode?
What OS is your instance of Mylar running on?

**Comment by lostkt87** [comment]
I’m trying to manually start it by using 

python Mylar.py

 Then I get the trace back error.

**Comment by lostkt87** [comment]
It’s usually always worked. Now, not so much.

**Comment by barbequesauce** [comment]
Okay... can you start with the verbose flag in the command line (python Mylar.py -v) and send the rest of the console output?

What OS is your instance of Mylar running on? What version of Python?

**Comment by evilhero** [comment]
pkg_resources is a base install with python - so the fact that it's throwing a cannot find error seems abit weird.  There have been some users that have had problems starting Mylar after doing the upgrade where the scheduler system got upgraded.

The fix for them, was to go into the lib/apscheduler directory and then delete all the .pyc files therein and in each subdirectory (not the .py, just the .pyc). Python is supposed to regenerate the .pyc files for execution when it sees a file with an updated timestamp - so what might be happening is that it's trying to execute the old .pyc file located in the same location instead of generating a new .pyc file for the new .py file.

You could also shutdown Mylar, rename the lib/apscheduler to apscheduler.back and then do a manual 'git pull' from within the Mylar directory in order to force download the structure. 

Either one should work, just the 2nd is obviously abit more destructive since you're renaming a directory - but it fools it into thinking it's been deleted so it has to redownload everything from git from scratch ;)

**Comment by lostkt87** [comment]
Did the above and says already up to date

**Comment by barbequesauce** [comment]
You removed the pyc files?

**Comment by lostkt87** [comment]
Yes, after that then tried the renaming

**Comment by evilhero** [comment]
Something's not adding up here - what version of python are you running Mylar against ? (ie. if you type in ```python``` at a command prompt, which version is it coming back with?)

**Comment by lostkt87** [comment]
2.7.12

**Comment by lostkt87** [comment]
Is there a link to an earlier one? It’s weird, it’s been working just fine then when I tried to update, it wouldn’t update, I couldn’t shut Mylar down, now I can’t get it back on.

**Comment by evilhero** [comment]
how do you normally start Mylar up - as a daemon or just via the command line ? 

Normally if it doesn't update it's due to some local changes, or what git thinks are local changes and then it can't proceed to do an update. Renaming the apscheduler directory and then doing a 'git pull' in the root of mylar has been enough normally to force it to update properly and things are fine thereafter. 

I guess it could still be a few things:
- After you did the rename, did you do a git pull and did it spit anything back ?
- Did you install Mylar via git or via source (you downloaded the zip, extracted it, etc)
- Is there more than one instance of Mylar currently running ?

**Comment by lostkt87** [comment]
Running on a Synology. Verbose mode gets exact same error. Nothing changes.

**Comment by lostkt87** [comment]
Did a guy pull after, got an already up to date. 

I did a git clone

No other instance that I know of.

**Comment by evilhero** [comment]
Try backing up your config.ini, mylar.db and entire cache directory - then wipe the mylar directory and re-clone it - then move the backed up files back and start it up again.

**Comment by lostkt87** [comment]
Did not work

**Comment by evilhero** [comment]
You probably need to do either a ```sudo apt-get install --reinstall python-pkg-resources``` or a ```pip install setuptools``` depending on your OS / setup. It sounds like the pkg-resources got removed when you did an update or cleaned up something at some point earlier.

**Comment by lostkt87** [comment]
Thank you very much. Doing the pip install setup tools fixed it. Not sure how it got messed up. But it’s fixed now. I appreciate your time!!!
