### ISSUE TITLE
no pullist for this week

### ISSUE THREAD

**Issue by thingfromspace** [evilhero/mylar#1742]
I'm not getting anything in the pull list for this week. I'm using ALT_PULL=2 on git development branch.

```
2017-10-12 09:22:17 | INFO | [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 41
2017-10-12 09:22:17 | INFO | [WEEKLY-PULL] There are 0 issues for the week of 41, 2017
2017-10-12 09:22:17 | INFO | ALT_PULL: 2 PULLBYFILE: False week: 41 year: 2017

```

**Comment by thewindupboy** [comment]
Same problem here

**Comment by evilhero** [comment]
Yep, was a problem on the backend with some duplicate series being populated incorrectly. Should be all fixed up now - a Recreate Pullist from the Weekly tab will straighten things up again (or you can wait til the 4hr interval refresh happens too otherwise).

**Comment by thewindupboy** [comment]
Will we need a new release?

**Comment by thewindupboy** [comment]
Nope, I guess not!  Looks good here!

**Comment by evilhero** [comment]
When stuff happens to the pullist it's all happening on the backend site that Mylar polls against. 

So in these cases, it's stuff that can only be manually fixed on the site which will then populate down to all the clients running Mylar when their respective pull-list's get refreshed. 

It was designed like this on purpose too- it gives me more granular control over what matches with what and ensures the changes are sweeping when a fix is made on the site. As opposed to the opposite way whereby everyone would have to manage their own pull-list changes via an exceptions.csv file kinda process (which was a pita by itself) and then get muddled down in how things match, why they aren't, volume issues, etc.

**Comment by barbequesauce** [comment]
Interesting... I never realized there was a back-end you were hosting...

Are you able to collect any statistics using it?

**Comment by evilhero** [comment]
Well the main reason behind it was there was no all-in-one site for getting the pull-list information for a given week that also had an api - so instead of having every client poll against a given website (or sites) at a set interval, the backend site does the polling, and all the clients poll against the backend thereby saving the hammering et all. Plus it allows me to code changes that have an immediate impact (as that's usually very important), vs the update method via git which can be very delayed.

There's just basic hit counts that get tallied - that's the only thing that's being tabulated right now as I wanted to know the load vs. the usage kinda thing (ie. so it counts unique hits vs. non-unique hits) in order to make sure the usage wasn't outside of the norm. I don't want to go full bore on statistics collecting cause that would cause some privacy concerns, so what's being tabulated doesn't cross that line ;)

**Comment by barbequesauce** [comment]
very cool...

So where's the tip cup to keep the back-end running?

**Comment by evilhero** [comment]
haha - it's just the normal 'coffee' donation fund within the interface :) 

I just divert a few java's from there when it's needed since it's all for Mylar usage anyways ( plus the wife says I shouldn't drink so much coffee, but meh - she's not the boss of me! ) 

> *hears wife*
    What?? No - I would never say anything like that!

**Comment by thingfromspace** [comment]
Looks good! Thanks!
