### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1768]
What is the appropriate way to clear the cache directory in Mylar?  My cache is currently 14.8GB, and not getting any smaller.

**Comment by evilhero** [comment]
Wow - that's alot. I keep on forgetting about the cache - I'll need to add an option to clear the cache somewhere in the GUI so that it's easier/automated.

In the meantime, if you delete all the .nzb, .torrent, .cbr, .cbz files that should get rid of most of them. You can also delete any directory that starts with 'mylar_' (ie. as in mylar_839kd1 a random alphanumerical directory where the metatagging occurs). Bascially everything but the .jpg's are temporary in nature and can be removed (the .jpg's are the covers for each series that is on your watchlist).

**Comment by DrSeussFreak** [comment]
Thanks, that is a starting point, I will do so now, and imagine that will clear out the majority of it all :)

**Comment by evilhero** [comment]
Did you happen to notice if the majority of the files were in the ```mylar_``` folders ? These would have been left-over from metatagging, which should have been fixed quite a few dev commits ago. It's possible that they were stragglers from when there was a problem with the metatagging and it wasn't able to clean up afterwards (it should be deleting the ```mylar_``` cache folders after it successfully metatags/post-processes the given issue).

I can't see the torrent / nzb files taking up that much space but I suppose it's possible if you're attempting to backfill and entire publisher or the like ;)

**Comment by DrSeussFreak** [comment]
99% of it was all the directories
