### ISSUE TITLE
Permission Issues for Meta Tagging

### ISSUE THREAD

**Issue by allkindsofralph** [evilhero/mylar#1780]
_Mylar Version: development
-- git build fc76303af4d0e9c93f03cb8bb242afbf50147fe4.
Python Version : 2.7.10_

I am getting this error on a test file I am trying to meta tag:

> 2017-11-23 10:24:16 | WARNING | [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /Applications/Mylar/cache and/or the location where Mylar is trying to tag the files from.

I have given full read/write access to both my comic folder and the Mylar folder in the Applications folder on my Mac. But it still will not work. I can't figure out why conversion is not working.

**Comment by evilhero** [comment]
I believe it's due to the unrar location problem with Mac's (if memory serves).

You need to manually set the unrar path in the mylarroot/lib/comictaggerlib/ct_settings/settings.ini file (it's called unrar_exe_path). I don't think the unrar version matters, but from what I can recall of previous conversations, if the perms are correct in both the cache location and the original post-process location then the unrar is the next culprit (on MacOS' anyways)

**Comment by allkindsofralph** [comment]
What location should I set it to? Should it be to a generic post processing folder?

**Comment by evilhero** [comment]
You set it to where the unrar binary is on your system. Not sure about the default location for Mac - is there an unrar in like /usr/bin or something?

**Comment by allkindsofralph** [comment]
I was looking into the permissions some more and it seems that the folders being created from comictagger in the post processing are creating with restricted permissions with access to everyone as none. Even with turning off force permissions it does the same. trying to turn off permissions and restarting shows that the setting is not being saved. I had to turn it to false in the config file but still same issue.

I even tried setting permissions to 0777 just to give full access and issue persists.

**Comment by evilhero** [comment]
Are you running mylar in a docker or something - and how did you install it?

The user that runs mylar is where the perms are assigned from. If they don't have enough perms in a given directory to chmod it to what was entered into mylar then it can't chmod it.

What are the perms on the cache directory within mylar (that's where the metatagging takes place)?

**Comment by allkindsofralph** [comment]
I installed as instructed via the wiki through git on Mac through terminal. I had it running as a daemon, and now I run it as a Automator app, but neither will allow CBRtoCBZ to allow tagging. Full 777 permissions on Download location and Mylarroot/cache folder but doesn't seem to work still. I still keep getting warnings and it keeps appending .BAD to the end of the files. So I need to turn off tagging so it can move and rename the files for me.

**Comment by evilhero** [comment]
Try the latest development commit as of now. There were some things that came up in the last few hours that might have actually fixed this problem - especially the .BAD filenaming (although I havent' been able to confirm this as of yet)

**Comment by allkindsofralph** [comment]
Sadly same effect. I might try and setup Mylar on a Linux VM just to see if post processing will work through there as a last resort. I wish I could think of more to try

**Comment by allkindsofralph** [comment]
Conversion using a separate install of Mylar in a Parallels VM works, if only it all worked normally. Hope it gets sorted out in the future or I can find the issue. Since it works in the VM do you think that would confirm issue is not with permissions?

Either that or I might need to make the VM my main install of Mylar and move some other services there for ease such as SABNZBD and such.

**Comment by evilhero** [comment]
Sorry didn't see this til now for some reason - if it worked in the VM, but not in the docker then the issue would be the permissions with the docker. Since the cache folder resides within the docker container itself, you'd be getting the permissions based on the user running the docker (ie. never run a docker as root). There are others that have dockers running of Mylar, and several had experienced permissions issues of this nature - but it usually came down to the docker itself and/or the user that initiated the docker.
