### ISSUE TITLE
When clicking "This Week" Pull-list throws: microseconds is an invalid keyword argument

### ISSUE THREAD

**Issue by bguidotti** [evilhero/mylar#1788]
I am running this on Windows 10 v1703, no errors on startup, Python 2.7.13.
This is on the newest development build.  Prior to this 'git pull,' this was working.

Traceback (most recent call last):
File "C:\Mylar\mylar\lib\cherrypy_cprequest.py", line 645, in respond
response.body = self.handler()
File "C:\Mylar\mylar\lib\cherrypy\lib\encoding.py", line 188, in call
self.body = self.oldhandler(*args, **kwargs)
File "C:\Mylar\mylar\lib\cherrypy_cpdispatch.py", line 29, in call
return self.callable(*self.args, **self.kwargs)
File "C:\Mylar\mylar\mylar\webserve.py", line 1500, in pullist
weekinfo = helpers.weekly_info(week, year)
File "C:\Mylar\mylar\mylar\helpers.py", line 2863, in weekly_info
weekly_last = weekly_last.replace(microseconds=0)
TypeError: 'microseconds' is an invalid keyword argument for this function

**Comment by evilhero** [comment]
LOL - this was just a stupid error, but it took me awhile to find it because of a whole bunch of errors I was fixing in relation to the timestamps. Once I fixed those, this error popped up and I fixed it - for reference, it was supposed to be ```microsecond```, not ```microseconds```.

Now it's on to binge drink for the next 5 minutes....

**Comment by bguidotti** [comment]
Nice clutch fix!
I will close this bad boy out.

Thanks.
