### ISSUE TITLE
Issue count on search off by 1

### ISSUE THREAD

**Issue by langbard** [evilhero/mylar#1799]
The issue count for series when searching to add appears to be consistently one less than the actual number of issues. Should be fairly reproducible but let me know if I can help. Currently on 48c30f150ff6a9f99ea7f1be3ba99c5fd478da4d of the development branch.

**Comment by evilhero** [comment]
This is actually normal behaviour believe it or not. The CV API doesn't hold the same values as the CV website - so when you see the info on the actual website, the API doesn't update until later in the week (I've noticed on Fridays previously but that was a long time ago). With some series, they don't ever update from the 0 count.

So there's no way to actually get it to the proper tally count without invoking more API calls against CV in order to get the actual total issues returned by the system. At one point early in the development, Mylar was assuming the CV total was correct, and then comparing it to the actual issue count it was able to tabulate on it's own as it queried CV for the info - whichever was bigger it would take as the numeric. 

But it was buggy as hell, and wouldn't work in some cases, got it wrong in others - it was literally just a pain to troubleshoot. So, I'm apprehensive to just go ```+1``` to every issue count total returned by CV, because at some point (if it's a new series especially), the count will go up by one on CV and then the determining factor about which is right vs. wrong comes into question again.

If it's possible to get an accurate count from CV in some way every time without invoking more API calls (think of a search returning 100+ results, that could be 100 extra API calls possibly in some instances) then I'd be willing to implement it to test things out - but as far as I'm aware CV hasn't changed anything in regards to the issue counts being correct in a timely manner, in years if ever.

**Comment by langbard** [comment]
Thanks for the explanation, I'll close the issue then.
