### ISSUE TITLE
32p account disabling due to reCaptcha

### ISSUE THREAD

**Issue by rrawb** [evilhero/mylar#1801]
More of an FYI, but just letting you know that I've had 2 instances in <24 hours where my 32p account has been banned because Mylar is failing the reCaptcha code when attempting to log in.

**Comment by evilhero** [comment]
Mylar cannot signon if the captcha is present - thus the reason why it uses the session cookie after an 
 initial successful signon. If the session cookie is present, it will bypass the captcha and can signon without any problems.

As long as you've been able to signon with Mylar at least once, the session cookie will be available for usage. But if you've changed your password, and/or the cookie has expired (I think it lasts 6-9 months from recollection), then it will fail and attempt to use the login/pass which would again fail if the captcha is present. If you've never signed on, and this is the first attempt - you unfortunately need to wait until the catpcha is no longer present on the signon screen, and then Mylar will be able to signon, create the session cookie for future use.

If you've changed your password, you can delete your .32p_cookies.dat file in the cache folder. That is your session cookie for 32p and holds the information that it uses to logon. From the sounds of it, either the 32p_cookies.dat file is incorrect due to a password change or it's expired. You'd have to delete it and then let Mylar recreate it once the captcha is no longer present on the logon page (ie. as of this exact moment, the captcha is not present).

**Comment by voor** [comment]
I'm not sure I understand how the login process is meant to work if you've never logged in successfully before.

**Comment by evilhero** [comment]
It will create a cookie stored locally once you've authenticated to 32p. 

If however the captcha is up on the 32p site, and you've never used Mylar to sign on prior (successfully) , you won't be able to authenticate until the captcha is removed and any attempt will fail. This is because 32p doesn't have an api, so Mylar has to authenticate using basic authentication.

**Comment by voor** [comment]
Do you have any documentation on how I could just login from a browser and then copy that cookie into a local file?  There's some cloudflare cookies, but it looks like a typical `session` and `user_data` cookie otherwise.  Right now my cache folder only has `jpg` files and `txt` files for releases.  I'm in a typical NAT situation, so both my browser computer and server running mylar are the same public IP.
