### ISSUE TITLE
Latest Update Deletes Root Folder

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#1803]
When a comic is in a folder (ie d:\_done\comics) that is unrelated to the issue, it deletes that directory.

As an example, I have d:\_done\comics as the folder Mylar monitors for new issues I manually download.  as an example, say I put War Stories issue 25 in that directory, but the file was alone, not in a directory of the same name.  Mylar remove the comics directory during clean-up.

**Comment by evilhero** [comment]
Is it literally d:_ or was that a typo?

Mylar doesn't pay attention to the folder name, so whether it's in its own directory or not doesn't really have any bearing on the file being deleted.

If you have you folder monitor set to done instead of done\comics then yes mylar would delete the comics dir as it's beneath the root monitor folder. I have tested this numerous times just in the last few days due to other problems being worked on, and it never once deleted the root folder location.

If it's doing it and the monitor is set as above - then I would need to see debug logs showing the workflow and thr tidy-up sequence.

**Comment by DrSeussFreak** [comment]
d:\_done\comics

and this was an issue in the past, then it was fixed, now it seems to be happening again.  I reproduced it, and debug logs are attached
[logs.txt](https://github.com/evilhero/mylar/files/1537025/logs.txt)

**Comment by evilhero** [comment]
Nothings changed with the pp stuff over the last while, so I'm wondering what's going on or if it's some kind of windows only related issue.

Have you tried changing the folder path to include a trailing slash?

**Comment by DrSeussFreak** [comment]
That is what it is set to (see screenshot)

![screen shot 2017-12-06 at 7 50 03 pm](https://user-images.githubusercontent.com/175500/33694616-c7c2ce56-dabe-11e7-8d20-3d8b805608ea.png)

**Comment by evilhero** [comment]
And trying it without the trailing slash does the same thing? I'm wondering if it's just failing to parse things properly due to the slash...

**Comment by DrSeussFreak** [comment]
I removed the trailing slash and the issue is gone, craziness, but it works!

**Comment by evilhero** [comment]
Will have to patch that as it shouldn't matter ;) thanks for coming back and saying it worked like that!
