### ISSUE TITLE
mylar not recognizing some files

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1805]
i mainly have a problem with the nickelodeon avatar comics.

https://comicvine.gamespot.com/nickelodeon-avatar-the-last-airbender-smoke-and-sh/4050-84748/

mylar doesn't recognize the files on my HDD

for the third issue of this series i've now tried these names

Avatar - The Last Airbender - Smoke and Shadow Part - three (2016)
Avatar - The Last Airbender - Smoke and Shadow Part - 003 (2016)
Nickelodeon Avatar The Last Airbender - Smoke and Shadow (2015) Part Three #003

but mylar is still saying that i have 0/3 files... :(

**Comment by HypKin** [comment]
ok, must've been the alternate naming i choose (i skipped the nickelodeon part on the initial files, also the downloads didn't work with the nickelodeon in it) very strange ...

it's working now, but i still have a qustion concerning the alternate naming:

does the alternate naming work on the file check AND the download? and how?

**Comment by evilhero** [comment]
The last one should work. The title has to appear exactly as to how it appears in CV otherwise it won't match. So with the ```Part - three``` and ```Part - 003```, the ```Part``` is not part of the title in CV, but based on the naming Mylar would assume that the word ```Part``` is actually apart of the series title itself, and thereby not match.

The Alternate Name works on file-check/download/post-processing - it just adds it as an alias and then will alter what it does to accommodate the alias as an extra step. So if it's searching for example, it will search for the CV name as it has it first, and then do a subsequent search for the alias. 

The Alternate File Naming might be something for you to consider as well given the title. With this option filled out, you would put in how you want all the titles in the series to be named (which would have to be different than CV), so ```Avatar - The Last Airbender - Smoke and Shadow``` instead of it having to include the Nickelodeon portion. Then it will rename all the files to this naming convention when performing post-processing, or performing a Rename Files (instead of it being named identical to the CV title)

Using both the Alternate Search Name and Alternate FileName could be advantageous in this particular case depending on your preference to the filenames.

**Comment by HypKin** [comment]
i think that the title in CV changed at some point, maybe this led to this confusing thing. I remember that one day suddenly all the other avatar series machted 0 files. i havent had time until now to look into it thoug... whatever, its working now :)

thx
