### ISSUE TITLE
nzbToMedia times out but am able to access Web UI

### ISSUE THREAD

**Issue by mgaulton** [evilhero/mylar#1811]
https://github.com/clinton-hall/nzbToMedia/issues/1313
I opened this over on the nTM git but it was pointed out it should likely be over here.

this looks like an issue with Mylar.

File "/opt/mylar/mylar-master/mylar/PostProcessor.py", line 2119, in Process_next
filename_in_error = os.path.split(pcheck, '||')[1]
TypeError: split() takes exactly 1 argument (2 given)
they should not be doing os.path.split(pcheck, '||')[1] as os.path.split only accepts 1 argument.

**Comment by evilhero** [comment]
Weird nothing has changed on the master branch in almost 2 months, so it's really weird it's happening.

The split error is occuring because it can't find the file during metatagging which should be returning a splitable string, but because of the error it isn't.

I'm not sure if this is fixed in dev as there are a huge amount of changes in there still not in master, but it's a possibility it's already been fixed.

It says it couldn't locate the file in its db initially, which would imply you're running the script on a download not initiated by Mylar?
