### ISSUE TITLE
Unable to load series with non integer issue numbers

### ISSUE THREAD

**Issue by ghost** [evilhero/mylar#1819]
I've come across three series that are continually stuck on loading. I think I've been able to track it down to each having an issue number that is not an integer. The three series are:

4050-20176 (Lady Death/Shi has issue Preview)
4050-22081 (Shi Senryaku has issue TPB)
4050-26450 (School Rumble has issue 14-16)

Message in the logs:

WARNING	Shi: Senryaku has not finished loading. Nulling some values so things display properly until they can populate.
WARNING	Lady Death/Shi has not finished loading. Nulling some values so things display properly until they can populate.

**Comment by evilhero** [comment]
Well the TPB and Preview issues wouldn't work as is - Mylar doesn't fully support TPB numbering/series, so if it comes across it when checking CV, it's kinda of hit and miss because unfortunately CV doesn't standardize things (ie. normally the TPB would not be included as part of an issue series, but be it's own CV # - which wouldn't cause any problems with Mylar therein). I do believe the 'Preview' issue might be possible, but I'd have to test against it.

The '14-16' I might be able to fix as well, but again - these are pretty specific problems that if fixing it causes issues with the general importer/filechecker, I would be hard-pressed to implement unfortunately. Because even if it was able to import the series properly with these issue numberings, the filechecker has to be able to query/parse against it and if it can't do that - it's not really going to matter in the long run ;)

**Comment by langbard** [comment]
Ideally, if you could fix it for those that without breaking the main usage, that would be great. If not, would it be possible to still get it to fail nicely and still load the issues it can handle and just ignore the others? Also, if you can point me to the spot(s) that would need changed, I can take a look and see if I can figure out a fix.
