### ISSUE TITLE
Error and Unable to Succesfully Add Series

### ISSUE THREAD

**Issue by luciusrenard** [evilhero/mylar#1829]
Although I am able to add a series (i.e. an entry is created on the home page), it never populates with any information, besides the Comic ID. The log is showing the following error message:

```
Uncaught exception: Traceback (most recent call last):
File "c:\Mylar\mylar\logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "c:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "c:\Mylar\mylar\importer.py", line 233, in addComictoDB
comlocation = os.path.join(mylar.CONFIG.DESTINATION_DIR, helpers.replace_all(chunk_folder_format, values))
File "c:\Python27\lib\ntpath.py", line 65, in join
result_drive, result_path = splitdrive(path)
File "c:\Python27\lib\ntpath.py", line 115, in splitdrive
if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
```
How can this be corrected?

Thank you!

**Comment by evilhero** [comment]
Just posting the error itself is not helpful without the context. Throw in the lines leading up to this error so I can understand what you're attempting to do from where.

Best guess without seeing the additional info, is your Comic Location is not set.

**Comment by NiteAngyl** [comment]
Hello,

I just experienced a similar error. My config is set up like my previous installation-- with the Comic Location set to the right directory.

I've just performed a fresh git clone of Mylar's development branch. Mylar worked just fine before this clean install. Now, when I want to import my comic directory, I get the following error in my log:

```
2018-01-02 11:28:44	WARNING	Error fetching data from ComicVine: [Errno 2] No such file or directory

2018-01-02 11:28:31	ERROR	Uncaught exception: Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/mylar/mylar/logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "/opt/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/share/MD0_DATA/.qpkg/mylar/mylar/webserve.py", line 3930, in preSearchit
logger.fdebug('[IMPORT] [' + str(len(sresults)) + '] search results')
TypeError: object of type 'bool' has no len()
```

I'm running Mylar through tmux on a Qnap NAS with the latest firmware, and Mylar currently runs on Python 2.7.13. The ComicVine site seems to be up and running atm, and the api key corresponds.

My comics are ready to be imported but they are unable to because of this error. I'm not sure in which file I have to look to see whether or not ComicVine's url has been specified correctly.


With best regards and a happy new year,
NiteAngyl.

**Comment by luciusrenard** [comment]
My bad! Apologies for omitting the lead-up to the error. You were correct, however, that is was the Comic Location not being set, another omission on my part.
