### ISSUE TITLE
Eliminate Series Folders but Keep File Renaming?

### ISSUE THREAD

**Issue by luciusrenard** [evilhero/mylar#1831]
Is there any way to eliminate series folders but keep the file renaming? For instance, have all of the downloaded files appear in the same folder but have the files renamed as per the conventions established in Mylar?

Thank you in advance for any help!

**Comment by evilhero** [comment]
Nope you can't eliminate series folders entirely - you can however turn off folder creation so that it will only create the series directory when issues are pp'd into them, or new series are added (in the config.ini, set create_folders to False). Mylar has to be able to monitor a given directory for a specific series, due to naming conventions, duplicate issue numbering, etc.
