### ISSUE TITLE
Remove Archived file selections

### ISSUE THREAD

**Issue by JaBaine** [evilhero/mylar#1836]
I have a number of series that have incorrect numbering relating to the have banner

![image](https://user-images.githubusercontent.com/3401143/34630445-25b74eb4-f23a-11e7-81e7-065a00834800.png)

I have a feeling it has something to do with having some issues that I had marked archived manually. 

05-Jan-2018 17:00:11 - INFO    :: Thread-18 : [FILE-RESCAN] Now checking files for Batgirl (2016) in D:\Media\Comics\DC Comics/Batgirl/V2016
05-Jan-2018 17:00:11 - INFO    :: Thread-18 : there are 19 files.
05-Jan-2018 17:00:11 - INFO    :: Thread-18 : [FILE-RESCAN] Total files located: 19
05-Jan-2018 17:00:11 - WARNING :: Thread-18 : [FILE-RESCAN] It looks like you have physical issues in the series directory, but are forcing these issues to an Archived Status. Adjusting have counts.
05-Jan-2018 17:00:11 - INFO    :: Thread-18 : [FILE-RESCAN] I have physically found 19 issues, ignored 0 issues, snatched 0 issues, and accounted for 1 in an Archived state [ Total Issue Count: 20 / 19 ]

How would I remove the archived status?

**Comment by evilhero** [comment]
You'd have to go into the series within Mylar and set each issue that's incorrectly marked as Archived to a status of Skipped. 

Then once you're done that, do a Recheck Files in order to rescan everything and hopefully it would clean itself.

Keep in mind that you can have an issue marked as Archived and have the same issue reside within the series directory. Mylar will try to count it as a Downloaded issue, but the status will be forced to Archived (or something similar, can't recall exactly atm)
