### ISSUE TITLE
Issue with number padding.

### ISSUE THREAD

**Issue by Lasborg** [evilhero/mylar#1843]
I have an issue with issue number padding.

Right now I have it set to 0x, but when I rename a series with 12 issues the files change to #01-#09 and then #010, #011 and #012
Should there be a leading zero on 10-12?

Mylar Version:  development
 -- git build 828ddb012423cef178e53c959d1c80d5ccd79b3b.
Python Version : 2.7.13

**Comment by Lasborg** [comment]
Woops github changed the numbers
It is 01-09 and 010, 011, 012.

So there are leading zeroes on the 10-12 where it should not be.

**Comment by evilhero** [comment]
No that's actually correct the way it is. The 0 means it will pad one zero as required, 00 means 2 (the x would denote an asterisk, it's not the total length of the numeric) . So if it's a 2 digit number it would get a single pad, a one digit number would get a 2 digit pad, and a 3 digit number would get no pad.

**Comment by Lasborg** [comment]
Just changed the settings to 00x and I then as per your description, I get the numbers 001-012 which is fine.
But I am still not sure that it at least is the most user friendly way of doing it. But I recon that there are different philosophies on number padding. I would always go according to the length of the number of the no make a nice even file list :)

Just one question if I choose 0x and rename a series of more than 100 issues will the numbers then be eg: 07, 029, 0142 

And is the option to choose format as "none" not a bit odd as there already a checkmark that could be unchecked if no padding is needed.

**Comment by evilhero** [comment]
I'm pretty sure the limit was 3 characters, so it would be 07,029,142 - but it's been awhile since I checked that part of the code.

As far as the None you could have no padding, which would mean it would rename any issue numbers with padding to be just the digits themselves (ie. 7,27,142) for consistency.

Obviously turning off the padding itself would leave the numbers as they originally appear.

There might be some arguments for a different methodology for number padding - what was implemented was what was requested by the majority of users at the time.

The problem with numbering based on length is that 01, 010, 011, 100 are sequential, numerically but when viewing a file listing the OS doesn't know it is  supposed to be considered numeric and treats the whole thing as a string. So with the same sequence but based on string comparisons, a series might look like 01,10,100,11 (based on what you though on your initial post) ...which I believe is one of the reasons why we did the padding the way it is.

**Comment by Lasborg** [comment]
Thanks for the great explanation, it cleared a lot up for me.
I will set padding to 00x for the best result. 
Thanks again
