### ISSUE TITLE
Forms based login does not allow ComicRN to do post processing.

### ISSUE THREAD

**Issue by claym** [evilhero/mylar#1845]
```
ERROR | Wed Jan 17 2018 22:17:43 | Post-process-script ComicRN.py for <comic> failed
-- | -- | --
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: </html>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: </body>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: </form>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: </div>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: <button>Sign in</button>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: <input type="password" placeholder="password" name="password" required />
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: </div>
INFO | Wed Jan 17 2018 22:17:43 | ComicRN: <i></i>
```

Other than that, works great! Perhaps on the form route check to see if the username/password were passed in and bypass the form?

**Comment by evilhero** [comment]
Fix is almost finished. Hopefully by tomorrow you can test it out

**Comment by evilhero** [comment]
This is in development, but you have to update your existing autoProcessComics.cfg and autoProcessComics.py to accomodate the change. The autoProcessComics.cfg has changed in that it no longer presents for a username/password, it just needs the mylar apikey. So if you don't have one generated, you need to generate it first within Mylar, save the config, plunk the apikey into the autoProcessComics.cfg file and be done with it ;)

If you're not using forms login, you can still upgrade the 2 files - it's only required if you're using forms authentication. Otherwise you can use the legacy autoProcessComics.py/.cfg files without upgrading.
