### ISSUE TITLE
Documentation for Tagging

### ISSUE THREAD

**Issue by Aquenon** [evilhero/mylar#1848]
[Comic Tagging.pdf](https://github.com/evilhero/mylar/files/1679296/Comic.Tagging.pdf)

**Comment by evilhero** [comment]
Looks good! Or at the very least it's a very good starting point for further discussion as new items are added in the future. 

Thanks for doing this. I'll open up the wiki edits and you can add this in under your nick so the credit is yours :)

**Comment by Tucker28** [comment]
I just put it into a document, you’re the one who patiently explained how to do it. But I can do that, I’ll come back later today to the site when I’m on my computer and not my phone.

**Comment by Tucker28** [comment]
I have a weird issue where it's not converting to CBZ on tagging for some comics. Others it does convert. Log shows meta tagging was successful. Is there a reason why it converts some to CBZ but not others? I should put that into the documentation for it.

Also, there is no method of posting to the wiki that I can find.

**Comment by evilhero** [comment]
It could be that the cbr is corrupt. It happens sometimes with newsgroup downloads, not often but it does happen. If you enable verbose logging, and try the tag again it should indicate the actual response during the conversion and any reason why it failed.

**Comment by Tucker28** [comment]
I thought about that at first as well. But I am able to unrar it manually just fine. Zip it up, change the extension, and then go about my business. Doesn't seem to be causing any issues, it's just odd.

**Comment by evilhero** [comment]
When you're manually extracting it, are you using the same version of unrar that mylar is using when it runs comictagger? 

There have been some instances whereby a particular version of unrar wasn't able to unrar certain types of rar files due to changes in specifications (I believe it was like the 5.40 branch and was due to timestamp comparison failures within that version of unrar, and again seemed to mainly happening with MAC OS users). 

If you check the contents of the rar file, it should say a ```ver``` (version) beside each file within the given cbr. I'm not 100% sure, but I think 2.9+ could have been an issue as well.

**Comment by Tucker28** [comment]
I thought that was it. I was using 4.20. I upgraded to 5.50. However, doing the same thing. If I didn't know it was supposed to convert to cbz, I would think it is working. Here are the logs for one issue. The rest of them all say the same thing. It looks like it is working, but it's outputting a car.


2018-02-02 20:05:25 | INFO | [MANUAL META-TAGGING] Sucessfully wrote metadata to .cbz (Alpha Flight #12.cbr) - Continuing..
-- | -- | --
2018-02-02 20:05:25 | INFO | [META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [/Applications/Python Scripts/mylar/cache/mylar_7QpWEK/Alpha Flight #12.cbr]
2018-02-02 20:05:22 | INFO | [META-TAGGER] Comicbooklover tagging meta-tagging processing started.
2018-02-02 20:05:22 | INFO | [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/Applications/Python Scripts/mylar/cache/mylar_7QpWEK/Alpha Flight #12.cbr]
2018-02-02 20:05:18 | INFO | [META-TAGGER] ComicRack tagging meta-tagging processing started.
2018-02-02 20:05:18 | WARNING | [META-TAGGER][COMIC-TAGGER] file is not in a RAR format: Alpha Flight #12.cbr
2018-02-02 20:05:17 | INFO | Attempting to move: move
2018-02-02 20:05:17 | INFO | New_Filepath: /Applications/Python Scripts/mylar/cache/mylar_7QpWEK/Alpha Flight #12.cbr
2018-02-02 20:05:17 | INFO | New_Folder: /Applications/Python Scripts/mylar/cache/mylar_7QpWEK
2018-02-02 20:05:17 | INFO | Filename: Alpha Flight #12.cbr
2018-02-02 20:05:17 | INFO | Filepath: /Volumes/Media/Comics/Marvel/Alpha Flight (1983)/Alpha Flight #12.cbr

**Comment by evilhero** [comment]
Well it says right in the log: ```WARNING[META-TAGGER][COMIC-TAGGER] file is not in a RAR format```.

So of its a .cbr and it's an actual rar then the unrar that comictagger is using can't read it, which would imply that its not the correct version that is being used. 

Are you sure the path location you specified for the unrar binary within mylar is pointing to the right unrar? If you run it from a command line against that rar field, it should result in the same error. 
From an old issue with regards to unrar, the version that was found that works is 4.24 - there was a link on the forums to it, but can't find it atm. Again this seems to be only a problem with MACs, but it might be time to do away with the unrar wrapper that CT uses.

**Comment by Tucker28** [comment]
Yeah, it's pointing to the right exec. Two different versions have been having the same problems. But the vast majority of issues it unrars and tags then zips. It's only about 2 or 3% of cbr files that it has trouble with.

My GUI app that I use manually can unrar them just fine. I am thinking that those aren't actual cbr files. Maybe they are cbz files that were changed to the wrong extension (the log does say that it is a cbz and a cbr file in the same line, which is what gave me the idea). The GUI app handles zip, rar, 7z, and many more... So that might be why it can open them.

I'm away for the weekend, but when I get home, I'm going to change the extension on a few of them to cbz and then see what happens. The few books it has happened on aren't my favorite series anyway. It's all 3 volumes of Alpha Flight, then a few issues here and there. If nothing else, I'll expand them and then compress them to cbz manually and then run them through.

**Comment by Tucker28** [comment]
I never did see anything on the wiki page where I could upload that document.

**Comment by evilhero** [comment]
Yeah that's my fault I ha e to enable the wiki edit for you to paste in. I'll do it later tonight when I'm on the laptop, as I can't do it on the phone atm.
