### ISSUE TITLE
If folder scan processes files before nzbget postprocessing, postprocessing hangs

### ISSUE THREAD

**Issue by mneko** [evilhero/mylar#1853]
If the title is confusing, the flow ends up like this.
NZBget has big list of comics.
Some comics languish in pp-queued status.
Mylar's own folder scan finds the files and moves them before nzbget can process them.
comicrn.py hangs forever while throwing a "There were no files located - check the debugging logs if you think this is in error" error.

I fixed this on my end by changing postprocessor.py
``` 
if filelist['comiccount'] == 0: # is None:  
                    logger.warn('There were no files located - check the debugging logs if you think this is in error.')  
                    return
```
to
``` 
if filelist['comiccount'] == 0: # is None:  
                    logger.warn('There were no files located - check the debugging logs if you think this is in error.')  
                    break
```
but I don't quite know enough about python to tell if this damages anything. 

Hotlink to the line for ez reference:
https://github.com/evilhero/mylar/blob/be28ccaa2886914bb2f016b0dae99a59cd6f3f0b/mylar/PostProcessor.py#L320

**Comment by evilhero** [comment]
You shouldn't have mylar monitor the same directory where the nzbget downloads go to. ComicRN will pp from any given folder as that's indicated by nzbget where the final destination will be.

What's happening is that comicRN runs, it tries to pp it and then the folder monitor kicks off and attempts to pp the same issue.  This results in the exception since its no longer in the location it's supposed to be (either comicRN or the monitor having moved it already). As an aside this also applies if you're using comicRN and completed download handling enabled as you can have only one enabled. 

So simple solution in this case is to have either nzbget send completed downloads to another directory, or just set the folder monitor to monitor a different location (or I guess you could even not use comicRN and the folder monitor would pick them up albeit it will lose some accuracy matching in some cases). 

The fix you indicated would stop pp'ing the current issue instead of throwing the exception, but the end result in both cases would be the same.

**Comment by mneko** [comment]
But that's too easy lol.

Thanks for replying so fast.

**Comment by evilhero** [comment]
No worries - you happened to catch me after the kids went to bed ;) 

I'm not 100% positive that the solution(s) I provided will fix things, but based on similar problems , it should.

Alot of these workflow problems also need to be documented much better within the program so it's easier to work with (that's a memo to remind myself).
