### ISSUE TITLE
Post process not actually triggering automatically

### ISSUE THREAD

**Issue by NixFifty** [evilhero/mylar#1854]
Relatively new Mylar user so I may be missing something obvious.

I have Settings -> Quality & Post Processing -> Enable Post Processing checked and to copy files but they don't seem to be getting copied to my /comics directory.

My comics location and downloads location are both set so I'm not sure what I'm missing. The logs don't seem to be indicating much either. 

If however, I trigger a manual post process, it works as expected.

**Comment by evilhero** [comment]
The enable post-processing option has to work in conjunction with another option, depending on how you are downloading.

If you use sab/nzbget you would need to either enable completed download handling, or use the comicRN script.

If you use torrents, there is no monitoring of torrents with mylar (unless you use deluge or rutorrent remotely, aka seedbox). 

If you run your torrent client locally, then you have to have Mylar monitor your completed location via the Folder Monitor option (ideally it would be your comics directory, but otherwise just the final torrent location). Mylar will then check the given folder every x minutes to see if anything can be post-processed - if it's still downloading, or the series doesn't exist on your watchlist it won't touch it. 

Note that in this last case, you probably want to change the post-processing action to either copy/link depending on your OS, metatagging and if you want to continue seeding.
