### ISSUE TITLE
Post-Processing replicates file in Cache directory until disk drive is full

### ISSUE THREAD

**Issue by lodasi** [evilhero/mylar#1859]
Post-Processing does not succeed. I have it set to move and the file is copied into the post-processing location in the cache folder under mylar-development. However, after the directory check, the thread no longer logs any activity and the same file is detected during the next post-processing thread and copied into the cache folder. I had hundreds of copies of the same file in different mylar-development/cache/mylar_XXXXX folders.

Regular Log: https://pastebin.com/ZcTBjhGH
Debug Log: https://pastebin.com/kM0PwN6C

**Comment by evilhero** [comment]
It's trying to do what it's supposed to - it copies it to the cache to perform metatagging and then moves it from the cache folder to your series folder. It then cleans up both the cache folder and the original file location thereafter. It's failing to move it from the cache to your series folder. 

One problem is you're supplying INFO level debug logs indicating that's there's some problem - when INFO level logs don't really mean anything for troubleshooting. Set Mylar to run in verbose/debug mode and log a post-process run again. Then look at it, or paste it back in here so I can look at it, as it's impossible to figure anything else out otherwise.  

The fact that it never updates the status, which would then stop subsequent pp runs of the same issue, indicates that it's failing to move the file to the final location due to something stopping it. 

If I were to wager you're either running out of space on the destination location, or permissions aren't set properly to allow the user running mylar to move the file.

**Comment by lodasi** [comment]
The destination drive had over half a TB free. Nothing weird when it came to folder permissions. I had to manually rename the file, but then manually running post-processing via the web interface with the file occurred without a problem, although the original CBR file was never deleted.

**Comment by evilhero** [comment]
If the original was never deleted and you have move enabled, then it didn't complete the pp run for some reason.

There's nothing at a glance that jumps out from the logs that would indicate something is amiss.

If you had some unknown option enabled for your rename files it might cause  problem, but it should indicate something of that sort. What is your folder and file format set to? Do you have any other rename options enabled?

Does this happen with juat manual run stuff or are you sending it from your nzb client?

**Comment by lodasi** [comment]
I don't run any post-processing using the nzb client. Files are downloaded to the monitored folder and Mylar used to handle all the rest. 

I have not changed my rename scheme ever.  "$Series $Issue ($Year-$month)"

The thread just seems to die at the [POST-PROCESSING][move] step. I've tested with more files and the same behavior recurs.

**Comment by lodasi** [comment]
The file that triggered this behavior was downloaded by Mylar at 2:10 am.

**Comment by evilhero** [comment]
This is probably related to #1861, which I should be able to fix this am

**Comment by lodasi** [comment]
It worked! Thank you!
