### ISSUE TITLE
Story Arc management missing option to mark all and add to wanted.

### ISSUE THREAD

**Issue by Outcats** [evilhero/mylar#1865]
As with the title, I can't mark all issues as wanted now and have to click wanted on each individual issue. There also is no longer the drop down to state what I want to do to each ticked open.

It adds all new issues as Skipped which stops the search for missing from working.

This is on Safari on iPad as well as Edge on Windows 10.

**Comment by evilhero** [comment]
There was never an option to mark all issues as Wanted from a Story Arc perspective. Right now, the Wanted status is taken directly from the watchlisted series, so if anything that is not on your watchlist but is in an Arc is set to Skipped. Otherwise, it's a manual process to mark the issue as Wanted via the 'Grab' option. The 'Search for Missing' does just that - anything that is in a Skipped status will be searched against. If it's not searching the Skipped status stuff, then there's some other error stopping it from running properly.

Again, this is a slow process to convert everything over to the one main Wanted list. Currently the Wanted Story Arc issues have now been merged into the existing Wanted list, which means that the they now follow the same search workflow as the normal issues, so doing a ForceSearch or doing the RSS check will search against any arc that's in Wanted status. 

Changing of status will be next, but unfortunately there are other bugs currently happening atm that need to be addressed before that gets done.
