### ISSUE TITLE
32p with rtorrent

### ISSUE THREAD

**Issue by Tucker28** [evilhero/mylar#1874]
I have 32p set up, and I have rtorrent to my remote seedbox set up and working, and connecting. But when the search happens, nothing works and it gives me an error. I did a manual search of one issue so I could easily find the correct logs.

I'm doubtful this even works as 32p uses torrent files and not magnet links. Is that correct?

Scott

2018-02-27 16:24:25 | ERROR | Uncaught exception: Traceback (most recent call last):File "/Applications/Python Scripts/mylar/mylar/logger.py", line 177, in new_runold_run(*args, **kwargs)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/Applications/Python Scripts/mylar/mylar/webserve.py", line 1340, in queueissuefoundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe, allow_packs=AllowPacks)File "/Applications/Python Scripts/mylar/mylar/search.py", line 255, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff)File "/Applications/Python Scripts/mylar/mylar/search.py", line 546, in NZB_SEARCHa = auth32p.info32p(searchterm=searchterm)File "/Applications/Python Scripts/mylar/mylar/auth32p.py", line 38, in __init__if not lses.login():File "/Applications/Python Scripts/mylar/mylar/auth32p.py", line 594, in loginif (self.test_login()):File "/Applications/Python Scripts/mylar/mylar/auth32p.py", line 565, in test_loginif (self.valid_login_attempt(self.un, self.pw)):File "/Applications/Python Scripts/mylar/mylar/auth32p.py", line 498, in valid_login_attemptlogger.error(self.module + " Got an exception when trying to login to %s POST [%s]", (u, e))File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1193, in errorself._log(ERROR, msg, args, **kwargs)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1286, in _logself.handle(record)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1296, in handleself.callHandlers(record)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 1336, in callHandlershdlr.handle(record)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 759, in handleself.emit(record)File "/Applications/Python Scripts/mylar/mylar/logger.py", line 42, in emitmessage = self.format(record)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 734, in formatreturn fmt.format(record)File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 465, in formatrecord.message = record.getMessage()File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 329, in getMessagemsg = msg % self.argsTypeError: not enough arguments for format string
-- | -- | --
2018-02-27 16:24:24 | INFO | Shhh be very quiet...I'm looking for Green Lanterns issue: 37 (2018) using 32P
2018-02-27 16:24:24 | INFO | Could not find Issue 37 of Green Lanterns (2016) using Oznzb [rss]
2018-02-27 16:24:24 | INFO | Shhh be very quiet...I'm looking for Green Lanterns issue: 37 (2018) using Oznzb(newznab) [RSS]
2018-02-27 16:24:24 | INFO | Could not find Issue 37 of Green Lanterns (2016) using 32P [rss]
2018-02-27 16:24:24 | INFO | Shhh be very quiet...I'm looking for Green Lanterns issue: 37 (2018) using 32P [RSS]
2018-02-27 16:24:24 | INFO | search provider order is ['32p', 'newznab:Oznzb']
2018-02-27 16:24:24 | INFO | Issue Title given as : a world of our own part 1
2018-02-27 16:24:24 | INFO | Initiating manual search for Green Lanterns issue: 37

**Comment by evilhero** [comment]
It works just fine with 32p - it's built to handle .torrent files.

The problem is that you're not authenticating properly to 32p. This could be due to any number of things - are you using auth mode or legacy mode? (it looks like it's auth mode) 

If auth mode, what happens when you try the test connection button for 32p?

Try enabling verbose/debug logs within mylar and trying the search again. 

If you've never signed onto 32p before using mylar, the captcha cannot be up on 32p - which would mean you'd have to wait for it to return to a normal logon session. Once you've signed on successfully, it doesn't matter about the captcha.

**Comment by Tucker28** [comment]
I had logged on already. Currently, I'm using the site manually. I am using Auth mode. I have my credentials entered, however the test button doesn't do anything (unlike the test button to test the remote seedbox connection on the download settings tab). It actually looks like it's just part of the background. I'll try it again tonight when I'm back home.

32 pages works with it and downloads the torrent files... But will Mylar upload those torrent files to my seedbox that I set up in the download settings using rtorrent? Or does that only work with magnet links?

**Comment by evilhero** [comment]
The test button for 32p should return your available ink drops and a test successful message  in the display box.

If Mylar snatches a torrent, it sends it directly to your download client (it downloads it locally first to the cache folder and then sends it to the client), labels it and then starts it (if both options are enabled). It has nothing to do with magnets, as 32p only houses the .torrent files themselves no magnet links.

**Comment by Tucker28** [comment]
Sorry I couldn't get this last night. But I'm not at home, and I think 32Pages does not like it when IP addresses change. I was able to remote into my computer this morning and do these tests.

This is all it does according to the log when I press test connection.
(It has been logged in on the computer before manually since that is how I'm using it at the moment)

2018-02-28 10:47:43 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
-- | -- | --

It does nothing else after this.

--------------------------------------------------------------------------------------------------

This is the log of when it tries to search automatically (I have it set for every 5 minutes currently):

2018-02-28 10:30:17 | INFO | Update complete
-- | -- | --
2018-02-28 10:30:17 | DEBUG | ReScheduled job: DB Updater to 2018-02-28 15:35:17
2018-02-28 10:30:17 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2018-02-28 10:28:42 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
2018-02-28 10:28:42 | DEBUG | [RSS-FEEDS] 32P mode set to Auth mode. Monitoring all personal notification feeds & New Releases feed
2018-02-28 10:28:42 | INFO | [RSS-FEEDS] Initiating Torrent RSS Feed Check on 32P.
2018-02-28 10:28:42 | INFO | [RSS-FEEDS] Initiating Torrent RSS Check.
2018-02-28 10:28:42 | INFO | [RSS-FEEDS] RSS Feed Check Initalizing....
2018-02-28 10:26:42 | DEBUG | ReScheduled job: Folder Monitor to 2018-02-28 15:31:42
2018-02-28 10:26:42 | INFO | [FOLDER-CHECK] Finished checking for newly snatched downloads
2018-02-28 10:26:42 | WARNING | There were no files located - check the debugging logs if you think this is in error.
2018-02-28 10:26:42 | INFO | there are 0 files.
2018-02-28 10:26:42 | DEBUG | [POST-PROCESSING] Manual Run initiated
2018-02-28 10:26:42 | DEBUG | [POST-PROCESSING] Manual Run Post-Processing enabled.
2018-02-28 10:26:42 | DEBUG | [POST-PROCESSING] Not using SABnzbd
2018-02-28 10:26:42 | DEBUG | [POST-PROCESSING] nzb folder: /Volumes/Working/Downloads/Comics
2018-02-28 10:26:42 | DEBUG | [POST-PROCESSING] nzb name: Manual Run
2018-02-28 10:26:42 | INFO | [FOLDER-CHECK] Checking folder /Volumes/Working/Downloads/Comics for newly snatched downloads

**Comment by evilhero** [comment]
Have you changed your pass on 32p recently at all ?

What you can try - in the cache folder within the mylar directory there's a hidden file called .32p_cookies.dat. This file holds the session credentials for your 32p signon, and if it detects it's presence it will use that. I would suggest (with Mylar not running), delete the .32p_cookies.dat file, start up Mylar and then try to do the test connection option. What you should get is a response saying 'Successful' and then a blurb in the same area saying how many inkdrops you have.

**Comment by Tucker28** [comment]
Nope, I haven't changed the password since I created it.

I deleted the file and then launched Mylar and ran the Test Connection button. Like before, nothing happens.

**Comment by evilhero** [comment]
What version of python are you running?

So you're saying that mylar will use 32p normally and sign in and snatch the .torrent files, but it fails on the test connection?

Do you have a screenshot of the mylar config showing the 32p values (blank out your username) - I'd like to see what you're seeing

**Comment by Tucker28** [comment]
Mylar Version: 053626a96bd1a8601b2ca87066261408e8c1cd30 (master)
Python Version: 2.7.14

As far as I can tell, nothing with 32p is working. I can only use it by going to the site in a web browser.

![mylar settings](https://user-images.githubusercontent.com/7991720/36820704-3e6031e4-1cbd-11e8-8ccd-908a58bbe21b.png)

**Comment by evilhero** [comment]
You're about 2 months behind on master, so you might want to update to the latest.

If you can run mylar from the command line, can you run it and try doing the test connection then? It might be suppressing the actual error if it's being run as a daemon, whereas directly from the cli it would break to the console.

**Comment by Tucker28** [comment]
Odd. I tried to upgrade from the GUI but it couldn't. I shut it down and then did a git pull. I am now running Version: 9c65a0d37a0723291280f8425a92253637f3acfb (master)

I shut it down, then launched it from the command line 'Python Mylar.py' but the results are the same, it still gives the same message in the logs.

**Comment by evilhero** [comment]
When you signon to 32p via browser, is it on the same machine?

Do you actually enter your credentials or does it remember and sign you in? If you're always signed in, try signing out and then in again and see if it throws an error.

Delete the 32p_cookies file again with mylar not running. Start mylar via the cli with the -v switch (ie. python Mylar.py -v), and try the test again. You should get something in the logs stating something about your user / pass being used since no session cookie could be found.

**Comment by Tucker28** [comment]
Yes, same machine.

I have it remember my credentials. I logged out and back in, and everything is fine on the site. No errors.

I shutdown mylar again. I deleted the cookie file again. And then I restarted with python Mylar.py -v
Nothing happened any different. It still refuses to do anything. Log messages upon doing that are as follows:


2018-03-02 15:47:38 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
-- | -- | --
2018-03-02 15:47:16 | DEBUG | [32P-AUTHENTICATION] Session cookie does not exist. Signing in and Creating.

**Comment by evilhero** [comment]
Do you have any special characters (ie. Not 0-9A-Za-z) in your username or password?

It really sounds like there's something almost blocking the attempt - any active firewalls or similar?

The only other thing I can think of is that your version of python is missing some component that's making it break - and really the only thing that would be is the openssl/cryptography stuff (that makes sense anyways)

**Comment by Tucker28** [comment]
Username is all alphanumeric. Password is as well all except for some dashes. I’ll change it here in a bit to remove the dashes and see if that was it.

**Comment by evilhero** [comment]
If you change your password, make sure to delete the session cookie from the mylar cache folder before signing on, or else you'll start knocking up the failed logon attempts at 32p (people have been temp disabled due to going over the 6 failed logon attempts because of a password change)

**Comment by Tucker28** [comment]
Changed the password to all alphanumeric, no special characters at all. Deleted the cookie file and set the new password inside Mylar. Same results as before. It doesn't do anything other than attempting to load the cookie. I looked in the cookie and there is only one line inside. Is that normal?

**Comment by Tucker28** [comment]
I’ve been trying things all day, and it seems like the problem is the cookie. It contains only one line (#LWP-Cookies-2.0), and nothing else. No username, no password, no hash values in case it doesn’t store these in plain text. There’s nothing in the cookie except that one line.

**Comment by evilhero** [comment]
Ok, so that narrows it down. For some reason, the cookies aren't being saved properly to your cookies file. It could be a number of different things, so let's try the obvious: the user running Mylar has to have complete permissions to the cache directory where the .32p_cookies.dat file resides. So if that's all a-ok, then another question is if you are using relative or absolute paths in your config.ini to denote where the cache directory resides ? (ie. config.ini / cache_dir)

There is also one other thing to try, although I'm not 100% sure of the effects. It's on a gist located [here](https://gist.github.com/evilhero/b8e5ab817a1d6341f762e3a50c38d538). So here's the instructions for that: 
- shutdown Mylar. 
- In the mylar/mylar subdirectory, there should be a auth32p.py file there, so back that up and also delete the .pyc file if it exists. 
- Then with the above gist file saved (either via the download zip option, or save the raw file), put the file into your mylar/mylar subdirectory where the original auth32p.py file was. 
- Delete the .32p_cookie.dat file located in the cache directory. 
- Start up Mylar and try doing a test connection. 

It should, I hope, log the exception that's being generated and/or maybe it will work given the 2 changes made within the file to attempt to accommodate the problem - at the moment, this seems extremely isolated to it being on a MacOS for whatever reason, as other systems aren't currently experiencing any problems.

**Comment by Tucker28** [comment]
I did have permissions on the Mylar folder and everything below it. I did shut down Mylar, reset the permissions, deleted the cookie file, restarted and tried again just in case. No change in behavior.

So then I went to the next item on your list, the config.ini file. I looked inside, and actually, I'm not using relative OR absolute paths to my surprise. cache_dir = None

I stopped right there before I went on to the last option since it was completely unexpected. Should it be /cache or /Applications/Python Scripts/Mylar/cache (where I have it installed)?

**Comment by evilhero** [comment]
If it's None, then it should be defaulting to your installation path for mylar from within Mylar itself (meaning it will assume it's the default installation path during runtime until its changed /saved). 

What that indicates tho as well, is that the config has never been saved, as once it's saved it stores the current cache location. Have you ever saved the config from the GUI?

**Comment by Tucker28** [comment]
That is weird. I have saved every time I make a change (which with trying to figure out this 32p thing is a lot). Should I manually enter the absolute path?

32p does have values in it:

[32P]
mode_32p = True
verify_32p = True
password_32p =
search_32p = False
username_32p =
deep_search_32p = False
passkey_32p =
rssfeed_32p =
enable_32p = True

The 4 blank fields above do have things in them, but they have been cleared for obvious reasons. Posting it here just in case the other 5 fields have anything to do with it.

**Comment by evilhero** [comment]
Well the only ones you need for auth mode are username/password, it doesn't hurt anything to have the other info present tho.

Definitely would enter the path for the cache if it's not there - just to rule it out. If it still doesn't work after that, try using the auth32p.py file I mentioned above in place of your existing one which might help shed some light on things.

**Comment by Tucker28** [comment]
Good lord, I am cursed.

Entered the absolute path. No change.

Replaced the auth32p.py file as instructed. Almost no change.

Instead of:
2018-03-04 17:16:10 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
2018-03-04 17:14:53 | DEBUG | [32P-AUTHENTICATION] Session cookie does not exist. Signing in and Creating.

I got this with the new file:
2018-03-04 17:16:10 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
-- | -- | --
2018-03-04 17:16:10 | DEBUG | [RSS-FEEDS] 32P mode set to Auth mode. Monitoring all personal notification feeds & New Releases feed
2018-03-04 17:16:10 | INFO | [RSS-FEEDS] Initiating Torrent RSS Feed Check on 32P.
2018-03-04 17:16:10 | INFO | [RSS-FEEDS] Initiating Torrent RSS Check.
2018-03-04 17:16:10 | INFO | [RSS-FEEDS] RSS Feed Check Initalizing....
2018-03-04 17:14:53 | DEBUG | [32P-AUTHENTICATION] Session cookie does not exist. Signing in and Creating.

It still hangs on:
2018-03-04 17:16:10 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...

But at least something new happened. The cookie file is still only one line.
Is there any way to create that cookie manually?

**Comment by evilhero** [comment]
Did you happen to delete the existing cookie file before trying the new auth32p.py file? With no cookie present it should be attempting to signon to 32p instead of loading the cookie.

**Comment by Tucker28** [comment]
Yes I did. That’s when it says Signing in and Creating.

**Comment by evilhero** [comment]
Let me try and mock up something that will test signing in and better logging. It will be a standalone python script tho, so we can isolate things better.

**Comment by Tucker28** [comment]
ok, sounds good. Sorry this is so much trouble.

**Comment by evilhero** [comment]
Ok, give [this](https://gist.github.com/evilhero/a6a8772c5ec4e858e06ff19d3131b397) a try. Make sure to put it in the root of your mylar installation (where your Mylar.py file is) - so that it can use your existing requests library that's already in the Mylar installation.

Edit the file ,and on lines 20-21, put in your username and password into the fields, but keep the quotation marks around both items. 

Save it, and then just run it as 'python authtest.py' from the command line. You'll get some basic info about what you're running, and then hopefully some additional logging in regards to 32p.

This will create a .32p_cookies.dat file in your home directory wherever that may be (in linux it's /home/username/.32p_cookies.dat as an example).

**Comment by Tucker28** [comment]
I got an error on line 106. I followed instructions exactly including making sure quotation marks were left intact. I looked in my home directory on the chance that it created the file anyway, and it didn't.

azeroth:Mylar scott$ python authtest.py
  File "authtest.py", line 106
    def valid_login_attempt(self, un, pw):
                                         ^
IndentationError: unindent does not match any outer indentation level

**Comment by evilhero** [comment]
Doh, stupid cut & paste. I updated the gist. Grab it again and it should run this time.

**Comment by Tucker28** [comment]
I think that one worked, although the cookie created still has just one line, and it still seemed to error out, though it wasn't a runtime error. Below is the readout:

azeroth:Mylar scott$ python authtest.py
REQUESTS VERSION: 2.7.0
session path set to : /Users/scott/.32p_cookies.dat
session cookie does not exist. Creating.
Got an exception when trying to login : [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)
[LOGIN] invalid login attempt.
[LOGIN] Clear existing cookies, and saving most likely INVALID cookie.
Both session key and credential-based logins failed.
login failed.
error: None
azeroth:Mylar scott$

**Comment by evilhero** [comment]
ah-ha
that was what I thought it was, but couldn't confirm until I just saw that.

Your python does not have the required openssl modules in order to authenticate properly against https sites - so basically it can't verify the connection to the given site so it just stops. You should be able to get it all installed automatically by doing a simple ```pip install requests[cryptography]``` from the command line, assuming you have pip installed of course.

**Comment by Tucker28** [comment]
I ran that command and installed the modules (except for maybe one which showed up in yellow). Then I tried the new file again, and got the same results. I tried running Mylar and got the same result. I then ran the pip command again and got this (I forgot to copy the install readout the first time):

azeroth:mylar scott$ pip install requests[cryptography]
Requirement already satisfied: requests[cryptography] in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
  requests 2.18.4 does not provide the extra 'cryptography'
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[cryptography])
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[cryptography])
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[cryptography])
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[cryptography])
azeroth:mylar scott$ 

The line [ requests 2.18.4 does not provide the extra 'cryptography'] was printed in a different color than the rest. So I don't know it that is an error or not.

Do I need to reboot the entire server before this takes effect?

I didn't see this command as being a prerequisite for mylar. Does 2.7.14 just not contain these modules?

**Comment by evilhero** [comment]
Doh stupid. I forgot they changed the command, it's now: ```pip install requests[security] --upgrade```

That will upgrade all the necessary stuff which should then allow you to connect.

Shouldn't need to reboot but if you are able it probably wouldn't hurt in the grand scheme of things.

As far as the requirement, it's why you need at a minimum python 2.7.9, as SNI support which involves https authentication is only available at that minimum level. Most individuals have the openssl stuff already installed, but yeah it should be mentioned how to address it as well as having better error handling for 32p failures (still not sure why it didn't log it properly, but I should be able to fix it so it does going forward)

**Comment by Tucker28** [comment]
Sorry, sleep decided it wouldn't be denied any longer.

I ran the upgrade command and it ran and with no errors, installing some new stuff, upgrading others.

I rebooted just to be safe.

Still will not connect, either Mylar using 32p or the authtest.py file.

Mylar still says [32P-AUTHENTICATION] Session cookie found. Attempting to load...

-------------------------------------------------------------------------------------
The authtest.py file still outputs:

azeroth:mylar scott$ python authtest.py
REQUESTS VERSION: 2.7.0
session path set to : /Users/scott/.32p_cookies.dat
session cookie does not exist. Creating.
Got an exception when trying to login : [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)
[LOGIN] invalid login attempt.
[LOGIN] Clear existing cookies, and saving most likely INVALID cookie.
Both session key and credential-based logins failed.
login failed.
error: None
azeroth:mylar scott$ 

-------------------------------------------------------------------------------------
The upgrade command outputs this when running again:

azeroth:mylar scott$ pip install requests[security] --upgrade
Requirement already up-to-date: requests[security] in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already up-to-date: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: idna<2.7,>=2.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: cryptography>=1.3.4; extra == "security" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: pyOpenSSL>=0.14; extra == "security" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests[security])
Requirement already up-to-date: asn1crypto>=0.21.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security])
Requirement already up-to-date: cffi>=1.7; platform_python_implementation != "PyPy" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security])
Requirement already up-to-date: enum34; python_version < "3" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security])
Requirement already up-to-date: six>=1.4.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security])
Requirement already up-to-date: ipaddress; python_version < "3" in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cryptography>=1.3.4; extra == "security"->requests[security])
Requirement already up-to-date: pycparser in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security])
azeroth:mylar scott$

**Comment by evilhero** [comment]
Unfortunately this isn't a mylar problem at this point - it's an openssl dependency problem with your OS.

So you'll have to do some reading and try different things as the normal avenues don't work for OS Sierra as the Openssl that ships with the OS is outdated and causing the problems.

https://www.google.ca/url?sa=t&source=web&rct=j&url=http://www.cbef.us/solving-sslv3-alert-handshake-failure-on-macosx/&ved=0ahUKEwjAhpScmdXZAhUE3mMKHZRSD_sQFghbMAQ&usg=AOvVaw34W0sqMt2mx6z4X79Zv2xf

**Comment by Tucker28** [comment]
Ok, I'll look into it. If it's a Sierra or High Sierra issue, then at worst case I'll roll back to El Capitan. Thanks so much for the help in finding the problem!

**Comment by Tucker28** [comment]
Apparently High Sierra comes with LibreSSL 2.2.7 instead of OpenSSL. Still, Python was using OpenSSL 0.9.8zh instead of LibreSSL.

Following the instructions from the site you linked, I installed OpenSSL 1.0.2n, and got Python3 working with it. However, nothing I have done has switched Python2 over to it. 2.7.14 is still stuck on OpenSSL 0.9.8zh. I'm still researching, but thought I'd post here just in case the information comes in handy for you at some point.

**Comment by Tucker28** [comment]
Well... it's working. =)

I actually had to remove every trace of Python. I removed every trace of both Python2 and Python3, and then explicity installed Python2 from Homebrew. This time it pulled in the correct OpenSSL version. I fired up the authtest.py file, and I actually laughed when it worked. I launched Mylar and just watched the log go. Then I went over to my seedbox and watched the files start coming in... all with a giant grin on my face.

Thank you so much for the help. I wouldn't have able to figure this out without you helping home in on the issue.

**Comment by evilhero** [comment]
Glad you finally got it working :)

I had suspected initially it was due to an ssl problem - but with the error messages saying nothing of the sort it was hard to maintain that thought as the problem lingered. Thanks to your troubleshooting, I now know that the current logging for the 32p signon method is really lacking in regards to error handling - so I'll be re-configuring the error handling in that part of Mylar so it can better accommodate those types of errors going forward.

And really, all I happened to do was do some specific word related google searches - you did all the hard work once it was all narrowed in - which I'm sure was rewarding in itself once it ran properly!

**Comment by Tucker28** [comment]
Oh, it definitely was. Much the same feeling I got once I finally had the macro I programmed in VBA working saving hours or in one case days of work. I really need to learn another language. I know Java a little bit, but that’s the only other one.

I’m glad that this issue has had a positive outcome on Mylar for the error handling. Very happy it wasn’t a complete waste of time for you.

One last question before I close this ticket... what are the differences between using the legacy method with the key vs using the authentication? If I’ve understood it correctly, legacy only checks new releases, while authentication can search the entire site?

Thanks again. I should start learning Python, I don’t know which version to start with, but I doubt there would be much difference as far as semantics.

**Comment by evilhero** [comment]
You're pretty much right about the difference between legacy & auth. With legacy, it's limited to just monitoring the rss feed - so if an issue happens to come out when Mylar isn't running, you'll miss being able to snatch it using Mylar. It does cache the results, so the longer you leave Mylar running, the more of a backlog it can pull from - but you're limited severely in how much Mylar can accomplish in this mode.

In auth mode, the world opens up...well kinda ;) It allows for monitoring of the rss feeds, same as legacy, but it also adds your subscription feeds on 32p into the monitor pool. It allows for backlog searching (ala api), as well as pack support being usable (on the Edit Settings of a given series when you have auth mode enabled only). It's just a nicer experience since you're not relying on just the rss feeds, and I'm constantly making improvements to accomodate diff situations therein, whereas with the legacy mode - there's not much I can add to it.

Plus with the seedbox, and your Mylar being local - you can make use of either the auto-snatch option built-in to automatically retrieve the comics Mylar sends to your rtorrent client, back to your local machine and post-process them....or you can even use [harpoon](https://github.com/evilhero/harpoon) (which does the same thing, but it works with most of the other automated downloaders too).

**Comment by Tucker28** [comment]
Auto-snatch? I need to do some research. That was the one piece of the puzzle that I’m still doing manually is downloading from my seedbox. That’s perfect. I’ll look into it or harpoon. =)

**Comment by Tucker28** [comment]
Cannot find the auto-snatch option to automatically download from the seedbox. Is it hidden?

**Comment by evilhero** [comment]
Of course it is!

Kidding aside, it's a config.ini option because it's an advanced option that wouldn't be used by alot of people so instead of cluttering up the interface even more, it's hidden away.

Here's the rundown:
- with Mylar shutdown, edit the config.ini
- in the config.ini, there should be a section called ```[AutoSnatch]```
- set the auto_snatch_script value to the full file location of where the getlftp.sh script is. This is included in mylar at ```post-processing/torrent-auto-snatch/getlftp.sh```
- set the auto_snatch field to True
The following values all involve your seedbox information:
- the pp_sshhost is your seedbox ip/hostname (do not include http/https or anything else other than the ip/hostname)
- the pp_sshuser is your username for your ssh signon on your seedbox
- the pp_sshpasswd is the password for your ssh on your seedbox
- the pp_sshport is the port your seedbox ssh listens on
- the pp_sshlocalcd is the local destination where you want mylar to 'snatch' the files to.
- if you use sshkeys to signon, leave the pp_sshpassword blank (or set to None), and then set the pp_sshkeyfile to the full path location to your keyfile.

Now when Mylar snatches a torrent, you'll should see it automatically say it's monitoring the download, when it's complete and that it is snatching it. Once it's snatched, it drops it into the pp_sshlocalcd directory specified above. Now atm, I can't recall exactly - but I don't think I have it auto-pp right after the snatch is finished, so what most of us that use this are doing is set your folder monitor to monitor the same location that you set the pp_sshlocalcd to, and then it wil post-process them automatically.

**Comment by Tucker28** [comment]
Awesome. Thanks. Now if I can get it to look up A+X... lol. It's treating that + as an operator, even with quotes
