### ISSUE TITLE
Python treats "Infinity" As a Numerical Value 

### ISSUE THREAD

**Issue by ForumFerret** [evilhero/mylar#1877]
Post-processing Infinity Countdown Prime (and, I imagine, the rest of the Infinity Countdown issues) 
causes python to blow up during Post-Processing, aborting the postprocessing of that issue and all the rest in that directory. 

Details in Pastebin: 

https://pastebin.com/Vq3LJCrK

**Comment by evilhero** [comment]
Actually this error is due to the story arc directory option not being enabled, when it thinks it should be.

This was fixed in development yesterday with commit (24512d6). 

So make sure you're up-to-date, and then go to the main page of the story arcs, and make sure that the 'Enable StoryArc Directory' option is enabled - and then update the settings. What was happening, is that it was enabled on the individual story arc page, but not on the main page. The main page being the global setting which controlled everything, as well as the Update button not actually working. 

It's now been altered so that the only place you can change the option to enable/disable the Story Arc directory option is on the main story arc page as it's a global option that will affect all Story Arcs.

**Comment by ForumFerret** [comment]
Ah, great! Working as described. Thanks!
