### ISSUE TITLE
post processing failing

### ISSUE THREAD

**Issue by jeroenpardon** [evilhero/mylar#1878]
I am having trouble with post processing, this keeps showing up in the logs when doing a manual update, but automatic is failing too:

> 05-Mar-2018 04:20:44 - INFO :: CP Server Thread-4 : Starting postprocessing for : Manual Run
05-Mar-2018 04:20:55 - INFO :: Thread-12 : there are 359 files.
05-Mar-2018 04:20:56 - INFO :: Thread-12 : Issue set to: 3000
05-Mar-2018 04:20:56 - ERROR :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/volume1/.apps/Mylar/mylar/logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/volume1/.apps/Mylar/mylar/PostProcessor.py", line 351, in Process
    filelist = flc.listFiles()
  File "/volume1/.apps/Mylar/mylar/filechecker.py", line 140, in listFiles
    runresults = self.parseit(self.dir, filename, filedir)
  File "/volume1/.apps/Mylar/mylar/filechecker.py", line 884, in parseit
    elif 'XCV' in alt_issue:
TypeError: argument of type 'NoneType' is not iterable

>Traceback (most recent call last):
  File "/volume1/.apps/Mylar/mylar/logger.py", line 177, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/volume1/.apps/Mylar/mylar/PostProcessor.py", line 351, in Process
    filelist = flc.listFiles()
  File "/volume1/.apps/Mylar/mylar/filechecker.py", line 140, in listFiles
    runresults = self.parseit(self.dir, filename, filedir)
  File "/volume1/.apps/Mylar/mylar/filechecker.py", line 884, in parseit
    elif 'XCV' in alt_issue:
TypeError: argument of type 'NoneType' is not iterable

Running on a Synology NAS, using a manually installed Mylar build

**Comment by evilhero** [comment]
Enable debug/verbose logging and try the manual pp again.

It's unclear exactly, but one of the filenames you're trying to post-process has a character in it that mylar is assuming is the issue number for some reason.

If you can tell me the filename, I can help as to the reason why and a possible solution (and/or I can fix the code so that it doesn't happen again)

**Comment by jeroenpardon** [comment]
Sorry for taking so long to get back to you on this. It appeared Mylar was choking on a subfolder containing magazines. When I removed that, it started processing again.
Part of the problem is that the torrent client I am using (DownloadStation on a Synology NAS) does not support assigning multiple download locations. This shortcoming is compensated by apps like Sonarr and Radarr which are able to tell the torrent client which (sub)folder to download to. Being able to do the same in Mylar would be very handy. This would allow me to automatically download to /Downloads/comics/ instead of /Downloads. That way Mylar would not go through for example /Downloads/Movies/, /Downloads/Music/ and so on with the "risk" of trying to process files in these folders as comic books.

**Comment by evilhero** [comment]
Unfortunately I don't have access to a download station in order to code and test the client, which is what would be necessary in order to implement it. I would also not be able to support it properly as such, since I couldn't debug things. 

Mylar will only parse filenames that end in cbr/cbz/webp - it ignores all others, so you must have had a magazine in one of those formats for it to even attempt to parse the filename. 

However, it would have been helpful to know the name of the file that was causing the problem so I could look into it more, but since you removed it already 'tis a moot point.

**Comment by edasque** [comment]
@evilhero , a related question

with NZBGet working well with the following download directory: /volume1/downloads/comics
and Download Station set with a watch directory /volume1/downloads/black_hole
that ends up downloading in /volume1/downloads/complete

Is the right way to set it up so it does folder monitoring on /volume1/downloads/complete ?

Right now they just stay there in /volume1/downloads/complete and nothing happens. Or does the watch folder have to also be the download folder?
