### ISSUE TITLE
Can't Update from GUI

### ISSUE THREAD

**Issue by wraith1385** [evilhero/mylar#1883]
I haven't been able to update from the Web GUI for a few weeks now.  It acts like it's updating, but when it comes back up it's still the same version.  If I want to actually update I have to shut down Mylar and update from the GIT command line.

**Comment by evilhero** [comment]
When you update from the GUI,  make sure you run mylar in a non daemon mode. When it goes to update it will break the messages to the console and you can see what it's erroring on.

Odds are the git_path field in the config.ini is blank and Mylar can't locate it in order to perform the update (just a guess). That or possibly your version of git needs to be updated.

**Comment by wraith1385** [comment]
You were right, the git_path field was set to None, so I'm not sure how it worked up to this point, but I've fixed it now.  

Thanks.
