### ISSUE TITLE
ERROR	[IMPORT] Unable to complete the scan: local variable 'unicode_comic_path' referenced before assignment

### ISSUE THREAD

**Issue by carbonbaseunit** [evilhero/mylar#1895]
I recently reinstalled Mylar from scratch.  Everything was working and then I decided to reorganize my Comics directory to make is easier for Mylar to read.  After I was finished and tried to scan the directory I got this....

`

2018-03-17 13:31:46 | ERROR | [IMPORT] Unable to complete the scan: local variable 'unicode_comic_path' referenced before assignment
-- | -- | --
2018-03-17 13:31:46 | INFO | bang
2018-03-17 13:31:45 | INFO | Scanning comic directory: P:\Comics
2018-03-17 13:31:45 | INFO | forcescan is: 0

`
How can I fix it?

**Comment by evilhero** [comment]
Try double-escaping the \ so it's ```P:\\Comics```

Are you running this from the Manage / Import a Directory tab?

If your existing db was fine just the paths are incorrect there are other alternatives available than having to reimport everything again (which is not as accurate for some things)

**Comment by carbonbaseunit** [comment]
I am running it from the Manage / Scan Comic Library tab.  It wasn't working very well (very slow) So I thought I would simplify my directory structure in my comic library.  After I did that and tried to rescan I got that error.

**Comment by evilhero** [comment]
Yeah it has to scan every comic and parse the filename for the required information. Then if you have the check metatagging option enabled it has to uncompress each file (that's a cbz) in order to read the metadata. Then it's  a crapshoot if the 2 are actually identical or not - so there are alot of what-it's that occur during the import process which make it undesirable to import a ginormous library all at once.

But if all you did was change the folder structure into something mylar can recognize, you don't have to reimport everything in order to pick up the new locations. If you still have your old .db you can just use that and there a few config settings you can enable that will change all the directory locations in the dB so they coincide with your new locations and you don't have to go thru the import process.

**Comment by carbonbaseunit** [comment]
It was working after I reinstalled.  I ran it and it worked.  I changed the directory structure (Which I can't imagine would do anything within Mylar) ran it again, and it threw errors.  The old database went to digital heaven with the SSD drive it was located on.

**Comment by evilhero** [comment]
Can I ask what your directory structure is?

**Comment by carbonbaseunit** [comment]
Its just a mapped folder to a windows shared drive.  I fixed it though.  There was some loose .cbz files in there outside of directories.  I deleted these and it scanned fine.  Fun stuff.  :)
