### ISSUE TITLE
OPDS Reading List

### ISSUE THREAD

**Issue by glberen** [evilhero/mylar#1896]
Hi - 

The Reading List through OPDS is showing an issue count, but no issues. I'm looking at it through the Chunky comic reader. Is that Chunky issue or something with Mylar, you think? 

![screenshot 2018-03-18 12 37 03](https://user-images.githubusercontent.com/9060576/37568897-71a7efd4-2aa9-11e8-8c07-049b8f8cde4e.png)

**Comment by DarkSir23** [comment]
Ok, I'm able to replicate this.  It's an issue in OPDS read list.  Let me investigate.

**Comment by glberen** [comment]
The latest commit fixed this for me in Chunky Reader. I can now view the reading list and download issues on my ipad where I had this configured already. Now if I can just figure out the URL to add the OPDS feed to my new ipad!

**Comment by barbequesauce** [comment]
Assuming you access mylar using:

http://192.168.1.10:8088/
Or
http://mylarhost.local:8088/

The OPDS feed would be:

http://192.168.1.10:8088/opds/
Or
http://mylarhost.local:8088/opds/

Things to be concerned with: are you using http or https, your IP or hostname, your port, your http_root if using a reverse proxy... all that should work fine with Chunky.

The ChunkyTNG beta is a bit flaky with name resolution though, and you should use an IP rather than a hostname...
