### ISSUE TITLE
Error when syncing comics from reading list (socket is closed)

### ISSUE THREAD

**Issue by exielo** [evilhero/mylar#1898]
I am consistently getting an error that prematurely ends my reading list syncing with my Chromebook. Any help or info would be greatly appreciated.
This is the error I have been getting:

2018-03-19 13:19:54 | ERROR | Uncaught exception: Traceback (most recent call last):
File "C:\Mylar\mylar\logger.py", line 177, in new_run
old_run(*args, **kwargs)
File "C:\Python27\lib\threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Mylar\mylar\readinglist.py", line 229, in syncreading
success = mylar.ftpsshup.sendfiles(sendlist)
File "C:\Mylar\mylar\ftpsshup.py", line 101, in sendfiles
return sendtohome(sftp, remotepath, filelist, transport)
File "C:\Mylar\mylar\ftpsshup.py", line 181, in sendtohome
transport = paramiko.Transport((host, port))
NameError: global name 'paramiko' is not defined

2018-03-19 13:19:54 | INFO | Forcibly closing connection and attempting to reconnect
2018-03-19 13:19:54 | INFO | Attempt #1: ERROR Sending issue to seedbox *** Caught exception: : Socket is closed

Thanks in advance!

**Comment by evilhero** [comment]
Is paramiko installed on your system? The error indicates that it can't load the module, but normally when it can't load it will throw out something indicating that it can't find paramiko and to install it.

**Comment by exielo** [comment]
Yes Paramiko is installed. It will send comics to the chromebook, but it only gets through 5-20 books before I get the error. I am moving about 400 books, so I just keep restarting it.

**Comment by evilhero** [comment]
It might be a paramiko related error as far as not being being able to unlock the socket in time for the next connection. Unfortunately paramiko isn't the most reliable, but at the time the reading list sync was created it was the only one available that fit into the existing structure of Mylar.

Things have changed immensely since that was created, and the sync has not been updated since it was created. So it's probably well overdue for a revisit. I'll mark this as an enhancement request atm, and hopefully another alternative to paramiko can be discovered that performs well (or maybe something in paramiko had even changed)...

**Comment by exielo** [comment]
Great to hear! Thanks for your work, it is greatly appreciated.
