### ISSUE TITLE
So this happened-- seemingly infinite downloads of an issue

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#1904]
Hi

The other day I realized a lot of things hadn't finished in sabnzbd. I looked and there were a couple of hundred downloads of a single comic, seemingly hung on a current process, and dozens more pending (of the same comic). I couldn't abort the stuck process, or restart sab, and had to pause sab, delete the file, reboot the pc, delete all pending instances, and unpause, to resolve. This didn't happen before or after this fateful file. Mylar and sab went on to process many new comic issues afterward without problem. Should we take a closer look or nah? 
![screen shot 2018-03-23 at 4 17 50 pm](https://user-images.githubusercontent.com/97095/37857553-1a3c0d3e-2eb9-11e8-9e5b-46ef5bdd7d46.jpg)

**Comment by evilhero** [comment]
Alot probably depends on how you have things configured in mylar for post-processing. 

There have been alot of changes to the backend code over the last few months - the autoProcessComics file got updated, completed download handling is an option now, the post-processing api changed (just to name a few).

It might be redownloading the file because the status isn't being updated properly as well.

What options do you have set for post-processing, and do you have completed handling enabled for sab, or are you using comicrn?
