### ISSUE TITLE
Logging Issues (UnicodeDecodeError)

### ISSUE THREAD

**Issue by davidmehren** [evilhero/mylar#1905]
Hi!
Im using Mylar on a Arch Linux machine and experience many errors like
```
25-Mär-2018 19:17:01 - INFO :: mylar.initialize.209 : MainThread : Successfully discovered local IP and locking it in as : 192.168.99.45
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 476, in format
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
Logged from file __init__.py, line 226
```
This is quite mysterious, because many other logging statements seem to work fine. I think the error only happens when printing unicode strings, like in `webstart.py, line 73` or when using unicode strings read from a file like in `__init__.py`.
After googling around a bit, it seems that the encoding is not correctly set to UTF-8 everywhere. I fixed the errors by adding
```
reload(sys)
sys.setdefaultencoding('utf8')
```
in `Mylar.py` but that is very ugly.

**Comment by davidmehren** [comment]
There definitely is a problem logging unicode strings. I just launched Mylar in PyCharm, stopped execution at a random point using the debugger and then tried to log something using `logger.info` with the "evaluate expression" feature.
`logger.info(u"test")` results in a `UnicodeDecodeError`, while `logger.info("test")` works.

Any idea how I can debug this further?

**Comment by evilhero** [comment]
I think it might be something local to your install, as the logging statements work fine for unicode (it sets the default encoding to utf-8 in Mylar.py, unless its misconfigured), and has been tested across various OS' and differing languages without anyone bringing up a similar issue (and believe me, it would have come up). 

You can check what your default encoding is set to for python by going into the python interpreter and just doing a simple one liner which should return 'UTF8' :
```import locale;
locale.getpreferredencoding()```

I'm assuming in all of this that you're using a version of python in the 2.7.x branch as that is all that is supported by Mylar.

**Comment by davidmehren** [comment]
I played around with a fresh install of Debian 9.4 in a VM.
If I just clone Mylar and start it with `python Mylar.py` everything works.
If I set the default locale to `de_DE.UTF-8` using `dpkg-reconfigure locales` and relogin, the errors appear.
So it seems that, for some reason, with `en_US.UTF-8` everything works fine, but with a german locale it doesn't. Note that in both cases, `locale.getpreferredencoding()` returns `UTF-8`.

**Comment by evilhero** [comment]
It's actually the logger that's messing things up. I switched locale today to try it today and got bombarded with utf-8 errors that couldn't be formatted due to the format string not working - I'm guessing due to trying to convert it and failing.

And changing the default encoding via the hack, would just break other modules within Mylar due to not expecting utf-8 encoded items, since ascii is the default encoding and most modules are coded against that aspect. 

I'm working towards a fix, but requires the logging code be changed / updated to accommodate things along with other parts of the codebase.

Don't expect the fix in a day or anything (unless I get really lucky), but I'm making headway on it when I can find the time to work on this aspect.
