### ISSUE TITLE
Setting torrents to "local watch dir" gives 502 error on restart

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#1906]
As it says in the title; each time that I've set torrenting to local watch dir and restarted, I have to delete all my settings as it will no longer load without a 502 error.

**Comment by silentArtifact** [comment]
This also happens when setting up Transmission, it seems. I'm using the linuxserver docker package, on a Synology NAS.

**Comment by evilhero** [comment]
I use the torrent local option for testing purposes, and have never had it 502 on me regardless of a startup or not.

It sounds like it's unable to save your config properly tho, I would imagine possibly due to permissions. Synology in itself can be problematic due to permissions not being properly set for the mylar directory. The docker would add more permissions permutations to it if you live strayed from their instructions due to personal configuration.

- Try starting mylar up with the -v option (in the cli, not as a daemon) and see if the error will present itself in the console.  Sometimes the error gets suppressed due to the daemon being used, so you won't see anything in the logs.

Also you don't have to restart mylar between config changes any longer, unless you're switching the authentication  method, and/or the web interface tab of the config.

**Comment by silentArtifact** [comment]
It looks like the logs show the problem:
`Failed to start on port: 8181. Is something else running? `
There's another service running on 8181, and Mylar's been instructed to use a different port than that... it looks like it changes the port setting to 8181 after I set up a torrent downloader. I just made sure that after changing the torrent option I double-checked the port, and changed it back to what it should be; that took care of the issue. 

I really should learn to read the logs before posting... thanks for the help! -_-;
