### ISSUE TITLE
Feature Request: Add Pack Downloads for all Series

### ISSUE THREAD

**Issue by weidercs** [evilhero/mylar#1910]
Instead of having to enable it for every series one-off, it would be nice to allow for pack searches for all the continuing series.

**Comment by evilhero** [comment]
Yeah it's a possibility. The only problem with packs and having it as a global option is that it's not perfect in the way it parses the titles (since it only works on 32p - I'm talking about 32p). It's decent enough, but yeah I've thought about this before, but it'll take abit of testing/work to get it going properly. 

I'll add this as an enhancement, and try to figure things out...

**Comment by Xeyk** [comment]
Just thought I'd throw in that I'd love this as well. I use 32p exclusively so I will definitely be marking the packs option every time I go to add a new comic series. 

Thank you for all that you do!

**Comment by mjsmjs** [comment]
any update on this?

**Comment by evilhero** [comment]
nope.
