### ISSUE TITLE
mylar doesnt start anymore after one of the last dev updates

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1912]
hey, i'm on a german version of windows 10 running mylar dev and after i hit the update button a few hours ago mylar stopped working. 

the python script window opens, displays something then closes immediatly afterwards (cant read it).

also the logs are empty :(

i tried to copy all the current files from dev into my mylar directory with no luck so far. what should i do next?

**Comment by evilhero** [comment]
How do you start mylar - by double clicking, using a .pyw file, or by some other method?

The Mylar.py file changed, so if it's the .pyw method you'd have to recopy Mylar.py to Mylar.pyw.

If you can start it in the console - either via the cmd line or git shell (if you installed with git), odds are the error message will break on the console and you can see what the error is.

**Comment by HypKin** [comment]
yes, i just double click mylar.py -  ill try to start it via command prompt to see what it says 

thx

**Comment by HypKin** [comment]
took me a bit, because i hadnt added python to the system path and... well i needed to learn how to start a python script via command line haha

i'm getting this error


language detected as non-English. Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
Traceback (most recent call last):
  File "Mylar.py", line 355, in <module>
    main()
  File "Mylar.py", line 180, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "D:\mylar\mylar\__init__.py", line 177, in initialize
    logger.mylar_log.initLogger(loglevel=mylar.LOG_LEVEL)
AttributeError: 'module' object has no attribute 'mylar_log'

**Comment by evilduck83** [comment]
I get the exact same error on linux since the newest dev update (I was actually 3 commits behind)

**Comment by evilhero** [comment]
Can I ask what language you guys are using with Mylar?

You can do it from within python by typing in ```import locale; locale. getdefaultlocale() ```

This was to fix some non-english Unicode errors in the logging, but it looks like you both are using non-english locales (I tested the fix using de_DE)

**Comment by evilduck83** [comment]
Here is my Python output:

```
>>> import locale; locale. getdefaultlocale()
('de_DE', 'UTF-8')
>>>

```

**Comment by evilhero** [comment]
@evilduck83 ,are you running in windows?

I'll have to throw my system into de_DE and do some testing. I can see one part where it might be causing a problem, but that's just me guessing atm

**Comment by evilduck83** [comment]
I'm using Linux, DietPi on an Odroid C2 to be precise

**Comment by HypKin** [comment]
my output is

de_DE and cp1252

**Comment by chmop** [comment]
Same error here. Debian, french.

>>> import locale; locale. getdefaultlocale()
('fr_FR', 'UTF-8')

**Comment by evilhero** [comment]
Fix is coming, will probably be up later tonight - still have to work out one error with it that popped up after but otherwise it should be fixed in next dev commit.

@chmop ,if you set en as your default then it will use the logger system that has been in place for a long time. Otherwise it uses the new method which fixes problems with formatting interpretations in some non-English languages (which was what I was trying to fix with the change)

**Comment by HypKin** [comment]
great!

**Comment by chmop** [comment]
Ok ! sorry for trying to guess (and doing it badly). Python really seems to have its own thing going with unicode. Good luck with that, and thank you for all the time you put into mylar!

**Comment by evilhero** [comment]
No worries, I tend to explain stuff in detail for my own benefit and reference - as alot of the same issues come up repeatedly so when I look back at a given issue I can read where the solution was coming from.

**Comment by evilhero** [comment]
Aights, should be all fixed now (I hope). 

I spent too much time switching between de_DE.UTF-8 and en_CA.UTF-8 in order to test all of the various nuances out in various attempts to get things working properly.

But it should now be working with this commit, regardless of the language being used. For eaiser future  reference, I also added a spot in the configuration GUI on the 1st tab under Configuration Options -where it will now display your system language and character encoding.

If for some reason, when you run Mylar you get no log output, you might have to force your log_level in the config.ini to a value of 1 now. The log_level option was really never used previously, and so it defaulted to 0 (which is Quiet) before this last commit, and going forward the default is now 1 (which is basically normal INFO logging). For those curious, 2 is DEBUG level (or verbose as the 'mylar' terminology goes..)

**Comment by HypKin** [comment]
up and running! thanks!

**Comment by claym** [comment]
So @evilhero , looks like the base docker image doesn't set a environment, so you might have additional people coming in here going "wtf?" because getdefaultlocale returns (None, None)

I've updated my development docker file to make sure it includes that stuff 

https://hub.docker.com/r/claymitchell/mylar/
