### ISSUE TITLE
Mylar wont start if git unavaible

### ISSUE THREAD

**Issue by waykohler** [evilhero/mylar#1917]
On windows, but should be similar on other os's.
I assume it only happens when running a git build.
If git.exe is not in the path mylar will fail with "Couldn't find latest installed version."
This error message could be more descriptive.

This happen to me when I used the github app to clone the mylar depot.

**Comment by evilhero** [comment]
Yeah some of the statements that actually log the errors are in debug mode (I've been converting them as I find them to make them more informational), but it's actually due to the git_branch not being set to a default value (it should default to Master, it defaults to None and then fails).

I'll fix this shortly...

**Comment by evilhero** [comment]
This should be fixed now in the latest development commit (6a2b123)
