### ISSUE TITLE
directly input a 32p series ID somewhere?

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#1920]
hey, i'm having troubles with the new Legion series from Marvel comics - mylar is matching on the dc comics version of "Legion"...

is there a way to just input a series ID or something like that?

**Comment by evilhero** [comment]
No there isn't - mainly because the publisher isn't provided in the 32p search options. Normally 32p does distinguish in the title if it's different publishers, so kind of surprised they didn't. This has been suggested before - I should be able to add in a series ID option for a given series to force point it to that within 32p for these special cases.

**Comment by HypKin** [comment]
this has been implemented already, i'll close this one
