### ISSUE TITLE
Post processing in nzbget marked as failed

### ISSUE THREAD

**Issue by casret** [evilhero/mylar#1921]
When you use the requests library nzbget (and presumably the others) jobs get marked as a failure.  The problem is that since pp.content is a string instead of an array the list comprehension returns single characters and the check doesn't work.  Here's my minimal diff to make it work, though arguebly you should fix it in the urllib block and make the test simpler.
```
diff --git a/post-processing/autoProcessComics.py b/post-processing/autoProcessComics.py
index 4017fdd..20b0523 100644
--- a/post-processing/autoProcessComics.py
+++ b/post-processing/autoProcessComics.py
@@ -80,6 +80,7 @@ def processIssue(dirName, nzbName=None, failed=False, comicrn_version=None):
             print 'statuscode: %s' % pp.status_code
             result = pp.content
             print pp.content
+            result = [result]
     else:
         url += "?" + urllib.urlencode(params)
         print "Opening URL:", url
```

**Comment by evilhero** [comment]
This actually is only happening when you use nzbget for some reason. Same code will hit regardless of client, but with SAB it's able to parse the return string with the newlines fine and figure out it's successful. With nzbget, it's not able to (the return values are the same) so it takes it all as a str and then fails because it can't parse it. 

I just split the result on newline characters (since that seems to be the stumbling block for nzbget for some reason), and it worked fine on both nzbget & sabnzbd.  Fix is in development now
