### ISSUE TITLE
Mylar not moving This Week's Upcoming to Wanted properly

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#1926]
<img width="1009" alt="screen shot 2018-04-19 at 18 16 17" src="https://user-images.githubusercontent.com/10370854/39007489-d647a0fc-43fd-11e8-9f16-f42c0af3fbf0.png">

The screenshot is pretty obvious. The pull dates are wrong and especially with Lazarus that means it will never match with my provider (in this case 32p which is having its own issues but that's nothing to do with this).

Configuration Options
Mylar Version: master
-- git build 9c65a0d37a0723291280f8425a92253637f3acfb.
Python Version : 2.7.12

Running on Linux with latest version of mono 5.10.1.47.

**Comment by evilhero** [comment]
The pull dates are pulled from CV, so if it's not populated correctly it's an error on that side. If the date is incorrect, you can click on the date field for the given issue when you're viewing the series and enter in a better/correct value. Also Mylar will try to search by publication date first, if that's not available it uses the store date. 

Now for the discrepancies. 
The pull date in the upcoming section is the store date, whereas the date listed on the wanted tab is the publication date. Publication dates will differ from store dates by up to 2 months. 

Why the difference? The upcoming is tied to the pullist as normally the issue data isn't present on CV yet to get correct info, so it populates the store date as that's known. 

The wanted tab/series are all publication dates as that's the industry standard. An issue won't get moved from the upcoming section to the actual wanted section until the issue data is present on CV (upcoming basically shows that mylar knows the issue is supposed to be Wanted, but can't add it yet cause it doesn't exist). There's like one guy doing all the new metadata at CV, so things can go slowly some days.

Also, shutdown mylar and edit your config.ini, and change the alt_pull value from 0 to 2. Save it and start Mylar back up and when you go to the weekly tab, do a Recreate Pullist. You're using a pullist method that has fallen by the wayside, and is used as a last resort option.

**Comment by Lusiphur** [comment]
Thanks for the detailed explanation. Top notch support as always.

I have updated the pull method as suggested and things look cleaner now.
