### ISSUE TITLE
config symlink overwritten

### ISSUE THREAD

**Issue by jangrewe** [evilhero/mylar#1931]
Hi, i'm maintaining all my config files in a central location, so Mylar's `config.ini` is only a symlink to the real file in a different folder. Unfortunately Mylar seems to always move the `config.ini` to `config.ini.backup` and then write a new file, which breaks my config management. 

Would it be possible to just write the running config to `config.ini.backup`, and the to-be-saved config to `config.ini`, without the moving around?

Thanks!

**Comment by evilhero** [comment]
The .backup extension is created by the configparser module itself when it can't physically read the file where it expects it to be. I tried it myself just now, and yes, it creates a ```config.ini.backup```, and created a blank ```config.ini``` file but it was done when the symlink wasn't an absolute path. I changed the symlink to point to an absolute path, and the config was loaded fine without any ```config.ini.backup``` being generated.

You can also pass the config location via the command line (```--config=location```) which would force it to load from the given location as well, again making sure to specify the absolute path to the symlinked config.ini file itself.

Unless you have your configs in a totally different mount point  (ie. different file system) in which case I don't think it will return a proper value from doing an ```os.path.isfile(symlink)```).If you are, then I think it might be possible to change the check to incorporate a mount point check as well, which would then allow for the symlink to be traversed properly.

But otherwise, I'm not fond of the idea of doing the .backup = running, .ini = saved. It just overly complicates matters/problems for the normal userbase, when something like this is probably in the 1% usage.
