### ISSUE TITLE
Not getting Mylar to work after install

### ISSUE THREAD

**Issue by soepstengel12** [evilhero/mylar#1945]
Hi,

Hadn't used Mylar for a long while. Now I'm starting to get it to work again, but even after following the wiki guide I still can't get it to work. I keep getting this error:

language detected as non-English (nl_NL). Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
Error in sys.excepthook:
TypeError: unbound method handle_exception() must be called with RotatingLogger instance as first argument (got type instance instead)

Original exception was:
Traceback (most recent call last):
  File "c:\Mylar\Mylar.py", line 342, in <module>
    main()
  File "c:\Mylar\Mylar.py", line 165, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "c:\Mylar\mylar\__init__.py", line 167, in initialize
    CONFIG = cc.read(startup=True)
  File "c:\Mylar\mylar\config.py", line 509, in read
    logger.mylar_log.initLogger(loglevel=mylar.LOG_LEVEL, log_dir=self.LOG_DIR, max_logsize=self.MAX_LOGSIZE, max_logfiles=self.MAX_LOGFILES)
  File "c:\Mylar\mylar\logger.py", line 80, in initLogger
    self.filename = os.path.join(log_dir, self.filename)
  File "C:\Python27\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

Tried a fix that was available that was sort of like this, but it didn't work for me. Still keep getting this message and Mylar isn't firing up.

Could someone please help out?

Thanks

**Comment by evilhero** [comment]
Do you have a log_dir set in the config.ini and if so what is it set to ?

**Comment by soepstengel12** [comment]
Looked it up and the setting as it is at the moment: "log_dir = None"

**Comment by evilhero** [comment]
Try just removing the entire line from the config.ini (yep, the whole ```log_dir = None``` line).

Otherwise, you can try to set the value to a location on your system where you want Mylar to save the logs. Normally, once Mylar is able to start up and possibly(?) update the config it would determine the log file location and save the config at that point. It's just not starting it at that point because of the None value I'm assuming (I'm also guessing that your config_version in the config_ini is probably not 8, as this gets changed when the config gets auto-updated)

**Comment by soepstengel12** [comment]
Adding a location worked. Mylar booted up succesfully.
Many thanks for your help!! 👍
