### ISSUE TITLE
mylar.service (Ubuntu 16+)

### ISSUE THREAD

**Issue by Ackis** [evilhero/mylar#1948]
If you wanted to update the service file in the repo, here's a systemd file that works for me.

```
[Unit]
Description=Mylar - Comic book grabber
After=all.target

[Service]
Type=forking
Restart=no
User=mylar
Group=mylar
RuntimeDirectory=mylar
RuntimeDirectoryMode=0750
GuessMainPID=no
ExecStart=/usr/bin/python /opt/mylar/Mylar.py --daemon --datadir=/opt/mylar --config=/opt/mylar/config.ini --nolaunch --port 8090

[Install]
WantedBy=multi-user.target
```

Edits: Forgot the Guess PID and made the ExecStart "bigger".

**Comment by BRTPOB** [comment]
Ackis, god damnit, stop showing up in random places, you bastard. (This is Offspring from #mmo-c).

**Comment by Ackis** [comment]
@BRTPOB Haha I'm everywhereeeeeeeee! Haven't been on IRC in a long time though.  I think I'm still idling there though.

**Comment by evilhero** [comment]
The mylar.service file included with Mylar is meant to use the mylar.default for the config values instead of directly modifying the mylar.service file itself (and thereby avoid adding all the custom commands in ExecStart). 

I'm not denying that your version works (cause it does obviously), it's just the mylar.default, mylar.service, mylar.initd files included with Mylar were included as a general-type usage example, as it's impossible to account for everyone's particular system setup.

Thanks for the offer tho (I might borrow the User/Group option as those aren't specified in the current mylar.default file).

PS. BRTPOB is a PITA.

**Comment by Ackis** [comment]
The problem (if you can call it that) is that the mylar.service file basically calls the init script. It felt... dirty.
