### ISSUE TITLE
Import not working when comic name has apostrophe

### ISSUE THREAD

**Issue by SUBnet192** [evilhero/mylar#1952]
Search results for import when comic name has an apostrophe returns nothing. Manual search works.

**Comment by evilhero** [comment]
Do you have any debug logs showing the search and what is being imported for? You can't manually search when importing - so not quite sure I know what you're describing exactly ubless you're just saying normal search works.

**Comment by SUBnet192** [comment]
I meant if I do a search from the top search box manually to add a new series it works. the mass import returns "no result" for anything with an apostrophe and even a dash or slash it seems.
![noresults](https://user-images.githubusercontent.com/11916348/39967793-21939206-5690-11e8-8189-77dfc24f8931.png)

**Comment by evilhero** [comment]
Those should actually be saying ```Manual Intervention``` (if you refresh the page does it change?). With ```Manual Intervention```, you have to choose the ```[Select]``` option to the far right for each series as it's indicating that you have to manually select a series from a shortened list of options, as there wasn't enough information provided for Mylar to automatically determine. Although with the ComicID being listed for each series on your list, it should be picking those up as well - have you tried to just use the checkbox and try to import one of the series that way to see if it would work ?

Note to that Mylar will not work with TradePaperBack's or Graphic Novels. This is due to the lack of an issue number in most cases which is one of the key factors for Mylar to be able to parse filenames properly, as well as with searching.

**Comment by evilhero** [comment]
Also, the import works with series with ```-``` in them (just mock tested against one of yours):
```16-May-2018 10:00:07 - DEBUG   :: mylar.preSearchit.3938 : Thread-26 : [IMPORT] Checking for any valid ComicID's already present within filenames.
16-May-2018 10:00:07 - DEBUG   :: mylar.preSearchit.3939 : Thread-26 : [IMPORT] {'Volume': u'v2018', 'ComicName': u'Hit-Girl', 'DynamicName': u'hitgirl', 'ComicID': '108817'....
16-May-2018 10:00:07 - INFO    :: mylar.preSearchit.3954 : Thread-26 : [IMPORT] Issues found with valid ComicID information for : Hit-Girl [108817]
16-May-2018 10:00:07 - INFO    :: mylar.addbyid.415 : Thread-26 : Attempting to add directly by ComicVineID: 108817
```
I would assume that the reason why the mass importer is failing is due to an error on the backend that's probably related to one of the series you're trying to import (ie. it's a TPB/GN, some weird issue number is present in the series, etc). You'd have to check the log to see (enable debug/verbose mode first), but you should see what series it was trying to import when it dies.
