### ISSUE TITLE
AUTO-COMPLETE-NZB issue

### ISSUE THREAD

**Issue by 2mny** [evilhero/mylar#1956]
I keep getting log messages like the below for the same 10 NZBID's. Restarting Mylar seems to resolve the issue until a file is processed by NZBGet.

> 14-May-2018 20:05:48 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 469}
> 14-May-2018 20:05:48 - WARNING :: mylar.processor.88 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
> 14-May-2018 20:05:48 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
> 14-May-2018 20:05:53 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 473}
> 14-May-2018 20:05:53 - WARNING :: mylar.processor.88 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
> 14-May-2018 20:05:53 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
> 14-May-2018 20:05:58 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 471}
> 14-May-2018 20:05:59 - WARNING :: mylar.processor.88 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
> 14-May-2018 20:05:59 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
> 14-May-2018 20:06:04 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 477}
> 14-May-2018 20:06:04 - WARNING :: mylar.processor.88 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
> 14-May-2018 20:06:04 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
> 

Also seeing post processing errors in NZBGet logs:

> Sun May 13 2018 15:16:17 | Post-process-script  ComicRN.py for  Koshchei.the.Deathless.05.of.06.2018.digital.Son.of.Ultron-Empire failed  (terminated with unknown status)
> -- | --

Not sure why the errors as Post Processing appears to be working correctly including Extra Script that runs after post-processing.

Using development build 4314b8b98cc25d6ed54313b611e638ab63711b4e. NZBGet is configured to use the ComicRN.py and AutoProcessComics.py scripts from this build.

**Comment by evilhero** [comment]
It looks like you have completed download handling enabled and you're using comicRN. If that's the case, you can only have one or the either enabled as they will fight for which can perform the post-processing at the same time, resulting in one throwing an error depending on the timing, while the other completes the post-processing.

(I thought there was mention of this in the GUI about having one or the other, but in looking I don't think there is - I should definitely fix that)

**Comment by MaartenMol96** [comment]
@evilhero I am getting the exact same unable to locate warning. I am using automated download handeling. However, when searching for a comic it semds them to nzbget, nzbget downloads it after that nothing happens anymore and I only get the message that it can't locate the item.

**Comment by phaelon74** [comment]
I am also having this issue.  ComicRN is not enabled, just Complete Download Handling.  This issue appears, if your download a comic faster than Mylar processes the previous one.  To get around this I've told it to scan the folder I download too every 1 minute.  This then successfully processes the comics BUT, it leaves them also in the NZBGet download directory.  So it requires manual intervention to clean up.

@evilhero I can replicate the problem if you'd like me too.

Also, YAYA, i got it working and it's soo beautiful.

**Comment by phaelon74** [comment]
To replicate, I took X-Men Gold, number 7 and 8.  Clicked Manual search in Mylar on both within a second of each other.  NZBGet got both, and once 7 finished, post-processing started, but 8 finished downloading within 3-4 seconds after 7 finished and the problem then occurred, where 8 finished downloading before 7 was done post-processing.

You can go to the bottom of the file and see the perpetual loop created:
24-May-2018 08:52:09 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
24-May-2018 08:52:14 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 269}
24-May-2018 08:52:14 - DEBUG   :: mylar.processor.96 : AUTO-COMPLETE-NZB : Now checking the active queue of nzbget for the download
24-May-2018 08:52:15 - DEBUG   :: mylar.processor.102 : AUTO-COMPLETE-NZB : valid queue result returned. Analyzing...
24-May-2018 08:52:15 - WARNING :: mylar.processor.105 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
24-May-2018 08:52:15 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
24-May-2018 08:52:20 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 269}
24-May-2018 08:52:20 - DEBUG   :: mylar.processor.96 : AUTO-COMPLETE-NZB : Now checking the active queue of nzbget for the download
24-May-2018 08:52:21 - DEBUG   :: mylar.processor.102 : AUTO-COMPLETE-NZB : valid queue result returned. Analyzing...
24-May-2018 08:52:21 - WARNING :: mylar.processor.105 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?

[mylar_nzbget_issue_CDH.txt](https://github.com/evilhero/mylar/files/2035603/mylar_nzbget_issue_CDH.txt)

**Comment by evilhero** [comment]
Y'all should be good to go now. Figured out the issue and will properly queue up and check things properly now.

Keep in mind though, manually queuing files quickly in succession can lead to some other errors - one of  which I'm looking at now (in other words, probably don't try too many like that)

**Comment by phaelon74** [comment]
Thanks @evilhero I've still left the File/Folder monitor active and it's doing a great job so far, but I'll grab the git shortly for the new version with the update to get it all good.

**Comment by phaelon74** [comment]
@evilhero How do I "load up" an ask to pull all comics from a series, in a nicer way?  What you mentioned above, manually queuing quickly causing issues.  Is there a better way to say add Spider-man and ask it to search for all 400+ issues missing?  I have it set to add comics as wanted right away, but it doesn't kick off a search.  For instance, in Sonarr, if I had a TV series, I have the capability to go to the Wanted tab, and click "search all" or "search all missing" and it will go out, find them if they are there and send them to nzbget.

Any way to do that in Mylar?  If not no worries and thanks for all your hard work.  How do I donate to the Mylar project?

**Comment by evilhero** [comment]
Well I'm working on a complete fix for the manually queueing up too quickly problem- but I have to make sure that I get all the search methods using the same fix, otherwise there will be problems, so it might be a few more days before it hits development.

As far as kicking immediate searches off:
- you can go to the Wanted tab and in the upper right corner there's an option to ```Force Check``` which will do an immediate search for all the issues that appear in the Wanted list.
- On the series detail page for the given series, you can also use the checkboxes and dropdown and select ```Wanted``` from there and it will mark all the given series as Wanted and start an immediate search for them (it will take a while if you have 400+ issues).
- When you add a series, and you have the 'add as wanted' option enabled it will just add them as wanted but not initiate an immediate search at that time.
- Make sure to enable the RSS option on the providers tab. This will continually check your providers feeds for new comic releases and cache the results. When it goes to search, it checks against the RSS first, before actually hitting the indexer's API so you might save some hits that way (plus you'll get stuff quicker usually with RSS as opposed to manually doing it or waiting for the scheduled search to happen)

There's a donation link to help aid my coffee addiction on the first tab in the Mylar configuration in the GUI. It's not required obviously, but much thanks if you happen to help me appease my addiction (I obviously fuel my coding with coffee, and sometimes it shows) ;)

**Comment by phaelon74** [comment]
Sent you some Bitcoin.  Keep up the good work.

I did the wanted tab, selected them all, and clicked wanted in the drop down and I'm not sure it's actually doing anything.  I did however tell it to grab 931 issues, so I see it slowly filling into NZBGet.

**Comment by phaelon74** [comment]
I think what I may be seeing/expecting, is for it to be like Sonarr, where it basically grabs 100+s and load them all in at once.

**Comment by evilhero** [comment]
Yeah, unfortunately for Mylar both Sonarr/Radarr have built in id's that they can reference on most sites in order to get the exact release (tvdbid, imdbid, etc) - whereas with Mylar there is no such luxury and it has to rely on straight parsing just filename information. What makes it even more cumbersome is that searching for an issue as '1' will produce different results than '01' and subsequently '001' as well - so in order to make sure Mylar hits all the right methods it has to do several searches for the same issue number with different paddings. I've done some tricks to try and speed up the searches, but when you have a good size queue of Wanted issues, it still has to go through the time/delays.

The current method is that it will do it one at a time, so you probably won't get much backlog in your download client as it performs the search, downloads and post-processes before moving on to the next item.

The new method that I'm working on will allow for some greater flexibility, and I'm pretty sure much less of a memory footprint.  The workflow is that it will search, and download the given issue - it will then either search for the next issue (if there's another to be searched for), while continuing to monitor the download for completion. Once it's completed (this is with Completed Download Handling obviously), it will send it for post-processing. Meanwhile, it will attempt to queue up the next download to monitor -  
while a search might also be being performed and/or post-processing all occurring on possibly different issues. Basically the end goal here is that you shouldn't notice anything different from a front-end standpoint, just things happening on a quicker level with some additional accuracy ;)
