### ISSUE TITLE
Add ratings?

### ISSUE THREAD

**Issue by shpanky73** [evilhero/mylar#1960]
Could we add ratings for new comics in some way?  Perhaps they can be scraped from comicvine or comicbookroundup?  That would be nice to see the new weekly list and discover new stuff.

**Comment by evilhero** [comment]
Well we can't scrape CV - if it's not in the API, won't be able to use it, so that's out of the Q.

Scraping the other site might work, but everything would have to be verified based on just series title & issue number alone and then attempt to match up to CV so that it can be attached to the correct series within Mylar (which would not be anywhere near 100% accurate - that's the problem with scraping).
It seems like a lot of work (and possibly problematic going forward), for such a little payoff - if there was something that was linkable without having to create another entire backend just for another pullist I'd look into that first (as I don't have the time to be doing that) - without site-scraping CV of course.

**Comment by shpanky73** [comment]
Hmm, I wonder how comicbookroundup is doing it then...must be a manual process. :-(  Ah well, it was an idea :-)
