### ISSUE TITLE
Manual Intervention Never Appearing

### ISSUE THREAD

**Issue by trumblejoe** [evilhero/mylar#1965]
Mylar Version: development
git build 4314b8b98cc25d6ed54313b611e638ab63711b4e.
Python Version : 2.7.13
Language : en_US.UTF-8

New user here. I have big chunks of comics already downloaded that I want to add to Mylar. I ran the importer but the Status under Import Results Management is always, _always_ No Results. I haven't seen Manual Intervention appear even once, tried refreshing on the page, etc. As far as the import, (totally not intuitive that I have to ADD the comic series before doing the import btw), it only imported 147 / ~550 issues. Also for my comic, Uncanny X-Men, the Uncanny X-Men is actually only issues 142 - 545; the first 1 - 141, are known as The X-Men. I tried adding the The X-Men and The Uncanny X-Men as comic series, but The X-Men failed to import any issues at all. I guess what I'm trying to say is I'm frustrated I have these files, and I know exactly what issues they are, and I have no way of matching them myself. I also find it very frustrating that I can't see which Comic Issue is matched to which specific file for error-checking.

**Here are examples of my file names:**
Uncanny X-Men 001 (1963) (digital) (Minutemen-Bluntman).cbz
Uncanny X-Men 010 (2013) (X-Men 50th Anniversary Variant).cbz
Uncanny X-Men 004 (2013) (Digital) (Zone-Empire).cbr
Uncanny X-Men 010 (2013) (Digital) (Zone-Empire).cbr
Uncanny X-Men 024 (2014) (Digital) (Zone-Empire).cbr
Uncanny X-Men 001 (2012) (Digital) (Zone-Empire).cbr
Uncanny X-Men 018 (2014) (Digital) (Zone-Empire).cbr
Uncanny X-Men 016 (2014) (Digital) (Zone-Empire).cbr
Uncanny X-Men 012 (2013) (Manara Variant) (Cover ONLY) (ArtNet).cbz
Uncanny X-Men 011 (2013) (Digital) (Zone-Empire).cbr
Uncanny X-Men 019.NOW (2014) (Digital) (Zone-Empire).cbr
Uncanny X-Men 013 (2013) (Chris Bachalo Variant) (Cover ONLY) (NN+ArtNet).cbr

**Comment by evilhero** [comment]
Well Manual Intervention will appear when there's a choice that needs to be made.  If you do not enable the ```use metadata``` option on the Scan Comic Library tab, it is forced to use just the text in the filename to gather available information which sometimes is less than desirable when attempting to import some series. As long as you have tagged your comics using a tagger (ie. ComicTagger, ComicVine Scraper, even ComicRack), it should be able to read the metadata and use the values therein to pin-point to the exact series that it is and import based on that. The metadata will only be read if it's a cbz file AND there is metadata present in the file.

This is the important part - DO NOT ADD the series prior to importing. 

That defeats the entire purpose of running the importer - it's purpose is to take a bunch of comics that do not currently exist on your watchlist (the main page which lists all of your series that you have), and add them so that they appear on your watchlist. 

If you add before running the importer, it won't import anything as the series already exists on your watchlist (and the logs will indicate this if you happened to look at them). If the series exists on your watchlist already, and you have a bunch of issues you want added, then you run the Manual Post-Processing on the given folder so that it can post-process the items into the correct series directories.

Mylar uses ComicVine as the data source primarily, so the way it appears there is the way that Mylar will attempt to use the data. It follows the same numbering convention in regards to series volumes as CV does, so again - the way CV has it is the way it is. You can however edit certain things once you have the series added, but that's not what this is about.

If the import is still a problem, go into the Logs tab, and click on the ```Toggle Debug Logging``` option in the upper right corner. Then go back to the import results screen, clear everything from the screen (ie. ```flush imports``` button at the top, or use the checkboxes and select everything and choose ```Remove``` from the dropdown). Then go back to the ```Scan A Directory``` tab and do the scan again (try enabling metadata this time if you didn't). When it's finished, you'll get a good size log file with all the relevant data. Pastebin that in here, or dropbox the relevant mylar.log file (if the import overflows the one log file, it will appear in mylar.log.2, etc).

Also:
- if you have the issues for a given series in one directory by itself, you can create a ```cvinfo``` file and just put in the full CV url to the particular series (not the issue, the series - all series end in 4050-XXXXX)
- when you're on the import results page, if you see a numeric in square brackets beside the series title (ie. [38381]), that's Mylar indicating that it detected a ComicID and it knows the exact series that everything in that particular directory will be imported as (if there is more than one ComicID it won't show anything however).
