### ISSUE TITLE
Unable to complete the scan: [Error 2]

### ISSUE THREAD

**Issue by knighteagle789** [evilhero/mylar#1971]
I'm getting the following errors when trying to do a mass import scan:
07-Jun-2018 12:32:14 - INFO    :: mylar.parseit.404 : LibraryScan : [SPECIAL-CHARACTER ISSUE] Possible issue # : –
07-Jun-2018 12:32:14 - INFO    :: mylar.parseit.404 : LibraryScan : [SPECIAL-CHARACTER ISSUE] Possible issue # : –
07-Jun-2018 12:32:16 - INFO    :: mylar.parseit.404 : LibraryScan : [SPECIAL-CHARACTER ISSUE] Possible issue # : –
07-Jun-2018 12:32:24 - INFO    :: mylar.parseit.404 : LibraryScan : [SPECIAL-CHARACTER ISSUE] Possible issue # : —
07-Jun-2018 12:32:24 - INFO    :: mylar.parseit.404 : LibraryScan : [SPECIAL-CHARACTER ISSUE] Possible issue # : —
07-Jun-2018 12:32:25 - ERROR   :: mylar.scanLibrary.622 : LibraryScan : [IMPORT] Unable to complete the scan: [Error 2] The system cannot find the file specified: 'M:\\Comics\\Marvel\\S.H.I.E.L.D. (2010)\\S.H.I.E.L.D. Vol.2010 #8 (June, 2011).cbz'

When I look at the last entry, I am seeing '\\' not sure that is correct, and not sure where that is coming from.

Configuration Options
Mylar Version: development
-- 
git build 5e6b861fadcbd6a43412e0a4e8a7cdee6e8e945c.
Python Version : 2.7.15
Language : en_US.cp1252
--

**Comment by evilhero** [comment]
The possible issue # lines are just indicating that it thinks that the dash is part of an issue number based on what the file parser can determine (basically, they're not named in a format that it can understand, otherwise the - would be interpreted properly).

The actual error tho would indicate that the file indicated cannot be located at that specific location during the scan. Maybe it's an external drive, and it lost connectivity - or even that the permissions on the file/folder don't allow for the scan to complete properly or read the file.

You can enable debug logging prior to the import (going into the Logs tab/click on the ```Toggle Debug Logging``` button. Then attempt to perform the import again and you'll get more detailed information as to what's occuring hopefully.

**Comment by knighteagle789** [comment]
ok.... after turning on the Debug, I was able to get the files to show up.... now I'm getting the following error:
07-Jun-2018 18:17:32 - ERROR   :: mylar.excepthook.314 : Thread-19 : Uncaught exception: Traceback (most recent call last):
  File "c:\mylar\mylar\logger.py", line 336, in new_run
    old_run(*args, **kwargs)
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\mylar\mylar\webserve.py", line 3962, in preSearchit
    self.addbyid(comicinfo['ComicID'], calledby=True, imported=imported, ogcname=comicinfo['ComicName'], nothread=True)
  File "c:\mylar\mylar\webserve.py", line 420, in addbyid
    return importer.addComictoDB(comicid, mismatch, None, imported, ogcname)
  File "c:\mylar\mylar\importer.py", line 468, in addComictoDB
    search.searchforissue(result['IssueID'])
  File "c:\mylar\mylar\search.py", line 2079, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)
  File "c:\mylar\mylar\search.py", line 334, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)
  File "c:\mylar\mylar\search.py", line 1783, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host)
  File "c:\mylar\mylar\search.py", line 2798, in searcher
    sendtosab = ss.sender()
  File "c:\mylar\mylar\sabnzbd.py", line 52, in sender
    'nzo_id': ''.join(sendresponse['nzo_ids']),
KeyError: 'nzo_ids'

**Comment by evilhero** [comment]
That's a search error related to completed download handling and sabnzbd. Can you paste the debug lines leading up to the error so I can see the context and how you got to that point?

**Comment by knighteagle789** [comment]
08-Jun-2018 14:11:03 - INFO    :: mylar.markImports.2413 : CP Server Thread-4 : importing selected series.
08-Jun-2018 14:11:03 - INFO    :: mylar.markImports.2441 : CP Server Thread-4 : Initiating selected import mode for 1451 series.
08-Jun-2018 14:11:03 - INFO    :: mylar.preSearchit.3999 : Thread-44 : [IMPORT][Spider-Verse Team-Up (v2014)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
08-Jun-2018 14:11:03 - ERROR   :: mylar.excepthook.314 : Thread-44 : Uncaught exception: Traceback (most recent call last):
  File "c:\mylar\mylar\logger.py", line 336, in new_run
    old_run(*args, **kwargs)
  File "c:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\mylar\mylar\webserve.py", line 4006, in preSearchit
    logger.fdebug('[IMPORT] [!none] dynamicname: ' + DynamicName)
TypeError: cannot concatenate 'str' and 'list' objects
****

**Comment by evilhero** [comment]
Weird, that error shouldn't be coming up. I've readjusted almost all of the logging statements in that particular import section to account for this type of error, so it shouldn't happen any further. This is now in development commit 97d4fbb. 

Give that a try and see if you can get any farther. If you can enable debug logging prior to starting the process again, it would help with further troubleshooting.

Some people have good luck with the importer, some unfortunately encounter a crap-tonne of problems due to either their naming conventions or some other problems that seem to be unique to their setup as they haven't been encountered by others for whatever reason.
