### ISSUE TITLE
Feature Requests For Mylar

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1975]
- Ability to specify automatic folder creation to drop articles ("The ", "A ", etc) (I know you can manually edit the comic directory, this would be for the automatic creation.)
- Option to not automatically create a folder for new series additions (it may be there already but I haven't found it.)
- Option to integrate Specials (like Annuals) with a series
- Library import should have an option to run comictagger (and presumably other post processing) on issues without metadata
- When deleting a series, an option to nuke it from the db file as well (it seems to remember things if you delete and re-add)
- When rechecking files for a series there should be an indicator on the comic series page that a check is in progress and an indicator when it's complete. 
- Advanced search option to be able to specify publisher, year range, number of issues range, etc.
- This is real long shot but I'd like to see many more options for folder/filename masks.   See below.

The way I organize my comics may be a little bit weird, although I'd like to see Mylar's folder/filename options allow me to automate it.     For this example assume the library root folder is the actual root folder.    

/PUBLISHER/ALPHA/BASE TITLE/YEAR[-SECONDARY TITLE

Limited/mini series I tend to add a (Mini) at the end of the title.

Examples:

/DC/T/Titans/1980-New Teen Titans
/DC/T/Titans/1982-Tales Of The New Teen Titans (Mini)
/DC/T/Titans/2016/(issues)

In this example, obviously, I'd need to have a way to tell Mylar that the "base title" for "Tales of The New Teen Titans" "Teen Titans" "New Titans" "Titans", "Titans East" and other variants that they all belong to "Titans".

**Comment by evilhero** [comment]
Ok, bullet form response again (it's probably easier to break up some stuff):

-  ```Article dropping in foldernames```: Good suggestion. Will have to build in a solution so users can update their existing libraries so everything is uniform, but aside from that should be doable.
- ```Not creating folders for new series```: Already exists in the config.ini (create_folders = True/False, default is True).
- ```Integration of specials```: Because CV doesn't link annuals to particular series, everything is done by Mylar on the backend - so it's not 100% accurate, but it's pretty decent.  You can integrate anything into a given series, just enter the ComicID into the lower right corner of the series detail page that's labelled as ComicID. For the most part as long as the special has an issue number it should import fine. What happens thereafter I'm not 100% sure about - as it wasn't tested against that type of detail. In theory it should be doable, but it would probably require some back-end code changes to account for the different naming in the file parser, search, post-processing, and some other items.
- ```Library import metatagging```: It's been requested before, but it's not as simple as just enabling an option. There's a lot of backend changes that have to be done in order to accomodate this properly. It's not a no atm, just more of a 'soon/in the future' option.
- ```nuke series in db```: It should not be leaving any stragglers when you delete a series. It removes all traces from the multiple db's it hits, albeit if you downloaded some issues, it would not delete that from your history. If you can give more details it might help in figuring out what you're describing.
- ```rechecking files```: Usually the recheck files locks the screen, so it updates the screen automatically when the recheck is completed. Not very long for most series, but if you're rechecking 2000ad as an example, the recheck will take awhile and lock the screen until it's completed (not ideal, but it's the only way to do a screen update immediately). There used to be a 'recheck completed' popup box that happens after the recheck is completed, but it's not happening so I'll have to look into that. If I can figure out a way to implement some kind of display option that shows that a recheck is currently in progress I'll try to implement that, but again, not sure if that's possible given the way the codebase is.
- ``` Advanced Search```: The search function is already streamlined so that it only returns hits regarding what you're searching for. Having additional options, while might lessen the search results, wouldn't lessen the search time frame since the way CV returns valid responses wouldn't change. Again, not saying no - but 'in the future' might look into it more as it would require a new page to display the options along with additional code changes that would take time to implement.
- ``` folder/filename masks```: From your requirements, it's not going to happen in the current code. The reason why is that there is no way to perform a grouping of Series cleanly such that it will always be adhered to. The Alpha option is possible, albeit with it's own problems related to renaming. There has been discussions of doing a grouping on the main page, but that was based on volumes not just series titles that could be manipulated/changed. Adding in that requirement changes the dynamics of the grouping entirely. From a folder organisation standpoint, the grouping aspect might be more easily done then within the GUI (especially since GUI is not my strong point at all) - but again it would require a good amount of testing/code change in order to accommodate changes and would probably be lumped into the soon to be popular 'soon/in the near future' option.
