### ISSUE TITLE
Issue with Linuxserver.io/Mylar Docker Container

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1979]
(**NOTE:** This is not an evilhero issue but I wanted to put this here in case people are having issues with it.   I've reported it on Linuxserver.io's github https://github.com/linuxserver/docker-mylar/issues/17)

The linuxserver.io mylar container published 2018-06-08 15:10:24 with `sha256:2176dc52bd24984ee650e09717f7013fdff8be420e7d26dcf02bb66b80edba2f` contains a library that Mylar is not happy about.    

Mylar appears to still run anyway but there could be unexpected results.

The error is visible in Mylar with debug logging enabled:

`DEBUG | [META-TAGGER] Output: /usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!`

**Comment by LeeThompson** [comment]
I've found if you have metatagger enabled and you get the above errors, Mylar is able to initially process the file in the /cache but then cannot move it to the new comics folder and so your cache will grow endlessly with not much happening.   (I've disabled tagging for now.)

**Comment by evilhero** [comment]
The only lines that have an output logging statement are ones that occur when the metatag fails for some reason (nor expected filesize, trying to convert a non-rar, corrupt archive, etc)

It looks like it's trying to access the requests library which comictagger doesn't do in the version that comes with mylar (not sure about the newer version which has become an entirely new fork almost). Are you using the version with mylar (it indicates as such in the logs) - and/or did you add any extra config options to comictagger in some way that it's trying to do additional things (ie. comparing images directly against CV)?

**Comment by LeeThompson** [comment]
I did nothing with Mylar or comictagger but it's possible linuxserver.io did for the Docker image.

I'll try to get you a full debug log, I don't want to post it in public due to the lame comics I like.

**Comment by evilhero** [comment]
Looking at that it looks like it's using the system requests instead of the one package with Mylar. What I'm guessing is that the Mylar version of requests is out-of-date (I think), but your OS version (and subsequent dependencies) are up-to-date - so it's throwing the warning about the version.

Mylar should have the dependencies file for all of that, but I haven't even tried to look at it - so that's why there are some modules in the /lib folder that probably don't have to be there.

However if it's failing to move - is this part of your other issue whereby you're having a race condition and the move fails ? 

And everyone reads lame comics - of course if you're reading My Little Pony then I would expect some smart quips about it however ;)

**Comment by vader083** [comment]
Getting the same issue, everything is snatched but post-processing fails with that issue.

**Comment by evilhero** [comment]
I believe this problem/error should be fixed in the latest development commit. Please try it and let me know if it's resolved or not.
