### ISSUE TITLE
Feature Request: Series Editor

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1985]
As I'm getting more familiar with Mylar and setting up the folders and such, I'm finding I want to change the way already added series folders are set up, right now this is a manual affair of editing a series and using the next and previous icons.   So "next", "edit settings", (changes) (update); repeat.

What would be really useful is perhaps already in the manage/comics screen if the folder path was shown (perhaps truncated with ... for display) and if you could edit "Comic Name", "Path" directly on that screen (similar to how phpmyadmin works when you're looking at rows of data).

I would not expect (or want) it to automatically *move* comics, create the new folder right away, or delete the old folder.   It would just be to make batch editing a bit faster.

Lame Example:

Checkbox | Comic Name | Path | Status | Check | Latest Issue | Publisher | Have | Updated 
----------- | -------------- | ----- | ------ | ------- | ------------- | ---------- | ---- |  -------
[ ] | Action Comics (1938) | /comics/DC/Action Comics/1938 | Ended | (Green Check) | 904 (2011-10-23) | DC Comics | 877/877 | 2018-06-08 13:06:15

if I clicked on "Action Comics" or "/comics/DC" ... it would let me edit them as text fields.

Barring that some kind of option called "Edit" for Batch Edit Mode in the pulldown would work too.

**Comment by evilhero** [comment]
Well you can't edit Comic Name. That's linked to CV ComicID, which has innumerable links within Mylar based on that specific naming (thus the reason why the Alternate Search Names field was made, etc). At least in it's current code base, it's can't be done easily - and I'm not really wanting to recreate everything based on a new UUID in lieu of using ComicID for obvious reasons.

The path tho is probably doable from the manage tab - I'll have to look into it and see what can be done. GUI stuff is not my strong point,  I would imagine some would like if the path exists and you edit the field, it would rename the folder to the corrected naming instead of keeping the current naming on the file system and a different one in the db (even if Mylar wasn't creating folders, it would still create an entirely new directory when required and then you'd have 2 separate folders kinda thing again). 

Batch editing is fine, but if it's only within the db - the relative usefulness of requesting such a feature is kind of lost in the mix as then you're doing more manual work outside of Mylar instead of automating something that could be done.

**Comment by LeeThompson** [comment]
I meant the "Series Name" (on the manage comics screen there's a rename series option).   Anyway UI isn't my strong suit either.   :)

I should probably actually help contribute some code if I ever get unbusy enough... (although I'm pretty new with Python, relatively speaking).
