### ISSUE TITLE
Mylar as a Windows Service

### ISSUE THREAD

**Issue by rg9400** [evilhero/mylar#1998]
I've been using mylar on windows 10. To launch it, I have to run a python command via Command. This is due to the fact that clicking on the script doesn't work. A command interface pops up and then quickly shuts down with nothing put in the logs. I don't think this is an issue with Python since I run a few other services in various folder locations, and I can click the py script to launch them.

Running via command works perfectly fine though, and from there, Mylar launches and works smoothly. Unfortunately, as mentioned, the main problem is that this issue does not allow me to use NSSM to run Mylar as a windows service using python as the startup program. It just keeps saying the service gave no error but did not launch correctly. I created a simple bat file to run the command lines, and that works. I placed that in my startup folder, but it does not launch at boot, only at login. Is there another way I can get mylar to be working on startup?

**Comment by PCurd** [comment]
It sounds like a path issue, but to answer your final question you can
create a scheduled task set to start at boot. These instructions are for
Windows 7 but 8/10 are much the same:
https://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html


I have my Mylar set to start from the Startup folder but I do have to login
to start it, as you said.

**Comment by rgupta9400** [comment]
I tried using the Task Scheduler, but it doesn't do anything. I configure it to start python.exe with the argument for the full location Mylar.py file, exactly the same way I configure NSSM. Nothing happens. Mylar only seems to want to run via the Command Interface, which is strange. I have a few services where I can just click the .py file for them to run (and this makes configuration as a Windows Service easy).

**Comment by evilhero** [comment]
Double-clicking on a .py file and having it run is a windows-related/python type of thing. Mylar is just a bunch of .py files like any other application, so you not being able to double-click on a .py file and it not running is actually normal. For the .py to execute on a double-click you have to make sure that your python executable is in the ENVIRONMENT_PATH variable of your OS, and/or change Mylar.py to Mylar.pyw (the .pyw will allow it to be double-clicked on while minimizing the command window that will probably popup).

As far as NSSM, no clue. I don't use windows so that's beyond me. I would imagine though if you're calling it from a batch file, add the -v switch to the command you're running within the batch (ie. python Mylar.py -v) so that it will verbosely log stuff. Then when it dies when you try to run it, you can check the logs/mylar.log file and see if it logged anything that might help fix things.

The only other thing I can think of is that if you have python3 on your system in addition to python2, make sure that the batch file/NSSM are calling the correct python version.
