### ISSUE TITLE
SUGGESTION: Enhanced error/info logging

### ISSUE THREAD

**Issue by kingfenix** [evilhero/mylar#2001]
I am getting this repeating currently in my log "this has an alpha-numeric in the issue # which I cannot account for." and even if I toggle the debug logging on, there is nothing to tell me which issue #, in which series, etc...so how can I know what I need to look at or fix?

Could someone review anything touching the log and make sure that some basic info is always accompanying those entries? hell maybe even a link to the offending item within mylar so the log can tell us all where to go, lol

**Comment by evilhero** [comment]
Everything is done in sequential order when it comes to viewing the logs. This is why we always ask for users to include the full debug log leading up to the error as the leadup-lines usually indicate exactly what it is that's being worked on or has further details. If you read a few lines above the alpha-numeric warning in the logs (look in the mylar.log files, not the GUI as the GUI tends to shorten stuff for display) it should indicate exactly what the file was that was being looked at in addition to the parsing details. In order for debug logs to log items however you have to have debug mode enabled prior to performing the problematic operation.

It also might depend on what you're doing when you encounter the error - since that warning can occur when you add a series / refresh a series / import a series / file check / post-process / etc...  It can probably be worked out so that the issue number is offered - but again, it might not even be a correct issue number (which might be the problem, as if the file parser cannot parse the file name properly the issue number won't exist, or will be entirely wrong). 

Also can't link to an offending item - since again, depending on what you're doing it may or may not be within Mylar and even then it might not have all the correct db data to link back to properly.

**Comment by kingfenix** [comment]
understood, thanks for explaining evil...I will go dig deeper now, thanks anyway

**Comment by evilhero** [comment]
Can I ask what you were doing when you encountered the warning ? If it was post-processing/file-checking kinda thing, the the file parser will display a listing of all the files it considers ```failed``` (which could mean anything from no issue number, unparsable series name to invalid dates, non-alpha numeric issue number, etc) in the debug log. When the parser can properly parse the item, it will indicate a breakdown for each file as to what it thinks the series, issue number, year, volume, etc are for the given filename it's parsing.

**Comment by kingfenix** [comment]
I had noticed while "paging through my series like a madman" that some of them seemed to be stuck in refresh mode, highlighted blue and had the busy spinny thing even though these series were added who knows how long ago. So for each of those series I would enter it and hit refresh comic, then move on...probably had 20 series like this in my whole collection....

the error seems to be re-occuring on its own now, sort of like every so often its still trying to refresh something but failing, which is why I assume a series remains highlighte blue with a spinny thing, I may end up just removing those to get rid of this.

**Comment by evilhero** [comment]
Can you name a few of the series thay you have that have the spinner and stuck on loading? The comicid alone would be enough

**Comment by kingfenix** [comment]
well I just went page by page (painful) looking for any highlighted blue like they were, and apparently on a series level at least they all updated and are now green, I remember a few of them and they were not oddballs or anything one was a cyclops LS, another was a amazing spidey/black cat LS, nothing to weird.
