### ISSUE TITLE
(Minor UI Issue) Mylar Keeps Pagination When Changing Weeks For Pull List

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#2003]
If you're using Mylar's weekly pull list UI and you're not on the first page, if you change weeks (previous or next), you will remain on the page you were on (unless the new week does not go that far).     It should reset the page if you change weeks.

(Or if some folks prefer that, make it a boolean flag somewhere.)

**Comment by evilhero** [comment]
The pagination remains due to the filter most likely. 

I'm not sure it's just as easy as being able to do a reset on the page numbering only (since the filter shouldn't be reset between page views, as I know people use that).

Allowing for a boolean flag, and then combining that with datatables and the GUI is also not a simple task for a minor UI problem ( especially for me ). 

I'll mark this as a bug/enhancement kind of thing - but not sure about any timeline for completion.
