### ISSUE TITLE
Weekly Pull List Issue: Strange Entry (May be ComicVine Issue)

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#2007]
This is probably a ComicVine issue but just in case:

Within Mylar, the weekly pull list for "July 08, 2018 - July 14, 2018 (15)" lists a "Superman (#1)" from "DC Comics" (Add or One-Off) option.   But if you click on the book's think the ComicVine entry is for the translated comic by Panini Comics. 

If you "Add" the book to Mylar, the 2017 Panini Comics run is what is listed.

I have not tried Mylar's "Re-create Pull List' option at this point and nothing else seems unusual.

(Obviously, if this is a ComicVine or other data source issue please close and sorry for taking up your time.)

**Comment by evilhero** [comment]
It's not really a CV issue, but it kinda is (in a roundabout way). I'll try and explain.

Mylar's pull-list uses more than just CV to draw upcoming issue information. It does however rely on CV to have seriesdata/issuedata present before the client can properly track it. Because of the amalgamation of sources, there's sometimes a ```dead spot``` where a series is new but doesn't have a comicid assigned yet on CV. Normally when this happens, Mylar knows enough to not track it and simply present an option called ```Auto-Watch``` whereby it will monitor CV for the data and when it's present it will automatically add the series to your watchlist and mark the given issue as Wanted.

The problem (in this particular case) is that because there was the previous volume that ended fairly recently, it thinks that it's a viable option and attempts to match to the closest volume it can find (which in this case was by Panini). This is large part to how the sql query works on the backend (Mylar doesn't hit CV directly for all of these queries, but an intermediary site) to retrieve all the data for the pull - I'll have to try and tweak it so that it can account for these instances properly, but because it's a huge sql query it's really tricky to get it right so other aspects don't break.

In the meantime, I removed this particular series from appearing on the pull for that week (right now the only option since it's being incorrectly mapped). Once it gets closer to the given week (July 8th+), and the series data becomes present on CV, the option to ```Auto-Watch``` should present itself and then it can track things normally.

I'll mark this as an enhancement/bug so I can make sure this gets addressed.

**Comment by LeeThompson** [comment]
That makes sense, thanks for explaining it. 

I should also note this is the only instance I've seen the behavior so it's not a big priority.
