### ISSUE TITLE
Version check not running automatically

### ISSUE THREAD

**Issue by kmccormi** [evilhero/mylar#2008]
This issue has been niggling at me for a while and I've tried various reinstalls/wipes to resolve it but nothing seems to work.

Installation Info: Win 10; Mylar installed via Git, up to date

Mylar is working fine, but the auto version check functionality has somehow become disabled. Initially I thought it was because of a corrupt config.ini file, so I wiped the installation and manually recreated the old configuration settings - didn't help. Checking for new commits from within Mylar works fine and it will update to the new commit without incident, but without resolving the auto version check issue.

I also updated via git pull from the Mylar directory without incident, with Mylar shut down, but still no luck.

I've enclosed a screen capture of the Activities/Jobs web page within Mylar which shows the version checker as last run in April (and some duplicate jobs as well - don't know what that is about)

![jobs screenshot](https://user-images.githubusercontent.com/20611120/41954409-b5e4bfac-7a0d-11e8-881b-d24c194c0f7d.png)

My config.ini file (edited to remove personal info) and debug log are also enclosed.
[config.txt](https://github.com/evilhero/mylar/files/2139867/config.txt)
[mylar.log](https://github.com/evilhero/mylar/files/2139868/mylar.log)

Thanks for any help

**Comment by evilhero** [comment]
There are 2 variables in your  config.ini that are probably set incorrectly if you're wanting to check the version at regular intervals.

- ```check_github``` has to be set to True if you want the Check Version to run on a scheduled time (ie. the Schedulers tab you pasted). Setting it to ```False``` would disable that particular scheduler from ever starting.

- ```check_github_on_startup``` should be set to ```True``` so that Mylar can check if it's up to date on each startup sequence.

Setting both of those as indicated above should get the scheduler running properly again for you.

As far as the duplicate scheduler entries, that's not normal. I've only seen this occur with one other person thus far, and a simple restart fixed things for them. I wasn't able to replicate things then, so I'm doubtful I could now (which sucks) - but seeing as how mylar pulls that info from your dB it would imply that it's some kind of db-related problem. If you're ok with it, I'd be interested in seeing your mylar.db file - or at the very least, see what the dB  table entires are for schedulers.

**Comment by kmccormi** [comment]
Thanks for replying so promptly - I made the changes and the auto check is back in action!

My mylar.db file was over 1 gig, so I zipped it and is now 167mb and available at the following link: 

https://1drv.ms/u/s!AmnntYTdMXGoy1_9UnGcNwanBF_6

Let me know if there is a problem with the link and I can send via other means.

Many thanks,

**Comment by kmccormi** [comment]
I saw your recent fix for duplicate scheduler entries (it worked!) so I’ll mark this issue closed, with thanks.
