### ISSUE TITLE
File with "Volume" in title name being ignored on import

### ISSUE THREAD

**Issue by p4tchw0rk** [evilhero/mylar#2009]
When I attempt to import the file, "Bone The Complete Cartoon Epic In One Volume 1 (2004)" for the series of the [same name](https://comicvine.gamespot.com/bone-the-complete-cartoon-epic-in-one-volume/4050-44338/), Mylar appears to be ignoring the word, "Volume," in the filename (see attached screenshot of the relevant debug log).

Enormous love for this project. Can't thank you enough for the effort you put into it.

![screenshot](https://user-images.githubusercontent.com/6001616/42115437-da3931a8-7bc0-11e8-95fc-889ac54dda7e.jpg)

**Comment by evilhero** [comment]
Mylar is built around the assumption that each file has an issue number. So because of this, it won't work well with trade paperbacks/graphic novels/ compilations. Alot depends on how CV has it as well - if CV has the issues labelled with an issue number then mylar has  better chance of figuring things out. But otherwise if it can't parse the filename, odds are it's due to lack of the issue number (which you can see in the log you provided that there is no issue number detected).

This might change at some point (being able to work properly with non-issue number items), but currently its really hit or miss if it will work properly with these types and detect everything as it should.

**Comment by p4tchw0rk** [comment]
Thanks for the feedback! That all makes sense. I didn't have any luck with the pound sign, but that's fine. I can live with a single file being left out. I suppose I could just add it manually to the db directly.

Thanks again.
