### ISSUE TITLE
Cache fills up storage volume

### ISSUE THREAD

**Issue by geeklingo** [evilhero/mylar#2018]
Is there a way to limit the cache folder size? My volume was filled up by mylar cache

**Comment by evilhero** [comment]
Yeah there should be a way - but it also depends on what was in the cache folder at the time it was filled up in your particular case. 

Normally the cache just holds images for the covers, and torrent/nzb files. But there are other options that if used could increase that exponentially:
- If you happen to use the download option in Mylar, it will copy the cbr file into the cache folder. 
- If you happen to have alot of post-processing occurring with metatagging, the files will get copied to the cache folder to get tagged, but they should be deleted after the post-processing has completed. 
- If they haven't been deleted  (meaning you have a bunch of ```mylar_XXXXX``` folders within the cache folder itself), then the post-processing wasn't able to delete the folders, and/or post-processing failed for some other reason (permissions, destination location full, etc). 

Do you happen to remember what the files were that were taking up all the space? (ie. if it's cover images, we can't really limit that without breaking functionality)

**Comment by geeklingo** [comment]
It was a bunch of mylar_XXXXX folders within the cache folder itself

**Comment by evilhero** [comment]
If there a bunch of those folders in the cache it means that the post-processing wasn't able to fully complete (or the metatagging itself).

Normally it's due to permissions problems, but could be due to corrupt cbr's, out of space on the destination, or even some other reason that would have been logged.

Basically, if you can't figure out why they're not completing properly (which would involve deleting the mylar_XXXXX folders), it's just going to continue filling up and possi lt have other problems such as redownloading issues since it might not have changed the status properly after post-processing.
