### ISSUE TITLE
Large Wanted List

### ISSUE THREAD

**Issue by leaderdog** [evilhero/mylar#2023]
Hi Evilhero,

I have over 500 issues wanted on my wanted list.  Many of these may never be uploaded.  I'm curious, does Mylar go through everything in the wanted list to see if it available for download?

If it does, I'm wondering if you can't make a new tab, or secondary wanted list (long shots or pipe dream) that will put the files from the current wanted list that haven't been found after a few months of searching.  This way the wanted list stays more reasonable and the secondary list Mylar will just do a scheduled monthly check for them (first of last day of each month).

I'd assume that would clear up some time wasted on books that aren't around.
for example,
Knights of the dinner table is no longer uploaded (that I know of)
Femforce (whatever it is, hasn't had a new issue uploaded in a very long time)

Those two alone would remove about 55 books.

**Comment by leaderdog** [comment]
awesome!  glad to hear this will get tackled.  The Wanted List for me takes a very long time to load.  Hopefully, with a two tiered system it won't?  Or maybe that has nothing to do with it.

Just happy it's in the works.,

Thanks.

**Comment by evilhero** [comment]
Tiered is available in the latest development commit f7c1629. Once an issue is added it stays in the 'primary queue' for 2 weeks whereby both RSS + API searches are performed as per usual. After 2 weeks, it drops down to the '2nd Tier' whereby they are only checked against RSS searches. Manual searches for the given issue will still perform both API + RSS however. 

You can see the Tiered list in the Wanted tab, whereby it shows the 2nd Tier Wanted items, as well as the Primary Tier.

I don't think it will fix the load time, albeit we might be able to work something out whereby it's configurable to show the 2nd Tier so that the load time is more snappy.

**Comment by leaderdog** [comment]
Sweet.

Looks good.  But ya that load time took 6 minutes 43 seconds (391 wanted items).  I take it, it's more than just a list? ;)  

I did try loading it a few times and with 2 different browsers just to be certain.
