### ISSUE TITLE
Jackett not working. jquery errors in console? Nothing in logs.

### ISSUE THREAD

**Issue by SCRPD** [evilhero/mylar#2035]
I was trying to add jackett into the torznab section and hitting test does nothing.

I guess the debug logs show nothing because the test button doesn't even process.

Picture of my setup:
![2018-07-25_23-26-23](https://user-images.githubusercontent.com/20602276/43239951-449a26dc-9062-11e8-912b-e3105c8bce0b.png)

Console errors:
![2018-07-25_23-26-49](https://user-images.githubusercontent.com/20602276/43239958-4fa1eca4-9062-11e8-8cea-f22f532d65e3.png)

The content of the oSort error in the console too:
```
jQuery.fn.dataTableExt.oSort['title-string-asc']  = function(a,b) {
	var x = a.match(/title="(.*?)"/)[1].toLowerCase();
	var y = b.match(/title="(.*?)"/)[1].toLowerCase();
	return ((x < y) ? -1 : ((x > y) ?  1 : 0));
};
```

**Comment by evilhero** [comment]
It should be that the test button is broken if I recall correctly. Using torznab during a search within mylar should still return valid results so long as things are named normally on the site you're using.

The osort error shouldn't come up on that as there's no datatable sort present on the config screen. So that's something to look into.

Which branch / commit of mylar are you running? On which OS? What browser are you using?

**Comment by SCRPD** [comment]
Okay.

I'm on Debian Stretch using Docker Compose [linuxserver/mylar](https://hub.docker.com/r/linuxserver/mylar/) container
Browser is Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Mylar info:**
Mylar Version: master
-- git build 668278107b7f3416d2e2c6abad67d5665b75e0e9.
Python Version : 2.7.14

**Branch history:**
[6682781] Merge branch 'development' {7 days ago/evilhero}

**Comment by NoxInmortus** [comment]
Hello, I have the same issue. How the stuff going ?

**Comment by ivtechboyinpa** [comment]
I can confirm that the test button does not work, but will return a valid result as long as you paste your Torznab link and API key from Jackett

**Comment by NoxInmortus** [comment]
Well yeah sure, but when you're trying to debug, that's pretty shitty.

Do you know if using https://jackett/torznab/all url works ?

**Comment by barbequesauce** [comment]
@NoxInmortus the project happily accepts PRs if you know a better way to handle it :)

**Comment by NoxInmortus** [comment]
@barbequesauce Honestly I would be glad to support open-sourced cool projects like Mylar, but first of all, I support too much cool projects... and I still need to sleep :(

And I don't think I will use Mylar that much to feel the need to go head into the code. 

Sorry !

But I'm still following tho.

**Comment by evilhero** [comment]
@Noxinmortus, you're absolutely right.

You shouldn't use mylar with your 'shitty' attitude towards open-source projects.

**Comment by NoxInmortus** [comment]
@evilhero Woa, calm down, i'm not being aggressive towards anyone, at worst I'm only pissed off by a bug, I'm not disrespecting your work or anyone else's works.

**Comment by evilhero** [comment]
No one's fired up - aside from the general lack of coffee atm. 

What I was meaning (in perhaps a not subtle way in retrospect) was that open-source projects are part-time/less time hobbies usually so there will be bugs.  

Having a test button be responsive, while annoying sure, it's not a game breaker as far as some of the other issues going on. We tend to focus on the big ones prior to the small ones, which is why @barbequesauce mentioned the PR.

**Comment by NoxInmortus** [comment]
And because of this I have a lot of respects for such projects, and people maintaining it. I was not trying to be disrespectful in anyway, sincere apologies if it was received that way. I completely understand there is bigger priorities to some small ui bug. Case closed. Cheers.

**Comment by ajslater** [comment]
The error is here:
https://github.com/evilhero/mylar/blob/d1ff6079a0d1994272fd441736fc27ee2c8084d1/data/interfaces/default/config.html#L2328
should be:

`var apikey = document.getElementById("torznab_apikey"+torznab).value;`

Either that or rename the html input field.

getElement() returns a null because the element does not exist and then it barfs trying to call the value of nothing.

**Comment by barbequesauce** [comment]
Great catch! Thank you!
