### ISSUE TITLE
Unable to use 32Pages

### ISSUE THREAD

**Issue by JohanSF** [evilhero/mylar#2054]
I can succesfully authenticate with 32p
![image](https://user-images.githubusercontent.com/6782603/43993110-f5249504-9d88-11e8-9a16-2d1398d75bd4.png)

However when I search for a wanted series, that I know exist on 32p and is not in a pack - and I have provided mylar with the 32p series ID nothing happens and I get this in the log:
`2018-08-11 17:02:10 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/mylar/logger.py", line 336, in new_runold_run(*args, **kwargs)File "/usr/lib/python2.7/threading.py", line 754, in runself.__target(*self.__args, **self.__kwargs)File "/app/mylar/mylar/importer.py", line 468, in addComictoDBsearch.searchforissue(result['IssueID'])File "/app/mylar/mylar/search.py", line 2118, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p)File "/app/mylar/mylar/search.py", line 336, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p)File "/app/mylar/mylar/search.py", line 1785, in NZB_SEARCHsearchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)File "/app/mylar/mylar/search.py", line 2627, in searcherrcheck = rsscheck.torsend2client(ComicName, IssueNumber, comyear, link, nzbprov, nzbid) #nzbid = hash for usage with public torrentsFile "/app/mylar/mylar/rsscheck.py", line 1083, in torsend2clienttorrent_info = rp.main(filepath=filepath)File "/app/mylar/mylar/test.py", line 52, in maintorrent = self.client.find_torrent(torrent_hash)File "/app/mylar/mylar/torrent/clients/rtorrent.py", line 72, in find_torrentreturn self.conn.find_torrent(hash)File "/app/mylar/lib/rtorrent/__init__.py", line 323, in find_torrentreturn(rtorrent.common.find_torrent(info_hash, self.get_torrents()))File "/app/mylar/lib/rtorrent/__init__.py", line 78, in get_torrents*[method.rpc_call + "=" for method in retriever_methods])File "/app/mylar/lib/rtorrent/rpc/__init__.py", line 148, in add_handle_unavailable_rpc_method(method, self.rt_obj)File "/app/mylar/lib/rtorrent/rpc/__init__.py", line 53, in _handle_unavailable_rpc_methodraise MethodError(msg)MethodError: Method isn't available.

2018-08-11 17:02:10 | WARNING | Unable to retrieve information from 32Pages - either it is not responding/is down or something else is happening that is stopping me.`

In my reaserch to solve this I am sure that theres no captcha when I log out and in to 32p.
Conf looks like this:
[32P]
mode_32p = True
password_32p = REDACTED
verify_32p = True
enable_32p = True
search_32p = False
username_32p = REDACTED
deep_search_32p = False
passkey_32p = REDACTED
rssfeed_32p = None

**Comment by evilhero** [comment]
Mylar will not work with the newest rtorrent (0.9.7) since they changed the api for usage.

Theres a PR/patch to address it but in doing so it breaks functionality for those not on the newest version so it has to be implemented properly.

**Comment by JohanSF** [comment]
Interesting, and is that known issue related to the first warning "unable to retrieve information from 32Pages..."?

**Comment by evilhero** [comment]
It's not the Warning, but the traceback error that's important.

The warning is actually an expected result if it cannot find the issue due to whatever reason.

**Comment by JohanSF** [comment]
I see, I will be standby for that RP to be implemented then :) thank you

**Comment by evilhero** [comment]
Curious now, which series / issue are you searching for on 32p? And what series id are you using for 32p?

**Comment by JohanSF** [comment]
I have tested for many series and it's the same for all of them.

**Comment by evilhero** [comment]
Works fine here. At this point it would appear to be a problem with either the config or the series you're searching for. Again, please give an example of a series and issue with the 32pseries id that you're searching for.

Debug logs might be helpful as well as just posting the error itself isn't useful for troubleshooting - need to see the leadup to the traceback error.

**Comment by JohanSF** [comment]
![image](https://user-images.githubusercontent.com/6782603/43994262-8f81cc14-9d9a-11e8-8e82-477f951d55b6.png)
![image](https://user-images.githubusercontent.com/6782603/43994265-9d40596a-9d9a-11e8-85d0-1e186555175b.png)
https://pastebin.com/y2PLYEsx
Hope that helps.

**Comment by JohanSF** [comment]
do I need to enable a higher log level?
![image](https://user-images.githubusercontent.com/6782603/43994696-bfb54f30-9da1-11e8-9e22-50f1ff86d813.png)

**Comment by evilhero** [comment]
How are you pulling that log info out? Are you like grep-ing the log file or something?

Try starting Mylar with the -v option or just go to the Logs tab and click on the Enable Verbose Logging button. And then try a search again. Post the mylar.log file results (just the search related stuff), not the GUI log as that's a little less descriptive.

**Comment by JohanSF** [comment]
Im using unRaid and have mylar in a docker.
![image](https://user-images.githubusercontent.com/6782603/43994820-6acafafe-9da3-11e8-91e4-d51cfb77ae2d.png)
I already have debug on
![image](https://user-images.githubusercontent.com/6782603/43994823-8683799c-9da3-11e8-8a25-03c9de573aa7.png)
I dont know how to start the docker with -v in unraid though

**Comment by JohanSF** [comment]
Ah, I thought "debug on" would mean that I would see debug info in the log, but it was the button, and not the current status of that button.

Anyway, I am here now, will update when more appears in the log:
![image](https://user-images.githubusercontent.com/6782603/43994908-13818662-9da5-11e8-97bf-57c2cb8cdfef.png)

**Comment by evilhero** [comment]
Unfortunately that log shows a manual post-processing run (ie. Folder Monitor). Try performing a manual search for one of the Witcher issues (the magnifying glass in the options column on the series detail page for the specific issue). 

I just tested it against issue 1 (with packs enabled, search id set to exact numeric of 6116 as you have, volume label set to None), and it searched and found the pack fine with no errors via 32p.

Not quite sure if setting deep_search_32p = True would affect anything or not as normally that only works if 32p is returning more than one search result (then it iterates over each result to narrow things down so it can try and figure out the lone proper result).

But even more important than that, is knowing which branch/commit of Mylar you're currently running. I'm guessing Master since you're running via docker, but the commit is relevant as there were some fixees that went in about 2 weeks ago that addressed some 32p searching problems.

**Comment by JohanSF** [comment]
Alright, I cleared the log.
I used manual search again, as you describe.
my version is: Version: 34e7705f6251bab259fcd06ff073136fa611367c (master)
[mylar.log](https://github.com/evilhero/mylar/files/2280502/mylar.log)

**Comment by evilhero** [comment]
K, we're getting kinda somewhere - but that log only hit on your RSS feed running, which unfortunately doesn't use the 32P API (as that's an API request, not an RSS request). The request for the search got logged, but because the RSS was running it got temporarily delayed until it was finished before it submitted it for searching, and your log cuts out prior to that.

Can you try again (sorry)?  Maybe turn off your folder monitor prior to performing the manual search so that the logs are abit cleaner/shorter. You do have to restart Mylar after changing the folder monitor setting so that the scheduler properly removes it, or else it will still run in the background (it's a recent bug that was brought up, but proving troublesome to properly fix).

At least you're current on Master, so that means that the codebase should be correct.

**Comment by JohanSF** [comment]
Np, Im the one needing help here :D
So I turned off rss and restarted mylar.
![image](https://user-images.githubusercontent.com/6782603/43995658-5a74534e-9db2-11e8-93a7-263a7656569e.png)
this so far:
![image](https://user-images.githubusercontent.com/6782603/43995710-70601a84-9db3-11e8-8d72-21d0dcc60527.png)

**Comment by evilhero** [comment]
Still a log full of folder monitor unfortunately. 
Can you disable the Folder Monitor option temporarily, save the config, and restart Mylar again? Then enable verbose logging via the Logs tab, and perform a manual search for that issue again (hopefully that'll be the log we're needing with all that turned off/enabled)

**Comment by JohanSF** [comment]
Did I disable it wrong? it is what I pictured in my post above right?

**Comment by evilhero** [comment]
Close - that's the RSS Feeds that you disabled (which is fine for trying to narrow things down, but it's not the Folder Monitor in this case which is logging all the unneeded details).

The Folder Monitor option is located in the Conifguration / Quality & Post-Processing tab / Post-Processing section / Enable Folder-Monitoring option).

**Comment by JohanSF** [comment]
take a look at my post above

**Comment by evilhero** [comment]
```Complete issue count of 5 issues are available within this pack for The Witcher```
It's searching 32P just fine, and it retrieved the .torrent file as well. The problem is that it can't send to your rtorrent client due to it being at 0.9.7. 

The warning that's being thrown up is in regards to your notification feeds on 32P - basically you have none so it can't find any. I will have to rework that Warning/method as it's not the correct terminology that's being used to describe what's occuring.

In order to get around the rtorrent problem, you could use the watchdir option (rtorrent config / WatchDir / Local WatchDir since I'm assuming you're running rtorrent locally) which would save the .torrent file in that directory, your rtorrent client would check that directory every few minutes and then load it automatically into your client. 

The only problematic method with this is that it can't assign a category to the torrent (unless you're using that via rtorrent watch directories and have that already configured). But aside from that it would it would load it fine.  You could then re-enable your Folder Monitor and set it to the location where your rtorrent is saving your completed torrents, and set your Mylar post-processing action to copy so that you can continue to seed and Mylar will post-process said torrents as they're completed (along with metatagging the copy versions and not the original versions).

**Comment by JohanSF** [comment]
1. How do I create a notification feed on 32P, and should I?
2. Ah the black hole method, that is a solution yes. If I do that it will be a temp. solution until the issue with 0.9.7 is fixed, and so I can live with no categories in that time I reckon.

**Comment by evilhero** [comment]
1. Wouldn't worry about it atm - it's only useful if you're using Legacy mode in 32P as a way to get a bigger RSS feed (basically).
2. I think the 0.9.7 is still roughly a week or two off from hitting development. Some other things are hitting development first (tiered wanted list mainly), and once that hits master is probably when I'll start looking at the 0.9.7 problem as I generally don't like to make too sweeping of changes to either branch.

**Comment by JohanSF** [comment]
Alright, I guess we can close this issue, I have another one if you're up for it :D 
Here's an appetizer:
![image](https://user-images.githubusercontent.com/6782603/43996105-f0a4c598-9dbb-11e8-84ec-61205e2e07e0.png)
I can create a new github issue for this?

**Comment by JohanSF** [comment]
Alright, closing this issue.
For people that might drop by: The solution is to wait for an update that makes mylar compatible with rutorrent 0.9.7.

**Comment by evilhero** [comment]
FYI: changes to accomodate 0.9.7 are now live in development branch 24130a8. If you can please try them out so that I can get some feedback on the working status of the fix.

**Comment by JohanSF** [comment]
Sounds awesome, I am hyper excited :D. I am using the `linuxserver/mylar` docker container on unRaid and very unsure about how to switch to develop and if it will f up my current mylar setup. So I might have to wait until it reaches master.

**Comment by DarkSir23** [comment]
It looks like they're following the Development fork, as the newest release was 6 days ago.  You should just be able to pull linuxserver/mylar:latest (note, this doesn't include the most recent update that evil's talking about, but it should show up within a day or two)

**Comment by JohanSF** [comment]
I just forced update of my container.
This is in the bottom of the webui:
Version: 3e12599502bc99343da8564762bd46277f5cdd8c (master)

**Comment by JohanSF** [comment]
Just updated the docker container again now and this is my version now:
Version: 3e12599502bc99343da8564762bd46277f5cdd8c (master)
