### ISSUE TITLE
Issues that are not "valid" to import

### ISSUE THREAD

**Issue by JohanSF** [evilhero/mylar#2055]
I downloaded the file manually and put it in the folder that it should otherwise end up in.

![image](https://user-images.githubusercontent.com/6782603/43999991-c4ea8896-9e17-11e8-9ee7-cf4bb484df2d.png)

*never mind the filename, I tried without the underscore and the original " - ".

But it seems that it is not "valid" whatever that means in this context

![image](https://user-images.githubusercontent.com/6782603/43996105-f0a4c598-9dbb-11e8-84ec-61205e2e07e0.png)

Here are the details for the issue in mylar:

![image](https://user-images.githubusercontent.com/6782603/43999995-f64f4aa2-9e17-11e8-9863-e636100b6f14.png)

**Comment by evilhero** [comment]
It's because the filename does not have an issue # in it, and according to CV there is one. 

You can try to add in the ```01``` (or whichever format padding you prefer, ```1``` ```001```) after the series title, which should allow it to be picked up - but it's failing due to the fact there's no issue number present. 

Like sir @barbequesauce mentioned, Trade Paperbacks, Graphic Novels, and Compendiums aren't really supported in Mylar. Mainly due to the lack of an issue #, but some can be added/scanned for if there's an issue number in the filename. However, searching probably won't work as items are posted with no issue numbers usually for those types, and a major constraint of the matching process for mylar is to match on issue numbers.

**Comment by JohanSF** [comment]
Thank you that fixed it :) It makes sense - but gives me hard time whether I should group them in one Cyanide & Happiness dir og keep them separate.
