### ISSUE TITLE
Unable to add any Batman comics newer than 2015

### ISSUE THREAD

**Issue by apastuszak** [evilhero/mylar#2059]
I am trying to add the 2016 DC Universe Rebirth run of Batman, which started in 2016.  When I enter Batman, BatMan, Bat Man, or Bat-Man in the search box, I shows nothing newer than than 2015.

**Comment by evilhero** [comment]
Can't confirm at this moment what the problem  is - but you can directly add a series via the search box at the top of any page and entering the full comicvine comicid (in the format of 4050-XXXXXX)

**Comment by apastuszak** [comment]
That worked!  Thank you!

**Comment by evilhero** [comment]
Just for future reference (and to remind myself), Mylar will limit the results returned to the first 1000. In this case, there are almost 1500 results, so it just takes the first 1000. Unfortunately it's not sorted in any particular order, and the series that was needed was sitting around mark 1300. 

I've redid the search so that it sorts by the most recent date that the series was updated on CV (because you can't sort by start year, which is stupid tbh). This will be available in the next development commit.

I'll also add in an option in the GUI to allow users to expand the results to view past the first 1000 entries in particular cases like this (or maybe even allow for an expanded search query in the search box as in something like 'Batman V2016' which would limit the search results to just series that started in 2016 named that).

**Comment by apastuszak** [comment]
Thank you!

**Comment by evilhero** [comment]
This should be fixed now in the latest development build f7c1629 (not the GUI portion, but the sorting so that the most recent will appear in the first 1000)
