### ISSUE TITLE
Issue Number Padding problem

### ISSUE THREAD

**Issue by JohanSF** [evilhero/mylar#2071]
What I want:
![image](https://user-images.githubusercontent.com/6782603/45264047-3aa62200-b436-11e8-8f50-0c6a3325be65.png)
What Issue Number Padding does:
![image](https://user-images.githubusercontent.com/6782603/45264053-55789680-b436-11e8-9a64-069a3007c102.png)
Settings:
![image](https://user-images.githubusercontent.com/6782603/45264071-b607d380-b436-11e8-97a0-d94f6d798b4e.png)

**Comment by evilhero** [comment]
The padding is to allow for OS sorting, not just visually. Being able to sort 3 digit issue numbers has to be also taken into account  (what happens when a series hits 3 digit issue numbering? ie. 100), since then it would go 01, 10, 100, 11...  instead of 01, 010, 011, 100...

This was discussed in #1843 with far better descriptions, and with more coffee.

**Comment by JohanSF** [comment]
I am not sure that is addressing my issue here. It's good that I get a zero in front of 1 digit numbers, but there should not be one in front of 2 digit numbers. Right?

**Comment by baz1860** [comment]
Where x is the issue number, your setting adds 0 in front. 1 becomes 01, 10 becomes 010. 

What you’re looking for is the ability to add 0 to *only* single digit issue numbers?

**Comment by evilhero** [comment]
Padding (none,0x,00x,000x) is shown how to 0 pad issues 1-9 where the x represents the single digit. This is to account for issues that higher than 2 digits (it should actually be 0000x for 4 digits since issue numbers can be greater than 1000 nowadays) 

Again, if you don't 0 pad the 2 digit numbers when you get to a 3 digit issue the sorting is out of whack as 100 comes before 11 (try adding in issue 100 into your file list and you'll see exactly what I mean).

This was determined long ago to be the most consistent with user requests for number padding while trying to adhere to some sort of standardized number formatting.

**Comment by JohanSF** [comment]
Exactly baz1860.

**Comment by JohanSF** [comment]
I understand about the majority use-case, and I would definitely think the majority would want, and expect it to do 01, 02, ..., 10, 11, ... when "0x" is picked but who knows, maybe the way it works now is somehow useful to someone. Thank you for all the hard work on this project btw.

The coolest feature would be if it first detected the number of issues and then applied the correct 0-padding, so that all issues in that comic have the same number of digits.
