### ISSUE TITLE
Archive? Snatched? Why?

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2074]
Hi

I frequently find that comics show as "archived" and "snatched", with no action on my part. What causes this? What is archiving, anyway?

Thanks!

**Comment by evilhero** [comment]
Snatched is when Mylar will snatch the comic from a provider and send it the respective download client. The fact that it remains in a Snatched status would inidicate that either the download failed to complete, and/or the given item has not been post-processed as of yet.

Archived is the status that Mylar gives to issues that are no longer located in the location that it thinks it should be. Usually it's used to indicate that the given issue has been deleted, but you don't want Mylar to re-download it again, so the status of Archived is given to show that it was there but has since been deleted/moved.

If the status is Archived after a post-processing run, then odds are the file was renamed to an invalid format, and/or it can't be located in the location it was originally scanned in.
