### ISSUE TITLE
Weekly Pull List & ComicVine Issue?

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#2079]
Started seeing this today:

```
14-Sep-2018 23:00:56 - INFO    :: mylar.pullit.70 : CP Server Thread-5 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
14-Sep-2018 23:00:56 - INFO    :: mylar.pullit.74 : CP Server Thread-5 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 36, 2018
```

Oddly there's no error regarding ComicVine so I'm not sure why it's going to the 'alternate site' but the data is ugly and it doesn't seem to know what comics are wanted and which aren't.

**Comment by evilhero** [comment]
The 'alternate site' is used as a fallback when Mylar fails to retrieve data from the main data site for the pullist (it's not CV).

In this case, the main site was offline and so it tries to load data from the alternate site in order to be able to display something relevant other than a blank page. The alternate site relies on page parsing, and works but it's not pretty at all (this is basically what you get when you set alt_pull=0 in the config.ini)

The main site is back up now, so everything should be working again (do a Recreate Pullist to get your pullist back to 'normal' of it hasn't updated itself yet).

**Comment by verbumfeit** [comment]
I'm having the same problem right now. Subsequently, issues in my pull-list aren't being downloaded/don't appear as new entries in the issue list of a comic.

Maybe you could add a status indicator to the settings/information page which shows if the regular site is online and working?
