### ISSUE TITLE
32p IP issue

### ISSUE THREAD

**Issue by Aquenon** [evilhero/mylar#2081]
Hi,
Recently, my IP was banned from 32p.  Not my account, just my IP.  It was an automated process and I got things straightened out, but apparently it was Mylar that caused the process to trigger.  Before I turn Mylar back on, is there anything I need to change other than the amount of time between scans?  I run in Auth mode.

Thanks

**Comment by evilhero** [comment]
What might have happened is that the site Mylar polls against in order to determine series availability on 32p was offline yesterday for abit (not sure when exactly - Friday night, until early Saturday). It polls constantly against that and if it wasn't available it might have tried to query 32p itself for the info and hit some throttle on their side (the other site throttles against requests every odd second).

Normally searching against 32p doesn't have any problems/issues for 32p - most users that end up temporarily disabled is either due to VPN usage, and/or their password changed and Mylar wasn't updated/aware to reflect the changes.

Did they happen to say what the type of query was that got you temp banned?

**Comment by Tucker28** [comment]
Unfortunately no. The first admin unbanned my IP and asked if I used Mylar. I disabled scanning then and asked about it, but the next admin said my Mylar configuration was my responsibility and closed the ticket.

Now, this all happened last week, and since I’m not on the actual website often, I have no idea how long I was banned. Plus, I usually am somewhere else when I check the site so therefore my home IP might have been banned for some time.  I’m currently in my last 2 weeks of college, so I have not been reading or keeping up with comics... just letting Mylar do it’s thing and I’ll catch up on my reading after graduation.  So, I could have been banned for a while before I noticed it.

I figured I would dial back on how often it scans, which is all I can think of to change.

**Comment by evilhero** [comment]
If you're checking the site from a different ip than from what mylar uses, it would count as a double login and probably got flagged due to that. 

As far as I'm aware you're allowed to sign in from only one ip to the website simultaneously (not sure if it recognizes your signon ip vs not). If you signed in from another ip while Mylar was running and it recently/was polling 32p (since it uses auth mode, that basically means mylar is signing onto the 32p website from that ip using your credentials), it would appear as if you're signing in from 2 different ip's at the same time, which is an immediate flag for them. Seeding is different, but logins they monitor heavily. 

I would either stop signing into the 32p site from a different ip when Mylar is running, and/or drop down to legacy mode if it's required that you sign in from the other ip as well. Legacy mode doesn't authenticate so you wouldn't get banned using it (think Rss feeds only), but then you're also limiting the usage of 32p to just RSS and back issue retrieval might be problematic with 32p depending on how long you've been running Mylar for.

**Comment by Tucker28** [comment]
Hmmm.  Good point.  I so very rarely log into the site that I wasn’t thinking of that.  I just normally think about the site when I’m away from home. It’s not an issue to wait, so I’ll make sure I only log into it when I’m home. Thanks!
