### ISSUE TITLE
Post-Processing failing to complete

### ISSUE THREAD

**Issue by prosolis** [evilhero/mylar#2084]
Mylar was working great for a day or so then it stopped processing downloaded files. I have tried restarting it but that failed to resolve the issue. I've turned on debug messaging and I'm including the output here:

[mylar.log](https://github.com/evilhero/mylar/files/2399098/mylar.log)

**Comment by evilhero** [comment]
Which branch /commit are you running of mylar?

You're processing 600+ issues, are you using the copy or move option for post-processing?

It's getting stuck on Sonic it looks like - do you have more than one series on your watchlist that are in the same year for that series?

As far as we are aware, as of today, post-processing works fine on the latest development build based on other users'  feedback (there were some issues that were addressed recently in the dev build).

However, this might be one of those edge cases where because of the number of issues in the folder you're post-processing it's hard to duplicate on our end properly.

**Comment by prosolis** [comment]
I'm under the dev branch using the move option. At first, restarting Mylar would get it going again. It was originally stuck on Spider-Man 588, I deleted it which got it going again. Perhaps, I'll move all but maybe 50 or so from that folder and slowly move them back.

**Comment by evilhero** [comment]
Are you up to date on the development branch? There was a fix that went in a few weeks ago that involved post-processing problems for series that had more than one valid match (ie. more than one volume of a particular series in your watchlist).

Other than that, I only briefly browsed the log since my phone choked on it, but I'll try and view it later and see if I can see something amiss.

**Comment by evilhero** [comment]
Ok I think I can see what's happening in that last log. Mylar is matching an issue to at least 2 or more series mistakingly. 

In doing so, it post-processes the first fine, but then it goes to post-process the same file against the other series match and can't find the file in the given location (to perform a filesize dupe check) and stops looking.

So two real problems:
- it should be performing a definitive match if more than one series on your watchlist is considered a match (it does a very basic match, and it picked up the alternate series naming of the filename which is causing problems and it shouldn't)
- it shouldn't be completely stopping on a failed dupe check lookup regardless of the reason why.

I'll have to look into this some more and do some testing / breaking. 

You might want to check your batman 2016 series as it looks like it incorrectly pp'd at least the #2 issue when it should have been against the tmnt/batman crossover series. 

Also, make sure your config.ini git_branch variable is set to development. It looks like you're ok and the checkout is being recognized, but just to be on the safe side thought I'd mention it (it defaults to master on a new install).

**Comment by prosolis** [comment]
I really appreciate the quick responses. 

I will double check the Batman 2016 series. Pasting another log just in case it helps to further the troubleshooting efforts. 

[mylar.log](https://github.com/evilhero/mylar/files/2399352/mylar.log)

**Comment by prosolis** [comment]
You were correct about Batman 2016. I'll just move the incorrectly matched issues for now.

**Comment by evilhero** [comment]
Haven't forgotten about this, just free time was shot this past week and when I was able to look at things briefly I couldn't reproduce any problem... Still looking at it, however ;)

**Comment by prosolis** [comment]
I understand. Let me know if you need any additional logs.
