### ISSUE TITLE
Use Name column as $Name

### ISSUE THREAD

**Issue by polybius01** [evilhero/mylar#2114]
Not really an issue but I would like to be able to use a $Name variable when renaming comics based on the Name column. I know not all titles have a name there (Archie Meets Batman '66 just has 'none') so it would probably want to be "use $Name unless it equals 'none'".

Also, having the Recheck Files function be a little less strict when adding would be nice. It seems it only recognizes the files when the name is the exact name that the Rename Files function would have given the files. Kinda defeats the purpose of Rename Files I think :)

Thanks for all your hard work!

**Comment by evilhero** [comment]
The $Name functionality has been requested previously - the problem with adding it in is that the file parser won't be able to parse the filenames properly. Wouldn't be a problem if everyone could agree on some kind of naming convention standard but when you have stuff like ```this comic 001 - I ran to the store 0.5 (2018)``` or ```this comic - i ran to the store 001 - 0.5 (2018)``` or even ```001 this comic - 0.5 I ran to the store (2018)``` it makes it almost impossible to be able to properly decipher what is what for the parser. And adding in that functionality, while it will work for the issue naming (I've gotten it to work in previous attempts), generally breaks usage in other aspects for other naming conventions that don't contain the issue name. So ATM, probably not going to happen as it will break the parser.

The ReCheck Files will only scan in what it knows to look for. If you start randomly renaming stuff to something not what CV/Mylar assume, there's no way Mylar can keep track of items that aren't properly named. And by properly, I mean having a series title, and an issue number at the very minimum.  

If you use the Alternate Search Name option for a given series, Mylar will use that in addition to the normal 'assigned' series name when scanning in order to maximize the scan results.  

However, I'm not sure what you're doing that you're renaming files to something different than what the Rename function would do automatically (ie. you're manually renaming?)  But yeah, if you happen to name it something like ```01.cbr```, it's not going to work - and it never will (I'm vehemently against naming stuff like that cause personally I think it's not a great method, and lacks any real indication of what the filename actually is).

**Comment by polybius01** [comment]
Ok no problem!
