### ISSUE TITLE
Feature request, $Name in file_format

### ISSUE THREAD

**Issue by MattMulhern** [evilhero/mylar#2118]
It would be nice if we could insert the comic name when renaming files.

From a brief look at the code this is what we can currently use as tags:
https://github.com/evilhero/mylar/blob/3e12599502bc99343da8564762bd46277f5cdd8c/mylar/helpers.py#L638-L649

I think we already have the comicid at this point which should be able to point us a the name of the comic.

**Comment by evilhero** [comment]
This was brought up just last week in #2114.

The brief gist of why it's not going to happen anytime soon - it has very little to do with adding in the value and performing the actual rename (that's the easy part). 

It has almost everything to do with the file parser being able to properly detect the issue name as opposed to the series title or variations thereof. There isn't any point renaming a file to include the issue name, if the parser can't scan it properly and its doubtful (past attempts while successful, broke other aspects of the parser) if it ever will because of lack of naming conventions.
