### ISSUE TITLE
SeriesYear in renamed file issue

### ISSUE THREAD

**Issue by UNiXMIT** [evilhero/mylar#2122]
I have just noticed something that seems a bit off to me.

I'll explain with the example of the series Batman (2016)

The directory is created for that series correctly with the SeriesYear of 2016
Batman issues 1 to 9 have the SeriesYear correct for example - Batman 002 (2016).cbz
Then the year changes for issues 10 to 33 - Batman 010 (2017).cbz
The issue 34 to 54 it changes again - Batman 054 (2018).cbr

Maybe I'm wrong but I would expect that to stay as 2016. Shouldn't that be the case?

Thanks

**Comment by evilhero** [comment]
It should be called IssueYear in that popup legend actually - but yeah that's right what it's doing (the $Year option is right). 

When you're talking about Folders, the $Year tag indicates the actual series year for the given series which will be static. 

When it's files, the $Year tag is actually the Issue Year - as is what's happening to your files correctly and is incrementing the year as required by the issue.

If you want to have the series year in the actual filename (and in order to avoid general confusion with naming and having 2 years in the filename with no distinction as to which is what) you can use either the ```$VolumeY``` or ```$VolumeN``` tags which would translate into ```V2016``` or ```v3``` accordingly. 

If you do put 2 years in the filename as ```sometitle 001 (2016) (2018)``` Mylar won't be able to distinguish which is the series year and which is the actual issue year, so it will fail in parsing the title.

**Comment by UNiXMIT** [comment]
Ok thanks so much. That makes sense.
