### ISSUE TITLE
Import / Post-processing not working on finished rtorrent downloads

### ISSUE THREAD

**Issue by JohanSF** [evilhero/mylar#2127]
**Mappings for my mylar docker container:**
![image](https://user-images.githubusercontent.com/6782603/49325624-fd899180-f545-11e8-8682-f89b35374bae.png)

**I am testing with Star Wars (2015) Volume 3:**
![image](https://user-images.githubusercontent.com/6782603/49325588-848a3a00-f545-11e8-801d-77f07bbe4b96.png)

**Mylar snatches the torrent via 32p:**
![image](https://user-images.githubusercontent.com/6782603/49325591-94098300-f545-11e8-9b9e-613051451f69.png)
![image](https://user-images.githubusercontent.com/6782603/49325596-9c61be00-f545-11e8-93a4-ae61c671867b.png)
**with these settings:**
![image](https://user-images.githubusercontent.com/6782603/49325606-bb605000-f545-11e8-8529-5d27fa397898.png)

**But it is never imported or post-processed as per my settings:**
![image](https://user-images.githubusercontent.com/6782603/49325602-ae436100-f545-11e8-921b-3f40d8db2ad0.png)

**If I do manual post-processing on '/media/downloads/completed' I get an error (it fails for some issue):**
![image](https://user-images.githubusercontent.com/6782603/49325628-18f49c80-f546-11e8-85ba-5123c12b1934.png)

**But if I put the files in their own folder first and post-process '/media/downloads/completed/test' it works fine and the files are renamed and meta-tagged as I want:**
![image](https://user-images.githubusercontent.com/6782603/49325639-59ecb100-f546-11e8-8cf5-a4fac3614797.png)

**Is the post-processing on downloaded issues equivalent to performing manual post-processing on '/media/downloads/completed' and is that why it doesn't work?**

**Comment by JohanSF** [comment]
> **If I do manual post-processing on '/media/downloads/completed' I get an error (it fails for some issue):**
> ![image](https://user-images.githubusercontent.com/6782603/49325628-18f49c80-f546-11e8-85ba-5123c12b1934.png)

I fixed this part, which seems to be a whole other issue, by removing the downloaded files that caused Mylar to throw an "Uncaught Exception".

This means that post-processing now works if started manually, but it takes a very long time as it scans the '/media/downloads/completed' folder which contains a lot of comic-files.

It still seems that post-processing is never started upon finishing downloading files.

**Comment by JohanSF** [comment]
Update: Very very strange.. I tried added Darth Vader (2017) Volume 2 via Mylar and it downloaded and imported on its own. I have no idea why it suddenly worked - I will do another test soon.

**Comment by evilhero** [comment]
Are you trying to have Mylar post-process your torrent downloads upon completion? Cause if so, Mylar can't do that. Once it sends it to your torrent client, it doesn't track the progress or anything else.

Now if you're trying to post-process based on Folder Monitor and you have uncaught exceptions occurring therein, then that's probably the file parser getting stuck on some filenaming that it doesn't understand properly, because you know, no naming standards exist for comics so it tries to generalise some items. It also has to scan the entire directory in order to see if there are any new files for it to pp - it does keep a record of the items that were pp'd before manually that were torrents so as to not double post-process items.

Not quite sure what you're saying in your last comment - you added a series and it downloaded and post-processed everything fine? When you add a series, it checks to see if any new issues are out on the current pullist and tries to download them. If it did everything on it's own, odds are it added the series, snatched the item, then the folder monitor ran almost exactly when the file was finished and it post-processed.

**Comment by JohanSF** [comment]
Thank you for explaining. I think the same, it makes sense since I removed the items that made the folder monitor fail.

**Comment by JohanSF** [comment]
One comment though, it would be a nice feature for Mylar to import downloaded files upon finished downloading. Especially with my use case because I seed a lot of comics that I don't want to add to Mylar. So the folder monitor has to go through all of those every time it runs.
