### ISSUE TITLE
add ettv.tv as an alternative to wwt

### ISSUE THREAD

**Issue by CuddleBear92** [evilhero/mylar#2131]
could we please have an update to add ettv.tv support on top of WWT. its the official Nem43 backup he said. 
https://www.reddit.com/r/torrents/comments/94zu5s/worldwide_torrents/e4mdleu

`https://www.ettv.tv/torrents.php?cat=55`
`https://www.ettv.tv/user/Nemesis43`

Esp now that it has been down since atleast 20:05_30.11.2018 (which is the last time the RSS feed of my Torrent client updated. 
There is talk that this downtime is the domain change to the .to domain.
While it prob will get back up again. Good to have backup and more sources when one is down or if one is missing content.

**Comment by evilhero** [comment]
Don't see it happening anytime soon at this point. It requires a custom parser for any backlog support, and I'm abit too busy atm with other things to spend time doing that. PR's are welcome (just base it off the worldwidetorrents one). 

Adding the RSS feed is probably easy enough, especially since demonoid is dead and has to be removed. But alot of times the feeds have different naming conventions and it has to be all accounted for / tested against.

**Comment by evilhero** [comment]
WWT domain has been updated now in f63e746. If the domain changes again, a reference point for the time being is the WWTURL variable in __init__.py which can be changed to the new domain. It will then be used throughout the program thereafter (I'll add it into the config.ini at some point, this was just a quick patch)

**Comment by CuddleBear92** [comment]
Closing issue cause you stated you pushed the changes to the dev build.
