### ISSUE TITLE
Snatch torrent based on file size and/or number of seeders

### ISSUE THREAD

**Issue by bonebox** [evilhero/mylar#2132]
I noticed with 32P torrent snatching (and I'm assuming torrent snatching in general) that when there are multiple potential matches, Mylar doesn't seem to give preference to the one with more seeders or the larger file size. As a matter of fact (perhaps coincidentally), more often than not it chooses the version that is smaller / has less seeders.  It would be great to have either of those as options.

**Comment by evilhero** [comment]
You're right - there is no preference given to more seeders / larger file size (outside of the initial constraints  if you enable them in the GUI).

As long as the initial constraint(s) are met (if there are more than 1 seeder, and the filesize is greater than  30mb as an example), then it takes the first successful match.

Unfortunately adding in those types of options (in addition to blacklisted words, etc) requires an almost complete overhaul of the search workflow due to how it currently works. 

Not that that's a bad thing - I need to rip a good portion of it out in order to get TPB/GN's searches working properly, which would remove all the internal search-matching logic in favour of using the filechecker parser for more consistency, and then in addition to re-adding back in the ```Choose your download``` option. So in doing those (in theory at least), I should be able to add the search constraint options in.  It's just not an easy thing to be tasked with when literally everything hinges on that one particular module and it has to be done in certain order of logistics ;)

So yeah, it's coming - just can't see all of that happening before the New Year, let alone January (it could happen, it's cold and I'll stay inside more - you never know)...

**Comment by bonebox** [comment]
I understand the complexity. I just wanted to see if it was even something on your radar.  Sounds like it is; great!
