### ISSUE TITLE
Auto Download Stopped Working

### ISSUE THREAD

**Issue by vader083** [evilhero/mylar#2143]
Issue:
Weekly Pull List has the issues marked as wanted, but they never get marked to wanted in each series.  I don't see any issues in "This weeks upcoming" or "upcoming no data".  I have to manually refresh each series to pick up the issues.

This started two weeks ago, after an update the weekly pull list stopped working, another bug for the stack trace told me to redo the pull list and change "alt_pull" to 2 instead of 0.  That fixed that issue but now have the above issue.

**Comment by vader083** [comment]
Oh and when I do "Manually check for issues" I see

"Issues are marked as Wanted, but no issue information is available yet so I cannot search for anything. Try Recreating the pullist if you think this is error."

**Comment by barbequesauce** [comment]
What branch and commit are you running, and on what platform? Can you provide a debug log please?

**Comment by vader083** [comment]
running docker and I'm on the latest tag from https://hub.docker.com/r/linuxserver/mylar/ on UnRaid .

**Comment by evilhero** [comment]
Make sure your CV apikey is valid and not temporarily banned or something. If the weekly pull is working fine, then it's a problem with your mylar client communicating with CV.

**Comment by vader083** [comment]
When I refresh a series it hits CV and gets the updated comic info so I'm assuming I'm not banned.

Logs for a recreate pulllist

2018-12-12 21:20:35 | INFO | No series have been marked as being on auto-watch.
-- | -- | --
2018-12-12 21:20:35 | DEBUG | cflist: []
2018-12-12 21:20:35 | DEBUG | [WALKSOFTLY] You are watching for: 50 comics
2018-12-12 21:20:34 | INFO | [PULL-LIST] Weekly Pull List successfully loaded with 130 issues.
2018-12-12 21:20:34 | INFO | [PULL-LIST] Successfully populated pull-list into Mylar for the week of: 49
2018-12-12 21:20:32 | INFO | [WEEKLY-PULL] There are 130 issues for the week of 49, 2018
2018-12-12 21:20:31 | INFO | [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 49, 2018
2018-12-12 21:20:31 | INFO | [PULL-LIST] Populating & Loading pull-list data directly from alternate website
2018-12-12 21:20:31 | INFO | Deleted existing pull-list data for week 49, 2018. Now Recreating the Pull-list...

**Comment by evilhero** [comment]
Can you post a debug log showing the same workflow? INFO level logging isn't much help when it comes to troubleshooting.

Theres nothing wrong with the site mylar polls against, so it's not that (which it sometimes can be).

Did your alt_pull revert back to 0?

**Comment by evilhero** [comment]
Weird, very weird. There's absolutely nothing wrong with the pull-list, aside from the fact that I get 131 issues for the given week instead of the 130 you posted, which might not mean anything as the backend updates every 4 hrs, so depending on the time the numbers might be slightly different.

Have to ask - have you tried to restart Mylar to see if it clears things up ?

You could also try using the arrows at the top of the weekly page to go back to the previous week, do a ```Recreate Pullist``` on that particular page, and let it finish. Then go to the current week, and perform a ```Recreate Pullist``` and see if that kicks things free.

**Comment by vader083** [comment]
I have restarted and also done the Recreate Pullist on a couple of prior weeks and current with no avail.

I guess I keep an eye on it for a couple weeks.  I can manually refresh each wanted series and it picks up the wanted comic as a workaround.

Worst case maybe I'll rebuild the db.

**Comment by vidjya** [comment]
I'm having this issue as well. "Recreate Pullist" worked for me. It worked last week without issue.

**Comment by barbequesauce** [comment]
There were a lot of updates in the last two or three weeks - are you up to date?

**Comment by vidjya** [comment]
As far as I know, yes, on the development branch. 40b466c according to Mylar. Turns out it didn't get all the issues, I had to manually refresh a couple of them. "This Weeks Upcoming" populated fine, but nothing went into "Wanted" until I recreated the pullist and refreshed those last two manually.

**Comment by barbequesauce** [comment]
Can you please shut Mylar down, make sure alt_pull is set to 2 in the config.ini, and then start it up in verbose (debug) mode?

`python /path/to/mylar/Mylar.py -v`

Then try to recreate the pullist. Once it finishes, do a force check from the wanted page. If it fails again, post the full debug log in a new issue please...

**Comment by evilhero** [comment]
What were the 2 series that you had to update manually ? Once you recreate the pull, if there's relevant data it should try to do an automatic refresh - if it's not, then it's possible that the pullist is pointing to an incorrect volume or some other data-related problem and it wouldn't signal for a local refresh of the series.

**Comment by vidjya** [comment]
Will, do, barbequesauce. I don't have anything to pull at the moment, since I forced it all, but I can try to create something in the next few days.

evilhero: Spider-Gwen (114734) and Amazing Spider-Man (112161).

**Comment by evilhero** [comment]
@vidjya , at the time you were trying to pull down the issues - CV had no issue information available for those (actually most of Marvel's stuff wasn't updated on CV for some reason).

The Wanted table only gets populated when issue data is available on CV for it to use (cause it needs it for downloading, post-processing, metatagging, etc) - so because CV had no info, Mylar also didn't have the info but it knew it was supposed to be there (thus the Wanted status on the pull-list). When you refresh a series, and Mylar has an item on the pull but no info (and there's a small bit of info on CV, like a   cover, etc), Mylar will fake the date so that it can be posted against - that's why it came up as ```0000-00-00```` which basically means there's no issue information on CV. 

The trick, since the date of ```0000-00-00```` might stop matches from occuring when searching (due to the invalid date), is to edit the date on the series detail page into what it should be (ie. ```2019-02-13```) - which can be done by just clicking on the ```0000-00-00``` on the series detail page, entering in the information and hitting enter to accept the changes.

**Comment by vidjya** [comment]
Opened a new bug #2209 with the issue of the Wanted section not being populated.
