### ISSUE TITLE
search 32p doesnt work?

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#2148]
I'm having trouble with mylar snatching a few series that are available on 32p

for example avatar the last airbender imbalance

![image](https://user-images.githubusercontent.com/15702664/50420255-aff70080-0835-11e9-8a9c-171d3a7e1be6.png)

initiating a manual search for the first issue leads to this log:

2018-12-25 11:07:06 | INFO | Update complete
-- | -- | --
2018-12-25 11:07:06 | DEBUG | ReScheduled job: DB Updater to 2018-12-25 10:12:06
2018-12-25 11:07:06 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2018-12-25 11:05:45 | INFO | Initiating manual search for Nickelodeon Avatar: The Last Airbender - Imbalance issue: 1
2018-12-25 11:05:45 | DEBUG | mode:want
2018-12-25 11:05:45 | DEBUG | ComicID:116035

so it's doing nothing?

**Comment by evilhero** [comment]
Odds are the WS site doesn't have the info in it for that series because it's a one-shot and it hasn't been updated since the week before last. The update process on WS is a manual process that that has to be done weekly so if it's a #1 /one-shot type the only way it will appear in searches is if the update process happens.

I'll do it in a few hrs, once the kids all settle down and start doing their own thing. I'll update this when it's completed.

**Comment by evilhero** [comment]
There is currently a search bug that's occurring and locking the search queue from being iterated over. The only fix (at this time) is to restart Mylar which will free up the queue and you can start searching again. Try to restart Mylar and then do the manual search again - odds are you'll be able to snatch it at that point.
