### ISSUE TITLE
unable to metatag

### ISSUE THREAD

**Issue by mediumwalter** [evilhero/mylar#2158]
Windows 10 Version: 34e540c75f06b773e5c8f0c0605345e3911f48c7 (master)

03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.26 : CP Server Thread-9 : [META-TAGGER] dirName:F:\Comics\Coda (2018)
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.31 : CP Server Thread-9 : ComicTagger Path location for internal comictagger.py set to : C:\Users\corey_000\mylar\comictagger.py
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.35 : CP Server Thread-9 : [META-TAGGER] Filename is : F:\Comics\Coda (2018)\Coda 7 (2018).cbr
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.50 : CP Server Thread-9 : Filepath: F:\Comics\Coda (2018)\Coda 7 (2018).cbr
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.51 : CP Server Thread-9 : Filename: Coda 7 (2018).cbr
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.53 : CP Server Thread-9 : New_Folder: C:\Users\corey_000\mylar\cache\mylar_gglmtu
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.55 : CP Server Thread-9 : New_Filepath: C:\Users\corey_000\mylar\cache\mylar_gglmtu\Coda 7 (2018).cbr
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.73 : CP Server Thread-9 : [META-TAGGER] Paths / Locations:
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.74 : CP Server Thread-9 : [META-TAGGER] scriptname : Mylar.py
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.75 : CP Server Thread-9 : [META-TAGGER] downloadpath : F:\Comics\Coda (2018)
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.76 : CP Server Thread-9 : [META-TAGGER] sabnzbdscriptpath : C:\Users\corey_000\mylar
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.77 : CP Server Thread-9 : [META-TAGGER] comicpath : C:\Users\corey_000\mylar\cache\mylar_gglmtu
03-Jan-2019 19:33:43 - DEBUG   :: mylar.run.78 : CP Server Thread-9 : [META-TAGGER] Running the ComicTagger Add-on for Mylar
03-Jan-2019 19:33:44 - WARNING :: mylar.run.107 : CP Server Thread-9 : [META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.
03-Jan-2019 19:33:44 - DEBUG   :: mylar.manual_metatag.5315 : CP Server Thread-9 : [MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.

**Comment by evilhero** [comment]
The key line in the log above is ```[META-TAGGER][WARNING] Make sure that you are using the comictagger included with Mylar.```

Did you replace the comictagger.py file included with Mylar with a different version? Or replace the comictaggerlib folder within the lib folder ? Altering/changing any of those items will cause issues when it goes to verify that the tagger is the correct one (it's a fork of CT due to some changes made, not the actual CT).

**Comment by mediumwalter** [comment]
I haven't touched it and I even deleted mylar and re-cloned it a few times. It was working fine for months. Very odd.

**Comment by evilhero** [comment]
The CT forked base got updated...umm..several months ago (not sure off the top of my head - summer last year maybe) and switched for users running Windows from using the bundled unrar.dll to using the unrar module.

Make sure you delete all .pyc references in the main root folder as well as the lib/comictaggerlib folder.

If you can run python from the command line, from the Mylar root directory just doing a simple ```python comictagger.py --version``` should give you more information about any errors (otherwise, it should paste in the version being used which should be a ninja-type version which is specific for Mylar usage).

**Comment by mediumwalter** [comment]
Traceback (most recent call last):
  File "comictagger.py", line 2, in <module>
    from lib.comictaggerlib.main import ctmain
  File "C:\Users\corey_000\mylar\lib\comictaggerlib\main.py", line 31, in <module>
    import cli
  File "C:\Users\corey_000\mylar\lib\comictaggerlib\cli.py", line 33, in <module>
    from options import Options
  File "C:\Users\corey_000\mylar\lib\comictaggerlib\options.py", line 29, in <module>
    from comicarchive import MetaDataStyle
  File "C:\Users\corey_000\mylar\lib\comictaggerlib\comicarchive.py", line 1, in <module>
    from comicapi.comicarchive import *
  File "C:\Users\corey_000\mylar\lib\comictaggerlib\comicapi\comicarchive.py", line 29, in <module>
    from rarfile import rarfile
ImportError: cannot import name rarfile

This is what I am getting.

**Comment by kosteva** [comment]
FWIW, getting the same symptoms and error message when running latest master (`34e540c75f06b773e5c8f0c0605345e3911f48c7`) on linux with python 2.7.12

```$ python --version
Python 2.7.12
$ python ./apps/mylar/comictagger.py --version 
Traceback (most recent call last):
  File "./apps/mylar/comictagger.py", line 2, in <module>
    from lib.comictaggerlib.main import ctmain
  File "/home/hd6/shjt/apps/mylar/lib/comictaggerlib/main.py", line 31, in <module>
    import cli
  File "/home/hd6/shjt/apps/mylar/lib/comictaggerlib/cli.py", line 33, in <module>
    from options import Options
  File "/home/hd6/shjt/apps/mylar/lib/comictaggerlib/options.py", line 29, in <module>
    from comicarchive import MetaDataStyle
  File "/home/hd6/shjt/apps/mylar/lib/comictaggerlib/comicarchive.py", line 1, in <module>
    from comicapi.comicarchive import *
  File "/home/hd6/shjt/apps/mylar/lib/comictaggerlib/comicapi/comicarchive.py", line 29, in <module>
    from rarfile import rarfile
ImportError: cannot import name rarfile
```

**Comment by kosteva** [comment]
update: looking at the output of `python -v ./comictagger.py --version` I found that python was trying to use a system installed version of `rarfile`:

```
# /usr/local/lib/python2.7/dist-packages/rarfile.pyc matches /usr/local/lib/python2.7/dist-packages/rarfile.py
import rarfile # precompiled from /usr/local/lib/python2.7/dist-packages/rarfile.pyc
```

instead of the bundled versions. I made this diff:

```
diff --git a/lib/comictaggerlib/comicapi/comicarchive.py b/lib/comictaggerlib/comicapi/comicarchive.py
index 6674bf5..16ab84e 100644
--- a/lib/comictaggerlib/comicapi/comicarchive.py
+++ b/lib/comictaggerlib/comicapi/comicarchive.py
@@ -26,7 +26,7 @@ import time
 import StringIO
 
 from natsort import natsorted
-from rarfile import rarfile
+from lib.rarfile import rarfile
 
 if platform.system() == "Windows":
     import _subprocess
```

and that made `comictagger.py`  use the bundled rarfile, and allow me to run `--version` as expected. On my mac, which does not have a system installed version of `rarfile`, this ran fine out of the box (since there was no system version to prefer).

I'm not python-smart enough to know if this is a proper fix; I can only describe what worked for me (which I made on a complete hunch).

**Comment by mediumwalter** [comment]
hmm moved the rarfile directory into the comictaggerlib folder and still getting the same error

**Comment by evilhero** [comment]
If the rarfile directory is in the /lib/comictaggerlib folder, the calls have to change. If it's in the /lib folder the calls have to change.

Fix is coming later today that will work for the rarfile directory in its' current location as then the module can be reused in other aspects of mylar should the need ever arise.

**Comment by mediumwalter** [comment]
Everything is working perfectly now, FYI.
