### ISSUE TITLE
Error when getting Batgirl 2016 from 32p

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#2167]
Seeing this error in the logs ..

2019-01-14 13:22:36 | ERROR | Exception: could not convert string to float: Prey
-- | -- | --

Mylar Version: development
-- git build 0733aa0f39f14db2f001706b7caecd9d3e5c0a92.
Python Version : 2.7.12
Language : en_GB.UTF-8

The issues were still snatched (not post processed yet, if that fails I will let you know).

**Comment by barbequesauce** [comment]
Thanks. False alarm, it should really be a debug statement...

**Comment by Lusiphur** [comment]
Seems to be happening a lot now ..


2019-01-14 13:53:51 | ERROR | Exception: could not convert string to float: Worlds
-- | -- | --
2019-01-14 13:53:51 | ERROR | Exception: could not convert string to float: the

**Comment by barbequesauce** [comment]
Yep - all related to TPB/GN matching.

**Comment by evilhero** [comment]
Post the full debug log showing the leadup to the exception being logged - not from the GUI but from the actual log files as they indicate module line numbers within.

Posting just the errors without seeing what it's trying to parse isn't very helpful.

**Comment by evilhero** [comment]
The error, like @barbequesauce mentioned is just for informational purposes and should be just a normal logging line (if included at all). It's getting tripped up on the ```of``` in the filename as you have an issue with the issue title in it and it's trying to determine if it's part of the actual series name or something else - but it's not harmful or stops anything. Will correct in the next dev commit.

As far as the Vol5 ->Vol1 pack items, if you can start a new issue and paste in the relevant information, and (let's just say it now) include the full debug logs from the log files showing the entire search process (not the post-processing as that doesn't matter) so that we can see why it's grabbing that particular pack.

**Comment by Lusiphur** [comment]
It will take me time to recreate as I cleaned it up already. Will get on that when I can.
