### ISSUE TITLE
New comic issue not updating in comic section (probably normal?)

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#2174]
I have a situation where a comic has a new issue that I can see in the weekly pull list but not in the comic section. Mylar is running 24/7.
The weekly pull list shows it as wanted and I also see it in the upcoming issues.
Is this normal (meaning one of the auto jobs will fix this)? What is the job that updates the comic section (auto-search?)? Is Mylar searching for the new issue already or this is done when the comic section is updated? I tried to search in the logs if it was already searching for this new issue but couldn't find it.

**Comment by cesalo** [comment]
Thanks. Do you know if auto-search is the job that does this? Just want to confirm that after the job runs the issue shows up correctly.

**Comment by evilhero** [comment]
Think of it as 2 separate entities trying to compare the same thing. The pullist/upcoming are one entity, and the series section is another. Mylar knows that there's a relevant issue coming out this week, but CV doesn't update their data until Wednesday morning (sometimes later). 

Because Mylar can't just randomly populate the issue data, it has to wait for CV to post the information. But we want to make sure that you know that Mylar knows it's due out and to watch for it. So Mylar marks it as Wanted in the pullist/upcoming section, and continually monitors the pulist for any changes (this is what the backend site does). 

Once it's determined that the pullist has new information for the given series, it attempts to refresh your local series so that your series page will contain the new information. Once it exists on your series page, then Mylar has all the necessary information required and removes it from the Upcoming section and puts it into the actual Wanted section and then searches can be performed against it.

**Comment by cesalo** [comment]
Thanks for the detailed response. Appreciate it.
