### ISSUE TITLE
Story Arc issue: Grabbing comic with same name but different version

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#2175]
Kind of a tricky one, just starting with the Story Arc functionality and trying to complete Secret Wars.
This has the Spider-Verse series of 2015 (5 issues) which is already available in Mylar. I also have the Spider-Verse HC of 2015 that is just 1 issue covering the Spider-Verse Story Arc.
I have them stored in the directories: Spider-Verse (2015) and Spider-Verse HC (2015) but the first issue has the same file name in their respective directories: "Spider-Verse 001 (2015).cbz".
When building the Story Arc Mylar is grabbing the HC issue and then 2-4 of the correct one. Is there anything that can be done to avoid this issue? I thought that by putting the HC in a different directory will fix the issue.

**Comment by evilhero** [comment]
When Mylar does searches against your watchlist for story-arc matches, it does so by CVID. So not quite sure exactly why it's matching on the HC one instead of the print series run, unless the HC is listed in the story arc itself somewhere on CV.  

It shouldn't be name matching, albeit the story arc's in Mylar don't distinguish between print vs TPB/HC series as of yet - have you tried to just add the 'HC' to the filename for the HC (ie. ```Spider-Verse 001 HC (2015).cbz```)? What does it say for the Edition of the HC series (does it say Print or TPB)?

**Comment by cesalo** [comment]
As far as I know it's not in the CV Story Arc or I would see it twice right?. It's 272 comics so couldn't go through all the pages in CV :).
I did the change you mentioned and it picked up the HC:
![image](https://user-images.githubusercontent.com/16859916/51623324-6d911400-1f06-11e9-9cf0-54e6fbb0539d.png)
The Edition is TPB:
![image](https://user-images.githubusercontent.com/16859916/51625146-72f05d80-1f0a-11e9-9b0a-0a94cbd98b99.png)

**Comment by cesalo** [comment]
As far as I can see the in CV the one here should be from the series of 5 comics and not the HC:
![image](https://user-images.githubusercontent.com/16859916/51625680-cadb9400-1f0b-11e9-965c-3e350eda1ff5.png)
I could try to delete the HC and see what happens (which I'll do anyway) but this would be just a workaround.
