### ISSUE TITLE
Story Arc order in CV seems different?

### ISSUE THREAD

**Issue by cesalo** [evilhero/mylar#2176]
I've opened another issue recently and while checking the story arc Secret Wars and noticed that the order in CV (at least in the website) doesn't match what I see in Mylar.
For example, in Mylar:
![image](https://user-images.githubusercontent.com/16859916/51625492-4b4dc500-1f0b-11e9-893c-83a16e97ce31.png)
In CV (second page of the issue list - starts in 31):
![image](https://user-images.githubusercontent.com/16859916/51625413-1c375380-1f0b-11e9-8ba8-6e9b318ded37.png)
I'm thinking that maybe the website has an error or is not updated but maybe is the opposite.
@evilhero Can you comment in this?
Also, since I'm just getting familiar with Story Arcs in general, I've found different alternative Story Arcs besides the ones in CV, for example the one in CV for Spider-Verse is a bit confusing and I had to manually update it. Is there a way to have another sources for this? Not even sure if there are other sites like CV that generates the Story Arcs in the format Mylar needs (I couldn't find any so far). I've seen several comments saying that the CBL option is outdated so no luck in that direction (not even sure how to generate a custom CBL).

**Comment by cesalo** [comment]
I actually didn't know you could change the order within the Arc section, that's actually great and very helpful. Even if you say there is a lot more work to do what you've created so far is pretty cool and very useful. Thanks.

**Comment by cesalo** [comment]
@evilhero not sure if there is an issue created for this but since I'm using a bit more the Story Arc functionality just circling back on few things you mentioned:
- I tried to change the order and it worked (need to refresh the page as you mentioned) but since this doesn't change the physical file is a bit hard to use specially for long story arcs because it needs to be manual. If a hit the refresh button it will pull the original Story Arc and rename it again - maybe an option to rename the files based on the cumulative changes done and not 1 by 1 can be added.
- This also represents an issue for ongoing Story Arcs (i.e. War of the Realms), at the moment the Story Arc is not complete (just the first 8 comic issues are present), if I make any changes now and refresh later to add the new comics I'll lose all the changes made in the first group - maybe a way to save the current order and then merge it with the official list will be needed.
Just some ideas :).

**Comment by cesalo** [comment]
@evilhero Sorry to go back on this, just want to confirm. Is this something that is handled at the moment? specially if renumbering the story arc should also change the physical files or not.
Thanks.

**Comment by evilhero** [comment]
If you renumber the arc, when it does a refresh it should retain your settings and apply those - but if the order has changed in regards to CV (then it probably is getting confused), it would apply the wrong sequence during the reordering I would imagine.

When the new backend comes online for storyarcs all of these types of problems related to storyarcs and CV will attempt to be resolved (ie. issues not pertaining to the arc being present, TPB/GN's included in the arc listing when they shouldn't be, having a structured reading order sequence that can actually be changed and retain the settings, custom arcs, etc). Until then though, I don't plan on code diving into the existing arc stuff just because it's currently a legit nightmare to work through, especially knowing that it's getting redone as is anyways.
