### ISSUE TITLE
CPU core maxed

### ISSUE THREAD

**Issue by mcaron1234** [evilhero/mylar#2212]
I'm using mylar in docker, on the development branch, build 2f4c7a3d7010131266c069b3242286dbd4017469. Mylar maxes a single core of my CPU as soon as it starts.  I suspect that I have a setting in my config.ini that is causing this because I
1. Stopped mylar
2. Moved the mylar config folder to mylar.bak
3. Started mylar with fresh config folder

This resulted in no cpu core max, and then I did:
1. Stopped mylar
2. Moved the mylar config folder to mylar.bak
3. Started mylar with fresh config folder
4. Moved config.ini from mylar.bak into the otherwise fresh mylar config directory

Which once again resulted in the maxed cpu core.

Can you scan my config.ini and see if there are any bad settings?

https://pastebin.com/b8pVSkkJ

**Comment by Faeton73** [comment]
The same things happens to me, and I have noticed that the culprit is DDL, in the 'search providers' tab. CPU usage is still high, though...

**Comment by evilhero** [comment]
Are you guys restarting mylar after you have the ddl provider option enabled ? There are queues that are pre-loaded for usage, and sometimes enabling/disabling the DDL provider option doesn't reinitialise the queue which would just send jobs to no-no land.

Also, when Mylar performs any task it has to eat some CPU - if you have a large wanted list it has to cycle thru each issue independently, while performing other tasks usually. Odds are the reasons why your CPU is hitting is because Mylar is performing something in the background (or multiple things simultaneously).  We know that the RSS check does eat some CPU (due to polling the providers) but that after the scan it goes back to normal - as well as searching for obvious reasons.

Also NEVER set your folder monitor to something like a minute (set it for every 5 minutes - I mean, it's comics.  A 4 minute difference isn't gonna kill anyone is it?). That's just asking for problems - you're telling Mylar to scan that folder every minute in addition to whatever else it is doing. If you're using torrents and the copy option, this will add significant overhead to your run due to the scan running every minute and might even cause over-lapping of jobs and/or items being scanned for post-processing multiple times after they've already post-processed.

Unfortunately, items like this are really difficult to track down - as trying to duplicate the issue so it can be troubleshooted on our systems isn't the easiest thing to do. If the DDL option is giving that much grief due to the high CPU usage, then you should disable the provider option until such time as things can be better tracked down / fixed.

**Comment by mcaron1234** [comment]
Disabling DDL and increasing the folder monitor to 5 minutes has stopped the core from being maxed out. I don't need DDL, although it is nice addition to mylar.  I'm going to close this issue, but please let me know if I can help in any way to provide assistance to tracking the cause of this.  Thank you for the help and for mylar.

**Comment by andrewenriquez** [comment]
Currently coming across this issue and it’s unfortunate cause I do use DDL. Is there a work around that anyone has found without disabling DDL or a better indexing option? I only have NBZGeek as my secondary option but it doesn’t seem to find Comics likes DDL does for me. Thanks in advance.

**Comment by evilhero** [comment]
This 'should' be fixed in the latest development build now - so going forward, enabling the DDL provider option won't eat the CPU as in previous instances.
