### ISSUE TITLE
Captain America vol. 5 #34 director's cut not finding match

### ISSUE THREAD

**Issue by edimusxero** [evilhero/mylar#2235]
Found and issue with Captain America volume 5.  There are 2 versions of issue #34.  One is titled

**Captain America 034 Director's Cut (2008)** 

which is how it get's labeled using comictagger.  This does not get picked up by Mylar.  If you look at mylar's wanted menu it appears as so

![Untitled](https://user-images.githubusercontent.com/15164376/54234352-55407d00-44e5-11e9-962d-3bf755a6f819.png)

Thanks

**Comment by evilhero** [comment]
Honestly it's probably not going to be an easy fix - or might not even be possible at all.

It's basically saying ```34 Director's Cut``` is the issue number which would literally break everything else the parser assumes when it parses files. So it's fix one, break everything - don't fix it, everything else stays as is.

I'll look into it some more, but this probably won't be a quick fix (just a warning)...

**Comment by edimusxero** [comment]
Even an option to manually tag it so it sticks.  I can mark it as archived but next time Mylar runs or updates it gets marked again as missing.

**Comment by evilhero** [comment]
Manually tagging it isn't going to help as it still requires the issue number to be able to be resolved for that exact same reason. There's a reason why there's a special subsection called ```annuals```, as they're issue numbers considered basically exactly like this - ```annual 001```, but obviously not an annual.

Adding a tagging option increases the complexity of the problem by tenfold for an option that is needed  for such an infrequent occurrence. It also would require rewrites of almost every module, so that's probably not going to happen. 

Stay tuned, that's all I can say atm...

**Comment by edimusxero** [comment]
Cool, thanks
