### ISSUE TITLE
config.ini not updating for enabling SSL

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#2243]
Ubuntu 18.04 with the dev branch of mylar Version: eea52178aa09e5caf010aabd3c6b3fbba0833741 (development)

I am in the web interface, I select enable ssl, the path to certs is correct.  I click save and restart, the config.ini is not updated, ssl is not enabled.

**Comment by evilhero** [comment]
Go back into the GUI and enable the HTTPS option and then save. Restart Mylar. When it comes up odds are it will be in non-https mode, due to something like this in your startup sequence log:
```24-Mar-2019 10:18:50 - WARNING :: mylar.main.290 : MAIN : The pyOpenSSL module is missing. Install this module to enable HTTPS. HTTPS will be disabled.
```
Make sure it's installed (```pip install pyopenssl```), and then try again. Note that the pyOpenSSL install requires your OpenSSL to be of a certain level as I believe it uses the cryptography module as well. Basically if you can't install pyopenssl via pip, you're gonna have to break out your google-fu to try and get it installed.

**Comment by DrSeussFreak** [comment]
That did it, I knew I had forgotten something
