### ISSUE TITLE
Issues with using Year as Volume number

### ISSUE THREAD

**Issue by Webby2687** [evilhero/mylar#2244]
Currently One-Shots with a volume number matching the year are not found by Mylar. Note this is only happening on one-shot series for some reason, normal series (ended or ongoing) pick up the files correctly.

File Name: `World of Animosity V2017 #01 (of 01) (September, 2017).cbz`

Log:

Timestamp | Level | Message
-- | -- | --
2019-03-25 17:28:28 | INFO | [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 1 ]
2019-03-25 17:28:28 | INFO | [FILE-RESCAN] Total files located: 0
2019-03-25 17:28:28 | INFO | there are 1 files.
2019-03-25 17:28:28 | INFO | [FILE-RESCAN] Now checking files for World of Animosity (2017) in F:\Comics\Files\Aftershock Comics\World of Animosity\(2017)

Changing the file name to V1, the status changes to downloaded.
File Name: `World of Animosity V1 #01 (of 01) (September, 2017).cbz`

Timestamp | Level | Message
-- | -- | --
2019-03-25 17:31:21 | INFO | [FILE-RESCAN] I have physically found 1 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 1 / 1 ]
2019-03-25 17:31:21 | INFO | [FILE-RESCAN] Total files located: 1
2019-03-25 17:31:21 | INFO | there are 1 files.
2019-03-25 17:31:21 | INFO | [FILE-RESCAN] Now checking files for World of Animosity (2017) in F:\Comics\Files\Aftershock Comics\World of Animosity\(2017)

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: [e.g. Dev/38aksi1]

**Additional information**
The reason moved to the year as the volume number was because with a multi-volume comic  mylar was counting the current series (in the root folder) as well as some of the records in the next level down folders for the other completed volumes.

Example with Aquaman, current volume is V8, 2016:
Root Folder: `F:\Comics\Files\DC Comics\Aquaman`
Sub-folder for V7, 2011: `F:\Comics\Files\DC Comics\Aquaman\Vol 7`
No other subfolders exist, just have these two volumes.

Ongoing issues stay in the root folder, with the other folder populated by the files for volume 7.
When Mylar checks the `Vol 7` folder, all the files match correctly. Folder has 57 files in it.
When Mylar checks the root folder for V8/current series it, it seems to count the current file count (47), plus the `Vol 7` folder, (57) to get 104 files. It moves 33 of the 47 in the on-going to an archived state for some reason. Nothing seems to be consistent on which issues it marks as archived. That 33 archived + 47 files gives 80. 

Timestamp | Level | Message
-- | -- | --
2019-03-25 23:10:47 | INFO | [FILE-RESCAN] I have physically found 47 issues, ignored 0 issues, snatched 0 issues, and accounted for 33 in an Archived state [ Total Issue Count: 80 / 47 ]
2019-03-25 23:10:47 | WARNING | [FILE-RESCAN] It looks like you have physical issues in the series directory, but are forcing these issues to an Archived Status. Adjusting have counts.
2019-03-25 23:10:47 | INFO | [FILE-RESCAN] Total files located: 47
2019-03-25 23:10:46 | INFO | there are 104 files.
2019-03-25 23:10:45 | INFO | [FILE-RESCAN] Now checking files for Aquaman (2016) in F:\Comics\Files\dc comics\Aquaman\

When I move the ongoing to its own folder, `Vol 8` or `(2011)` then the on-going counts correctly. Since CV doesnt store the count of volumes as the volume number, but rather stores the volume as the year, I went down this path which led to my error up top...

Sorry for the long issue, I can break this out into two issues if that helps. Thanks again for your hard work on this, really enjoying it so far!

**Comment by evilhero** [comment]
The 1st issue with regards to the vYEAR, nothing has changed that would alter how Mylar interprets that information when parsing/matching - so I'll have to take a closer look at things and see what's occurring. Off the top of my head I'd wager to bet that having a ```V1``` or ```V2017``` isn't needed, since one-shots technically aren't considered to be part of a volume (they're not more than 12 issues long kinda deal). Normally with one shots, since many of them don't have an actual issue number - the logistics behind Mylar will allow for issues with an issue number and without, with the compromise being that there is no volume label as it's not associated with an actual volume. This is kind of a requirement so that the parser doesn't cough on the parsing of all the items, and intended to help automate things while trying to maintain some precision. In the naming of the filename herein, I'm guessing that it's taking the ```V2017``` as the issue number and ignoring the ```1``` whereas the ```V1``` works as both the volume and the issue contain the same numeric (which also happens to match up to the issue numbering it's looking for).

The 2nd issue isn't so much of an issue as it is about your directory structure. Mylar will scan subdirectories as part of the given series - so if your series path is ```F:\Comics\Files\dc comics\Aquaman``` then everything under that path is considered part of that particular series on that particular series detail page. This is because alot of individuals have subdirectories containing annuals, specials, etc for each volume. So, basically when Mylar scans files doing a ReCheck Files - it only scans based on issue number, not volume or the like- which is why the directory location has to have only issues for the particular series it's tagged to within Mylar. It's also the reason why you have to have series directories so that Mylar knows the boundaries when it's scanning in files.

CV does store the count of volumes as the volume number, however there are some glaring problems with the method they use - such as:
- mini-series are counted as a volume for some series, but others they are not. I've read somewhere that anything more than 12 issues is considered a volume, however I've also seen series that doesn't apply to.
- they base volume based on publisher only, so different publishers will have different volumes
- they have some overlap of volumes on some series due to how the rebooting of some volumes occured (ie. Fantastic Four is a bitch one of if I recall).
So they actually do have the count, it's just not what some might consider proper if they have different expectations.

Hopefully didn't confuse the issue more with all that.....now on to more coffee, round two!

**Comment by Nobrumski** [comment]
Would it be possible to have a setting which defaults to forcing all one shots to TPB/GN as a possible solution?
