### ISSUE TITLE
Permission Denied when creating folder

### ISSUE THREAD

**Issue by juliemars** [evilhero/mylar#2264]
Hi I have a strange issue, I recently moved the Comic's to a Synology NAS, before they were on a WD My Cloud. When Mylar finds a new comic it downloads and post processes it fine, the comic gets renamed and added to the correct folder. 

However I went to add a new comic today that I have not collected before, but it never adds I get the following errors in the log file:

```
Error not an encryption that I recognize.

[DIRECTORY-CHECK] Could not find comic directory: /media/NAS2/Comics/COMIC(2019)

[DIRECTORY-CHECK] Could not create directory: /media/NAS2/Comics/COMIC (2019) [[Errno 13] Permission denied: '/media/NAS2']. Aborting.

Error trying to validate/create directory. Aborting this process at this time.
```

I am running Mylar on a Raspberrypi running Debian (Latest version), other apps running on the PI are able to create and edit folders on the NAS I have checked and the NFS permissions on the NAS are setup correctly, I tried mapping the user for NFS to admin in the options.

Under Permissions on Mylar I have tried setting the Group and User to the folder owner names on the NAS

Any ideas?

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Is your Comic Location path set to ```/media/NAS2``` ? Mylar will not create the main folder location - ie. the comics directory in the /media/NAS2/Comics location has to already exist or else it won't be created.

If your Comic Location is set to ```/media/NAS2/Comics```, then you would probably have to set the UID:GUID as the ownership name:group within Mylar if you're wanting to enforce permissions on the NAS. However, enforcing permissions on a different system than the one that the application is running on is generally not a good practice.

You could probably just disable Enforce permissions within Mylar and let it keep your default permissions as is. This of course is assuming that you have setup default permissions on your shares, so that when a file/folder is created therein that the default permissions are assigned instead of something like root or wheel.

**Comment by juliemars** [comment]
Hi evilhero 

Double checked and the folder location is correct, I disabled the enforce permissions but the same error happens. 

It's just strange an existing Comic will add episodes fine, but not a new folder under the same folder location. 

Thanks

**Comment by evilhero** [comment]
Synology is known to enforce permissions, and causes problems when trying to change them.

Normally this occurs due to  installing the synopackage version of mylar - how did you install mylar?

**Comment by juliemars** [comment]
Mylar is on a Raspberrypi not the sinology device. It's mounted via NFS

**Comment by evilhero** [comment]
Yeah sorry forgot. The uuid:guid should be identical on both systems for things to work.

However, odds are it's still a perms issue - as it can't even access the given path, just not sure the root cause of it.

```su``` to the user you run mylar as and then do a ```mkdir /mnt/NAS2/Comics/test``` or something. Odds are you'll get the same permissions error doing that which would indicate that it's a mount/perm problem of some kind.

**Comment by juliemars** [comment]
sorry for the delay, logged in as Mylar user and moved to the NAS mount and created a test folder worked fine, created a test file worked fine. 

I then wiped the install and DB files and started from scratch and it worked fine so we can close this down, no idea why it never worked with the orig config but its working now. Thanks
