### ISSUE TITLE
Missmatch. Appears to be ignoring (date) and other obvious match

### ISSUE THREAD

**Issue by insanemal** [evilhero/mylar#2291]
**Describe the bug**
Trying to get the old "Hellblazer" books. Keeps matching "The Hellblazer (2016)" as Hellblazer.
I've included the COMICINFO line. 
Everything else appears to be working fine, its just his missmatch. It looks like an issue with the matching logic.

It's double frustrating as it also matches these as being the correct download for "The Hellblazer (2016)"

It's triple frustrating as they have all 300 of the Original ones indexed. 

**Screenshots/Logs**
A redacted log entry:

mylar.COMICINFO: [{'IssueID': u'29089', 'pack_numbers': None, 'IssueNumber': u'1', 'nzbtitle': u'The Hellblazer 001 (2016) (2 covers) (digital) (Son of Ultron-Empire)', 'nzbid': u'NOPE', 'size': '30.4 MB', 'newznab': (u'NOPE', u'https://NOPE', u'0', u'NOPE', u'NOPE', u'1'), 'ComicName': u'Hellblazer', 'provider': u'NOPE', 'ComicID': u'4008', 'ComicVolume': u'None', 'modcomicname': u'Hellblazer', 'link': u'NOPE', 'IssueDate': u'1988-01-01', 'kind': 'usenet', 'torznab': None, 'SARC': None, 'oneoff': False, 'pack_issuelist': None, 'IssueArcID': None, 'comyear': '1988', 'nzbprov': 'newznab', 'tmpprov': u'nope (newznab)', 'pack': False}]

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Branch / commit: Master

**Additional information**
Heck even having a per release "blacklist" for words would be gravy. I'd just blacklist Ultron or something.

**Comment by barbequesauce** [comment]
Are you on 32p, or using nzbs? If 32p, you can specify the comic id from them - it simplifies marching considerably...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by evilhero** [comment]
Don't redact the logs - that forces us to redact our answers as we don't know the context leafing up to the problem.

Show the full debug log from the log files showing a search and false match for a given issue, and we can better assist.

**Comment by insanemal** [comment]
NZB's
Also I only removed APIkeys and URLS because private trackers and I don't want my private tracker and API key plastered in a github ticket. I'm sure you can understand that.

Also I do heaps of python devel, I'd love to help once I get my head around the code base but there is quite a bit of catching up needed to comment sensibly.

Anyway the important parts are there in `'nzbtitle': u'The Hellblazer 001 (2016) (2 covers) (digital) (Son of Ultron-Empire)'` and the match to ` 'ComicName': u'Hellblazer'`

**Comment by insanemal** [comment]
Also post processing is not matching them. It goes to post process and doesn't move anything. So the post processing seems to get the matching correct.

**Comment by evilhero** [comment]
We srsly need to see the debug logs - just pasting the comicinfo line isn't enough - the whole process of why it matched is in the debug lines previous to that along with additional information pertaining to the match. 

You don't want to paste the keys, yeah we get that - however most keys should be removed (the nzbid is not a key, it's literally the id of the nzb/torrent).

But you also need to realize that you're severely limiting our ability to help without those logs - I don't have the time to try and mock up what I think your workflow is in order to get the same result. 

You can pm me the log if you want, and it won't go farther than that (and no I don't care about your keys, I have my own and have far better things to do than try and key hunt accounts). 

Point being, if you want help - you're going to have to help us.  You can even hop on irc to further discuss if desired.

**Comment by insanemal** [comment]
[mylar no apikeys.log](https://github.com/evilhero/mylar/files/3255073/mylar.no.apikeys.log)

It's all good man. I was just rerunning with full debug and parsing through sed to get the other API keys you don't automagically get. Sorry for the delay. 

It actually makes it weirder because it seems to find the good one and toss it out for reasons I can't quite understand.

**Comment by evilhero** [comment]
Yeah that nzb one is from the experimental search, which it doesn't match on in the search process - so it's not that particular one.

There is something going on with the item being searched against from your redacted provider however - it's assuming the date is equivalent as there's only one volume listed for the given title. There was some code put in a few weeks(?) ago to circumvent some matching problems due to dates being improperly matched when volumes weren't present, this might be along those lines whereby it's assuming a match when it should be rejecting it.

And yeah, the post-processing module has a much more stricter method of matching than the search (even tho they all use the same file parser, the actual portion where it decides if it's a match or not is different due to the different workflows being presented).

I'm looking at the log now (thank you), tryin' to mock up something to at least duplicate the issue so I can work thru it better...

**Comment by evilhero** [comment]
So it's failing on the good one from experimental due to the ```[1/1]``` in the header - this is due to the experimental search failing to parse out that information (which is why it's experimental, sometimes it works, other times it fails for some odd reason). I mistakingly said it was throwing it out because it was incorrect matching, and that was wrong - it should be matching, but that header is screwing up the parser.

Since your familiar with python, if I paste a short line of code - can you edit the search.py file and modify a given line, then run it and see if it fixes for you? Since you're running master branch, everything hits development branch first usually - so taking items out of sequence usually causes merging problems when dev merges with master.

**Comment by insanemal** [comment]
Both of those NZBs are available on my redacted server. So for some reason its stopping short on that incorrect match.

I've also tested development branch. It appears to do the same thing. 
I manually downloaded the Hellblazer.003.(1988) nzb and it is the correct one.

The think I'm seeing is when it looks at the one with .003 in the name it keeps treating .003 as a decimal. Also looking harder at it `Hellblazer.003.(1988).(digitalEmpire) [1/1]` the `[1/1]` is making it decide it must be 

But sure if you send me some code I can do whatever

**Comment by barbequesauce** [comment]
What is the full nzb name and file name?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barbequesauce** [comment]
Side note - joining irc would help expedite this as there’s a few of us online right now looking at it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by insanemal** [comment]
Oh just to add to the oddity the NZB on my tracker looks like this `Hellblazer.001.(1988).(digitalEmpire)`
file is `Hellblazer.001.(1988).(digitalEmpire).cbr`

And sure I'll get an IRC client installed and mozy on over

**Comment by insanemal** [comment]
`diff --git a/mylar/search.py b/mylar/search.py
index d3f0a7a..a0096b1 100755
--- a/mylar/search.py
+++ b/mylar/search.py
@@ -1180,7 +1180,7 @@ def NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDa
                 if vers4vol != "no" or vers4year != "no":
                     logger.fdebug("Series Year not provided but Series Volume detected of %s. Bypassing Year Match." % fndcomicversion)
                     yearmatch = "true"
-                elif ComVersChk == 0:
+                elif ComVersChk == 0 and parsed_comic['issue_year'] is None:
                     logger.fdebug("Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check")
                     yearmatch = "true"
                 elif any([UseFuzzy == "0", UseFuzzy == "2", UseFuzzy is None, IssDateFix != "no"]) and parsed_comic['issue_year'] is not None:`

git diff of fix that resolved the issue for me. 

Thanks again guys/galls you all rock :D
