### ISSUE TITLE
Comics are still not moving from completed to proper place

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2300]
**Describe the bug**
Mylar seems to create a folder in the destination, but after my recent configuration changes, the files still sit in the completed folder. I think this is merely because I've not set up the config correctly, in Sabnzbd or in Mylar. For example, I have "comics" in the sabnzbd category field, but currently no instruction in the sabnzbd config, no category called comics". Do I need to create one or is this just not correctly or optimally setup?

I'm supposed to stop using comicsRN right? What is the optimal setup get comics from completed to the proper destination folder?

**Screenshots/Logs**
Will provide logs if needed
Screenshots
![Screen Shot 2019-06-23 at 2 28 47 PM](https://user-images.githubusercontent.com/97095/59982245-fc907e00-95c3-11e9-9d76-c8a8d7444312.jpg)
![Screen Shot 2019-06-23 at 2 35 36 PM](https://user-images.githubusercontent.com/97095/59982276-6e68c780-95c4-11e9-9d52-6c468adebd3a.jpg)
![Screen Shot 2019-06-23 at 2 36 11 PM](https://user-images.githubusercontent.com/97095/59982278-79bbf300-95c4-11e9-9e40-13ea21c026d9.jpg)
![Screen Shot 2019-06-23 at 2 36 57 PM](https://user-images.githubusercontent.com/97095/59982282-83455b00-95c4-11e9-898b-dddd0f7b2e7c.jpg)

**Environment (please complete the following information):**
Windows 10 pro fully updated
Mylar Version: development
-- git build 0af13913eaf120ced01bddeafb23ceedbcdfc0e8.
Python Version : 2.7.14
Language : en_US.cp1252

**Additional information**
Add any other information about the problem here.

**Comment by AtariBaby** [comment]
Well now it’s not downloading anything, despite adding new/popular/recent titles. I have 3 very sturdy nzb providers on nzbhydra too. I get pretty much complete success with my other operations like sonarr and radarr 

Please help.

**Comment by AtariBaby** [comment]
A few trickled in last night, but for example I added "daredevil 2019" and it took about 13 hours to get an issue. I got only #2, no #1 or other. And per usual, they are in my completed folder. Mylar created the folder in the comic library but didn't move the comic into it.
So two problems: comics only downloading partially and hours after adding, and they aren't being moved from Completed to the destionation where Mylar created a folder for them.
Thank you for reading and sorry for all the trouble.

**Comment by AtariBaby** [comment]
I read somewhere that post processing must also have folder monitoring checked. I checked it, put in the "completed" folder, but it's still not moving the files. Maybe I'll try to add another comic with logging.

**Comment by AtariBaby** [comment]
[mylar.log](https://github.com/evilhero/mylar/files/3328206/mylar.log)

**Comment by kanine** [comment]
I've determined currently for me at least that folder monitoring is the most reliable method, I've turned off 'Enable Completed Download Handling' which seemed to fail after a fairly short period of time. Using Post-Processing scripts seems to crash quite regularly and freezes the sabnzdb completion tasks.

I've also turned off RSS feeds which was not working properly with su, and results have been much better now.

With a folder monitoring interval of 20m it's now working almost flawlessly.

I have my NZB Search Interval at 360 minutes, and Search Delay set to 2 minutes. With this setup mylar has been running great. I do find that particularly with back issues I might have to search them out manually but pretty much anything 2018+ hardly needs touching.

**Comment by evilhero** [comment]
You can't folder monitor the location where your sabnzbd downloads go to - you'll end up getting errors due to race conditions when CDH and folder monitoring both try to post-process the same item. They're most likely downloading partially due to your folder monitor being set to 1 minute (!), along with CDH running on the same folder location. Mylar can't tell SABnzbd to just stop downloading something partially (or at all) - so either it's what I mentioned above or the files are incomplete on your provider.

Also, debug logs are required. INFO level logs aren't of any help whatsoever in these types of situations.

**Comment by AtariBaby** [comment]
Sorry evilhero. To be honest there seems to be a lot of confusion about how to properly configure mylar  now. I got that from Reddit. Is kanine’s configuration the way to go? The only guides I can find in here and your forum still reference comicsRN. Can you tell me the ideal configuration? I’ll test with another download today I thought debug log was on sorry

**Comment by evilhero** [comment]
Everyone's different with their configurations, so it's not just a simple one solution for all kinda deal due to how everyone has a different setup/need.

However some points to consider:

- CDH is better than folder monitor and comicRN simply because it passes along the issueid/comicid during the post-processing so it knows exactly what issue it is. Folder Monitor and comicRN both rely on file name parsing to determine what the file is, so it's not always 100% accurate.

- CDH requires that you enable CDH within Mylar and that the category you've assigned in SABnzbd to comics is identical to the one within Mylar. You have to ensure that you do not have any other script running on your download client for that specific category altering the filename/path (ie. ComicRN, nzb2media). After all that once you enable CDH, you don't need to do anything else.

- Point your Folder Monitor to a different comic path and have it draw in files that way as opposed to monitoring the completed download location from your download client (which would result in race condition errors). Any files that CDH cannot process for whatever reason, you can manually post-process by moving said files into that folder and Mylar will try to post-process them on the next run.

- If your post-processing is not running and/or you encounter any sort of error whatsoever, restart Mylar. Mylar will keep the queue that that the error occurred in (post-processing, searching, etc) locked up until such time as the error is cleared (and the only way is to restart/shutdown Mylar).

**Comment by AtariBaby** [comment]
Thank you! I will set that up. And maybe I could do a little wiki on it or something.

--
Gregory Fleming
415-218-4101
Misspelled from my iPhone

**Comment by AtariBaby** [comment]
okay with debug log with i hope 
[mylar.log](https://github.com/evilhero/mylar/files/3331852/mylar.log)

justice league dark moved to the comics folder! but, separate folder for each issue. no bueno. how do i get it to work like before, single issues in one title folder?

**Comment by AtariBaby** [comment]
I can't find an answer for this anywehere.

**Comment by AtariBaby** [comment]
So my problems right now.
CDH is putting issues into my library with a separate folder per issue. Strangely, Issue #1 goes into an unnumbered folder, then each additional cbr is on the same level, not in the master folder, the folders are numbered. I need cbr files under each folder like it used to be.
Hundreds of comics are in the “completed folder”. Is there a way to get them all into the library again, files collected in a folder named “Title (year)”, like it used to work?
Not sure Mylar is doing a great job of downloading new and old comics that are wanted.

**Comment by AtariBaby** [comment]
Oh wow it's working correctly now! Maybe it was an unsaved setting change.

I'm gonna close this now and I'll come back to these separate issues later as needed. I think I know what to do about the "completed" mess. I'll stick them in a separate folder and try to import them.
