### ISSUE TITLE
Annuals don't have Cover image URL on database

### ISSUE THREAD

**Issue by WedgeSparda** [evilhero/mylar#2301]
Normal issues from comics have URLs for cover and alt cover stored on the database but that doesn't happen for annual issues. If someone wanted to display those covers (in a new layout or using API), would not be able to do it since the covers URLs are not there.

Would be possible to have covers for the annuals?

Thanks and keep the good job.

**Comment by evilhero** [comment]
Should be able to - however if annual integration is not enabled, then the annuals are stored in the issues table and would have the URLs therein. So the changes would only need to be done for situations where the annual integration is enabled.

I'll mark this as an enhancement request - not sure as to the timetable due to other items, but it shouldn't be that difficult when the time comes.
