### ISSUE TITLE
Issue changing reading order of comics StoryArc

### ISSUE THREAD

**Issue by jimbojnr81** [evilhero/mylar#2310]
I need to change the order of a StoryArc (there're 2 comics that need to be swapped around in the reading order). 
I've tried just editing the position number but nothing happens. 
I can see that i am able to add a new issue with the position, so i figure if i delete the comic altogether and then re add it in the correct position,  but its asking for an issue number and i have no idea where to get this.

**Comment by evilhero** [comment]
It's actually the IssueID from CV, not the actual issue number. The IssueID is in a format of ```4000-XXXXXX```, where the 4000 indicates that it's an issue (4050 is a series, etc). So enter in the 4000-XXXXXX of the given issue you're looking for (you'll have to lookup that particular series and then issue on CV), and put in the position # and it should add it fine.

The arcs are in the midst of a complete overhaul, mainly cause the arcs on CV suck. As in they don't actually maintain a specific reading order, they have TPBs/GNs/etc in the arcs that already contain the individual series thereby inflating the arc count as well as messing up the reading orders, and some arcs have foreign publishers listed in addition to the American publishers - it's literally a mess. So because of all of this, reordering a story arc when it's basically an arbitrary list is difficult when the data presented changes on each refresh of the arc.

The new arc system (when it comes into play - probably not til the Fall at this rate) will allow for more granular control over specific reading order positioning within a given arc that will remain static across refreshes, so changing an issue position will not be as problematic.
