### ISSUE TITLE
Series is suppose to be 4 issues but is treated like a TPB

### ISSUE THREAD

**Issue by leaderdog** [evilhero/mylar#2323]
The Infinite Loop
https://comicvine.gamespot.com/the-infinite-loop/4050-104659/

In Mylar it shows it as a TPB
` Publication Date: September 2017 - December 2017
Publisher: IDW Publishing
Status: Active
Edition: TPB
Last Updated: 2019-08-03 20:31:04
Issues in Series: 4 issues
Directory
H:\IDW Publishing\The Infinite Loop (2017) `

Nothing I do can get it to read more than one file, which is Issue 2.  And it will rename issue one to issue 2... ??

I have removed it, and readded it, I've deleted the folder, and let it add it again.  I've renamed all the files to include the dates to my new preferred naming pattern and still doesn't see them.  I'm stumped.

Not sure if this is a mylar issue, or a comicvine config issue.

**Comment by evilhero** [comment]
Go to the ```Edit Settings``` tab for that particular series and check the ```Forcibly Mark Series as Print```, update the settings and then it will show appropriately. This is due to how CV has decided to put in a description that doesn't follow their previous conventions when it comes to declaring TPBs/GN that are not part of the current series (meaning basically it's probably just this one series, or if some one is editing the description on CV - their stupid arse).

**Comment by leaderdog** [comment]
Awesome thanks!  That worked.

I didn't get a notification for this, so just noticed it now.
