### ISSUE TITLE
Spider-Gwen V2 and Spider-Man 2099 v3 do not see the files in the folder.

### ISSUE THREAD

**Issue by leaderdog** [evilhero/mylar#2324]
This has me quite perplexed.

1) The folders and the directory location match I've copied the one from Mylar and put it in the "my computer" window to prove it goes to the right location.
2) I've 'rechecked Files' numerous times.
3) I've removed the files, then readded them manually
4) changed the "alternate Search Names" to the exact comic listing in the windows folder
5) In the case of Spider-Gwen it had renamed all the files. then "forgot" 20 and 21 were in there and tried to snatch them, but all files now are in archive state except 20 and 21 that are in a snatched state.
6) in the case of spider-man 2099 it had renamed all the files to... 'v3'  ??  no clue why.  And even putting the original files back in comic ids are different and they both redirect to the correct series on comicvine.
7) I've clicked shutdown on Mylar and then started it up again and repeated the recheck and refresh to no avail.
8) I've deleted the comic and then added it again, with no success.

Here's a link to the log: `https://www.dropbox.com/s/rzw5n1qenrud3r9/2019-08-05%20-%20mylar.log?dl=0`

Mostly it just shows there's nothing in the folder.  I don't know what I can do to fix this.

**Comment by evilhero** [comment]
You're files aren't really named appropriately for the parser:
```Spider-Gwen v2 - (2016-01) - 002.cbr``` doesn't follow a normal-type of naming convention, so having it in that particular format throws off the parser.  The ```-``` between each will cause problems with the parser, however if you insist on keeping the ```-``` you would need to switch the issue and date around so that it can be properly parsed. Also keep in mind that if you're using dates as per that format, a date with a month of ``00`` (ie. ```2016-00```) will be rejected as a valid date, as 00 is not a specific month, and thereby fail in the parsing.

Generally speaking your filenames should conform to some sort of naming standard (and since everyone sucks at naming, the general ```$Series $Annual $Issue ($Year)``` is that standard that Mylar adopts). Obviously there are variations on that, but the main problem with the given series above is that the year comes before the issue number, which the parser uses the actual placement of the date and issue number to detect various other aspects of the filename.

This also goes with your spider-man files, seeing as how they're just ```v3 - (2016-01) - 001.cbr``` kinda thing, it wouldn't get picked up either way. Mylar doesn't touch the files and/or rename files once they're in a downloaded status. Unless is was a manual metatag / post-process, generally speaking of course, Mylar will not rename them to your custom format. If I were to guess, I would think that your file format was messed up at the particular time that the spider-man series was either being mass renamed via the Manage Comics tab, or even manual metatagging possibly.

**Comment by leaderdog** [comment]
Oh sweet chesus!

I just renamed everything that way in my entire collection.  (took 3 days to do it) I figured since in Mylar it shows year and date in the middle on the page it was going to be helpful for determining the issues later.

As for Spider-man 2099.  The files were originally like this (And still are in a backup folder) but it wouldn't see them either `Spider-Man 2099 v3 - 001.cbr`

**Comment by evilhero** [comment]
Yeah somethin is messed up with the spider-man 2099 stuff it looks like, at least in that naming convention. Only fix for that atm  is to remove the v3 from the equation and then it should pick it up again (for that particular series at least). It'll require a code-dive/change, and not too sure about a timeline for a fix as my coding time is basically non-existent until summer is over.

**Comment by leaderdog** [comment]
So essentially, you're saying i need to rename my whole collection again?

**Comment by leaderdog** [comment]
I removed the v3 for one of the files to test for Spider-Man 2099  - 001.cbr.

Still didn't see it.  I stuck it into the manual post-processing folder and it didn't pick it up either.

**Comment by evilhero** [comment]
If all of your files are following that naming convention of ```$Series $VolumeN - ($Year-Month) - $Issue```, then yes if you want Mylar to be able to see if they're already downloaded/exist

But all jokes aside, prior to renaming your existing collection to that format - did you not happen to check to see if having some files in that format would get picked up by Mylar first (ie. a small data-set).

Even if I had the time to try and get the parser to pick up files in that naming convention, odds are it would break another aspect of the parser as there are specific items/placements the parser looks for and then determines where to go from that point. So I always make no guarantees when I say I'll try to fix the parser to accommodate the naming convention - as if it breaks something for the majority of the users in order to fix something for the minority, it probably won't happen.

**Comment by leaderdog** [comment]
No, I didn't think to test that format at all. I just figured since mylar listed the year and date on the comic page in that order I figured it made sense to add it.  

so just a single year in the file name makes the most sense?
Spider-Gwen (2019) - 001.cbr

**Comment by evilhero** [comment]
You can use YY-MM: ```2019-05``` just fine, it's just issues that might be ```2001-00``` will cause errors as it verifies the month and it can't verify 00 as it's not a valid month number. The 00 stuff can occur in older series where the actual month of publication wasn't ever recorded in CV.

Also, the use of the ```-``` can cause problems as it's not an actual word separator, it's a mathematical component, so if Mylar sees that in some cases it might assume it's a negative issue number. So if there's no space between the ```-``` and the subsequent numeric, it will assume it's a negative issue number.

But basically yes, ```$Series $Annual ($Year) - $Issue``` should work fine.

**Comment by leaderdog** [comment]
ok, one last question:  Will this format work? :)

$Series $VolumeN ($Year) $Annual - $Issue

And is annual necessary? I never had it listed, so wasn't sure.  This way, annual get's placed by date rather than at the bottom of the list (I think).

**Comment by leaderdog** [comment]
ok, going with this, unless you say something is wrong with it:

$Series $VolumeN $Annual ($Year) - $Issue

**Comment by evilhero** [comment]
I think you might have better success with ```$Series $Annual $VolumeN ($Year) - $Issue``` just because the ```$Annual``` will actually put the word Annual therein if it's a given annual issue. Having the word Annual after the volume but not having the issue number follow immediately might throw off the parser in some instances due to the year separating the two.

**Comment by leaderdog** [comment]
ok, changing it to that.

Thanks for your help Evilhero! :)
