### ISSUE TITLE
Comic series incorrectly identified as [One Shot]

### ISSUE THREAD

**Issue by spydermixx** [evilhero/mylar#2355]
Superior Spider-Man v2 (ComicID=116160) shows up in Mylar as a One-Shot edition and so searches fail.

Branch: 823d2a (development)

![image](https://user-images.githubusercontent.com/12326471/65709825-a5e68480-e089-11e9-8142-2bbb37f281e5.png)

**Comment by barbequesauce** [comment]
The CV entry has the words "one-shot" in it - that's throwing off the parser.

**Comment by leaderdog** [comment]
The whole One-shot addition by comicvine is potentially the lamest thing they've ever done.  I'm hoping Evilhero can look at that and have it removed automatically both when creating the folder - so we don't have it in our folder structures - and so that searches won't be crippled by them.

I know we can go into each of them and change the alternate search/file name but this is something comicvine never should have done, yet here we are. ;)

**Comment by evilhero** [comment]
Yep, we need to add that exclusion to the description parser so that it can properly detect the edition. CV is down atm, so I can't add/test - but once it's back up and I'm awake I'll do some testing against the description to narrow it down properly.

@leaderdog, the ongoing thing you mention (yes it's annoying I agree) is a bit different than the issue here. The word 'One-Shot' is in the description field for this particular series, which Mylar uses to determine what edition it is. It has common wording/phrases that CV uses in order to help determine what is what, and this is a new one that's not added as of yet. What you're mentioning is the word 'Ongoing' in the actual series title (or One-Shot even) - totally different, yet somewhat related. If you can make a new issue and describe this enhancement - basically that the terms ```Ongoing / One-Shot / whatever``` are removed from the actual series title, so that it doesn't propagate down to folder creation, searches, renames, etc. I can take a look more into this when I have some time (plus I won't forget or lose the request as easily).
