### ISSUE TITLE
Alternative options for Comic Vine

### ISSUE THREAD

**Issue by cclick815** [evilhero/mylar#2357]
It appears that Comic Vine is starting to lag behind with updating their information like current Issue numbers or new series.

Is there an Alternative Option for keeping current series updated?

**Comment by cclick815** [comment]
According to a recent Forum post, Any new content is only added to Comic Vine the day before the scheduled publication release date.

I feel this kind of breaks functionality when trying to add a newly announced series and how often are series already added updated with new/future issue numbers?

> [](https://comicvine.gamespot.com/forums/editing-tools-2761/new-issue-rejected-2048194/)
> 
>   #2 Posted by Cloudguy (2714 posts) - 3 days, 19 hours ago - Show Bio
> 
> @Azuravian: From the looks of it, you tried adding the issue a little too early. **We try to only add new issues the day before they're meant to be released.**

**Comment by evilhero** [comment]
There is no other alternative for Mylar usage than CV. It was built around how CV manages their data and utilises their API and so it's an integral part of the program.  It doesn't break Mylar functionality at all - Mylar waits until the CV information is present before it downloads / searches for anything. In some cases, for new series that are starting in a given week - there's the 'auto-watch' option which will monitor CV for that particular series and when it's present it will auto-add it to your watchlist and mark the new issue as Wanted (you can go up to 4 weeks in advance in the pull-list within Mylar).

Building in other alternatives to CV (there are none that have an open API) would require non-api usage - relying entirely on web page parsing and then trying to massage the data for the program to use. You wouldn't be able to metatag anything either until the CV data is present as most metadata scrapers rely solely on CV for obvious reasons. Building scrapers like that are unreliable for a program like Mylar, and the amount of time that would be spent fixing the scrapers when the websites changes would far surpass my time available.

In addition Mylar used to use gcdcomics in addition to CV in order to supplement the CV data (since at that time, the CV API was nowhere near as usable as it is now) - and from that perspective I don't want to have to manage more than one data-set of information as it's a logistics nightmare trying to match things up properly between the sites. I'm already doing that with the backend of the pull-list, as well as the upcoming storyarcs - and there's just not enough time in the day to add in comixology or the like.

It's also always been this way with CV - they have **never** updated an issue prior to the issue's store date. They do however add a new series usually on the Monday/Tuesday prior to the issue being released on the Wednesday. For the past year (roughly) they've been slow at updating the new issues on Wednesday, which seem to trickle into Thursday and sometimes Friday. Prior to that tho, they were updated on the Wednesdays like clockwork.

I have been working on some additions to Mylar that will allow downloads of issues that do not have CV data yet (meaning new weekly releases) - so it would download the issue(s) when available on download sites (nzbs/torrents/ddl) based on the information in the weekly pull for the given week. It would then keep these downloads in a monitored queue that would auto-tag them once the data on CV exists. Of course, if you don't want Mylar to metatag, then it would just download them and place them in your series directory as per normal. It's working, but it needs some additional testing prior to getting into the development branch, as when it fails (currently at least) - it goes really badly.
