### ISSUE TITLE
Issues like 10.MU once renamed show as archived after running rename

### ISSUE THREAD

**Issue by war3zlod3r** [evilhero/mylar#2358]
**Describe the bug**
Example: All-New X-Men 1.MU shows up as downloaded but after using the rename feature it becomes archived, I have to manually rename the file back and recheck it for it to show as downloaded.

**Screenshots/Logs**
[mylar.log](https://github.com/evilhero/mylar/files/3684035/mylar.log)

**Environment (please complete the following information):**
 - OS:  Windows 10 Pro
 - Branch / commit:  Dev

**Comment by evilhero** [comment]
It looks like it's the naming convention being used - normally it's something like ```$Series $Volume $Issue ($Year)```, but in the log it shows it as being ```All-New X-Men 1.MU v2 (2017)```. The problem with this format is that it's not a format that Mylar recognises. The file parser determines what an item is based on what the previous item was (ie. it tries to find the issue number first, and based on that it knows that in 95% of the case, the volume is supposed to come before). So in order to accommodate this particular format, the file parser would have to be altered (and obviously not break any other parser-related item in the process).

You can get around this if you change your file format structure as above, or if it's just a few of these particular issues, you can manually rename them so that the volume label is before the issue number. You can also keep the existing format you have, and just put a ```#``` sign immediately before the issue number (ie. ```#1.MU```) and that will get picked up as well.

Can look into this, but not sure about the time frame.

**Comment by war3zlod3r** [comment]
Thanks for the quick response I can alter the format, I was worried that might have been the case! Thanks for the help, your app is awesome!
