### ISSUE TITLE
Disabled on 32P for mylar (auth mode)

### ISSUE THREAD

**Issue by infomofo** [evilhero/mylar#2370]
**Describe the bug**
I have been using Mylar for about a year now without issue. On November 23rd my 32P account was disabled. This morning I was able to reach them and I was told that Mylar was "flooding country changes".

They suggested I switch back from auth mode to legacy mode.

My mylar is running on a hetzner dedicated server. 

**Environment:**
 - OS: Ubuntu 18.04
 - Branch / commit: (HEAD detached at 5ffe8fb)

**Comment by evilhero** [comment]
You cannot run Mylar on a seedbox using Auth mode, and then signon to the website from another IP - you'll look like you're signing on from 2 different IP's at the same time and you'll eventually get flagged by the 32P system as per your message.  The flooding country changes would imply that you were signed on via a web browser or the like from a different machine, while Mylar was performing some searches and because you live in a different country than your seedbox (best guess), the IP was changing frequently enough to get you flagged. 

This is a 32P security stipulation and there's nothing that Mylar can do to circumvent it, nor would we try (the legacy mode was kept so that at least you could monitor the RSS feeds and thereby get new releases that way, albeit not the most reliable way).

If you run Mylar on a seedbox and you use your local machine to sign-on, your best bet is to run Mylar in Legacy mode and then you can still use your local machine for signon attempts.
