### ISSUE TITLE
Mylar not picking up new naming schema?

### ISSUE THREAD

**Issue by professionaltart** [evilhero/mylar#2372]
**Describe the bug**
Some new Marvel comics, this week and last week, are coming out with a new name format, which I am assuming Mylar doesn't have the patterns to match it against.

I'm not sure if there are any other comic releases having this issue.  I had thought maybe last week was an anomaly.

**Environment (please complete the following information):**
 - OS: Windows10
 - Branch / commit: latest dev

**Additional information**
Examples of file names:
 Excalibur, 2019-11-20 (02) (digital) (Glorith-HD) 
 Marauders, 2019-11-20 (02) (digital) (Glorith-HD) 
 New Mutants, 2019-11-27 (02) (digital) (Glorith-HD) 
 Fallen Angels, 2019-11-27 (02) (digital) (Glorith-HD) 
 X-Force, 2019-11-27 (02) (digital) (Glorith-HD) 

At least, I'm assuming it's because the comics are now 'title, date (issue number)', rather than 'title issue number (date).

**Comment by evilhero** [comment]
It's due to the scanner deciding to put the issue number in brackets, which under most normal circumstances (ie. like 99% of the time) the issue number is not within a bracket.  So yeah that naming convention is unable to be parsed properly as Mylar uses bracket placements as a way to determine the start/end points of specifics - and having the issue number within a bracket throws off the parser.

Unfortunately your only option is to manually rename those files (even just removing the brackets around the 02 and preceding the issue with a # would be enough for Mylar to pick them up properly during a post-processing run and then they can be renamed during that process as per your settings). I'll look into trying to fix the parser to address this, but not sure of a timeframe.

**Comment by professionaltart** [comment]
I won't be able to try it for a few days to confirm, but does that mean that a filename like, say,  Fallen.Angels,.2019-11-27.02.digital.Glorith-HD  would still have problems, with no leading # ?

**Comment by evilhero** [comment]
Yep, that would cause a major problem for it. The problem is that's an nzb-type of name, not the actual filename - but the same parser is used in the search, post-processing, and file-checker modules within Mylar so they share the same advantages / disadvantages. The decimals - as - a - space - delimiter is always a problem (because what if it's a decimal issue, or the series contains an actual decimal in it), but that coupled with that particular format and it's just an utter mess.

I'm not saying it can't be done, just atm - that particular item would compose of 2 different problems of which I would probably address the formatting first, and then the decimal problem secondly (since that's much more difficult to work thru)

**Comment by professionaltart** [comment]
Thanks.  Looking in my sab logs, and it looks like both releases were, as you said, different NZB names, but the same filename.

I saw something a few days ago suggesting that some scene releasers may have changed.  Hopefully the new naming scheme is related to that, and will be corrected soon.

**Comment by professionaltart** [comment]
Weird.  I just logged in to hydra to do a few test searches, and it looks like other recent Marvel titles are fitting the usual convesntions, it's just the 'Dawn of X'/X-men titles over the past 20-30 days that are quirky.

**Comment by evilhero** [comment]
Spent some time on this tonight, got it working for both ```Series, 2019-11-30 (02) (digital) (Glorith-HD)``` and ```Some.Series,.2019-11-30.02.digital.Glorith-HD``` (as just generic examples obviously). Was able to snatch, post-process, and recheck files against them with no problems thus far.

Not exactly happy about some other things I've noticed, so I'm going to try and patch things up before I release this - but I'll probably push it out tomorrow as an FYI.

**Comment by professionaltart** [comment]
[mylar.2019.12.05 excerpt.log](https://github.com/evilhero/mylar/files/3925410/mylar.2019.12.05.excerpt.log)

It looks like it's not PPing them because CV hasn't been updated this close to their release?  Otherwise, I believe this is working as it should be, now, thanks!

**Comment by controversy187** [comment]
I'm not sure if it's related to this or not, but the timing seems to line up. Recently Mylar stopped picking up any files and are marking previously existing files are "archived." As an example, my naming convention is: "Amazing Mary Jane (2019) 002.cbz" and the log is showing:

FAILED FILES: [{'series_volume': None, 'issue_year': '2019', 'comiclocation': u'E:\\Comics\\Marvel\\Amazing Mary Jane (2019)', 'series_name': u'Amazing Mary Jane (2019) 00', 'scangroup': None, 'alt_series': None, 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Amazing Mary Jane (2019) 002.cbz', 'issue_number': '2', 'alt_issue': None}, {'series_volume': None, 'issue_year': '2019', 'comiclocation': u'E:\\Comics\\Marvel\\Amazing Mary Jane (2019)', 'series_name': u'Amazing Mary Jane (2019) 00', 'scangroup': None, 'alt_series': None, 'issueid': None, 'sub': None, 'booktype': 'issue', 'parse_status': 'failure', 'comicfilename': 'Amazing Mary Jane (2019) 003.cbz', 'issue_number': '3', 'alt_issue': None}]

Is my naming convention throwing it off?

**Comment by evilhero** [comment]
Yeah, although the change that would affect that particular naming convention was put into development in early December. The problem is related to the bracket positioning in relation to the other items in the filename. 

Basically Mylar uses the position of the detected year as a basis to determine where the issue number and series titles are. So in some instances filenames have no spaces between the brackets which throws off the parser - the fix in early December was to make sure that proper spacing was present before it actually parsed the filename, which in looking at the code now, wasn't really detecting the position of the brackets properly.

So I got it fixed now in my local branch - will push to development soon for you to test against your current naming convention so that you don't have to rename everything.

**Comment by controversy187** [comment]
@evilhero I pulled down the latest dev branch and tested against several series. It seems to be working fine again. Thanks for all your hard work!
