### ISSUE TITLE
Unable to add new comic

### ISSUE THREAD

**Issue by Bussterj** [evilhero/mylar#2378]
**Describe the bug**
I've run into a problem recently trying to add a new comic it seems to start then doesn't get far in logs I get some things like
Database error executing INSERT INTO issues ...... disk I/O error

**Screenshots/Logs**
[mylar.log](https://github.com/evilhero/mylar/files/3937290/mylar.log)
[mylar1.log](https://github.com/evilhero/mylar/files/3937291/mylar1.log)

**Environment (please complete the following information):**
 - Windows10
 - Version: 5ffe8fbd3080e11884c6d11ad3aacbc9f6a73cb3 (master)

**Additional information**
Tried a development build but I seemed to get more errors so jumped back
Any help would be appreciated

**Comment by evilhero** [comment]
Disk I/O errors are usually system related errors, not so much sqlite or mylar.

Are you using NFS as the filesystem where the mylar.db resides? 

It could be that it can't create the journal for the dB, that the hdd is failing, or that something else is locking the db up other than mylar (or a 2nd instance).

You'd have to describe your system setup so that we can troubleshoot things better than just guessing.

**Comment by Bussterj** [comment]
I thought it might have been my system!
![image](https://user-images.githubusercontent.com/34540688/70399308-b7012980-1a1a-11ea-8e56-b25f0ac941a3.png)
Just tried moving the directory and got that message :'( 
My mylar.db is now 793MB is there a file limit or is it just corrupt? Any way to save my database?
