### ISSUE TITLE
New issues not showing in series

### ISSUE THREAD

**Issue by Serneum** [evilhero/mylar#2388]
**Describe the bug**
Series that have new issues coming out this week (Week 0, 2020) don't seem to reflect that fact in the UI, at least not in all locations. They do show up in the pull list, and they even (sort of) show up in the main listing of comics, but the series will still show one less issue being required for the series.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/1091716/71638676-8cc71400-2c34-11ea-9d5a-23c440208b35.png)
![image](https://user-images.githubusercontent.com/1091716/71638682-9486b880-2c34-11ea-90f4-c06a18dbea06.png)
![image](https://user-images.githubusercontent.com/1091716/71638683-9f414d80-2c34-11ea-9787-523936b15f2c.png)
![image](https://user-images.githubusercontent.com/1091716/71638685-ac5e3c80-2c34-11ea-9e79-3c3a7e2a9deb.png)

This log is after I clicked Refresh Comic for Transformers (2019). It doesn't really seem to show much but figured it would be worth including. It's a bit long, so I threw it up on [Pastebin](https://pastebin.com/P6hT3MMd)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch / commit: master

**Additional information**
I've noticed this with at least two comics, Dreaming and Transformers, though refreshing the comic updates the main index to show the previous issue as latest. Ex: Transformers showed 15 as the latest issue in the index, but after refreshing the comic it showed 14 again.

Minor note: Transformers also shows as Ended, though the pull list has an issue 15. That issue (and more) can also be seen as upcoming on the IDW website. I've manually forced the series to be marked as Continuing, but I'm curious if the series will update itself once Mylar (and maybe ComicVine?) recognize the 15th issue.

**Comment by leaderdog** [comment]
The problem here is comicvine hasn't updated the comic information.  

Mylar gets it's "this week" list from a more reliable source.  Unfortunately, that reliable source doesn't have an api.  Until some one decides to do a more efficient job at updating comics with an api other than comicvine, this type of thing will continue to happen.  

Nothing Mylar can do about it.

**Comment by Serneum** [comment]
Fair enough. Can Mylar be updated to sync up "Last Issue" with ComicVine instead? As shown in 
![image](https://user-images.githubusercontent.com/1091716/71638676-8cc71400-2c34-11ea-9d5a-23c440208b35.png)
the "Last Issue" seems to come from that more reliable source and makes it confusing.

**Comment by leaderdog** [comment]
If you follow the link to comicvine you will find that The Dreaming is one of the maybe 5 books that are updated so far for this week.  Someone this morning had updated some books.

Hopefully, the rest will be updated soon.

**Comment by evilhero** [comment]
Pretty much what @leaderdog said - the pullist is an amalgamation of CV and another site, so the backend site (which is what Mylar polls against) has to do an inane amount of matching in order to match the 2 different data sets.

It's not that the other site is more reliable, it has numerous matching issues that have to manually adjusted every week in order to properly match up to Mylar. It's reliable in the sense that we can poll weeks in advance if an issue is to be released, as opposed to CV where we only know based on when they populate the issue data for a given issue (which is typically Wednesday, but lately Thursday or even Fridays it seems). So users that are waiting for a release 2 weeks out, can see when it's available as opposed to waiting until the issue data is present on CV in order to add the series (that's one aspect at least).

The Last Issue is based off of CV - but it's also not 100% accurate and it's dependent on being updated by CV to reflect new issues usually.  If it says, as in your example, issue 17 for last issue on the main page, and the issue doesn't show up in the series, then that means that the series hasn't been updated locally to reflect the update for any number of reasons (ie. no CV issue data yet, or the issue data is present on CV but the series is in the process of being updated locally).

The Last Issue comes from the pullist, and unfortunately changing it to poll from CV would cause some issues with the issue management aspect, as there are several calculations that are based off of the Last Issue (ie. to signify when a series has finished or not). But we might be able to colour that particular issue if it's a 'new' issue that has no CV data as of yet (ie. make the cell appear yellow or something)
