### ISSUE TITLE
cant update current version [none]

### ISSUE THREAD

**Issue by HypKin** [evilhero/mylar#2397]
**Describe the bug**
I decided to start fresh with mylar (because i downloaded a lot of comics i didn't ever read) and now have a problem with the update function.

I used the source files to install on a windows 10 computer. 
I tried to use the gitpull method at first, but to be honest i couldn't figure out how that exactly works so i deleted the whole mylar folder and then installed anew.

but as the title suggested: i cant update, maybe i forgot some file regarding the gitpull method or something?

**Screenshots/Logs**

`

2020-01-11 10:13:48 | WARNING | [ERROR] Could not get commits behind from github: 'total_commits'
-- | -- | --
2020-01-11 10:13:48 | DEBUG | Comparing currently installed version [None] with latest github version [d1ff6079a0d1994272fd441736fc27ee2c8084d1]
2020-01-11 10:13:43 | DEBUG | If you can read this message, debug logging is now working
2020-01-11 10:13:43 | INFO | Verbose (DEBUG) logging is enabled
2020-01-11 10:13:34 | WARNING | [ERROR] Could not get commits behind from github: 'total_commits'

`

**Environment (please complete the following information):**
Mylar Version: master
-- source build None.
Python Version : 2.7.13
Language : de_DE.cp1252

**Additional information**
I'd prefer to not use github updates, anything i can easily do to get it working again?

**Comment by evilhero** [comment]
Not sure why you're doing git pulls - the whole point of using git for Mylar is that you can then use the updater within Mylar to check and perform updates. The whole thing of doing git pulls from the command line isn't necessary unless you're modifying the local files for some reason (then the updater within Mylar wouldn't be able to update).

For git, from the root of the location where you want mylar to install, you do an initial ```git clone https://github.com/evilhero/mylar.git -b development```. And that's it. You then run Mylar as per normal and any updates should be able to be done via the updater within Mylar.

Installing from source is fine, just the built in updater has had problems updating in the past due to keeping outdated files  instead of just removing them. Source installs are just downloading the zip from the github repository page for mylar, unzip, and then run. Updates are pretty much dl the zip, hammer all the existing files, run again. However in this type of scenario legacy files are retained if they're deleted in the github repository and can cause problems. You can do the hammering in a new zip without issues, however there is the odd chance it might be affected by a legacy file (we don't remove stuff very often).

With Windows installs the updater might fail and say cannot update which is normal as it assumes it can't run git on Windows (the codebase was done awhile ago) - I'll revisit it today and see exactly what it does.

**Comment by HypKin** [comment]
ireinstalled fresh via git, and now its working perfectly again :D
