### ISSUE TITLE
Cannot Find Files in Directory

### ISSUE THREAD

**Issue by DrSeussFreak** [evilhero/mylar#2408]
**Describe the bug**
I added a new comic "Dead@17 Blood of Saints" (path on NAS '/media/comics/Viper Comics/Dead@17 Blood of Saints [2004]'.  When I click recheck files nothing happens. I have attached debug logs below

**Screenshots/Logs**
[mylar.log](https://github.com/evilhero/mylar/files/4119108/mylar.log)

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - Branch / commit: Version: 52bd27cb6b1377b45e154da238e60e819798c1e8 (development)

**Additional information**
n/a

**Comment by evilhero** [comment]
The ```@``` is being stripped from the regex, so when it goes to match it's looking for ```dead17``` and not ```dead@17```. The simplest fix would be to just add ```dead17 - Blood of Saints``` to your ```Alternate Search Field``` for the series and it'll be picked up for rechecks just fine if you keep your current naming scheme as you have it in the log (ie. ```dead17 blood of saints```).

I'll see if I can get a patch out for this as it's a simple fix, but since we've pretty much halted development on the python2 version of Mylar while we migrate to python3 (save for critical issues), it makes things abit more time consuming to make sure everything is at the same level.

**Comment by DrSeussFreak** [comment]
I had been testing the filename versions, so I changed it to Dead17, but I only changed the alternate filename not series name.

What is the ETA for the python3 version to be released?

**Comment by DrSeussFreak** [comment]
I can confirm the fix, I updated just now and the files are being located with the '@' in the filenames and series folder

**Comment by evilhero** [comment]
Python3 dev is still ongoing - our goal is still mid-February but we're kind of adding stuff into it as we're recoding various aspects, as is normal when migrations happen. You can check it out [here](https://github.com/mylar3/mylar3) if you want to see how development is going. Note if you're going to check it out make sure to use the python3-dev branch and be aware that some things are broken, while some things are also new.
