### ISSUE TITLE
Dumping comics to the root of the drive

### ISSUE THREAD

**Issue by The-Nusbaum** [evilhero/mylar#2413]
**Describe the bug**
Post Porcessing and Import seem to be ignoring the comicbook location. I detects/creates the comicbook folder, then simply moves/copies the file to the root of the drive.

**Screenshots/Logs**
`15-Feb-2020 22:13:50 - INFO :: mylar.validateAndCreateDirectory.1706 : Thread-23 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: E:\Media\Comics\Correct_Publisher\Correct_Series_(2005)
15-Feb-2020 22:13:52 - INFO :: mylar.Process_next.2618 : Thread-23 : [POST-PROCESSING] copy successful to : E:\Correct_Series_044_(2006).cbz` 

**Environment (please complete the following information):**
 - OS: Windows7, python2.7
 - Branch / commit: Master and Development

**Additional information**
Pretty sure this is somehow my fault, but I dont see how. Ive followed the code, though I do not have a sqlite browser on my media machine, I see where its pulling comicnzb from the DB and then comlocation from that, which strikes me as odd (but, not knowing what is in comicnzb it may not be? I could just dump that to the logs I suppose

**Comment by The-Nusbaum** [comment]
1 - yeah. comicnzb is the COMIC level... derp.
2 - it doesnt seem to be an issue on linux, so Im chalking it up to forcing the poor dear to run on windows.

**Comment by evilhero** [comment]
Can you paste the actual debug log (from the files, not from the GUI since the files contain code-line references). We need to see the leadup to the error so we can get the workflow model it's using and what the values are that it's trying to use - just pasting the error unfortunately is not enough information for us to help with.

I have a feeling your Folder Format / File Format might not be correct (ie. you have path options in your File Format), but without seeing the debug log showing the formats it's impossible to guess correctly.

**Comment by Bart274** [comment]
It must be a configuration issue as it always worked nicely for me on Windows

**Comment by The-Nusbaum** [comment]
you were correct. There was a / at the beginning of the issue title, so yeah... it was dumping to the root, exactly like I accidentally told it to
