### ISSUE TITLE
Feature Request: Series Setting to ignore "Edition" when searching for issues

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#2414]
I have 2 series that Mylar has marked the booktype as "Digital".  They are Destiny, NY and Prison Witch.  Issues are available on 32p but Mylar will not download them because the 32p issues are marked as "Issue" and not "Digital"...
`2020-02-20 14:35:04 | DEBUG | Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.`

It would be nice to be able to tell Mylar to ignore this booktype when searching and finding issues.

Also, what is an example of a series that has a "Digital" booktype on 32p?

**Comment by evilhero** [comment]
There isn't - the booktype is used by Mylar only based on the CV data. 

In this case, you probably added the digital series to your watchlist and you're finding results for the printed one. Try adding the printed series to your watchlist, and then Mylar can match properly to 32P.

If you added the correct edition but it's being flagged wrong, you can force the edition to Print via the Edit Settings tab on that particular series detail page. 

Also, if you're using Auth mode you can set the 32P ID on the Edit Settings tab in order to force Mylar to search only against that specific series ID.

Having the book type present is fundamental in the search requirements as it's how Mylar can tell if something is a TPB, digital, one-shot or standard series. Removing that would mean it would be downloading incorrect issues for different series (ie. As in your case, the print edition for the digital which would then not match up numeric wise to what Mylar expects to be present)

**Comment by BenBeyond** [comment]
For both of these series, there is no "printed" series to be found on CV, only "Digital".  But the issues available on 32p are the exact same as what is shown on CV (based off of cover art, release date, and issues number.)  
I understand that this might be an anomaly for the specific series that I am looking for, and that other digital series might not line up like that.

> If you added the correct edition but it's being flagged wrong, you can force the edition to Print via the Edit Settings tab on that particular series detail page.

The setting quoted above is exactly what I am asking for, but I can't find it on the Edit Settings tab on these series... There is one to "Forcibly Mark series as TPB/GN", but the tooltip doesn't say anything about booktype or digital, so I didn't think that was it.

> Also, if you're using Auth mode you can set the 32P ID on the Edit Settings tab in order to force Mylar to search only against that specific series ID.

I also did this for both series, but the booktype seems to override or ignore the 32p ID.

**Comment by evilhero** [comment]
Feature development has stopped on Mylar, as we have shifted to Mylar3. So basically that means only critical bug fixes will be patched in 2 up until such time as we decide not to do so anymore. If you want to see the python3 branch, it's [https://github.com/mylar3/mylar3](https://github.com/mylar3/mylar3). Same concepts are being applied there, most stable is Master - bleeding edge is development but usually is just as stable.

**Comment by BenBeyond** [comment]
Excellent! I will definitely be checking out the new version.  Is the code base similar enough to do simply copy the DB from the old Mylar to Mylar3?

**Comment by evilhero** [comment]
Yes, that's what those of us that have been / are currently running mylar3 did initally. It's a pretty simple process: 
- git clone into a fresh directory
- pip install -r requirements.txt
- copy over your mylar.db, config.ini and cache folder (cause of the images or else they'll all come up as blank placeholders until each series gets refreshed). 
- edit the ini and make sure the logs_dir option is putting the logs into the new location path (otherwise it will put the logs into the old location).
- then either:
   - delete the mylar python2 (old version) directory. Rename the mylar3 folder to the old version directory name so that startup scripts, etc can all be located properly without too much monkeying around.
   - keep the existing mylar3 directory as is. Update your startup scripts or the like to point to the mylar3 location instead of the old mylar location.
