### ISSUE TITLE
One issue downloads then nothing until I reboot?

### ISSUE THREAD

**Issue by paulr24** [evilhero/mylar#2437]
Hi, I recently started using Mylar and I'm experiencing some strange issues. I have set up both NZB and DDL (GetComics) as search providers. For some reason upon opening Mylar it seems that it will often grab one issue of a comic via NZB, but then stop (but not always, sometimes it will not grab anything). If I close and re-open Mylar, it grabs one comic again, then stops. Via DDL comics seem to download at random as well, and it's rare.

What can I do to troubleshoot this? I have set logging to verbose and can post logs but not sure where to start since they're obviously long.

**Comment by evilhero** [comment]
You'll want to be using the mylar3 repo instead of this version as it's no longer really supported as we've moved development & troubleshooting over to the python3 version. That repo can be found [here](https://github.com/mylar3/mylar3). 

If you're still experiencing problems after switching, then post an issue on the mylar3 issues list please.

**Comment by paulr24** [comment]
Ah I'm sorry, I got my versions mixed up, I am running mylar3. I will post this over there. Thanks!
