### ISSUE TITLE
Error When Importing a CBL file

### ISSUE THREAD

**Issue by thewindupboy** [evilhero/mylar#2450]
I'm trying to make sure I understand the CBL format, and so I've grabbed a cBL file that i think is in the correct format, and I'm trying to import it into mylar.  I get the following error, and I'm attaching the file (I edited the file to have a slightly different series name, but I doubt that would have caused this problem)

Error !
TypeError: string indices must be integers
<table class="configtable"> <tr> <form action="arcOptions" id="chkoptions" method="GET"> <% if arcdetail['percent'] == 101: css = '<div class=\"progress-container warning\">' if arcdetail['percent'] == 100: css = '<div class=\"progress-container complete\">' if arcdetail['percent'] < 100:
/home/hd27/moleboy/apps/mylar/data/interfaces/default/storyarc_detail.html, line 43:
<%
/home/hd27/moleboy/apps/mylar/data/interfaces/default/base.html, line 87:
${next.body()}
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 899:
callable_(context, *args, **kwargs)
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 873:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
/home/hd27/moleboy/apps/mylar/lib/mako/runtime.py, line 838:
**_kwargs_for_callable(callable_, data))
/home/hd27/moleboy/apps/mylar/lib/mako/template.py, line 462:
return runtime._render(self, self.callable_, args, data)
/home/hd27/moleboy/apps/mylar/mylar/webserve.py, line 57:
return template.render(http_root=mylar.CONFIG.HTTP_ROOT, **kwargs)

**Comment by thewindupboy** [comment]
[flurp.txt](https://github.com/evilhero/mylar/files/5643322/flurp.txt)

**Comment by evilhero** [comment]
Yeah probably don't use the import CBL aspect at this time. It hasn't worked as far as I'm aware since the last major overhaul to the arc stuff, which was years ago when it was in mylar2.  We changed how Mylar pulls data from CV for arcs, and in doing so, basically broke CBL import (from what I recall). That option in the GUI should be removed for the time being. 

It's been years since it's been touched, and honestly, atm at least, I don't have the free time to get it working properly (without sacrificing time on other aspects of Mylar). 

One of the enhancements upcoming is updating the entire storyarc code so that it uses a different reading order system, in addition to other things, one of which is being able to support custom reading lists ( from either a file or data-entry within the GUI ).

**Comment by thewindupboy** [comment]
OK, cool, I'll leave it be then, thanks!
