### ISSUE TITLE
UID Issue

### ISSUE THREAD

**Issue by lostkt87** [evilhero/mylar#620]
What do you do if in the Rss feed, there is no uid, just the api key. for example https://dognzb.cr/rss.cfm?r=(apikey)&t=7030?

**Comment by Rawh** [comment]
Hello Evil, any more news on the dog UID front?

**Comment by evilhero** [comment]
I actually thought this was fixed until I tried it yesterday because of this issue and found out it wasn't. Got it working again, and even got file sizes working now with dog (previously it ignored the min/max file size restrictions), so it's an improvement in the end. 

If anyone wants to help, I'm more than willing to merge stuff into mylar - I'm just really slow at doing so cause I usually have a bunch of stuff going on within the code that hasn't been pushed out yet. But please if you feel like you can help, please do - it's always appreciated :)

**Comment by Rawh** [comment]
I'm guessing I won't see any results till you move it to the master branch?

**Comment by evilhero** [comment]
Easter weekend is kicking me in the nuts with free time, so I haven't had a chance to finish the changes. I'll try and finish it and push them up hopefully tomorrow, or possibly the next day depending on time. I'll reference this issue in the commit though, so you should get notified when it's up ;)

**Comment by cybrwizrd** [comment]
Maybe I can help. I had a patch to get the DOG file size as well and a few
other RSS issues. I was about to send it all to you but since you released
a big updated I took it down to go back to testing. I'll finish rebasing
stuff and submit it later today.

Unfortunate that we both worked on the same thing. Anyway, if you have
fixed it already you can see the way I did it and pick whatever you like
from the rest of my stuff.

**Comment by evilhero** [comment]
By all means, I'm always wanting to push stuff from the community when it comes to Mylar, so anything you want to help with is much appreciated. :)

**Comment by cybrwizrd** [comment]
Ok, I have just issued a pull request (#974) for a few RSS issues.

The DOGNZB UID is not used in the RSS query so it doesn't matter what is put in the interface. Mine is empty and it works fine (on my branch).

DOG file size is also fixed in that pull request. ('Cause I got bitten by that DOG when somebody uploaded a bunch of variant covers a few weeks back). 

A few other issues fixed (NZB.su was rejecting our RSS queries, newznab RSS search wasn't searching the rssdb table correcly) and some cleaning up in that pull request too.

I've commented on each commit separately too in case there's any need. So if there's anything in there that you like / don't like / hate with the fury of a thousand suns, just tell me. And if there's anything I didn't explain clearly, just ask, it will be my pleasure to answer.

**Comment by evilhero** [comment]
Dude thats awesome work - I especially love the way you modded the feedparser library on the fly (didn't even know you could do that - I learn so much reading other people's code). 

The patch I was working on, I cleaned up a lot of the crap code that you got rid of too, and tried to streamline things - I ended up using the xmtodict library though, so I'm not sure which one would be more robust going forward. 

The other stuff I added was fairly minor in comparison, save for maybe the removal of all apikey & userids from the rss results link field, so that if a users api changes at any given point they could still use the rss db to retrieve (currently it won't work if the apikey has changed as it's stored with it). That and some threaded calls to ensure the rss doesn't run simultaneously (on startup and then a force check manually). 

I really like the ability to call individual rss checks within your pull as well, with a simple button on the config page one could initiate individual rss checks if they're wanting to pull from one specific provider. 

I didn't change any db structure although I was thinking of separating the torrents from the nzb. With the change from cbt to 32p I might have to add some extra columns to the rss table, that probably wouldn't be used by the nzbs.

Suffice to say, I'll probably use a big portion of what you did and it's awesome that you took the time to help out - it's so appreciated and definitely welcome (when it's only myself doing most of the coding, it can get a bit strenuous sometimes). 

I can't get to a machine until later tonight to pull in the request, but definitely gonna do this so that it helps users get the Wednesday fix ;)

**Comment by Rawh** [comment]
So it's going to be wednesday patch-day eh? :+1:

**Comment by cybrwizrd** [comment]
Woohoo! Glad you liked it. That certainly makes me feel welcome, thanks.

Yes, I learn a lot by looking at people's code and just trying to do stuff too. I learned a lot just doing those patches and that is great.

Those are all problems I experienced myself so I had a great interest in having them fixed. Like 'I can see the issue on their site, why hasn't it been picked up yet?' . I had no idea the nzb.su RSS feed didn't work until I looked at the database and realised nzb.su had no entries in rssdb in the last few months. And the DOGNZB problem I experienced when I realized the check on file size didn't do anything and Mylar was downloading a bunch of variant covers. 

I don't use torrents so I can't be a big help there, but I watch those NZB RSS feeds like a hawk :)

Oh, I didn't even notice the UID was put in the database as part of the URL. Yeah... if a user changes UID that could be a problem. Not sure if it happens a lot, but that could certainly happen. I have wiped rssdb several times to test now, so I wouldn't really have a backlog to go to if I changed UID.

DATABASE KEY:
Ah, yeah. About the database, there's something I wanted to ask you. I noticed that in rssdb (again), the key to the table is only the title. Wouldn't it make sense to be a composite key made of the provider and the title? Reason being, right now if 2 providers have the same title, won’t it be overwritten in the database on parsing the second provider?

That might not be so bad, but I think it would be overwritten by the upsert whenever one of the 2 providers is parsed as long as they’ve still got it in their feed. 

I was thinking maybe we could add the provider to the key so you could get multiple entries for a title. In that case once the RSS search goes through the rssdb table looking for an issue, it could even sort the results according to the preferred provider order. And it the first one fails, the second one could still be used because it would still be in the database.

I wouldn’t rely on the preferred order while scanning because the RSS feeds seems to be the first thing to go whenever a site in under stress. Considering It’s most likely an automated process (whenever I am not looking :) ), that’s not a bad decision. The parser will be back in 20 minutes anyway. So… we could delay picking the right issue from the database until you know you want to get it.

So maybe splitting the torrent RSS from the NZB RSS could be a good thing.

DATABASE INDEX:
I was about to say I don’t think I have seen any index declaration in the database, maybe it would make it faster to add some. But I just now noticed there’s a few columns declared as UNIQUE and that seems to have SQLITE create an index on those fields, so might cover it. I might still try to add a few indexes on other fields, just to see if it helps in some queries.

Anyway, those are definitely not things I complain about, just stuff I could have a casual look into as long as you don’t have any objection.
