### ISSUE TITLE
Replace interface with a Bootstrap based interface

### ISSUE THREAD

**Issue by Decipher** [evilhero/mylar#648]
One of my pet peeves of all similar services to this one is that the interfaces don't necessarily work on mobile, when there really should be no reason why that would be the case.

The Bootstrap system is basically tailor made to the interface you are providing and has a lot of wonderful things to offer.

I'm currently building a python based web service to skill up so I can contribute to projects like this and am using Bootstrap myself, so I'm happy to do the majority of the work if you're receptive to the idea.

**Comment by edasque** [comment]
I know this is an old thread but I can't find a more recent issue on a similar subject. Mylar's lack of mobile responsiveness is my main issue with the app. I would love for it to adopt a responsive framework or fix its existing pages one by one. On an iPad for example, the top menu doesn't appear fully, history is hidden, until you awkwardly zoom out.

**Comment by evilhero** [comment]
Yeah, I'll admit I have like zero knowledge of bootstrap or even the mobile programming aspect, and while I might be interested in learning about it and trying to get Mylar to use it - I honestly just don't have the time to undertake such a project at the moment. Between fixing the problems with Mylar, troubleshooting problems, adding on stuff because other things are broken due to CV changes, and my own personal life - it's just not possible.

Plus, with what @Decipher had said about the templates all having alot of logic in the themed layer it  would require even more time to move the logic out of the templates and with that would cause undoubtedly more problems / fixes.

I'm not against the idea of someone doing a PR for this, or templating, etc - but waiting for me to undertake this, unless something changes in the next little while, is going to be some time.
