### ISSUE TITLE
Add support for 'Collected Editions'

### ISSUE THREAD

**Issue by Decipher** [evilhero/mylar#679]
I don't think this is an official part of the CV API, but some comics have listings of 'Collected Editions' (http://www.comicvine.com/invincible/4050-17993/ - Expand full wiki summary).

It'd be nice if these could be supported, I know it would be tricky due to a potentially inconsistent format, but it should be possible.

**Comment by AreFinstad** [comment]
any updates on this?
adding to "annual" works but it cannot seem to find the file automatically like normally.
if mylar searched for series name in the filename it could work, then we could name them as the series name is in comicvine. 
or let us manually link and point to a file.
personally i like to name them with the issues they cover like: "Gotham Academy 01-06 (2015).cbz"

i also think the series page need to have a manual files section so manual files or series you add with ID's gets not placed in the annual section. or a dedicated tpb/collection area on the page.

manual linking these files would be for the best in the long run i think so  people can always do that no matter what.
somehow marking the normal issues the TPB cover as downloaded with the TPB file would be the last and final step with something like that.

parsing the wiki and so on is nice, but could be faulty. 
manual linking and its own little section on the series page is a huge step forward as im sure there is many that like tpb over normal issues at times. (personally always try to have tpb only when i can)

**Comment by AreFinstad** [comment]
alot of these issues if not all could be fixed by just reading the embedded metadata in the files tho. the url line points to the series page on comicvine. issue number and series name can also work.
if the user would rename the series data and issue data to cover the main issues it would be amazing, but then mylar need to support multiple issues in one file. which it does now.
just find it a bit sad to have all the metadata without using it :D 

reading most if not all metadata lines should be done (there is import metadata options but it doesnt work for me) 
should read series, title, alternate series/story title and ofc the volume numbers and alt numbers. finally the web/url line. 

the web/url line should be read no matter what. that means people could rename the series line for example. 
(say TPB vol 1 for batman would be just batman 01-07 (2011) instead of Batman: The Court of Owls 01 (2012))
reading alt series can help aswell as many times people could have the tpb title in the alt series, or if the tpb covers say annual or other series aswell it can be covered there.

im really new to mylar in general so plz correct me if im wrong or anything. just find it weird that metadata isnt read for most functions. 

on a sidenote i do see a "use existing metadata" setting for the manage setting but that never finds anything on my searches. 
sorry for the wall of text ramble >___<

**Comment by evilhero** [comment]
No update. Adding TPB is a massive overhaul of the existing file-check system and enabling the checking for it will fail (out of 35 tests I do for file-checking, allowing for naming such as 1-6, or 1 - 6 or however you name it causes 80% failure rate which means normal issue scanning gets broken big time).

The Use existing metadata option is only for importing series that don't already exist within Mylar. Mylar will read the meta-tags during this process if you have the option toggled on, but again it depends on how you have your tagging (it will read CVINFO and CVDB tags if they're present). And if you're talking all of this about TPB's, it's not going to work because again, it all relies on finding the issue #, which can't be easily found on TPB's as it's not a lone issue number. So while it could scan in fine with the use of CVINFO and CVDB tagging, adding the series would cause issues as it wouldn't be able to lineup the issue #'s accordingly. Reading the metadata for non-TPB type issues works fine for most users (depending on the series of course).

And again, modifying the series page to include TPB/Comp goes in line with what I said above. There's no point in creating a separate tab or the like within Mylar, when it can't support it anyways. Annuals are supported, which is why it's included. The idea is not to add TPB using the green arrow/Manual Annual Add option, but to add annuals. If you're adding non-annuals, you're pretty much throwing caution to the wind and you have to expect problems.

The naming part, is a personal preference. You might name them like that, but I know at least 3 other people (in short convo's), that name them all differently than how you do and that I'd have to account for everyone's different naming conventions. This isn't like TV shows where they have to follow a typical SXEX numbering convention, people name things in a really weird format and expect it to work (Mylar has to be able to decipher if a 10-11, is a tpb 10-11, or an issue # 10-11 and yes there is one, or if 10 is part of the series, and it's a -11 issue number, or whatever else). 

Manual linking has been brought up before, and while no other auto-downloader has this option available, it might be of benefit within Mylar to have. Albeit, it wouldn't encompass TPB's again, because then you'd have to have multiple issues to point it to and the current code base can't handle that without some massive overhaul that I just don't have the free time to devote to (and trust me, I devote quite abit of time to mylar as it is much to the delight of my wife sometimes). 

Too many what-if's and other possible problems with the naming/checking and it would be opening up a pandora's box that couldn't be closed as easily as it was open :(

Maybe one day, when things are more manageable or there's more than just myself working on this on a constant basis it could be revisited. But at this point in time, given my lack of free time lately I don't see this getting worked on anytime soon.
