### ISSUE TITLE
Issue name of ½

### ISSUE THREAD

**Issue by smyther** [evilhero/mylar#915]
Hi, some of my comics have ½ in their file name, e.g issue 0.5 - i cant seem to find a way to make them get recognized.

I just get an error like this:

UnicodeEncodeError: 'ascii' codec can't encode character u'\uf022' in position 14: ordinal not in range(128)

Renaming the issue works, but then it doesnt get recognised!

**Comment by evilhero** [comment]
I need abit more information - the ½ exists within the name of the file or are you just saying that the issue is that? 

Are you on the development/master build of Mylar ? 

Can you provide the name of the file you're attempting to scan? I'm assuming you're just trying to scan it in for an existing series and you're not doing a manual post-processing or downloading et all.

With the file named as 0.5 (for a ½ issue), it seems to work:
![default 5](https://cloud.githubusercontent.com/assets/909424/5600014/bcd63466-929f-11e4-9449-8c06d99bf10c.png)

**Comment by smyther** [comment]
Aha! No, i was running from master, not development/master - Thank you very much!
