### ISSUE TITLE
Not recognizing the name with spaces

### ISSUE THREAD

**Issue by IPyandy** [evilhero/mylar#917]
For example some cbr/cbz names are superman 001 (2011) release-group. with a manual process, Mylar cannot detect the name. But if I change the name to have (.) as superman.001.(2011).release-group it's then recognized for most things.

Having an issue where 3 flash comics are just not being recognized no matter what I do, that's 023.1, 023.2 and 023.3.

Thanks

**Comment by evilhero** [comment]
Is Red Lanterns the name of the issue and Green Lantern the series itself? Mylar would assume (in this case) that anything after the - is the issue title and ignore it.. It doesn't have anything to do with spaces in the filename. Issue title inclusion in filenames is coming shortly (right  now you can search only) 

The flash is primarily because you're using decimals to denote spaces which makes it really difficult for mylar to parse properly. It should still work however, with spaces, decimals or even '_'. 

Are you on the master or development branch of mylar and are you up to date? Filenames with spaces, decimals and underscores all will work with decimal places and have for awhile, which is why I'm asking the branch/commit.

**Comment by IPyandy** [comment]
The Green Lantern is the series and yes, the red lantern would be the issue. The Flash's original name was something like "The Flash 023.1 (2013) (Digital)" and may have had a release name after it. It was not able to recognize it that way, so I started playing with the names. Did it with a few others and like I mentioned, adding a (.) in the lace of spaces worked. Just seems weird, because it's not with every release, some names similar or the same as the flash, green lantern were recognized and organized right away.

I am in the development branch, install last night. I like the software, it organized a mess of comics I had really nicely and downloaded some missing issues. The behavior just seems weird and not at all consistent, maybe I'm missing something, I'll see if I can find another pattern or better illustration.

Thanks

**Comment by IPyandy** [comment]
I should probably clarify that this is with "manual post-processing". I had an existing library before using Mylar and I'm adding the comics to my Mylar list, then going in and manual processing directories. This is where sometimes the issue occurs. When mylar downloads something automatically, it works just fine.
