### ISSUE TITLE
FR: watch words

### ISSUE THREAD

**Issue by mgaulton** [evilhero/mylar#928]
I'd like the ability to designate a list of words that will automatically trigger a comic add. ie. 'Iron Man' will automatically add and download any iron man related series. I'm thinking this would catch any new series without me having to manually go in and find/add them.

**Comment by evilhero** [comment]
That could involve a fairly big code change depending on how encompassing the scope is. 

Are you indicating that you'd like to apply the keywords to the weekly pull and then have it either mark as Wanted and grab (if it's in your watchlist already), or have it auto-add the series and thereby the issue as well (if it's not on your watchlist) or have it auto-grab only (as in a one-off)?

**Comment by mgaulton** [comment]
Auto-add series if not already existing, mark issues as wanted.

**Comment by evilhero** [comment]
Auto-add would be an attempted auto-add, as for some series it might be difficult for mylar to figure out which series is which (when there's reboots, etc). Then it becomes a matter of how to inform users that the auto-add failed and has to be done manually. 

Marking as Wanted though would be very doable since it's just automarking it and then basically doing an one-off grab. And since the watch words would be applied to the pullist, subsequent releases would get auto 'one-off'd grabbed as well.
