### ISSUE TITLE
Avoid the 60s period

### ISSUE THREAD

**Issue by AAraKKe** [evilhero/mylar#929]
Hi,

thanks a lot for this awesome tool in the first place. 
I just wanted to ask if there is a way of avoiding the 60s waiting period to look for releases or if it is considered to be added. I have vip suscription for several indexers and a dedicated pc for the usenet server so I find myself a lot of times waiting for mylar to search instead of download.

Is this needed for some stability reason for Mylar? Could it be avoided?

Thanks a lot!

**Comment by evilhero** [comment]
Actually that was an intentional delay. For most indexers, regardless of whether you're VIP or not, if you hammer the api, you'll get temporarily banned - and eventually if it happened enough times, they would ban the application (remember this was headphones issue awhile ago). 

So I put the 60s delay in for just between newznab indexers & dognzb & nzb.su. If you're using Experimental or Torrents (either one), the 60s delay doesn't apply. If you find a successful match on one of the newznabs (or dog or nzbsu), then the 60s gets reset and it starts searching immediately again.

If you're running a local newznab, the 60s delay is also bypassed.

I know it becomes an issue when you're waiting for things and if you have several indexers there could be a good delay accumulating - but right now, I don't have any plans on changing the delay or even modifying it to allow customization. This might change in the future, if there's enough demand - but it's more about safeguarding things with regards to hammering (I know nzbsu will ban clients, and I believe mylar was on the list at one point)

**Comment by AAraKKe** [comment]
Thanks a lot for your answer! I am actually using oznzb with newsznad and it seems that delay is being applied. What does experimental search actually do? Should I enable it? I think the delay is being applied because when I look at the logs it only searches every minute and unlike sickbeard for example I never get a queu to download with mylar because they are snatched slower.

In any case, it would be nice if I could bypass that but I can totally live with it if, as you say, it may create other problems with any other indexer.

Thanks!

**Comment by evilhero** [comment]
Experimental is the raw indexer nzb indexing,
