### ISSUE TITLE
Logs tell me I don't have any provider `search provider order is []`

### ISSUE THREAD

**Issue by MoOx** [evilhero/mylar#930]
Here is my config

![screen shot 2015-01-24 at 07 43 58](https://cloud.githubusercontent.com/assets/157534/5886393/d19ede30-a39c-11e4-932f-b7435d044e75.png)

![screen shot 2015-01-24 at 07 44 35](https://cloud.githubusercontent.com/assets/157534/5886399/e07743c0-a39c-11e4-89ed-09acabaa6af3.png)

What am I doing wrong so Mylar don't want to try to look on KAT?

**Comment by evilhero** [comment]
You need to save the configuration and restart Mylar so that the new values can be loaded properly.  If you make any configuration change (especially enabling/disabling providers) and don't restart mylar after saving, you'll get that message almost every time. If you're still getting it after a restart, shutdown mylar, edit the config.ini and find the provider_order line. Delete the entire line, save the config and start up mylar and it should work then. 

You might also want to check off rss feeds so that mylar can read/store the rss in the cache - but it's not required.

**Comment by MoOx** [comment]
Thanks for the quick response. I'll try that asap.

**Comment by MoOx** [comment]
So here is what I did:
- shutdown mylar
- edit /usrl/local/mylar/config.ini with vim, I deleted the following line `provider_order = 0, Experimental`
- restart mylar

This time it look good, I've ['kat'] as search provider. Thanks !
