### ISSUE TITLE
Uncaught Exception - While Searching Wanted - Latest Development Update

### ISSUE THREAD

**Issue by IPyandy** [evilhero/mylar#933]
getting this exception when searching for wanted issues

```
2015-01-25 20:07:03 INFO    pausing for 60 seconds before continuing to avoid hammering
2015-01-25 20:07:03 INFO    Shhh be very quiet...I'm looking for The Flash annual issue: 1     (1963) using NZBGeek (newznab)

Uncaught exception: Traceback (most recent call last):
File "C:\Apps\mylar-development\mylar\logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "C:\Python\lib\threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "C:\Apps\mylar-development\mylar\search.py", line 1374, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear),     comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy,     ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck,     ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "C:\Apps\mylar-development\mylar\search.py", line 225, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate,     StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host,     ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID,     issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "C:\Apps\mylar-development\mylar\search.py", line 661, in NZB_SEARCH
stamp = time.mktime(issue_convert.timetuple())
OverflowError: mktime argument out of range
```

Installed python 64bit and stills ame

**Comment by evilhero** [comment]
Can you post the mylar.log file showing the lead up to the error? It looks like it's having a problem with the issue date for that particular issue for some reason.

**Comment by IPyandy** [comment]
Here you go.

https://gist.github.com/IPyandy/040da5b36baacddd0f9f

**Comment by IPyandy** [comment]
I marked that annual issue as "Skipped" and forced a check, here's one with the same exception for a different issue

https://gist.github.com/IPyandy/33b691e3e8b4f2ae337f

**Comment by evilhero** [comment]
I think those two issues have mucked up dates. 

You can check by going to the Manage tab and clicking on the Manage Issues button. 

Change the status to Wanted (cause these are Wanted status), and check what the dates are for those two issues. I have a feeling that one of them is way off (or similar).

**Comment by IPyandy** [comment]
Here:

    The Flash	105	1959-03-01	0000-00-00	Wanted	
    The Flash	105	1995-09-01	0000-00-00	Wanted

One is from the 1959 Series, and the other from v2 1987 Series, the annual causing the issue prior to this one, there's only one.

For some reason the annual doesn't show up under manage issues

![capture](https://cloud.githubusercontent.com/assets/2131779/5894358/dd121458-a4d2-11e4-8d9b-5e6e2b5b587f.PNG)

**Comment by evilhero** [comment]
The annual might be due to it being an annual and wasn't initially included - I'll have to double check on that later tonight. I'll also load those series up on my local repo and see if I can replicate the issue - at this point I'm abit stumped without at least attempting it myself.

**Comment by IPyandy** [comment]
Doing some research (not sure if those lines are new in the code) seems to have something to do with the epoch on my system. Windows 8 x64

    >>> time.gmtime(0)
    time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)

Which is why I installed 64bit python, funny thing is the reason I mention if that time conversion is new. I've added and successfully searched for much older comics <= 1937.

**Comment by evilhero** [comment]
Those lines of code have been in mylar for probably close to a year now, aside from the gmt problem from a few months ago (where it used your OS formatted date instead of what it does now, use a generic timestamp) , it really hasn't caused that many problems. 

What version of python are you running?

**Comment by IPyandy** [comment]
2.7.9, I just installed mylar-development on mac os x and do not have the same issue, same version of python

**Comment by evilhero** [comment]
This appears to be a Windows only problem in the use of the mktime statement and how it uses the underlying C+ library of the OS when running. It's screwing the epoch up basically. I've been able to replicate this on a Windows machine myself, so I can start to figure this out.

**Comment by evilhero** [comment]
Should be working in the latest development commit (e7b1cdf). It just will set a pre-determined value now for anything prior to 1970 for store date, but this is just used when comparing the store date to the posting date to see if it's a valid match.

**Comment by IPyandy** [comment]
awesome, thanks for taking care of it, will check it out.

**Comment by baz1860** [comment]
I'm getting the same problem - and the same error message - for the Thor Annual 1 (2015-04-30

Latest develop: dea9ee using Python 2.7.9 on OS X 10.10.2

**Comment by evilhero** [comment]
Is it the mktime error in the same part of the log?

**Comment by baz1860** [comment]
I shall check when I get home - don't have access to logs at the moment

**Comment by baz1860** [comment]
I shall check when I get home - don't have access to logs at the moment

**Comment by baz1860** [comment]
As it turns out, its similar, but not entirely the same:

Uncaught exception: Traceback (most recent call last):
File "/Applications/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/Applications/mylar/mylar/search.py", line 1384, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/Applications/mylar/mylar/search.py", line 225, in search_init
findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
File "/Applications/mylar/mylar/search.py", line 1265, in NZB_SEARCH
nzbname = nzbname_create(nzbprov, info=comicinfo, title=entry['title'])
File "/Applications/mylar/mylar/search.py", line 1562, in nzbname_create
nzbname = re.sub('.cbr', '', nzbname).strip()
UnboundLocalError: local variable 'nzbname' referenced before assignment

**Comment by evilhero** [comment]
Totally different error, or had an issue with the time, your error relates to the nzb/torrent and the provider you're using. 

Which download method are you using (torrents /sab/nzbget), and which provider is the error occurring for? If you check the mylar.log file it will indicate all of those as well as the actual search release its having problems with
