### ISSUE TITLE
Error(log info in message) cant update and not downloading

### ISSUE THREAD

**Issue by stustaff** [evilhero/mylar#938]
I pressed update button when notified about beong 8 commits behind it did nothing. I restarted and tried again still nothing. Log has below error.

I havent done anything on my end other than turn system off and back on.

015-02-02 10:58:22 	ERROR 	Uncaught exception: Traceback (most recent call last):
File "/Applications/mylar-master/Mylar.py", line 261, in
main()
File "/Applications/mylar-master/Mylar.py", line 237, in main
mylar.start()
File "/Applications/mylar-master/mylar/__init__.py", line 1371, in start
rsscheck.tehMain()
File "/Applications/mylar-master/mylar/rsscheck.py", line 52, in tehMain
mylar.search.searchforissue(rsscheck='yes')
File "/Applications/mylar-master/mylar/search.py", line 1374, in searchforissue
foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
File "/Applications/mylar-master/mylar/search.py", line 47, in search_init
logger.info('AlternateSearch is : ' + AlternateSearch)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by evilhero** [comment]
You might have to re-git clone your repo from scratch if you can't get past that to do the actual update. That error isn't related to the update, but to the search on startup it does when checking for rss (if you have it enabled of course). If you can get to a gui, try doing the update - and then check the mylar.log file for the error that comes back.

Just make sure to backup your config.ini, mylar.db & /cache directory (in it's entirety) before you wipe the directory and restart it. That way you won't lose anytihng. That error was one of those ones that was fixed within a few minutes after it was pushed out, so not sure what's going on exactly...

There is one thing you can try since it's doing the check on startup:
open your config.ini (without mylar running) and edit these 2 values:
```
nzb_startup_search=0
enable_rss = 0
```
(Setting those values to 0 will turn off the auto-searching on startup, so you should be able to get to the GUI with no errors and then do an update)

**Comment by stustaff** [comment]
Sorry the first sentence is above my pay grade..??

I'm in gui fine when I try to update nothing happens.! I'll back up and retry again :) thanks

**Comment by stustaff** [comment]
OK so its sorted.
Disabled RSS, NZB startup was already on 0 
rebooted and it launched fine no error showing in log.
did update, shutdown, reenabled rss, rebooted.

All good

thanks
