### ISSUE TITLE
Exit(1) Syntaxerror

### ISSUE THREAD

**Issue by omega127** [evilhero/mylar#941]
Recentally installed Mylar on Windows 8.1 for the first time, got it set up so that it's snatching comics and SABnzbd is downloading them.  However when SAB goes to run ComicRN.py, I get the following error:

File "C:\SickRage-master\autoProcessTV\ComicRN.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

I'm not a python developer at all, but did some research that came up mostly blank.  Seems that any type of document like this would need the <! html declaration on the first line.  Note:  all I've done is downloaded Mylar from Github, and moved the three files to my SickRage folder as that is what SAB points to.  I've renamed AutoProcessComics.cfg.sample to AutoProcessComics.cfg.  Nothing else has been done. 

Any ideas? App seems like an awesome idea.

**Comment by evilhero** [comment]
Yeah the html error is just the response page that you get in error when sabnzbd executed the script and can't get a response, it's not actually a part of mylar perse. 

When you edited the AutoProcesscomics.py, are the values you entered correct? Usually the html error indicates it can't reach the mylar server because the values were entered incorrectly (or it wasn't running) . 

Is there any additional information in the mylar.log file indicating a problem?

**Comment by omega127** [comment]
I ended up just having mylar scan the sab folder and it does it quick enough that I don't mind it.  It's pushing the files and pulling them from the VM that has Sab back to my NAS, so all is good.
