### ISSUE TITLE
You have 0 search providers

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#942]
I was looking at my logs and I noticed that I was getting an error with nzb.su. Understandable because I'm limited there. But I saw nothing about my other search providers, including dognzb, so I unchecked nzb.su. I now see in my logs "warning: you have 0 search providers". What gives? if dognzb was configured incorrectly, I would expect an error to that effect. Therefore I assume something else is amiss.

**Comment by evilhero** [comment]
Did you restart mylar after you did the configuration change? The 0 providers error usually comes up when you male a provider configuration change and don't restart mylar after the save.

Otherwise, shutdown mylar and edit your config.ini. Wipe out the provider_order line entirely, save the config.ini and then start up mylar. All will be working then.

**Comment by AtariBaby** [comment]
Yes a restart may have fixed it. We'll see! Suggestion: put a notice there and where you configure sabnzbd, stating that "a restart will be required".
