### ISSUE TITLE
One of Mylar's greatest foes: The Fantastic Four lol

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#947]
If I search Fantastic Four Annual (2014) (one issue), it says "Already in Library". If I click on "Already in Library" I'm taken to the current regular ongoing volume of the series, not an annual. (and saw a spoiler in the process _cries_) Is dis anudder prank by the yancy street gang?

**Comment by evilhero** [comment]
Do you have annuals enabled in the configuration?  

Mylar will automatically attach new annuals to a given series if it can determine specific things on comicvine.

**Comment by AtariBaby** [comment]
It is not checked. So, is being directed to the main series a bug if unchecked?

Regardless, should I check it to get my annual? Mostly annuals suck so I don't bother, unless it's by the main writer or otherwise doesn't suck.

**Comment by evilhero** [comment]
Yes, it shouldn't redirect to the series (if it's an annual) unless it's attached to the given series (annuals enabled). 

Enabling annuals will most likely allow it to be the auto added to the series, so them it would get marked as Wanted accordingly, or you could mark it yourself at that point. The only caveat is that the annuals have to reside within the series directory since it's 'attached' if the annuals option is enabled. 

Just remember if you enable it, to save the config, and restart Mylar. Then refresh the series and you should see it appear at the bottom of the page under the annuals heading. If it doesn't, you can enter in the ComicID of the annual series (not the issueid)  in the little box in the lower right and it will force-attach the given ComicID to the series ;)

**Comment by AtariBaby** [comment]
None that I see.
![screen shot 2015-02-18 at 2 25 31 pm](https://cloud.githubusercontent.com/assets/97095/6258032/148ad08c-b77a-11e4-8bef-02ddc9bb64f9.png)

**Comment by evilhero** [comment]
I'll scope things out later on.. It's probably getting confused because you have the normal series in your watchlist.

**Comment by AtariBaby** [comment]
Let me know if I can help, for example, deleting and re-adding.

**Comment by evilhero** [comment]
Heh no worries, I still have your db file to fool around with.

**Comment by evilhero** [comment]
Ok, quick glance there was no catch for checking to see if annuals was enabled or not. So it searched your annuals db for references (I'm assuming at one point you had it enabled), I tested both with and without. Check is now in place, expect in next development commit :)

![ff](https://cloud.githubusercontent.com/assets/909424/6320633/1718fef2-bab1-11e4-881d-a182338eec98.png)

**Comment by AtariBaby** [comment]
Great!

**Comment by AtariBaby** [comment]
Not sure if this is related. There are a handful of comics that jam up sabnzbd+ and the only way to resolve it is to kill it and restart. One of them is ```New Avengers 030 (2015) (digital) (Minutemen-Midas).cbr``` There are 3 or 4 others. Usually an Avengers or New Avengers title for some reason. Any idea why and what i can do about it?

**Comment by evilhero** [comment]
When you look inside the .cbr file, are all the jpgs in a folder that's identical to the filename? There  have been some users reporting that such a cbr causes lockups when the metatagging goes to extract the jpgs.

**Comment by AtariBaby** [comment]
Interesting. Behold images, cbr and containing folder name

![screen shot 2015-02-27 at 3 45 30 pm](https://cloud.githubusercontent.com/assets/97095/6423240/d235d824-be97-11e4-847e-1ef262cc8fbc.png)
![screen shot 2015-02-27 at 3 41 48 pm](https://cloud.githubusercontent.com/assets/97095/6423241/d267599e-be97-11e4-8252-45d32da1e68a.png)

**Comment by AtariBaby** [comment]
Thanks for the updates! I guess we'll tackle the above issue next time I see it.
