### ISSUE TITLE
Search Providers Doubled up

### ISSUE THREAD

**Issue by edru** [evilhero/mylar#950]
Config shows this:

provider_order = 0, Experimental, 1, nzbsu https, 2, nzbs, 3, Dog, 4, kat

Logs show this:
INFO	search provider order is ['Experimental', 'newznab:nzbsu https', 'newznab:nzbs', 'newznab:nzbsu https', 'newznab:Dog', 'kat']

No matter what I do to rectify the situation, I always get nzbsu https doubled up.

**Comment by evilhero** [comment]
Don't enter nzb.su as a Newznab provider, it has its own entry so just use that (it needs a different url call because it's a modified Newznab base). 

If the above doesn't work, shutdown mylar, edit the config.ini and wipe out the entire provider_order line. Save the config, start up mylar and it should detect everything properly.

**Comment by edru** [comment]
Yes I know there is a built in, but there is no indication that it is HTTPS
or not, and I want to make sure im using the HTTPS api call, not HTTP. This
has always worked fine until I added NZBSU today - but in the past it was
cool and worked fine.

If you are using HTTPS for API calls, then yeah ill just use in the built
in ones.

**Comment by evilhero** [comment]
The url for api calls in mylar is 'https://api.nzb.su',  and I'm pretty sure the direct link downloads when mylar finds a match are in the same protocol.

**Comment by edru** [comment]
Thanks, it solved it.
