### ISSUE TITLE
Post Processing Issues on Freenas

### ISSUE THREAD

**Issue by psychoflame** [evilhero/mylar#960]
Hey i recently moved my mylar install over to a freenas box and im having a bit of trouble getting post processing to work. Originally i was having trouble with sab being able to call the PP script. It was spitting out this error. 

         "  env: python: No such file or directory"

Using this (https://github.com/evilhero/mylar/issues/698) i was able to edit the script to be able to call python but i ran into another problem. PP fails, and sab outputs this error form the script log

Loading config from /mnt/media/downloads/sabnzbd/PP_Scripts/autoProcessComics.cfg
Opening URL: http://localhost:8090/post_process?nzb_name=Star.Wars.003.2015.digital.Minutemen-Midas&failed=0&nzb_folder=%2Fmnt%2Fmedia%2Fdownloads%2Fsabnzbd%2Fcomplete%2Fcomic%2FStar.Wars.003.2015.digital.Minutemen-Midas.1
Unable to open URL:  [Errno socket error] [Errno 61] Connection refused

In mylar it errors out with

Uncaught exception: Traceback (most recent call last):
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/pbi/mylar-amd64/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/webserve.py", line 1168, in retryissue
sendit = search.searcher(Provider, nzbname, comicinfo, link=link, IssueID=IssueID, ComicID=ComicID, tmpprov=fullprov, directsend=True)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 1868, in searcher
notify_snatch(nzbname, sent_to, helpers.filesafe(modcomicname), comyear, IssueNumber, nzbprov)
File "/usr/pbi/mylar-amd64/share/mylar/mylar/mylar/search.py", line 1873, in notify_snatch
snline = modcomicname + ' (' + comyear + ') - Issue #' + IssueNumber + ' snatched!'
TypeError: cannot concatenate 'str' and 'NoneType' objects

2015-03-11 23:52:29 	INFO 	setting the nzbid for this download grabbed by dognzb in the nzblog to : 72984354f378a8199582e4db4f1e0001

2015-03-11 23:52:29 	INFO 	Successfully sent nzb file to SABnzbd

**Comment by evilhero** [comment]
That looks like you're using the Retry option for the given issue ? There's an outstanding bug related to that and notification on snatch (it fails to find the necessary information within the mylar database to be able to send to your notification client).

The fix for this should be in the next development commit, until then all I can suggest is to either not use the retry option, or turn off your notification on snatch. Shouldn't be too long before the fix comes out though - just have had the need to spend some family time as of late so haven't even been able to crack open the laptop to code anything.

**Comment by psychoflame** [comment]
Even letting it running normally still errors out with the exact message i get above. Also thanks i will upgrade the PP scripts. Maybe that'll fix my problem

**Comment by evilhero** [comment]
Your getting a connection refused message (just noticed it now)  - in your AutoProcesscomics.cfg make sure your host is set to exactly the same as you have put for the mylar host address within mylar. If you can avoid using localhost, try using the ip directly in both locations. There's been a few users saying they had problems using localhost, and switching to ip fixed things.

**Comment by psychoflame** [comment]
Yep that fixed it. All i had to bind was bind the ip address and edit the PP script to point to python to work. Thanks evil.

Edit: a quick question
What is folder monitoring under the PP part of settings do. Curious

**Comment by evilhero** [comment]
It will monitor a given folder for new issues every X minutes. Basically a manual post-processing will be run at that point against the folder being monitored. 

Useful if you use torrents at all (since there is no post-processing directly) , or if you downloaded a bunch of stuff outside of mylar at some point, and want the issues integrated in now. It will only work on series that exist in your watchlist, otherwise it won't touch the files.
