### ISSUE TITLE
Issue : auto process does not work with manual download and PP script

### ISSUE THREAD

**Issue by tchirou** [evilhero/mylar#967]
Hello
When I manually add a nzb to sabnzbd for wanted files that mylar can't find and use the auto PP script (nzbtomylar), I get this error 
MYLAR: Failure - could not initially locate nzbfile in my database to rename.
But it works with a manual PP
Is there a simple way for you to change the way auto PP is built to avoid using manual PP ?
Thanks

**Comment by evilhero** [comment]
You can't download outside of mylar and then expect mylar to know what it is that you downloaded. Running the ComicRN (or nzbtomylar) script on nzb's that are manually downloaded will not work. Manual post-processing is handled differently as it scans your entire watchlist for any matches to the given filename.

There isn't a simple way to change the way it currently works and it would be too much of an undertaking to get it so that post-processing will work. You can always just set your watch folder to your comics download directory and then it will attempt to manually post-process the directory every X minutes.

**Comment by tchirou** [comment]
Well it is too rare to ask you this and to program a scan every x minutes
Is there a possibility to allow to browse through the folders like the manual PP in Sickrage allows to tell mylar where to look before applying the run instead of having to manually type the path ?

**Comment by evilhero** [comment]
Just set the folder you want monitored within the config.ini itself:
```enable_check_folder = 0 /1 to disable/enable
download_scan_interval = set the time in minutes to scan the folder
check_folder = the full path to the folder to scan```

The Manual Post-Processing tab is mainly for post-processing folders that aren't in your check folder (if you use that), or if you don't use the folder monitor.

Sickrage is based off of Sickbeard which has different coding entirely - it doesn't flow into Mylar easily (and usually not at all) and alot of the times I spend more time trying to decipher how it all flows then the actual coding. If you want to have the button, you're more than welcome to try to port over the code into Mylar - but at this point in time, it's not high on the to-do list atm.

**Comment by tchirou** [comment]
Thanks
I will keep the way it, is writing the path manually
