### ISSUE TITLE
Unable to locate downloaded file to rename

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#978]
Hi

so, it's weird. they downloaded, they are in there, but there is a second set of sabnzbd entries. The originals were SUCCESSFUL! immediately after, sab reported the old locate/rename bug.

Did this crop back up because of this morning's updates?

```

           Loading config from /home/misterfantastic/.sickbeard/autoProcessTV/autoProcessComics.cfg
Opening URL: http://localhost:8090/post_process?nzb_name=Spider-Woman.006.2015.Digital.Zone-Empire&failed=0&apc_version=1.0&comicrn_version=1.0&nzb_folder=%2Fmedia%2Fstorage%2FDownloads%2Fcomplete%2Fcomics%2FSpider-Woman.006.2015.Digital.Zone-Empire
nzb name: Spider-Woman.006.2015.Digital.Zone-Empire

nzb folder: /media/storage/Downloads/complete/comics/Spider-Woman.006.2015.Digital.Zone-Empire

nzbname: Spider-Woman.006.2015.Digital.Zone-Empire

Failure - could not initially locate nzbfile in my database to rename.

trying again with this nzbname: Spider-Woman.006.2015.Digital.Zone-Empire

Unable to locate downloaded file to rename. PostProcessing aborted.






    Spider-Woman.006.2015.Digital.Zone-Empire            
Exit(1) Unable to locate downloaded file to rename. PostProcessing aborted. (More)
2015-04-10 08:56:36  
    Spider-Woman.005.2015.Digital.Zone-Empire            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:56:27  
    Spider-Woman.004.2015.Digital.Zone-Empire            
Exit(1) Unable to locate downloaded file to rename. PostProcessing aborted. (More)
2015-04-10 08:56:21  
    Spider-Woman.006.2015.Digital.Zone-Empire            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:56:10  
    Invisible.Republic.001.2015.digital.Son.of.Ultron-Empire             
Post Processing SUCCESSFUL! (More)
2015-04-10 08:55:48  
    Spider-Woman.003.2015.Digital.Zone-Empire            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:54:57  
    Spider-Woman.004.2015.Digital.Zone-Empire            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:54:41  
    Spider-Woman.002.2015.Digital.Zone-Empire            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:53:21  
    Spider-Woman.001.2015.Scanbro            
Post Processing SUCCESSFUL! (More)
2015-04-10 08:53:19  

```

**Comment by evilhero** [comment]
That might be the race condition I mentioned in issue #921 - it involves users that have a somewhat large list of items in their Wanted list, which gets searched either via a Force Search option or the 6hr mark search happens AND during that, the RSS Check goes off and attempts to find said Wanted issues. The RSS finds the issues and downloads them and marks them as Downloaded and post-processes, then later on, the initial Force Search/6hr mark search finds the issues and re-downloads them because the list it is going off was a 'snapshot' in time of the Wanted list that doesn't reflect the issues that the RSS has downloaded.

I'm looking into this, but some other items were abit more pressing so required more time (namely the 32p entry, and the rss feed problems that cybrwizrd majorily helped with). The 32P is working, I  just need to clean up some code and make some additional changes to accomodate the new way things work - once I push it out, I'll be looking into this re-downloading thing now that I have actually seen it do it (I was in front of the machine when it actually happened previously).

**Comment by AtariBaby** [comment]
oh if it's not a problem then i don't mind the error messages :) good luck with your stuff and thanks for all the hard work! please figure out a way for us to download comics from the future. The build up to Secret wars is killing me lol

**Comment by evilhero** [comment]
Try the future upcoming pull-list - it can be accessed by going to the bottom of the Wanted tab, and selecting the tab that says 'no data upcoming' or 'future pull-list'. Within each of those tabs at the very top of the tab you'll see a click able link to go to the future pull list. Click on it and them on the new page click on Create pullist. It will take a few minutes to generate, but then you should get a few months in advance.. From there you can mark issues / series as Wanted (which will get added to the nodata-upcoming' tab previously mentioned and it checks comicvine for said issues every weekly pull refresh. It's not perfect and it probably needs abit of refinement, but it does seem to work - it's just the gathering of the data can be a bit jumbled.
