### ISSUE TITLE
Error 100

### ISSUE THREAD

**Issue by Trance56k** [evilhero/mylar#989]
I keep getting Error 100 invalid user credentials. I have checked the config file to verify everything is correct. The provider I'm using is NZB.su . I also use sickbeard and I'm having no issues with the API I'm using. I only started  getting this error when I got a Surface Pro 3 and installed Mylar on it. I also run Mylar on my Mac and do not receive this error. I'm stumped and I'm not sure what else to do.

**Comment by evilhero** [comment]
It sounds like you're trying to access the incorrect url for whichever version of mylar you're running on. 

Are you on the surface trying to access the mylar on the surface or on the Mac? If you're on the Mac, can you access mylar on the surface?

**Comment by Trance56k** [comment]
No, the Surface has its own Mylar. I have it set where it's local only. So I can only access Mylar through the computer it's on.

**Comment by evilhero** [comment]
So ok, I'm confused - the error 100 occurs when you're doing searching on mylar through the surface, or when you attempt to sign on to mylar? 

Nzb.su has been having api problems that are hit/miss - it's documented on reddit and in their forums. If you're not getting the error on the Mac, make sure you're running the same versions and that your api key is correct for nzb.su on the tablet. 

It's a configuration issue on the surface, it's just trying to find out what the problem is.

**Comment by Trance56k** [comment]
Sorry I did not mean to confuse you. I have Mylar setup on two computers, my Surface and iMac. I only get the Error 100 on mylar that I have setup on my Surface that I can only access on from my Surface. I do not get that error while using Mylar on my iMac. I wonder if it is API issue. I double  checked my API on my Surface and everything matches up.

**Comment by Trance56k** [comment]
I just copied the config file from my mac onto my Surface and made changes to directories and now it works lol! I have no idea why but it works. Thanks for the quick replies.
